import type { LevelContent } from '../../../core/types'

const level: LevelContent = {
  lessons: {
    // ───────────────────────────────────────────────────────────── l1-1
    'l1-1': {
      id: 'l1-1',
      title: 'Co je chemie a jak bezpečně pracovat',
      goals: [
        'Vysvětlit, čím se chemie zabývá, a rozlišit fyzikální a chemickou změnu',
        'Pojmenovat základní laboratorní pomůcky a říct, k čemu slouží',
        'Rozpoznat výstražné symboly GHS a dodržovat pravidla bezpečné práce',
        'Správně zahřát zkumavku a poskytnout první pomoc při drobné nehodě',
      ],
      hook: 'Ahoj, já jsem Atomík! Co mají společného pečení palačinek, rezavé kolo a nabíjení mobilu? Všude tam probíhá chemie. Dnes zjistíš, co přesně chemie zkoumá – a jak u toho nepřijít o obočí.',
      sections: [
        {
          title: 'Chemie je všude kolem tebe',
          blocks: [
            { type: 'p', text: '**Chemie** je přírodní věda o **látkách**. Zkoumá, z čeho se látky skládají, jaké mají vlastnosti a hlavně jak se **přeměňují** na jiné látky.' },
            { type: 'p', text: 'Látkou je voda, cukr, železo, vzduch i plast, ze kterého je tvoje lahev. Chemik se dívá na svět a ptá se: „Z čeho to je a co se s tím může stát?“' },
            { type: 'list', items: [
              '**Kuchyně:** těsto kyne, maso zhnědne na pánvi, mléko zkysne.',
              '**Koupelna:** šampon, zubní pasta, deodorant – to všechno navrhli chemici.',
              '**Sport:** iontový nápoj, funkční trička z umělých vláken, magnézium na rukou horolezců.',
              '**Doprava:** v motoru hoří benzín, v elektromobilu pracuje lithiová baterie.',
              '**Medicína:** léky, dezinfekce, rentgenová kontrastní látka.',
            ] },
            { type: 'callout', variant: 'fact', title: 'Chemická továrna v tobě', text: 'Ve tvém těle proběhnou každou sekundu miliardy chemických přeměn. Trávíš oběd, dýcháš, rosteš – to všechno je chemie.' },
            { type: 'p', text: 'Chemie není jen pro vědce v bílém plášti. Když víš, jak se látky chovají, rozumíš vaření, praní, zdraví i ekologii.' },
            { type: 'check', question: { kind: 'choice', q: 'Čím se chemie zabývá především?', options: ['Látkami, jejich vlastnostmi a přeměnami', 'Pohybem planet a hvězd', 'Stavbou a funkcí živých buněk', 'Působením sil na tělesa'], answer: 0, explain: 'Chemie je věda o látkách a jejich přeměnách. Pohyb planet a síly patří do fyziky, buňky do biologie.' } },
          ],
        },
        {
          title: 'Fyzikální, nebo chemická změna?',
          blocks: [
            { type: 'p', text: 'Při **fyzikální změně** nevzniká žádná nová látka. Mění se jen tvar, velikost nebo skupenství. Led roztaje na vodu, ale pořád je to voda.' },
            { type: 'p', text: 'Při **chemické změně** (chemické reakci) vznikají **nové látky** s jinými vlastnostmi. ==Rozhoduje otázka: vznikla nová látka?== Z těsta je koláč, ze dřeva popel a kouř.' },
            { type: 'table', headers: ['Děj', 'Typ změny', 'Proč'], rows: [
              ['tání ledu', 'fyzikální', 'voda zůstává vodou, mění se jen skupenství'],
              ['rozpuštění cukru v čaji', 'fyzikální', 'cukr získáš zpět odpařením vody'],
              ['trhání papíru', 'fyzikální', 'kousky jsou pořád papír'],
              ['hoření dřeva', 'chemická', 'vzniká popel, kouř a plyny'],
              ['rezavění železa', 'chemická', 'vzniká rez – nová hnědá látka'],
              ['kysnutí mléka', 'chemická', 'vznikají nové látky, mléko zhoustne a zkysne'],
            ] },
            { type: 'list', items: [
              'změna barvy',
              'vznik plynu (bublinky, pěna)',
              'uvolnění tepla nebo světla',
              'vznik sraženiny (zakalení roztoku)',
              'nový zápach',
            ] },
            { type: 'callout', variant: 'tip', title: 'Znaky chemické změny', text: 'Seznam nahoře ti napoví, že asi proběhla reakce. Stoprocentní důkaz to ale není: i vařící voda bublá, a přesto jde o fyzikální změnu.' },
            { type: 'callout', variant: 'mascot', text: 'Hořící svíčka je pěkný chytrák: vosk kolem knotu jen taje (fyzikální změna), ale jeho páry hoří (chemická změna). Obojí najednou!' },
            { type: 'p', text: 'Chemickým reakcím se budeš podrobně věnovat v úrovni 4. Zatím ti stačí dobrá intuice.' },
            { type: 'check', question: { kind: 'tf', q: 'Rozpuštění cukru v čaji je chemická změna.', answer: false, explain: 'Cukr zůstává cukrem, jen se rozptýlí ve vodě. Když vodu odpaříš, cukr získáš zpět – je to fyzikální změna.' } },
            { type: 'check', question: { kind: 'multi', q: 'Které děje jsou chemické změny?', options: ['smažení vajíčka', 'tání čokolády', 'rezavění plotu', 'lámání tužky', 'hoření plynu na sporáku'], answers: [0, 2, 4], explain: 'Při smažení, rezavění a hoření vznikají nové látky. Tání i lámání mění jen skupenství nebo tvar.' } },
          ],
        },
        {
          title: 'Laboratorní pomůcky',
          blocks: [
            { type: 'p', text: 'V laboratoři má každá pomůcka svůj úkol. Když víš, co k čemu slouží, pracuješ rychleji a bezpečněji.' },
            { type: 'table', headers: ['Pomůcka', 'K čemu slouží'], rows: [
              ['**kádinka**', 'široká nádoba s výlevkou na míchání, ohřívání a přelévání kapalin'],
              ['**zkumavka**', 'malé pokusy s malým množstvím látek, zahřívání'],
              ['**baňka**', 'varná (kulatá) na zahřívání, Erlenmeyerova (kuželová) na míchání a titrace'],
              ['**nálevka**', 'přelévání kapalin do úzkého hrdla a filtrace'],
              ['**kahan**', 'zdroj plamene pro zahřívání'],
              ['**stojan**', 'upevnění aparatury pomocí držáků, svorek a kruhů'],
              ['**pipeta**', 'odebrání malého a přesného objemu kapaliny'],
              ['**odměrný válec**', 'odměření objemu kapaliny'],
            ] },
            { type: 'p', text: 'Dále budeš potkávat **třecí misku s tloučkem** (drcení látek), **odpařovací misku**, **hodinové sklo**, **držák na zkumavky**, **keramickou síťku** pod kádinku, **skleněnou tyčinku** a **střičku** s destilovanou vodou.' },
            { type: 'p', text: 'Plynový **kahan** hoří dvěma druhy plamene. Když je přívod vzduchu otevřený, hoří modrý **nesvítivý plamen**, který je nejteplejší (až kolem 1500 °C). Se zavřeným přívodem vzduchu hoří žlutý **svítivý plamen**, který je chladnější a čadí.' },
            { type: 'list', ordered: true, items: [
              'Zkontroluj hadici a přivři přívod vzduchu.',
              'Škrtni zápalkou.',
              'Přilož hořící zápalku k ústí kahanu.',
              'Teprve teď pomalu otevři přívod plynu.',
              'Otevři přívod vzduchu, až je plamen modrý a nesvítivý.',
            ] },
            { type: 'callout', variant: 'tip', title: 'Jak číst odměrný válec', text: 'Hladina vody ve válci je zakřivená dolů (tvoří **meniskus**). Objem odečítej v úrovni očí u spodního okraje menisku.' },
            { type: 'callout', variant: 'warning', text: 'Stupnice na kádince je jen orientační. Když potřebuješ přesný objem, použij odměrný válec nebo pipetu. Pipetu nikdy nenasávej ústy – na to je pipetovací balonek nebo nástavec.' },
            { type: 'check', question: { kind: 'match', q: 'Přiřaď pomůcku k jejímu použití.', pairs: [['odměrný válec', 'odměření objemu kapaliny'], ['nálevka', 'filtrace a přelévání'], ['kahan', 'zahřívání'], ['pipeta', 'odebrání malého přesného objemu'], ['stojan', 'upevnění aparatury']], explain: 'Každá pomůcka má svou práci: válec měří, nálevka převádí kapalinu, kahan hřeje, pipeta odebírá přesně a stojan drží aparaturu.' } },
          ],
        },
        {
          title: 'Bezpečnost a výstražné symboly',
          blocks: [
            { type: 'p', text: 'Laboratorní řád není buzerace. Každé pravidlo vzniklo proto, že se někdy někomu něco stalo.' },
            { type: 'list', items: [
              'Pracuj jen se svolením učitele a přesně podle návodu.',
              'Nos **ochranné brýle** a plášť, dlouhé vlasy si stáhni.',
              'V laboratoři nejez, nepij a nic neochutnávej.',
              'Nečichej přímo nad nádobou – páry si ovívej rukou k nosu.',
              'S jedovatými a zapáchajícími látkami pracuj v **digestoři** (odsávané skříni).',
              'Při ředění kyselin platí: **nejdřív voda, potom kyselina**.',
              'Zbytky chemikálií nevylévej do umyvadla, patří do připravených nádob.',
              'Každou nehodu, i malou, hned ohlas učiteli.',
            ] },
            { type: 'diagram', id: 'lab-safety', caption: 'Výstražné symboly GHS – najdeš je na chemikáliích ve škole i na čisticích prostředcích doma' },
            { type: 'table', headers: ['Symbol', 'Význam', 'Příklad'], rows: [
              ['plamen', 'hořlavé', 'líh, benzín, aceton'],
              ['plamen nad kruhem', 'oxidující (podporuje hoření)', 'koncentrovaný peroxid vodíku'],
              ['explodující bomba', 'výbušné', 'zábavní pyrotechnika'],
              ['plynová láhev', 'plyny pod tlakem', 'propan-butan, bombička do šlehačky'],
              ['kapky leptající ruku a kov', 'žíravé', 'kyselina sírová, čistič odpadů'],
              ['lebka se zkříženými hnáty', 'akutně toxické', 'methanol, některé jedy na hlodavce'],
              ['vykřičník', 'dráždivé, zdraví škodlivé', 'některé čisticí prostředky'],
              ['silueta člověka s hvězdicí', 'vážně nebezpečné pro zdraví', 'benzín, methanol'],
              ['strom a mrtvá ryba', 'nebezpečné pro životní prostředí', 'benzín, přípravky proti hmyzu'],
            ] },
            { type: 'p', text: 'Na etiketě najdeš i **signální slovo**: „Nebezpečí“ (vážnější riziko) nebo „Varování“ (menší riziko). Dále tam jsou **H-věty**, které popisují nebezpečí, a **P-věty** s pokyny, jak s látkou bezpečně zacházet.' },
            { type: 'callout', variant: 'fact', text: 'Symboly GHS (z anglického *Globally Harmonized System*) platí téměř na celém světě. V Evropské unii od roku 2015 úplně nahradily starší oranžové čtverce s černými symboly.' },
            { type: 'check', question: { kind: 'choice', q: 'Na lahvi čističe odpadů je piktogram s kapkami, které leptají ruku a kov. Co znamená?', options: ['žíravé', 'hořlavé', 'akutně toxické', 'nebezpečné pro životní prostředí'], answer: 0, explain: 'Kapky leptající ruku a kovovou desku označují žíravinu. Čistič odpadů obsahuje silnou žíravinu, proto rukavice a brýle.' } },
          ],
        },
        {
          title: 'Zahřívání zkumavky a první pomoc',
          blocks: [
            { type: 'p', text: 'Zahřívání zkumavky vypadá jednoduše, ale právě při něm se stává nejvíc nehod. Postupuj takhle:' },
            { type: 'list', ordered: true, items: [
              'Nasaď si ochranné brýle.',
              'Nalij kapalinu nejvýše do třetiny zkumavky.',
              'Uchop zkumavku držákem v horní třetině, blízko ústí.',
              'Drž ji šikmo a ústí otoč od sebe i od ostatních.',
              'Zahřívej v nesvítivém plameni a zkumavkou stále mírně pohybuj.',
            ] },
            { type: 'callout', variant: 'warning', title: 'Utajený var', text: 'Když se kapalina ohřívá jen u dna, může se v ní náhle vytvořit velká bublina páry a obsah vystříkne ven. Proto zkumavkou pohybuj a nikdy se do ní při zahřívání nedívej shora.' },
            { type: 'table', headers: ['Nehoda', 'Co udělat'], rows: [
              ['chemikálie na kůži', 'oplachuj proudem studené vody aspoň 10–15 minut, svlékni potřísněný oděv'],
              ['chemikálie v oku', 'vyplachuj oko s otevřenými víčky čistou vodou 10–15 minut, pak k lékaři'],
              ['popálení', 'chlaď pod tekoucí studenou vodou, puchýře nepropichuj, nemaž je krémem'],
              ['pořezání o sklo', 'ránu vypláchni a obvaž, střepy nesbírej holou rukou'],
              ['spolknutí chemikálie', 'vypláchni ústa vodou, nevyvolávej zvracení, volej lékaře'],
            ] },
            { type: 'callout', variant: 'remember', title: 'Důležitá čísla', text: '**155** záchranná služba, **150** hasiči, **112** jednotné evropské číslo tísňového volání. Toxikologické informační středisko radí při otravách nonstop na čísle 224 919 293.' },
            { type: 'callout', variant: 'mascot', text: 'Nejdůležitější pravidlo ze všech? Každou nehodu hned řekni učiteli. Nikdo ti hlavu neutrhne, zato ti pomůže – a rychlost je u popálenin a poleptání k nezaplacení.' },
            { type: 'game', gameId: 'swipe', text: 'Zahraj si **Pravda, nebo lež?** a ověř si, jestli bezpečně poznáš fyzikální a chemické změny i správná pravidla v laboratoři.' },
            { type: 'check', question: { kind: 'order', q: 'Seřaď kroky při zahřívání kapaliny ve zkumavce.', items: ['Nasaď si ochranné brýle.', 'Nalij kapalinu nejvýše do třetiny zkumavky.', 'Uchop zkumavku držákem v horní třetině.', 'Drž ji šikmo, ústím od lidí.', 'Zahřívej a zkumavkou stále pohybuj.'], explain: 'Nejdřív ochrana očí, pak správné množství a úchop, a teprve nakonec zahřívání s pohybem, aby nedošlo k utajenému varu.' } },
          ],
        },
      ],
      summary: [
        'Chemie zkoumá látky, jejich vlastnosti a přeměny.',
        'Při fyzikální změně nevzniká nová látka, při chemické změně ano.',
        'Kádinka, zkumavka, baňka, nálevka, kahan, stojan, pipeta a odměrný válec jsou základní laboratorní pomůcky.',
        'Nejteplejší je modrý nesvítivý plamen kahanu; kahan zapaluješ tak, že nejdřív škrtneš zápalkou a pak pustíš plyn.',
        'Výstražné symboly GHS ukazují, jestli je látka hořlavá, žíravá, toxická nebo nebezpečná pro přírodu.',
        'Zkumavku plníš nejvýše do třetiny, držíš ji šikmo ústím od lidí a při zahřívání s ní pohybuješ.',
        'Při potřísnění kůže nebo oka oplachuj velkým množstvím vody a nehodu hned ohlas.',
      ],
      quiz: [
        { kind: 'choice', q: 'Kterou pomůckou nejpřesněji odměříš 25 ml vody?', options: ['odměrným válcem', 'kádinkou', 'hodinovým sklem', 'třecí miskou'], answer: 0, explain: 'Odměrný válec má přesnou stupnici. Stupnice na kádince je jen orientační.' },
        { kind: 'tf', q: 'Žlutý svítivý plamen kahanu je teplejší než modrý nesvítivý.', answer: false, explain: 'Nejteplejší je modrý nesvítivý plamen s dostatkem vzduchu. Svítivý plamen je chladnější a čadí.' },
        { kind: 'multi', q: 'Která pravidla v laboratoři platí?', options: ['Chemikálie nikdy neochutnávám.', 'Vůni zjišťuji ovíváním par rukou k nosu.', 'Při ředění nalévám vodu do koncentrované kyseliny.', 'Pipetovat ústy smím, když jde jen o vodu.', 'Ochranné brýle nosím po celou dobu pokusu.'], answers: [0, 1, 4], explain: 'Při ředění platí „nejdřív voda, potom kyselina“ – kyselina se lije do vody. Pipetovat ústy se nesmí nikdy, ani s vodou, kvůli zvyku a riziku záměny.' },
        { kind: 'match', q: 'Přiřaď piktogram k jeho významu.', pairs: [['plamen', 'hořlavá látka'], ['lebka se zkříženými hnáty', 'akutně toxická látka'], ['kapky leptající ruku a kov', 'žíravina'], ['strom a mrtvá ryba', 'nebezpečné pro životní prostředí']], explain: 'Piktogramy GHS jsou navržené tak, aby jim člověk rozuměl bez ohledu na jazyk.' },
        { kind: 'choice', q: 'Spolužákovi vystříkla do oka kapka roztoku. Co uděláš jako první?', options: ['Budu mu oko vyplachovat velkým množstvím čisté vody.', 'Nechám ho, ať si oko promne.', 'Kápnu mu do oka jinou chemikálii, která roztok zneutralizuje.', 'Počkám, jestli pálení samo přejde.'], answer: 0, explain: 'Nejdůležitější je okamžitě a dlouho (10–15 minut) vyplachovat vodou. Mnutí a „neutralizace“ jinou chemikálií oko poškodí ještě víc.' },
        { kind: 'tf', q: 'Hnědnutí rozkrojeného jablka je chemická změna.', answer: true, explain: 'Látky v jablku reagují se vzdušným kyslíkem a vznikají nové hnědé látky – jde o chemickou změnu.' },
        { kind: 'order', q: 'Seřaď kroky při zapalování plynového kahanu.', items: ['Přivři přívod vzduchu.', 'Škrtni zápalkou.', 'Přilož hořící zápalku k ústí kahanu.', 'Pomalu otevři přívod plynu.', 'Otevři přívod vzduchu, až je plamen modrý.'], explain: 'Plyn se pouští až ve chvíli, kdy u ústí kahanu už hoří zápalka. Jinak by se nahromadil a mohl vzplanout najednou.' },
        { kind: 'text', q: 'Jak se jmenuje široká skleněná nádoba ve tvaru válce s výlevkou, ve které se nejčastěji míchají a ohřívají kapaliny?', accept: ['kádinka'], placeholder: 'název pomůcky', explain: 'Kádinka je nejběžnější nádoba v laboratoři. Na přesné měření objemu se ale nehodí.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l1-2
    'l1-2': {
      id: 'l1-2',
      title: 'Vlastnosti látek a skupenství',
      goals: [
        'Rozlišit látku a těleso a vyjmenovat hlavní vlastnosti látek',
        'Spočítat hustotu, hmotnost nebo objem ze vztahu $ρ = m / V$',
        'Pojmenovat všechny změny skupenství a vysvětlit je pomocí částic',
        'Vysvětlit, co je difuze a Brownův pohyb',
      ],
      hook: 'Proč kostka ledu plave v limonádě, ale kus železa klesne ke dnu? A proč ucítíš voňavku spolužáka, i když sedí na druhém konci třídy? Odpověď se skrývá ve vlastnostech látek.',
      sections: [
        {
          title: 'Látka, nebo těleso?',
          blocks: [
            { type: 'p', text: '**Těleso** je konkrétní předmět, který má tvar a objem: hrnek, lžíce, klíč. **Látka** je to, z čeho je těleso vyrobené: porcelán, nerezová ocel, mosaz.' },
            { type: 'table', headers: ['Těleso', 'Látka'], rows: [
              ['hrnek', 'porcelán'],
              ['lžíce', 'nerezová ocel'],
              ['okenní tabule', 'sklo'],
              ['svíčka', 'parafín'],
              ['elektrický drát', 'měď'],
            ] },
            { type: 'p', text: 'Z jedné látky můžeš vyrobit mnoho různých těles – ze skla je sklenice, okno i láhev. A jedno těleso může být z několika látek: tužka je ze dřeva, tuhy a barvy.' },
            { type: 'callout', variant: 'tip', text: 'Zeptej se: „Co to je?“ – odpovědí je těleso. „Z čeho to je?“ – odpovědí je látka.' },
            { type: 'check', question: { kind: 'multi', q: 'Které z těchto slov označují látky?', options: ['hliník', 'plechovka', 'voda', 'kapka', 'cukr'], answers: [0, 2, 4], explain: 'Hliník, voda a cukr jsou látky. Plechovka a kapka jsou tělesa – mají určitý tvar a velikost.' } },
          ],
        },
        {
          title: 'Vlastnosti látek a hustota',
          blocks: [
            { type: 'p', text: 'Látky poznáváme podle jejich **vlastností**, podobně jako lidi podle obličeje. Některé zjistíš smysly, jiné musíš změřit.' },
            { type: 'keyterms', items: [
              { term: 'barva, lesk, zápach', def: 'zjistíš pozorováním (a zápach opatrným ovíváním)' },
              { term: '**hustota**', def: 'jakou hmotnost má určitý objem látky' },
              { term: '**teplota tání a varu**', def: 'při jaké teplotě látka taje a vře' },
              { term: '**rozpustnost**', def: 'jestli a kolik látky se rozpustí třeba ve vodě' },
              { term: '**elektrická a tepelná vodivost**', def: 'jak dobře látka vede elektrický proud a teplo' },
            ] },
            { type: 'p', text: '**Hustota** (značka $ρ$, čti „ró“) říká, jakou hmotnost má jeden centimetr krychlový látky. Kostka železa a stejně velká kostka dřeva vypadají podobně, ale železná je mnohem těžší – železo má větší hustotu.' },
            { type: 'formula', text: '$ρ = m / V$', caption: 'hustota = hmotnost : objem; jednotky g/cm³ nebo kg/m³' },
            { type: 'table', headers: ['Látka', 'Hustota (g/cm³)'], rows: [
              ['vzduch', '0,0012'],
              ['líh (ethanol)', '0,79'],
              ['led, jedlý olej', '0,92'],
              ['voda', '1,00'],
              ['hliník', '2,70'],
              ['železo', '7,87'],
              ['olovo', '11,3'],
              ['rtuť', '13,5'],
              ['zlato', '19,3'],
            ], caption: 'Hustoty při pokojové teplotě (led při 0 °C)' },
            { type: 'example', title: 'Z čeho je kvádr?', problem: 'Kovový kvádr má rozměry 2 cm × 3 cm × 5 cm a hmotnost 81 g. Z jakého kovu je?', steps: [
              'Objem kvádru: $V$ = 2 cm · 3 cm · 5 cm = 30 cm³',
              'Hustota: $ρ = m / V$ = 81 g : 30 cm³',
              '$ρ$ = 2,7 g/cm³',
              'Porovnáme s tabulkou: hustotu 2,70 g/cm³ má hliník.',
            ], answer: 'Kvádr je z hliníku.' },
            { type: 'example', title: 'Kolik váží olej?', problem: 'Jakou hmotnost má 1,5 litru jedlého oleje ($ρ$ = 0,92 g/cm³)?', steps: [
              'Převedeme objem: 1,5 l = 1500 cm³ (1 l = 1000 cm³)',
              'Ze vzorce vyjádříme hmotnost: $m = ρ · V$',
              '$m$ = 0,92 g/cm³ · 1500 cm³ = 1380 g',
            ], answer: '$m$ = 1380 g = 1,38 kg' },
            { type: 'callout', variant: 'remember', text: '1 ml = 1 cm³ a 1 g/cm³ = 1000 kg/m³. Těleso z látky s menší hustotou než voda na vodě plave, s větší hustotou klesne ke dnu.' },
            { type: 'callout', variant: 'fact', text: 'Led má menší hustotu než kapalná voda, proto plave. Jezera tak zamrzají odshora a ryby pod ledem přežijí zimu. U většiny jiných látek je pevné skupenství naopak hustší než kapalné.' },
            { type: 'check', question: { kind: 'number', q: 'Kovový předmět o objemu 20 cm³ má hmotnost 158 g. Jaká je jeho hustota v g/cm³?', answer: 7.9, tolerance: 0.05, unit: 'g/cm³', explain: '$ρ$ = 158 g : 20 cm³ = 7,9 g/cm³. Podle tabulky je předmět nejspíš ze železa.' } },
          ],
        },
        {
          title: 'Teplota tání, teplota varu a vodivost',
          blocks: [
            { type: 'p', text: '**Teplota tání** je teplota, při které se pevná látka mění v kapalinu. **Teplota varu** je teplota, při které kapalina vře – mění se v plyn v celém svém objemu.' },
            { type: 'p', text: 'Čistá látka má obě teploty přesně dané. Proto podle nich chemici látky poznávají a kontrolují jejich čistotu.' },
            { type: 'table', headers: ['Látka', 'Teplota tání', 'Teplota varu', 'Skupenství při 20 °C'], rows: [
              ['kyslík', '−218 °C', '−183 °C', 'plynné'],
              ['líh (ethanol)', '−114 °C', '78 °C', 'kapalné'],
              ['rtuť', '−39 °C', '357 °C', 'kapalné'],
              ['voda', '0 °C', '100 °C', 'kapalné'],
              ['kuchyňská sůl', '801 °C', '1465 °C', 'pevné'],
              ['železo', '1538 °C', '2862 °C', 'pevné'],
            ], caption: 'Hodnoty platí při normálním tlaku 101,325 kPa' },
            { type: 'callout', variant: 'fact', text: 'Teplota varu závisí na tlaku. Na vrcholu Mount Everestu vře voda už kolem 70 °C, takže tam vajíčko natvrdo skoro neuvaříš. V tlakovém hrnci naopak vře až kolem 120 °C, a jídlo je proto hotové dřív.' },
            { type: 'p', text: '**Rozpustnost** říká, jestli se látka rozpustí v rozpouštědle. Cukr se ve vodě rozpustí, písek ne. Podrobně se jí budeme věnovat v lekci o roztocích.' },
            { type: 'p', text: '**Elektrická vodivost:** kovy jako měď vedou elektrický proud výborně, proto jsou z nich dráty. Plasty, sklo a keramika proud nevedou – jsou to **izolanty**. **Tepelná vodivost:** kovová lžička v horkém čaji rychle zteplá, dřevěná vařečka ne.' },
            { type: 'callout', variant: 'tip', text: 'Proč mají pánve rukojeť ze dřeva nebo z plastu? Kov vede teplo tak dobře, že by kovová rukojeť za chvíli pálila.' },
            { type: 'check', question: { kind: 'choice', q: 'V jedné lahvi je voda, v druhé líh. Obě kapaliny jsou čiré a bezbarvé. Kterým měřením je spolehlivě rozlišíš?', options: ['změřením teploty varu', 'změřením objemu kapaliny', 'změřením teploty v laboratoři', 'zvážením celé lahve i se zátkou'], answer: 0, explain: 'Voda vře při 100 °C, líh už při 78 °C. Teplota varu je vlastnost látky, kdežto objem nebo hmotnost lahve závisí jen na tom, kolik kapaliny v ní je.' } },
          ],
        },
        {
          title: 'Skupenství a jejich změny',
          blocks: [
            { type: 'p', text: 'Látky se vyskytují ve třech základních **skupenstvích**: pevném, kapalném a plynném. (Čtvrté skupenství, plazma, najdeš v blesku, v zářivce nebo ve Slunci.)' },
            { type: 'p', text: 'Všechny látky se skládají z nepatrných **částic**, které se neustále pohybují. Skupenství závisí na tom, jak blízko sebe částice jsou a jak se pohybují. Co jsou tyto částice zač (atomy, molekuly, ionty), zjistíš v úrovni 2.' },
            { type: 'diagram', id: 'states', caption: 'Částice v pevné látce, v kapalině a v plynu' },
            { type: 'table', headers: ['Skupenství', 'Částice', 'Tvar', 'Objem'], rows: [
              ['pevné', 'těsně u sebe, pravidelně uspořádané, jen kmitají na místě', 'stálý', 'stálý'],
              ['kapalné', 'blízko u sebe, neuspořádané, posouvají se po sobě', 'podle nádoby', 'stálý'],
              ['plynné', 'daleko od sebe, rychle a chaoticky létají', 'podle nádoby', 'vyplní celou nádobu, dá se stlačit'],
            ] },
            { type: 'table', headers: ['Změna', 'Ze skupenství -> do skupenství', 'Příklad'], rows: [
              ['**tání**', 'pevné -> kapalné', 'zmrzlina v létě'],
              ['**tuhnutí**', 'kapalné -> pevné', 'voda v mrazáku'],
              ['**vypařování**', 'kapalné -> plynné (z povrchu, při každé teplotě)', 'schnutí prádla, louže po dešti'],
              ['**var**', 'kapalné -> plynné (v celém objemu, při teplotě varu)', 'voda v konvici'],
              ['**kapalnění** (kondenzace)', 'plynné -> kapalné', 'orosené brýle, rosa na trávě'],
              ['**sublimace**', 'pevné -> plynné', 'suchý led, prádlo schnoucí na mrazu'],
              ['**desublimace**', 'plynné -> pevné', 'jinovatka, ledové květy na okně'],
            ] },
            { type: 'callout', variant: 'remember', text: '**Vypařování** probíhá jen na povrchu kapaliny a při jakékoli teplotě. **Var** probíhá v celém objemu kapaliny, a to jen při teplotě varu – proto se uvnitř tvoří bubliny páry.' },
            { type: 'callout', variant: 'warning', text: 'Suchý led (pevný oxid uhličitý, −78 °C) nikdy neber holou rukou – způsobí omrzliny. A nikdy ho nezavírej do lahve: plyn, který sublimací vzniká, by ji roztrhl.' },
            { type: 'check', question: { kind: 'match', q: 'Přiřaď změnu skupenství.', pairs: [['tání', 'pevné -> kapalné'], ['kapalnění', 'plynné -> kapalné'], ['sublimace', 'pevné -> plynné'], ['desublimace', 'plynné -> pevné'], ['tuhnutí', 'kapalné -> pevné']], explain: 'Každá změna má svou „opačnou“ dvojici: tání × tuhnutí, vypařování a var × kapalnění, sublimace × desublimace.' } },
            { type: 'check', question: { kind: 'tf', q: 'Při varu se bubliny vodní páry tvoří uvnitř kapaliny, ne jen na jejím povrchu.', answer: true, explain: 'Právě to odlišuje var od vypařování: při teplotě varu se kapalina mění v páru v celém objemu.' } },
          ],
        },
        {
          title: 'Difuze a Brownův pohyb',
          blocks: [
            { type: 'p', text: 'Kápni do sklenice vody kapku potravinářského barviva a nemíchej. Za chvíli je obarvená celá sklenice. Jak je to možné?' },
            { type: 'p', text: 'Částice vody i barviva se neustále neuspořádaně pohybují a narážejí do sebe. Částice barviva tak samy pronikají mezi částice vody. Tomuto samovolnému promíchávání říkáme **difuze**.' },
            { type: 'list', items: [
              'Vůně pečeného chleba se rozšíří po celém bytě.',
              'Čajový sáček obarví vodu, i když nemícháš.',
              'Parfém ucítíš na druhém konci místnosti.',
            ] },
            { type: 'callout', variant: 'tip', title: 'Domácí pokus', text: 'Dej jeden čajový sáček do sklenice studené vody a druhý do sklenice horké vody. V horké vodě se barva šíří mnohem rychleji: čím vyšší teplota, tím rychleji se částice pohybují. V plynech je difuze rychlejší než v kapalinách.' },
            { type: 'p', text: 'V roce 1827 pozoroval botanik Robert Brown mikroskopem drobná zrníčka z pylu ve vodě. Neustále sebou nepravidelně škubala, jako by tančila. Tento **Brownův pohyb** vysvětlil až v roce 1905 Albert Einstein: do zrníček ze všech stran nepravidelně narážejí neviditelné částice vody.' },
            { type: 'callout', variant: 'fact', text: 'Einsteinovo vysvětlení Brownova pohybu patřilo k prvním přesvědčivým důkazům, že částice látek skutečně existují. Ještě kolem roku 1900 o tom někteří vědci pochybovali!' },
            { type: 'game', gameId: 'quickfire', text: 'Zkus **Bleskovou výzvu**: kolik otázek o skupenstvích a vlastnostech látek zodpovíš za 60 sekund?' },
            { type: 'check', question: { kind: 'choice', q: 'Proč se barvivo rozptýlí rychleji v horké vodě než ve studené?', options: ['Částice se za vyšší teploty pohybují rychleji.', 'Horká voda má větší hustotu.', 'Barvivo se v horké vodě mění na plyn.', 'V horké vodě jsou částice větší.'], answer: 0, explain: 'Difuzi způsobuje pohyb částic. Za vyšší teploty se částice pohybují rychleji, takže se látky promíchají dřív.' } },
          ],
        },
      ],
      summary: [
        'Těleso je předmět, látka je to, z čeho je vyrobený.',
        'Látky poznáme podle vlastností: barvy, zápachu, hustoty, teploty tání a varu, rozpustnosti a vodivosti.',
        'Hustota se počítá jako $ρ = m / V$; těleso s menší hustotou než voda na vodě plave.',
        'V pevné látce částice jen kmitají, v kapalině se po sobě posouvají a v plynu volně létají.',
        'Změny skupenství jsou tání, tuhnutí, vypařování, var, kapalnění, sublimace a desublimace.',
        'Difuze je samovolné promíchávání látek díky neustálému pohybu částic; za vyšší teploty je rychlejší.',
      ],
      quiz: [
        { kind: 'tf', q: 'Hrnek je látka a porcelán je těleso.', answer: false, explain: 'Je to naopak: hrnek je těleso, porcelán je látka, ze které je vyrobený.' },
        { kind: 'number', q: 'Jakou hmotnost má 250 cm³ lihu ($ρ$ = 0,79 g/cm³)? Výsledek uveď v gramech.', answer: 197.5, tolerance: 0.5, unit: 'g', explain: '$m = ρ · V$ = 0,79 g/cm³ · 250 cm³ = 197,5 g.' },
        { kind: 'number', q: 'Zlatý prsten má hmotnost 9,65 g. Jaký má objem v cm³? ($ρ$(zlato) = 19,3 g/cm³)', answer: 0.5, tolerance: 0.01, unit: 'cm³', explain: '$V = m / ρ$ = 9,65 g : 19,3 g/cm³ = 0,5 cm³.' },
        { kind: 'match', q: 'Přiřaď skupenství k chování částic.', pairs: [['pevná látka', 'částice těsně u sebe, jen kmitají na místě'], ['kapalina', 'částice blízko sebe, posouvají se po sobě'], ['plyn', 'částice daleko od sebe, rychle létají všemi směry']], explain: 'Čím volněji se částice pohybují, tím snáz látka mění tvar a objem.' },
        { kind: 'choice', q: 'Na okně se v mrazivé noci vytvořily ledové květy přímo z vodní páry ve vzduchu. Jak se tato změna nazývá?', options: ['desublimace', 'tuhnutí', 'kapalnění', 'sublimace'], answer: 0, explain: 'Pára se změnila rovnou v led, bez kapalné fáze. Přechod z plynného do pevného skupenství je desublimace.' },
        { kind: 'multi', q: 'Které vlastnosti mají kovy, jako je měď nebo hliník?', options: ['dobře vedou elektrický proud', 'dobře vedou teplo', 'všechny kovy jsou za pokojové teploty pevné', 'mají kovový lesk'], answers: [0, 1, 3], explain: 'Kovy vedou proud i teplo a mají lesk. Ne všechny jsou ale pevné – rtuť je za pokojové teploty kapalina.' },
        { kind: 'choice', q: 'Proč ucítíš vůni guláše i v pokoji na druhém konci bytu?', options: ['Díky difuzi – částice vůně se samovolně šíří vzduchem.', 'Protože guláš sublimuje.', 'Protože vzduch má větší hustotu než guláš.', 'Protože se teplem zvětšují částice vzduchu.'], answer: 0, explain: 'Částice vonných látek se díky neustálému pohybu samy šíří mezi částicemi vzduchu – to je difuze.' },
        { kind: 'tf', q: 'Vypařování probíhá jen při teplotě varu.', answer: false, explain: 'Vypařování probíhá z povrchu kapaliny při jakékoli teplotě – proto uschne i louže v zimě. Při teplotě varu probíhá var.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l1-3
    'l1-3': {
      id: 'l1-3',
      title: 'Směsi a chemicky čisté látky',
      goals: [
        'Rozlišit chemicky čistou látku a směs',
        'Zařadit směs jako stejnorodou, nebo různorodou a pojmenovat druh různorodé směsi',
        'Uvést příklady slitin a jejich použití',
        'Vysvětlit rozdíl mezi prvkem a sloučeninou',
      ],
      hook: 'Na lahvi stojí „100% čistá pramenitá voda“. Chemik se jen pousměje: ta voda obsahuje rozpuštěné minerální látky, takže chemicky čistá není. Co tedy znamená „čistá látka“?',
      sections: [
        {
          title: 'Chemicky čistá látka × směs',
          blocks: [
            { type: 'p', text: '**Chemicky čistá látka** obsahuje jen jednu jedinou látku. Má stálé vlastnosti: přesnou teplotu tání, teplotu varu i hustotu. Příkladem je destilovaná voda, cukr, měď nebo kyslík.' },
            { type: 'p', text: '**Směs** se skládá ze dvou nebo více látek, kterým říkáme **složky**. ==Vlastnosti směsi závisí na tom, kolik které složky obsahuje.== Příkladem je slazený čaj, vzduch, mléko nebo žula.' },
            { type: 'table', headers: ['', 'Chemicky čistá látka', 'Směs'], rows: [
              ['složení', 'jediná látka', 'dvě a více látek'],
              ['vlastnosti', 'stálé', 'závisí na poměru složek'],
              ['teplota varu', 'přesná a během varu stálá (voda 100 °C)', 'během varu se mění (slaná voda vře nad 100 °C)'],
              ['rozdělení', 'fyzikálními metodami ji na jiné látky nerozdělíš', 'složky se dají oddělit fyzikálními metodami'],
            ] },
            { type: 'callout', variant: 'warning', title: 'Pozor na slovo „čistý“', text: 'V běžné řeči „čistý“ znamená „bez špíny“. V chemii „chemicky čistý“ znamená „jen jedna látka“. Voda z kohoutku je zdravotně nezávadná, ale chemicky čistá není.' },
            { type: 'callout', variant: 'fact', text: 'Absolutně čistá látka neexistuje, vždy obsahuje nepatrné stopy něčeho jiného. Křemík pro počítačové čipy se ale vyrábí s čistotou 99,9999999 % – na miliardu částic křemíku připadá jen asi jedna cizí.' },
            { type: 'check', question: { kind: 'tf', q: 'Minerální voda je chemicky čistá látka.', answer: false, explain: 'Minerální voda obsahuje rozpuštěné minerální látky (a často i oxid uhličitý). Je to směs.' } },
          ],
        },
        {
          title: 'Stejnorodé a různorodé směsi',
          blocks: [
            { type: 'p', text: 'Ve **stejnorodé (homogenní) směsi** nerozlišíš složky okem ani mikroskopem a všude má stejné složení. Patří sem **roztoky**: slaná voda, ocet, vzduch, ale i slitiny kovů.' },
            { type: 'p', text: 'V **různorodé (heterogenní) směsi** složky rozlišíš okem nebo aspoň pod mikroskopem. Třeba písek ve vodě, müsli nebo žula, ve které vidíš různě barevná zrnka.' },
            { type: 'keyterms', items: [
              { term: '**suspenze**', def: 'pevné částice rozptýlené v kapalině: bahnitá voda, křída rozmíchaná ve vodě' },
              { term: '**emulze**', def: 'kapičky jedné kapaliny v jiné kapalině, se kterou se nemísí: mléko, majonéza, protřepaný olej s octem' },
              { term: '**pěna**', def: 'bublinky plynu v kapalině nebo v pevné látce: šlehačka, pěna do koupele, polystyren, molitan' },
              { term: '**dým (kouř)**', def: 'pevné částice rozptýlené v plynu: kouř z komína' },
              { term: '**mlha**', def: 'kapičky kapaliny rozptýlené v plynu: mlha, oblak, sprej' },
            ] },
            { type: 'p', text: 'Dým a mlhu dohromady nazýváme **aerosoly** – jsou to drobné pevné nebo kapalné částice rozptýlené v plynu.' },
            { type: 'table', headers: ['Směs', 'Druh'], rows: [
              ['ocet', 'stejnorodá (roztok)'],
              ['vzduch', 'stejnorodá'],
              ['nerezová lžička', 'stejnorodá (slitina)'],
              ['müsli', 'různorodá'],
              ['pomerančový džus s dužninou', 'různorodá (suspenze)'],
              ['šlehačka', 'různorodá (pěna)'],
            ] },
            { type: 'callout', variant: 'fact', title: 'Mléko pod lupou', text: 'Mléko vypadá stejnorodě, ale pod mikroskopem uvidíš drobné kapičky tuku ve vodě – je to emulze. Posviť laserovým ukazovátkem skrz zředěné mléko a uvidíš dráhu paprsku. Skrz slanou vodu ji neuvidíš. (Laserem nikdy nesviť nikomu do očí!)' },
            { type: 'callout', variant: 'tip', text: 'Emulze se časem rozdělí – olej vyplave nahoru. Aby vydržela, přidávají se **emulgátory**. V majonéze tuhle práci dělá vaječný žloutek.' },
            { type: 'check', question: { kind: 'match', q: 'Přiřaď k různorodé směsi její druh.', pairs: [['šlehačka', 'pěna'], ['mléko', 'emulze'], ['bahnitá voda', 'suspenze'], ['kouř z ohně', 'dým'], ['ranní opar nad řekou', 'mlha']], explain: 'Rozhoduje, co je v čem rozptýlené: plyn v kapalině je pěna, kapalina v kapalině emulze, pevná látka v kapalině suspenze, pevná látka v plynu dým a kapalina v plynu mlha.' } },
            { type: 'check', question: { kind: 'choice', q: 'Která směs je stejnorodá?', options: ['ocet', 'müsli', 'bahnitá voda', 'žula'], answer: 0, explain: 'Ocet je roztok – složky v něm nerozlišíš ani mikroskopem. Ostatní směsi jsou různorodé.' } },
          ],
        },
        {
          title: 'Slitiny – kovy, které se smísily',
          blocks: [
            { type: 'p', text: '**Slitina** vznikne, když se roztavené kovy (někdy i s nekovem, třeba s uhlíkem) smísí a nechají ztuhnout. Je to stejnorodá směs, vlastně „pevný roztok“.' },
            { type: 'p', text: 'Slitiny se vyrábějí, protože mají lepší vlastnosti než čisté kovy. Bývají tvrdší, pevnější nebo odolnější proti korozi.' },
            { type: 'table', headers: ['Slitina', 'Hlavní složky', 'Použití'], rows: [
              ['**mosaz**', 'měď + zinek', 'kliky, trubky a trumpety, šroubení'],
              ['**bronz**', 'měď + cín', 'sochy, zvony, medaile'],
              ['**ocel**', 'železo + trocha uhlíku', 'stavby, nástroje, karoserie aut'],
              ['**nerezová ocel**', 'železo + chrom + nikl', 'příbory, dřezy, lékařské nástroje'],
              ['**dural**', 'hliník + měď + hořčík', 'letadla, rámy kol'],
              ['**pájka**', 'cín + stříbro + měď (dříve cín + olovo)', 'spojování součástek v elektronice'],
            ] },
            { type: 'elements', symbols: ['Cu', 'Zn', 'Sn', 'Fe', 'Cr', 'Ni', 'Al'], caption: 'Kovy, ze kterých se vyrábějí nejběžnější slitiny' },
            { type: 'callout', variant: 'fact', title: 'Kolik zlata je ve zlatém prstenu?', text: 'Šperky bývají ze slitiny zlata se stříbrem a mědí. Čtrnáctikarátové zlato obsahuje jen 585 dílů zlata z tisíce. Ryzí zlato je totiž tak měkké, že by se prsten brzy ohnul.' },
            { type: 'check', question: { kind: 'multi', q: 'Které předměty jsou vyrobené ze slitiny?', options: ['nerezový příbor', 'bronzová socha', 'drát z čisté mědi v elektroinstalaci', 'mosazná klika', 'cihla ryzího zlata v trezoru banky'], answers: [0, 1, 3], explain: 'Nerezová ocel, bronz a mosaz jsou slitiny. Drát z čisté mědi a ryzí zlato jsou kovy bez přídavku dalších složek.' } },
          ],
        },
        {
          title: 'Prvky a sloučeniny',
          blocks: [
            { type: 'p', text: 'Chemicky čisté látky se dělí do dvou skupin. **Prvek** je látka, kterou už žádnou chemickou reakcí nerozložíš na jednodušší látky. Třeba železo, síra, kyslík, zlato nebo uhlík. Dnes známe 118 prvků.' },
            { type: 'elements', symbols: ['H', 'C', 'O', 'S', 'Fe', 'Au'], caption: 'Několik prvků: vodík, uhlík, kyslík, síra, železo, zlato' },
            { type: 'p', text: '**Sloučenina** vzniká chemickým spojením dvou nebo více prvků a dá se chemicky rozložit na jednodušší látky. Třeba voda se elektrickým proudem rozloží na vodík a kyslík. Sloučeninou je i kuchyňská sůl, cukr nebo oxid uhličitý.' },
            { type: 'p', text: 'Sloučenina má **úplně jiné vlastnosti** než prvky, ze kterých vznikla. Sodík je měkký kov, který prudce reaguje s vodou. Chlor je jedovatý žlutozelený plyn. A jejich sloučenina? Kuchyňská sůl, kterou si sypeš na brambory.' },
            { type: 'example', title: 'Směs, nebo sloučenina? Železo a síra', problem: 'Smícháš železné piliny se sírou. Část směsi pak zahřeješ. Jak poznáš, že vznikla sloučenina?', steps: [
              'Ve směsi rozeznáš lupou šedá zrnka železa i žlutá zrnka síry.',
              'Magnet z nezahřáté směsi vytáhne železné piliny – složky jde oddělit fyzikálně.',
              'Po zahřátí se směs rozžhaví a žhnutí se šíří samo dál – uvolňuje se teplo, probíhá chemická reakce.',
              'Vznikne tmavě šedá látka, ve které už zrnka nerozeznáš, a magnet z ní železné piliny nevytáhne.',
            ], answer: 'Vznikla nová látka s novými vlastnostmi – sloučenina (sulfid železnatý; jak se takové názvy tvoří, se naučíš v úrovni 3).' },
            { type: 'callout', variant: 'warning', text: 'Pokus se železem a sírou dělá jen učitel v digestoři. Když síra při zahřívání začne hořet, vzniká dusivý a jedovatý oxid siřičitý.' },
            { type: 'table', headers: ['Skupina látek', 'Co pro ni platí', 'Příklady'], rows: [
              ['prvek', 'chemicky ji nerozložíš na jednodušší látky', 'železo, kyslík, síra'],
              ['sloučenina', 'chemicky ji rozložíš na prvky; má stálé složení', 'voda, sůl, oxid uhličitý'],
              ['směs', 'fyzikálně ji rozdělíš na složky; složení se může měnit', 'vzduch, mléko, mosaz'],
            ] },
            { type: 'callout', variant: 'remember', text: 'Prvek chemicky nerozložíš. Sloučeninu chemicky rozložíš na prvky. Směs rozdělíš fyzikálně na složky. Proč tomu tak je, pochopíš v úrovni 2, až nahlédneš do atomů.' },
            { type: 'game', gameId: 'swipe', text: 'Otestuj se v rychlé hře **Pravda, nebo lež?** – poznáš bez váhání prvek, sloučeninu a směs?' },
            { type: 'check', question: { kind: 'choice', q: 'Bílá látka se při zahřívání rozložila na plyn a černou pevnou látku. Co o ní víš jistě?', options: ['Není to prvek.', 'Je to směs.', 'Je to prvek.', 'Je to kov.'], answer: 0, explain: 'Prvek se na jednodušší látky rozložit nedá. Víme tedy jistě, že to prvek není. Jestli jde o sloučeninu, nebo o směs, z pokusu nepoznáme.' } },
          ],
        },
      ],
      summary: [
        'Chemicky čistá látka obsahuje jen jednu látku a má stálé vlastnosti.',
        'Směs obsahuje dvě a více složek; její vlastnosti závisí na jejich poměru.',
        'Ve stejnorodé směsi složky nerozlišíš ani mikroskopem, v různorodé ano.',
        'Různorodé směsi jsou suspenze, emulze, pěna, dým a mlha; dým a mlha jsou aerosoly.',
        'Slitiny, jako mosaz, bronz nebo ocel, jsou stejnorodé směsi kovů.',
        'Prvek chemicky nerozložíš, sloučenina se dá chemicky rozložit a má jiné vlastnosti než prvky, ze kterých vznikla.',
      ],
      quiz: [
        { kind: 'multi', q: 'Které látky jsou chemicky čisté?', options: ['destilovaná voda', 'kyslík', 'vzduch', 'cukr (sacharóza)', 'voda z kohoutku'], answers: [0, 1, 3], explain: 'Destilovaná voda, kyslík a čistý cukr jsou jednotlivé látky. Vzduch je směs plynů a voda z kohoutku obsahuje rozpuštěné minerální látky.' },
        { kind: 'tf', q: 'Slitiny jsou stejnorodé směsi.', answer: true, explain: 'Ve slitině jsou kovy promíseny tak dokonale, že složky nerozlišíš ani mikroskopem.' },
        { kind: 'match', q: 'Přiřaď k různorodé směsi její druh.', pairs: [['majonéza', 'emulze'], ['pěna na kapučínu', 'pěna'], ['kouř z táboráku', 'dým'], ['křída rozmíchaná ve vodě', 'suspenze']], explain: 'Majonéza je olej ve vodném prostředí, pěna je vzduch v mléce, kouř pevné částice ve vzduchu a křída ve vodě pevná látka v kapalině.' },
        { kind: 'choice', q: 'Z čeho se skládá bronz?', options: ['z mědi a cínu', 'z mědi a zinku', 'ze železa a uhlíku', 'z hliníku a hořčíku'], answer: 0, explain: 'Bronz je slitina mědi a cínu. Měď se zinkem tvoří mosaz, železo s uhlíkem ocel.' },
        { kind: 'tf', q: 'Sloučenina má vždy vlastnosti někde mezi vlastnostmi prvků, ze kterých vznikla.', answer: false, explain: 'Sloučenina má úplně nové vlastnosti. Z měkkého kovu sodíku a jedovatého plynu chloru vzniká jedlá kuchyňská sůl.' },
        { kind: 'choice', q: 'Voda se elektrickým proudem rozkládá na vodík a kyslík. Co z toho plyne?', options: ['Voda je sloučenina.', 'Voda je prvek.', 'Voda je směs vodíku a kyslíku.', 'Voda je slitina.'], answer: 0, explain: 'Látka, kterou lze chemicky rozložit na prvky, je sloučenina. Kdyby šlo o směs, složky bychom oddělili fyzikálně a měly by vlastnosti plynů.' },
        { kind: 'text', q: 'Jak se nazývá směs, ve které nerozlišíš složky ani mikroskopem? (Stačí jedno přídavné jméno.)', accept: ['stejnorodá', 'homogenní', 'stejnorodá směs', 'homogenní směs'], placeholder: '… směs', explain: 'Stejnorodá (homogenní) směs má všude stejné složení – třeba roztok soli nebo vzduch.' },
        { kind: 'choice', q: 'Neznámá bezbarvá kapalina vře a během varu její teplota postupně stoupá z 80 °C na 95 °C. Co to nejspíš je?', options: ['směs', 'chemicky čistá látka', 'prvek', 'sloučenina'], answer: 0, explain: 'Chemicky čistá látka vře při jedné stálé teplotě. Když se teplota během varu mění, jde o směs.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l1-4
    'l1-4': {
      id: 'l1-4',
      title: 'Jak oddělit složky směsí',
      goals: [
        'Popsat usazování, dekantaci, filtraci, odpařování, krystalizaci, destilaci, sublimaci, chromatografii, magnetickou separaci a odstřeďování',
        'Vybrat vhodnou metodu podle vlastností složek směsi',
        'Navrhnout postup rozdělení směsi o více složkách',
        'Vysvětlit, jak se v úpravně vyrábí pitná voda',
      ],
      hook: 'Představ si, že ti do misky se solí spadne hrst písku a pár železných pilin. Vyhodit? Kdepak! Chemik má na každou směs svůj trik. Dnes se je naučíš všechny.',
      sections: [
        {
          title: 'Usazování, dekantace a odstřeďování',
          blocks: [
            { type: 'p', text: 'Každá oddělovací metoda využívá toho, že se složky směsi v něčem liší: velikostí částic, hustotou, teplotou varu, rozpustností nebo magnetickými vlastnostmi.' },
            { type: 'p', text: 'Při **usazování (sedimentaci)** klesají těžší pevné částice suspenze vlivem gravitace ke dnu. Kapalinu nad usazeninou pak opatrně slijeme – tomu říkáme **dekantace**.' },
            { type: 'diagram', id: 'separation', props: { method: 'decantation' }, caption: 'Dekantace: kapalina se opatrně slévá z usazeniny' },
            { type: 'p', text: 'Dvě kapaliny, které se nemísí (olej a voda), oddělíš v **dělicí nálevce**. Kapalina s větší hustotou je dole, takže ji kohoutem vypustíš jako první.' },
            { type: 'p', text: '**Odstřeďování (centrifugace)** usazování mnohonásobně zrychlí. Směs se v odstředivce rychle točí a těžší částice se tlačí ke dnu. Tak se krev dělí na krevní plazmu a krvinky, z mléka se odstřeďuje smetana a pračka ždímá prádlo.' },
            { type: 'callout', variant: 'fact', text: 'Laboratorní centrifuga se točí rychlostí i přes 10 000 otáček za minutu. Částice v ní „cítí“ sílu tisíckrát větší, než je jejich tíha.' },
            { type: 'check', question: { kind: 'choice', q: 'Jak nejjednodušeji oddělíš olej od vody?', options: ['dělicí nálevkou', 'filtrací', 'magnetem', 'sublimací'], answer: 0, explain: 'Olej a voda se nemísí a mají různou hustotu. V dělicí nálevce vytvoří dvě vrstvy a spodní vodu vypustíš kohoutem.' } },
          ],
        },
        {
          title: 'Filtrace',
          blocks: [
            { type: 'p', text: '**Filtrace** odděluje pevné částice od kapaliny nebo plynu pomocí **filtru** s drobnými póry. Kapalina projde, pevné částice zůstanou na filtru. Kapalině, která filtrem prošla, říkáme **filtrát**.' },
            { type: 'diagram', id: 'separation', props: { method: 'filtration' }, caption: 'Filtrační aparatura: stojan, nálevka s filtračním papírem a kádinka' },
            { type: 'list', items: [
              'Filtrační papír slož do kužele a vlož do nálevky tak, aby byl asi 1 cm pod jejím okrajem.',
              'Papír navlhči destilovanou vodou, aby ke sklu přilnul.',
              'Stopka nálevky se má dotýkat stěny kádinky – filtrát pak stéká bez stříkání.',
              'Kapalinu lij po skleněné tyčince a hladinu udržuj pod okrajem papíru.',
            ] },
            { type: 'p', text: 'Filtry máš i doma: překapávač na kávu, sítko na čaj, filtr ve vysavači, respirátor nebo filtr v konvici na vodu.' },
            { type: 'callout', variant: 'warning', text: 'Filtrací neoddělíš látku rozpuštěnou ve vodě! Rozpuštěné částice jsou tak malé, že projdou každým filtračním papírem. Slaná voda projde filtrem pořád slaná.' },
            { type: 'check', question: { kind: 'tf', q: 'Filtrací lze z mořské vody odstranit rozpuštěnou sůl.', answer: false, explain: 'Sůl je v mořské vodě rozpuštěná a projde filtrem s vodou. Filtrací oddělíš jen nerozpuštěné pevné částice.' } },
          ],
        },
        {
          title: 'Odpařování, krystalizace a destilace',
          blocks: [
            { type: 'p', text: 'Při **odpařování** zahříváš roztok v odpařovací misce. Rozpouštědlo se vypaří a rozpuštěná pevná látka zůstane. Tak se už tisíce let získává mořská sůl v **salinách** – mělkých nádržích, ze kterých vodu odpaří slunce.' },
            { type: 'diagram', id: 'separation', props: { method: 'evaporation' }, caption: 'Odpařování: voda odchází jako pára, sůl zůstává v misce' },
            { type: 'p', text: 'Při **krystalizaci** se z horkého nasyceného roztoku při pomalém chladnutí vylučují pravidelné **krystaly**. Nečistoty zůstanou v roztoku, a tak se krystalizací látky zároveň čistí. (Co je nasycený roztok, zjistíš v příští lekci.)' },
            { type: 'p', text: '**Destilace** odděluje kapaliny s různou teplotou varu nebo kapalinu od rozpuštěných pevných látek. Směs se zahřívá, těkavější složka se vypaří, v **chladiči** zkapalní a stéká do předlohy jako **destilát**.' },
            { type: 'diagram', id: 'separation', props: { method: 'distillation' }, caption: 'Destilační aparatura s Liebigovým chladičem' },
            { type: 'list', items: [
              '**Destilační baňka** s **varnými kamínky** – kamínky brání utajenému varu.',
              '**Teploměr** – jeho baňka je ve výšce odbočky, kde měří teplotu odcházejících par.',
              '**Liebigův chladič** – chladicí voda přitéká spodem a odtéká horem, aby chladič byl stále plný.',
              '**Předloha (jímadlo)** – nádoba, do které stéká destilát.',
            ] },
            { type: 'callout', variant: 'fact', text: 'Destilací se vyrábí destilovaná voda, pálenky i vonné silice do parfémů. Rafinerie dělí destilací ropu na benzín, naftu a další frakce (úroveň 8). A dokonce i vzduch se po zkapalnění dělí destilací na dusík, kyslík a argon.' },
            { type: 'check', question: { kind: 'order', q: 'Seřaď, co se děje při destilaci slané vody.', items: ['Slaná voda se v baňce zahřeje k varu.', 'Vodní pára stoupá k odbočce baňky.', 'Pára v chladiči zkapalní.', 'Destilát (čistá voda) steče do předlohy.'], explain: 'Voda se vypaří, v chladiči znovu zkapalní a steče do předlohy. Sůl se nevypařuje, a proto zůstane v baňce.' } },
          ],
        },
        {
          title: 'Sublimace, chromatografie a magnet',
          blocks: [
            { type: 'p', text: '**Sublimací** oddělíš látku, která sublimuje (třeba jod), od látky, která nesublimuje (písek). Zahřátý jod se mění rovnou ve fialové páry. Na studeném dně baňky s ledovou vodou pak páry desublimují zpět na lesklé tmavé krystalky.' },
            { type: 'callout', variant: 'warning', text: 'Páry jodu dráždí oči a dýchací cesty. Sublimace jodu se proto dělá jen v digestoři.' },
            { type: 'p', text: 'Při **chromatografii** putují složky směsi spolu s rozpouštědlem po papíře nebo náplni kolony. Každá složka se pohybuje jinak rychle, takže se rozdělí do barevných skvrn nebo pásů. Chromatografie odhalí drogy v krvi, doping u sportovců i barviva v potravinách.' },
            { type: 'diagram', id: 'separation', props: { method: 'chromatography' }, caption: 'Papírová chromatografie: barviva putují s rozpouštědlem různě daleko' },
            { type: 'callout', variant: 'tip', title: 'Domácí pokus', text: 'Na proužek papírového filtru na kávu udělej asi 2 cm od spodního okraje tečku černou fixou, která se rozpouští ve vodě. Spodní okraj ponoř do vody tak, aby tečka zůstala nad hladinou. Za pár minut uvidíš, že „černá“ je ve skutečnosti směs modré, žluté a růžové.' },
            { type: 'p', text: 'Při **magnetické separaci** vytáhne magnet ze směsi látky, které přitahuje – hlavně železo, nikl a kobalt. Využívá se při třídění kovového odpadu a recyklaci plechovek.' },
            { type: 'elements', symbols: ['Fe', 'Co', 'Ni'], caption: 'Železo, kobalt a nikl – kovy, které přitahuje magnet' },
            { type: 'check', question: { kind: 'match', q: 'Přiřaď ke směsi nejvhodnější metodu oddělení.', pairs: [['jod a písek', 'sublimace'], ['barviva ve fixě', 'chromatografie'], ['železné piliny a písek', 'magnetická separace'], ['líh a voda', 'destilace']], explain: 'Jod sublimuje, barviva putují různě rychle, železo přitahuje magnet a líh vře při nižší teplotě než voda.' } },
          ],
        },
        {
          title: 'Jak vybrat správnou metodu',
          blocks: [
            { type: 'p', text: 'Než začneš, zeptej se: ==Čím se složky směsi liší?== Podle toho vybereš metodu.' },
            { type: 'table', headers: ['Metoda', 'Využívá rozdílu v…', 'Příklad'], rows: [
              ['usazování a dekantace', 'hustotě, nerozpustnosti', 'písek a voda'],
              ['odstřeďování', 'hustotě', 'krev, smetana z mléka'],
              ['filtrace', 'velikosti částic', 'kávová sedlina a káva'],
              ['odpařování, krystalizace', 'těkavosti (pevná látka se nevypaří)', 'sůl z mořské vody'],
              ['destilace', 'teplotě varu', 'líh a voda, destilovaná voda'],
              ['sublimace', 'schopnosti sublimovat', 'jod a písek'],
              ['chromatografie', 'rychlosti putování s rozpouštědlem', 'barviva v inkoustu'],
              ['magnetická separace', 'magnetických vlastnostech', 'železné piliny a síra'],
            ] },
            { type: 'example', title: 'Písek, sůl a železné piliny', problem: 'Máš směs písku, kuchyňské soli a železných pilin. Jak získáš každou složku zvlášť?', steps: [
              'Magnetem vytáhni železné piliny.',
              'Zbytek zalij vodou a zamíchej – sůl se rozpustí, písek ne.',
              'Přefiltruj: písek zůstane na filtru, roztok soli proteče jako filtrát.',
              'Filtrát odpař v odpařovací misce – zůstane sůl.',
            ], answer: 'Magnet -> rozpuštění ve vodě -> filtrace -> odpaření. Získáš železo, písek i sůl.' },
            { type: 'callout', variant: 'tip', text: 'Ke každé složce si napiš její vlastnosti: rozpouští se ve vodě? přitahuje ji magnet? vypaří se snadno? Postup pak vyplyne sám.' },
            { type: 'check', question: { kind: 'choice', q: 'Kterou metodou získáš z inkoustu čistou vodu?', options: ['destilací', 'filtrací', 'dekantací', 'magnetickou separací'], answer: 0, explain: 'Barviva jsou ve vodě rozpuštěná, takže projdou filtrem a neusadí se. Destilací se voda vypaří a v chladiči zkapalní, barviva zůstanou v baňce.' } },
          ],
        },
        {
          title: 'Oddělování v praxi: úpravna vody',
          blocks: [
            { type: 'p', text: 'Voda z řeky nebo přehrady obsahuje písek, bahno, zbytky rostlin a mikroorganismy. V **úpravně vody** z ní vyrobí pitnou vodu – a používá k tomu metody, které už znáš.' },
            { type: 'list', ordered: true, items: [
              '**Česle a síta** zachytí větve, listí a jiné hrubé nečistoty (hrubá filtrace).',
              '**Čiření:** do vody se přidá látka (třeba síran hlinitý nebo železitý), ze které se tvoří vločky. Na ně se nalepí jemné nečistoty.',
              '**Usazování:** vločky klesnou v usazovací nádrži ke dnu.',
              '**Filtrace** přes vrstvu písku, někdy i přes **aktivní uhlí**, které pohltí pachy a pachuti.',
              '**Dezinfekce:** chlor, oxid chloričitý, ozon nebo UV záření zničí bakterie a viry.',
            ] },
            { type: 'callout', variant: 'fact', text: 'Kdyby se pitná voda nedezinfikovala, šířily by se jí nemoci jako cholera nebo břišní tyfus. Úprava vody zachránila víc životů než většina léků.' },
            { type: 'p', text: 'Co se děje s vodou, když odteče do kanalizace, a čím se liší úpravna od čistírny odpadních vod, uvidíš v lekci 6.' },
            { type: 'game', gameId: 'quickfire', text: 'Rozehřej se v **Bleskové výzvě**: stihneš za minutu přiřadit co nejvíc směsí ke správné metodě?' },
            { type: 'check', question: { kind: 'order', q: 'Seřaď kroky úpravy vody na pitnou.', items: ['Česle zachytí hrubé nečistoty.', 'Čiření – vznikají vločky.', 'Vločky se usadí.', 'Písková filtrace.', 'Dezinfekce chlorem, ozonem nebo UV zářením.'], explain: 'Nejdřív se odstraní hrubé nečistoty, pak jemné (čiření, usazování, filtrace) a nakonec se voda dezinfikuje, aby v potrubí zůstala nezávadná.' } },
          ],
        },
      ],
      summary: [
        'Oddělovací metody využívají rozdílů ve vlastnostech složek: hustotě, velikosti částic, teplotě varu, rozpustnosti nebo magnetismu.',
        'Usazování s dekantací a odstřeďování využívají rozdílné hustoty, filtrace velikosti částic.',
        'Filtrací neoddělíš rozpuštěnou látku; tu získáš odpařením nebo krystalizací.',
        'Destilace odděluje kapaliny s různou teplotou varu; pára zkapalní v chladiči a stéká do předlohy.',
        'Sublimací oddělíš jod, chromatografií barviva a magnetem železo.',
        'Úpravna vody používá česle, čiření, usazování, filtraci a dezinfekci.',
      ],
      quiz: [
        { kind: 'choice', q: 'Na jakém rozdílu ve vlastnostech složek je založena destilace?', options: ['na rozdílné teplotě varu', 'na rozdílné velikosti částic', 'na rozdílných magnetických vlastnostech', 'na rozdílné barvě'], answer: 0, explain: 'Při destilaci se nejdřív vypaří složka s nižší teplotou varu, zkapalní v chladiči a oddělí se od ostatních.' },
        { kind: 'tf', q: 'Chromatografií se dají rozdělit barviva obsažená v inkoustu.', answer: true, explain: 'Barviva putují s rozpouštědlem po papíře různě rychle, a proto se rozdělí na barevné skvrny.' },
        { kind: 'multi', q: 'Které směsi lze rozdělit filtrací?', options: ['písek a voda', 'křída rozmíchaná ve vodě', 'cukr rozpuštěný ve vodě', 'líh a voda', 'kávová sedlina a káva'], answers: [0, 1, 4], explain: 'Filtrem se zachytí jen nerozpuštěné pevné částice – písek, křída a sedlina. Rozpuštěný cukr i líh projdou s vodou.' },
        { kind: 'match', q: 'Přiřaď k činnosti z běžného života oddělovací metodu.', pairs: [['ždímání prádla v pračce', 'odstřeďování'], ['získávání soli v salinách', 'odpařování'], ['překapávaná káva', 'filtrace'], ['výroba pálenky', 'destilace']], explain: 'Pračka odstřeďuje vodu, slunce odpařuje mořskou vodu, filtr zadrží kávovou sedlinu a destilací se odděluje alkohol.' },
        { kind: 'order', q: 'Seřaď kroky, kterými ze směsi soli a písku získáš čistou sůl.', items: ['Směs zalij vodou a zamíchej.', 'Směs přefiltruj.', 'Filtrát odpař v odpařovací misce.', 'V misce zůstane sůl.'], explain: 'Sůl se ve vodě rozpustí a proteče filtrem, písek zůstane na filtru. Odpařením filtrátu pak získáš sůl.' },
        { kind: 'choice', q: 'K čemu slouží varné kamínky v destilační baňce?', options: ['brání utajenému varu', 'zrychlují chlazení par', 'zachytávají nečistoty', 'zvyšují teplotu varu'], answer: 0, explain: 'Na kamíncích se tvoří drobné bublinky, takže kapalina vře klidně a nevystříkne.' },
        { kind: 'tf', q: 'Chladicí voda v Liebigově chladiči přitéká horem a odtéká spodem.', answer: false, explain: 'Voda přitéká spodem a odtéká horem. Jen tak je chladič celý zaplněný vodou a chladí nejlépe.' },
        { kind: 'text', q: 'Jak se nazývá kapalina, která prošla filtrem?', accept: ['filtrát'], placeholder: 'jedno slovo', explain: 'Kapalina, která prošla filtrem, je filtrát. Pevné částice zůstávají na filtru.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l1-5
    'l1-5': {
      id: 'l1-5',
      title: 'Roztoky a hmotnostní zlomek',
      goals: [
        'Popsat roztok jako rozpuštěnou látku v rozpouštědle a rozlišit nasycený, nenasycený a přesycený roztok',
        'Vyčíst rozpustnost z tabulky a vysvětlit, jak ji ovlivňuje teplota',
        'Spočítat hmotnostní zlomek a připravit roztok o daném složení',
        'Počítat ředění, zahušťování a míchání roztoků',
      ],
      hook: 'Fyziologický roztok v nemocnici, ocet v kuchyni i ionťák po tréninku – to všechno jsou roztoky a u všech záleží na tom, kolik čeho obsahují. Kdyby měl fyziologický roztok desetkrát víc soli, pacientovi by uškodil. Pojďme počítat!',
      sections: [
        {
          title: 'Co je roztok',
          blocks: [
            { type: 'p', text: '**Roztok** je stejnorodá směs. Skládá se z **rozpouštědla** (té látky, které je víc – nejčastěji vody) a jedné nebo více **rozpuštěných látek**.' },
            { type: 'formula', text: 'roztok = rozpuštěná látka + rozpouštědlo' },
            { type: 'table', headers: ['Roztok', 'Rozpuštěná látka', 'Rozpouštědlo', 'Skupenství roztoku'], rows: [
              ['slaná voda', 'kuchyňská sůl', 'voda', 'kapalné'],
              ['sodovka', 'oxid uhličitý', 'voda', 'kapalné'],
              ['jodová tinktura', 'jod', 'líh', 'kapalné'],
              ['vzduch', 'kyslík, argon a další plyny', 'dusík', 'plynné'],
              ['mosaz', 'zinek', 'měď', 'pevné'],
            ] },
            { type: 'p', text: 'Voda rozpouští tolik látek, že se jí říká „univerzální rozpouštědlo“. Tuk ale nerozpustí. Na mastnou skvrnu potřebuješ jiné rozpouštědlo, třeba technický benzín, nebo prostředek na nádobí.' },
            { type: 'callout', variant: 'tip', text: 'Roztok je vždy čirý (průhledný). Může být barevný, jako čaj, ale nikdy není kalný. Když je kapalina kalná, nejde o roztok, ale o suspenzi nebo emulzi.' },
            { type: 'check', question: { kind: 'tf', q: 'V jodové tinktuře je rozpouštědlem líh.', answer: true, explain: 'Jod se ve vodě rozpouští jen málo, proto se jodová tinktura připravuje rozpuštěním jodu v lihu.' } },
          ],
        },
        {
          title: 'Nasycený, nenasycený a přesycený roztok',
          blocks: [
            { type: 'p', text: 'Sypeš do vody cukr a mícháš. Zpočátku se rozpouští, ale jednou přijde chvíle, kdy se další cukr už nerozpustí a zůstane ležet na dně. Roztok je **nasycený**.' },
            { type: 'keyterms', items: [
              { term: '**nenasycený roztok**', def: 'při dané teplotě v něm rozpustíš ještě další látku' },
              { term: '**nasycený roztok**', def: 'při dané teplotě v něm už víc látky nerozpustíš' },
              { term: '**přesycený roztok**', def: 'obsahuje víc rozpuštěné látky než nasycený; je nestálý a při otřesu nebo po vhození krystalku z něj nadbytek vykrystalizuje' },
            ] },
            { type: 'p', text: 'Přesycený roztok se připraví tak, že za tepla vytvoříš nasycený roztok a opatrně, bez otřesů, ho ochladíš. Nadbytečná látka zůstane rozpuštěná, dokud nedostane podnět ke krystalizaci.' },
            { type: 'callout', variant: 'fact', title: 'Ohřívací polštářek', text: 'Uvnitř je přesycený roztok octanu sodného. Když cvakneš kovovou destičkou, spustíš krystalizaci. Roztok ztuhne a uvolní teplo – polštářek se ohřeje asi na 50 °C. Povařením ve vodě se krystaly znovu rozpustí a polštářek můžeš použít znovu.' },
            { type: 'callout', variant: 'mascot', text: 'Přesycený roztok je jako třída pět minut před zvoněním. Navenek klid, ale stačí jeden impuls – a všechno se dá do pohybu!' },
            { type: 'check', question: { kind: 'choice', q: 'Do roztoku soli vhodíš malý krystalek soli a ten se rozpustí. Jaký byl roztok?', options: ['nenasycený', 'nasycený', 'přesycený', 'emulze'], answer: 0, explain: 'Rozpustila se další sůl, takže roztok ještě nebyl nasycený. V nasyceném by krystalek zůstal, v přesyceném by kolem něj začaly růst krystaly.' } },
          ],
        },
        {
          title: 'Rozpustnost a teplota',
          blocks: [
            { type: 'p', text: '**Rozpustnost** udává, kolik gramů látky se při dané teplotě nejvýše rozpustí ve 100 g vody. Vznikne přitom nasycený roztok.' },
            { type: 'table', headers: ['Teplota', 'kuchyňská sůl $NaCl$', 'dusičnan draselný $KNO3$', 'cukr (sacharóza)'], rows: [
              ['0 °C', '35,7 g', '13,3 g', '179 g'],
              ['20 °C', '36,0 g', '31,6 g', '204 g'],
              ['40 °C', '36,6 g', '63,9 g', '238 g'],
              ['60 °C', '37,3 g', '110 g', '287 g'],
              ['80 °C', '38,4 g', '169 g', '362 g'],
              ['100 °C', '39,8 g', '246 g', '487 g'],
            ], caption: 'Rozpustnost ve 100 g vody (jak se tvoří názvy solí, jako je dusičnan draselný, se naučíš v úrovni 5)' },
            { type: 'p', text: 'Když rozpustnost zakreslíš do grafu proti teplotě, dostaneš **křivku rozpustnosti**. U dusičnanu draselného strmě stoupá, u kuchyňské soli je skoro vodorovná. Z křivky i z tabulky vyčteš, kolik látky se při určité teplotě rozpustí.' },
            { type: 'example', title: 'Kolik krystalů se vyloučí?', problem: 'Ve 100 g vody při 60 °C je rozpuštěno nejvíce dusičnanu draselného, kolik jde. Roztok ochladíš na 20 °C. Kolik gramů krystalů se vyloučí?', steps: [
              'Při 60 °C se ve 100 g vody rozpustí 110 g $KNO3$ (tabulka).',
              'Při 20 °C se ve 100 g vody udrží rozpuštěných jen 31,6 g.',
              'Zbytek se vyloučí jako krystaly: 110 g − 31,6 g = 78,4 g.',
            ], answer: 'Vyloučí se 78,4 g krystalů $KNO3$.' },
            { type: 'callout', variant: 'remember', text: 'Rozpustnost většiny pevných látek s teplotou **roste**. Rozpustnost plynů s teplotou **klesá** – teplá limonáda rychleji vyčichne a ryby mají v létě v teplé vodě méně kyslíku.' },
            { type: 'list', items: [
              '**mícháním** – k pevné látce se stále dostává „čerstvá“ voda,',
              '**zahřátím** – částice se pohybují rychleji,',
              '**rozdrcením** – práškový cukr má větší povrch než kostka.',
            ] },
            { type: 'callout', variant: 'warning', text: 'Míchání a rozdrcení rozpouštění jen **urychlí**, ale rozpustnost nezmění – nerozpustí se víc látky. Rozpustnost pevné látky ve vodě změní teplota.' },
            { type: 'check', question: { kind: 'number', q: 'Kolik gramů dusičnanu draselného se nejvýše rozpustí ve 200 g vody při 40 °C?', answer: 127.8, tolerance: 0.5, unit: 'g', explain: 'Ve 100 g vody se při 40 °C rozpustí 63,9 g, ve 200 g vody dvojnásobek: 2 · 63,9 g = 127,8 g.' } },
          ],
        },
        {
          title: 'Hmotnostní zlomek',
          blocks: [
            { type: 'p', text: 'Složení roztoku nejčastěji vyjadřujeme **hmotnostním zlomkem** $w$. Říká, jakou část hmotnosti celého roztoku tvoří rozpuštěná látka.' },
            { type: 'formula', text: '$w(A) = m(A) / m(roztoku)$', caption: 'kde $m(roztoku) = m(A) + m(rozpouštědla)$' },
            { type: 'p', text: 'Hmotnostní zlomek je číslo od 0 do 1 a nemá jednotku. Když ho vynásobíš stem, dostaneš **procenta**: $w$ = 0,09 znamená 9 %.' },
            { type: 'example', title: 'Kolik procent cukru?', problem: 'Rozpustíš 20 g cukru ve 180 g vody. Jaký je hmotnostní zlomek cukru v roztoku?', steps: [
              'Hmotnost roztoku: $m(roztoku)$ = 20 g + 180 g = 200 g',
              '$w$ = 20 g : 200 g = 0,10',
            ], answer: '$w$ = 0,10, tedy 10 %' },
            { type: 'example', title: 'Příprava fyziologického roztoku', problem: 'Připrav 500 g fyziologického roztoku, ve kterém je hmotnostní zlomek $NaCl$ 0,009 (0,9 %). Kolik soli a kolik vody potřebuješ?', steps: [
              'Ze vzorce vyjádříme hmotnost soli: $m(NaCl) = w · m(roztoku)$',
              '$m(NaCl)$ = 0,009 · 500 g = 4,5 g',
              '$m(vody)$ = 500 g − 4,5 g = 495,5 g',
            ], answer: 'Potřebuješ 4,5 g soli a 495,5 g vody (to je asi 495,5 ml, protože 1 ml vody má hmotnost přibližně 1 g).' },
            { type: 'callout', variant: 'warning', title: 'Nejčastější chyba', text: 'Nedělit hmotností vody! Do jmenovatele patří hmotnost **celého roztoku**, tedy rozpuštěné látky i rozpouštědla.' },
            { type: 'callout', variant: 'fact', text: 'Fyziologický roztok (0,9 % $NaCl$) má stejnou koncentraci solí jako krevní plazma, proto se smí podávat přímo do žíly. Kvasný ocet mívá 8 % kyseliny octové a peroxid vodíku z lékárny 3 %.' },
            { type: 'p', text: 'Složení roztoků se dá vyjádřit i jinak, třeba molární koncentrací. Tu poznáš v úrovni 4.' },
            { type: 'check', question: { kind: 'number', q: 'V 300 g roztoku je rozpuštěno 45 g soli. Kolik procent soli roztok obsahuje?', answer: 15, unit: '%', explain: '$w$ = 45 g : 300 g = 0,15, tedy 15 %.' } },
          ],
        },
        {
          title: 'Ředění, zahušťování a míchání',
          blocks: [
            { type: 'p', text: 'Když k roztoku přidáš vodu (**ředění**), rozpuštěné látky je pořád stejně, jen přibude roztoku – hmotnostní zlomek klesne. Když vodu odpaříš (**zahušťování**), hmotnostní zlomek stoupne.' },
            { type: 'callout', variant: 'remember', text: 'Při ředění i zahušťování se ==nemění hmotnost rozpuštěné látky==. Z toho vychází každý výpočet.' },
            { type: 'example', title: 'Ředění', problem: 'K 200 g 15% roztoku přileješ 100 g vody. Jaký je nový hmotnostní zlomek?', steps: [
              'Rozpuštěná látka: $m$ = 0,15 · 200 g = 30 g',
              'Nová hmotnost roztoku: 200 g + 100 g = 300 g',
              '$w$ = 30 g : 300 g = 0,10',
            ], answer: 'Nový roztok je 10%.' },
            { type: 'example', title: 'Kolik vody přidat?', problem: 'Kolik vody musíš přidat k 50 g 30% roztoku, aby vznikl 10% roztok?', steps: [
              'Rozpuštěná látka: 0,30 · 50 g = 15 g',
              'Při $w$ = 0,10 musí mít roztok hmotnost 15 g : 0,10 = 150 g',
              'Přidaná voda: 150 g − 50 g = 100 g',
            ], answer: 'Přidáš 100 g vody.' },
            { type: 'example', title: 'Zahušťování', problem: 'Ze 400 g 5% roztoku soli odpaříš 150 g vody. Jaký je hmotnostní zlomek soli teď?', steps: [
              'Sůl: 0,05 · 400 g = 20 g (odpařením se nezmění)',
              'Nová hmotnost roztoku: 400 g − 150 g = 250 g',
              '$w$ = 20 g : 250 g = 0,08',
            ], answer: 'Roztok je nyní 8%.' },
            { type: 'formula', text: '$m1 · w1 + m2 · w2 = (m1 + m2) · w$', caption: 'směšovací rovnice: látka z obou roztoků se sečte; čistá voda má $w$ = 0' },
            { type: 'example', title: 'Míchání roztoků', problem: 'Smícháš 100 g 20% roztoku a 300 g 4% roztoku. Jaký je hmotnostní zlomek výsledného roztoku?', steps: [
              'Látka z prvního roztoku: 0,20 · 100 g = 20 g',
              'Látka z druhého roztoku: 0,04 · 300 g = 12 g',
              'Celkem 32 g látky ve 100 g + 300 g = 400 g roztoku',
              '$w$ = 32 g : 400 g = 0,08',
            ], answer: 'Výsledný roztok je 8%.' },
            { type: 'callout', variant: 'tip', title: 'Křížové pravidlo', text: 'Chceš smíchat 40% a 10% roztok tak, aby vznikl 20%? Od 40 odečti 20 = 20 dílů 10% roztoku. Od 20 odečti 10 = 10 dílů 40% roztoku. Poměr 10 : 20 = 1 : 2, tedy 1 díl 40% a 2 díly 10% roztoku (díly jsou hmotnostní). S „křížovým pravidlem“ pro vzorce z úrovně 3 to nemá nic společného.' },
            { type: 'game', gameId: 'quickfire', text: 'Procvič si hmotnostní zlomek v **Bleskové výzvě** – rychle, ale s kalkulačkou v hlavě!' },
            { type: 'check', question: { kind: 'number', q: 'Smícháš 150 g 10% roztoku cukru a 50 g 30% roztoku cukru. Kolik procent cukru má výsledný roztok?', answer: 15, unit: '%', explain: 'Cukr: 0,10 · 150 g + 0,30 · 50 g = 15 g + 15 g = 30 g. Roztok: 200 g. $w$ = 30 g : 200 g = 0,15, tedy 15 %.' } },
          ],
        },
      ],
      summary: [
        'Roztok je stejnorodá směs rozpouštědla a rozpuštěné látky; nejběžnějším rozpouštědlem je voda.',
        'Nasycený roztok už při dané teplotě další látku nerozpustí; přesycený roztok je nestálý a snadno krystalizuje.',
        'Rozpustnost pevných látek s teplotou většinou roste, rozpustnost plynů klesá.',
        'Míchání, zahřátí a rozdrcení rozpouštění urychlí.',
        'Hmotnostní zlomek je $w = m(látky) / m(roztoku)$; vynásobený stem udává procenta.',
        'Při ředění a zahušťování se hmotnost rozpuštěné látky nemění; při míchání se látka z obou roztoků sčítá.',
      ],
      quiz: [
        { kind: 'choice', q: 'Co je rozpouštědlem ve slazeném čaji?', options: ['voda', 'cukr', 'čajové lístky', 'citronová šťáva'], answer: 0, explain: 'Rozpouštědlem je látka, které je v roztoku nejvíc a ve které se ostatní látky rozpouštějí – tedy voda.' },
        { kind: 'tf', q: 'Mícháním zvýšíš rozpustnost cukru ve vodě.', answer: false, explain: 'Míchání rozpouštění jen urychlí. Kolik cukru se nejvýše rozpustí, určuje teplota.' },
        { kind: 'match', q: 'Přiřaď druh roztoku k popisu.', pairs: [['nenasycený roztok', 'rozpustí ještě další látku'], ['nasycený roztok', 'při dané teplotě už víc látky nerozpustí'], ['přesycený roztok', 'nestálý, při podnětu z něj vykrystalizuje nadbytek']], explain: 'Nasycený roztok obsahuje přesně tolik látky, kolik jde při dané teplotě rozpustit. Přesycený víc, nenasycený méně.' },
        { kind: 'number', q: 'Kolik gramů soli potřebuješ na přípravu 400 g 5% roztoku?', answer: 20, unit: 'g', explain: '$m$ = 0,05 · 400 g = 20 g soli (a 380 g vody).' },
        { kind: 'number', q: 'K 80 g 25% roztoku přileješ 120 g vody. Kolik procent má nový roztok?', answer: 10, unit: '%', explain: 'Látka: 0,25 · 80 g = 20 g. Nový roztok: 80 g + 120 g = 200 g. $w$ = 20 g : 200 g = 0,10, tedy 10 %.' },
        { kind: 'tf', q: 'Rozpustnost kyslíku ve vodě se s rostoucí teplotou snižuje.', answer: true, explain: 'Rozpustnost plynů s teplotou klesá. Proto mají ryby v teplé vodě v létě málo kyslíku.' },
        { kind: 'multi', q: 'Co urychlí rozpouštění kostky cukru v čaji?', options: ['míchání lžičkou', 'rozdrcení kostky', 'zahřátí čaje', 'přisypání dalšího cukru', 'použití většího hrnku'], answers: [0, 1, 2], explain: 'Míchání přivádí k cukru čerstvou vodu, rozdrcení zvětší povrch a zahřátí zrychlí pohyb částic.' },
        { kind: 'number', q: 'Smícháš 200 g 30% roztoku a 300 g 10% roztoku. Kolik procent má výsledný roztok?', answer: 18, unit: '%', explain: 'Látka: 0,30 · 200 g + 0,10 · 300 g = 60 g + 30 g = 90 g. Roztok: 500 g. $w$ = 90 g : 500 g = 0,18, tedy 18 %.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l1-6
    'l1-6': {
      id: 'l1-6',
      title: 'Voda a vzduch',
      goals: [
        'Rozlišit vodu destilovanou, pitnou, užitkovou, odpadní a minerální a vysvětlit tvrdost vody',
        'Porovnat úpravnu vody a čistírnu odpadních vod',
        'Popsat složení vzduchu, podmínky hoření a způsoby hašení',
        'Vysvětlit vznik smogu a kyselých dešťů a rozdíl mezi ozonovou vrstvou a přízemním ozonem',
      ],
      hook: 'Bez jídla vydržíš týdny, bez vody pár dní, ale bez vzduchu jen pár minut. Přesto obojí bereme jako samozřejmost – dokud z kohoutku neteče hnědá voda nebo nad městem nevisí smog.',
      sections: [
        {
          title: 'Druhy vod',
          blocks: [
            { type: 'p', text: 'Voda pokrývá asi 71 % povrchu Země, ale sladká je jen asi 2,5 % veškeré vody – a většina z ní je zamrzlá v ledovcích. Voda, kterou pijeme, je proto vzácnější, než se zdá.' },
            { type: 'table', headers: ['Druh vody', 'Co o ní platí', 'Použití'], rows: [
              ['**destilovaná**', 'získaná destilací, bez rozpuštěných látek', 'laboratoř, lékárny, žehličky'],
              ['**pitná**', 'zdravotně nezávadná, obsahuje malé množství rozpuštěných minerálních látek', 'pití, vaření, hygiena'],
              ['**užitková**', 'není určená k pití, ale smí se použít na mytí, splachování nebo zalévání', 'úklid, WC, zahrada, průmysl'],
              ['**odpadní**', 'znečištěná po použití v domácnostech a továrnách', 'odtéká kanalizací do čistírny'],
              ['**minerální**', 'obsahuje hodně rozpuštěných minerálních látek (často přes 1 g v litru) nebo oxid uhličitý; některé jsou léčivé', 'pití, lázně (Karlovy Vary, Luhačovice)'],
            ] },
            { type: 'p', text: '**Tvrdost vody** způsobují rozpuštěné sloučeniny vápníku a hořčíku. **Tvrdá voda** jich obsahuje hodně, **měkká voda** málo. Měkká je třeba voda dešťová nebo destilovaná.' },
            { type: 'elements', symbols: ['Ca', 'Mg'], caption: 'Vápník a hořčík – původci tvrdosti vody' },
            { type: 'list', items: [
              'v konvici a na topných spirálách se tvoří **vodní kámen**,',
              'mýdlo a šampon v ní hůř pění,',
              'na sklenicích a bateriích zůstávají bílé skvrny.',
            ] },
            { type: 'callout', variant: 'tip', title: 'Vodní kámen v konvici', text: 'Vodní kámen odstraníš octem nebo kyselinou citronovou – obojí ho rozpouští. Pak konvici důkladně vypláchni. Proč to funguje, zjistíš v úrovni 5.' },
            { type: 'check', question: { kind: 'tf', q: 'Destilovaná voda je měkká voda.', answer: true, explain: 'Destilovaná voda neobsahuje téměř žádné rozpuštěné látky, tedy ani sloučeniny vápníku a hořčíku. Je dokonale měkká.' } },
            { type: 'check', question: { kind: 'choice', q: 'K čemu smíš použít užitkovou vodu?', options: ['k zalévání zahrady', 'k vaření čaje', 'k pití', 'k přípravě kojenecké výživy'], answer: 0, explain: 'Užitková voda není zdravotně zaručená, takže se nesmí pít ani používat na přípravu jídla. Na zalévání nebo splachování je ale ideální.' } },
          ],
        },
        {
          title: 'Úpravna vody × čistírna odpadních vod',
          blocks: [
            { type: 'p', text: 'Tyhle dvě stavby si lidé často pletou, ale dělají opačnou práci. **Úpravna vody** vyrábí z vody z řeky, přehrady nebo studny **pitnou vodu**. **Čistírna odpadních vod (ČOV)** čistí **použitou vodu** z kanalizace, aby ji mohla vrátit do řeky.' },
            { type: 'table', headers: ['', 'Úpravna vody', 'Čistírna odpadních vod'], rows: [
              ['vstup', 'surová voda z přírody', 'odpadní voda z kanalizace'],
              ['výstup', 'pitná voda do vodovodu', 'vyčištěná voda do řeky'],
              ['hlavní kroky', 'česle, čiření, usazování, filtrace, dezinfekce', 'mechanické a biologické čištění, zpracování kalu'],
            ] },
            { type: 'p', text: 'ČOV má dva hlavní stupně. **Mechanický stupeň** odstraní pevné nečistoty. V **biologickém stupni** se do vody vhání vzduch a mikroorganismy (hlavně bakterie) „sežerou“ rozpuštěné znečištění z odpadní vody.' },
            { type: 'list', ordered: true, items: [
              '**Česle** zachytí hadry, plasty a větve.',
              '**Lapák písku** – usadí se písek a štěrk.',
              '**Usazovací nádrž** – usadí se jemnější nečistoty.',
              '**Aktivační nádrž** – bakterie rozkládají znečištění, do vody se vhání vzduch.',
              '**Dosazovací nádrž** – usadí se kal s bakteriemi.',
              'Vyčištěná voda odtéká do řeky.',
            ] },
            { type: 'diagram', id: 'separation', props: { method: 'decantation' }, caption: 'Usazování je základem úpravny vody i čistírny – jen v obřích nádržích' },
            { type: 'callout', variant: 'fact', text: 'Z kalu se ve velkých čistírnách vyrábí ve vyhnívacích nádržích **bioplyn**. Jeho spalováním získávají čistírny elektřinu a teplo pro vlastní provoz.' },
            { type: 'callout', variant: 'warning', text: 'Do záchodu nepatří vlhčené ubrousky, tuk z pánve ani léky. Ubrousky ucpávají čerpadla, tuk v potrubí ztuhne a léky čistírna neumí úplně odstranit – skončí v řece.' },
            { type: 'check', question: { kind: 'choice', q: 'Ve které části čistírny odpadních vod pracují bakterie?', options: ['v aktivační nádrži', 'v česlích', 'v lapáku písku', 've vodovodním potrubí'], answer: 0, explain: 'V aktivační nádrži bakterie za přívodu vzduchu rozkládají znečištění. Česle a lapák písku čistí jen mechanicky.' } },
          ],
        },
        {
          title: 'Z čeho je vzduch',
          blocks: [
            { type: 'p', text: '**Vzduch** je stejnorodá směs plynů. Suchý vzduch má v přízemní vrstvě atmosféry po celé Zemi téměř stejné složení:' },
            { type: 'table', headers: ['Plyn', 'Objemová procenta', 'Zajímavost'], rows: [
              ['dusík $N2$', '78 %', 'málo reaktivní; plní se jím sáčky s chipsy'],
              ['kyslík $O2$', '21 %', 'potřebujeme ho k dýchání, podporuje hoření'],
              ['argon $Ar$', '0,9 %', 'vzácný plyn; ochranná atmosféra při svařování'],
              ['oxid uhličitý $CO2$', '0,04 %', 'rostliny z něj fotosyntézou vyrábějí cukry; skleníkový plyn'],
              ['neon, helium, methan, vodík…', 'stopy', 'dohromady méně než 0,01 %'],
            ] },
            { type: 'p', text: 'Navíc vzduch obsahuje proměnlivé množství **vodní páry** (zhruba 0–4 %) a prachu. Vzorce jako $N2$ nebo $CO2$ zatím ber jako zkratky – co znamenají, zjistíš v úrovni 2.' },
            { type: 'p', text: 'Složení vzduchu udáváme v **objemových procentech**: ve 100 litrech vzduchu je asi 78 litrů dusíku a 21 litrů kyslíku. Stejně se udává obsah alkoholu v nápojích, třeba „40 % obj.“.' },
            { type: 'elements', symbols: ['N', 'O', 'Ar', 'C', 'Ne', 'He'], caption: 'Prvky, které najdeš ve vzduchu (uhlík v podobě oxidu uhličitého)' },
            { type: 'p', text: 'V průmyslu se vzduch ochladí na teplotu kolem −200 °C, zkapalní se a pak se destilací rozdělí. Jde to proto, že jeho složky mají různé teploty varu: dusík −196 °C, argon −186 °C a kyslík −183 °C.' },
            { type: 'callout', variant: 'fact', text: 'Kapalný dusík (−196 °C) se používá ke zmrazování vzorků v medicíně i k výrobě „kouřící“ zmrzliny. Holou rukou se ho ale nikdy nedotýkej – způsobuje těžké omrzliny.' },
            { type: 'callout', variant: 'remember', text: 'Dusík 78 %, kyslík 21 %, argon necelé 1 %, oxid uhličitý 0,04 %.' },
            { type: 'check', question: { kind: 'number', q: 'Kolik litrů kyslíku je přibližně ve 200 litrech suchého vzduchu?', answer: 42, tolerance: 1, unit: 'l', explain: 'Kyslík tvoří 21 % objemu vzduchu: 0,21 · 200 l = 42 l.' } },
          ],
        },
        {
          title: 'Kyslík a hoření',
          blocks: [
            { type: 'p', text: '**Hoření** je rychlá chemická reakce hořlavé látky s kyslíkem, při které se uvolňuje teplo a světlo. Kyslík sám nehoří, ale hoření **podporuje**. Když doutnající špejli vložíš do čistého kyslíku, znovu vzplane.' },
            { type: 'p', text: 'Aby něco hořelo, musí být současně splněny tři podmínky. Říká se jim **požární trojúhelník**:' },
            { type: 'list', items: [
              '**hořlavá látka** – dřevo, papír, benzín, plyn,',
              '**kyslík** – obvykle ze vzduchu,',
              '**dostatečně vysoká teplota** – látka musí být zahřátá na svou **zápalnou teplotu**.',
            ] },
            { type: 'p', text: 'Hašení znamená odebrat aspoň jednu stranu trojúhelníku: **ochladit** hořící látku (voda), **zamezit přístupu kyslíku** (deka, písek, pěna, oxid uhličitý) nebo **odstranit hořlavinu** (zavřít přívod plynu, vykácet průsek v lese).' },
            { type: 'table', headers: ['Hasivo', 'Jak hasí', 'Pozor'], rows: [
              ['voda', 'ochlazuje pod zápalnou teplotu', 'ne na elektrická zařízení pod proudem ani na hořící olej a benzín'],
              ['pěnový přístroj', 'pěna odděluje hořlavinu od vzduchu', 'ne na zařízení pod proudem'],
              ['sněhový přístroj ($CO2$)', 'vytlačí kyslík a ochladí', 'vhodný na elektroniku; nesahej na trysku – omrzliny'],
              ['práškový přístroj', 'prášek přeruší hoření a zakryje hořlavinu', 'téměř univerzální, ale nadělá hodně prachu'],
              ['hasicí deka, poklice', 'zamezí přístupu kyslíku', 'ideální na hořící olej v hrnci'],
            ] },
            { type: 'callout', variant: 'warning', title: 'Hořící olej nikdy nehas vodou!', text: 'Voda pod rozpáleným olejem okamžitě změní skupenství na páru. Ta vymrští hořící olej do prostoru a vznikne ohnivá koule. Vypni plotýnku a hrnec přiklop poklicí nebo hasicí dekou. Hasiči mají číslo 150.' },
            { type: 'callout', variant: 'mascot', text: 'Požární trojúhelník je jako stolička na třech nohách. Podřízni jednu – a oheň spadne.' },
            { type: 'game', gameId: 'swipe', text: 'Pravda, nebo lež? Zahraj si **rychlou hru** o vzduchu, hoření a hašení.' },
            { type: 'check', question: { kind: 'multi', q: 'Na sporáku začal hořet olej v hrnci. Co je správné udělat?', options: ['přiklopit hrnec poklicí', 'přikrýt ho hasicí dekou', 'polít ho vodou', 'vypnout plotýnku', 'odnést hořící hrnec ke dřezu'], answers: [0, 1, 3], explain: 'Poklice i deka zamezí přístupu kyslíku a vypnutím plotýnky přestaneš olej dál zahřívat. Voda by způsobila výbuch hořícího oleje a s hořícím hrncem se nechodí.' } },
          ],
        },
        {
          title: 'Znečištění ovzduší',
          blocks: [
            { type: 'p', text: 'Spalováním uhlí, dřeva, benzínu a nafty se do vzduchu dostávají škodliviny: prach (jemné částice PM_{10} a PM_{2,5}), oxid siřičitý $SO2$, oxidy dusíku (třeba $NO2$) a jedovatý oxid uhelnatý $CO$, který nemá barvu ani zápach.' },
            { type: 'keyterms', items: [
              { term: '**smog**', def: 'směs kouře, mlhy a škodlivin, která za bezvětří visí nad městem (z anglického *smoke* + *fog*)' },
              { term: '**zimní (londýnský) smog**', def: 'kouř, prach a oxid siřičitý z topenišť v chladném vlhkém počasí' },
              { term: '**letní (fotochemický) smog**', def: 'vzniká ze zplodin aut za silného slunečního záření; jeho hlavní složkou je přízemní ozon' },
              { term: '**kyselý déšť**', def: 'déšť okyselený oxidem siřičitým a oxidy dusíku' },
            ] },
            { type: 'table', headers: ['Ozon', 'Kde je', 'Jak na nás působí'], rows: [
              ['**ozonová vrstva**', 've stratosféře, asi 15–35 km nad Zemí', 'pohlcuje nebezpečné UV záření – chrání nás'],
              ['**přízemní ozon**', 'u země, hlavně v létě ve městech', 'dráždí oči a plíce, poškozuje rostliny – škodí'],
            ] },
            { type: 'callout', variant: 'remember', text: 'Ozon nahoře chrání, ozon dole škodí. Je to stejná látka, jen na jiném místě.' },
            { type: 'p', text: 'Ozonovou vrstvu ničily **freony** – plyny z ledniček a sprejů. Nad Antarktidou kvůli nim vznikla **ozonová díra**. Montrealský protokol z roku 1987 jejich výrobu zakázal a vrstva se pomalu obnovuje; nad Antarktidou by se měla zotavit kolem roku 2066.' },
            { type: 'p', text: '**Kyselé deště** vznikají, když oxid siřičitý a oxidy dusíku reagují se vzdušnou vlhkostí na kyseliny (podrobně v úrovni 5). Poškozují lesy, okyselují jezera a rozpouštějí sochy z vápence a mramoru.' },
            { type: 'callout', variant: 'fact', text: 'V 70. a 80. letech kyselé deště zničily velkou část smrkových lesů v Krušných a Jizerských horách. Po odsíření uhelných elektráren v 90. letech se ovzduší výrazně zlepšilo a lesy se vracejí.' },
            { type: 'callout', variant: 'tip', title: 'Co můžeš udělat ty', text: 'Jezdi MHD, vlakem nebo na kole, šetři energií a nikdy nepal odpadky v kamnech – hořící plasty uvolňují jedovaté látky přímo do vzduchu, který dýcháš ty i sousedé.' },
            { type: 'check', question: { kind: 'choice', q: 'Proč je přízemní ozon škodlivý, když ozonová vrstva je užitečná?', options: ['U země ho dýcháme – dráždí plíce a škodí rostlinám.', 'Přízemní ozon je úplně jiná látka než ozon ve stratosféře.', 'Přízemní ozon propouští UV záření, stratosférický ne.', 'Přízemní ozon způsobuje ozonovou díru.'], answer: 0, explain: 'Jde o stejnou látku. Vysoko ve stratosféře pohlcuje UV záření, ale u země ji vdechujeme a dráždí dýchací cesty.' } },
            { type: 'check', question: { kind: 'tf', q: 'Hlavní příčinou kyselých dešťů jsou oxid siřičitý a oxidy dusíku.', answer: true, explain: 'Tyto plyny ze spalování uhlí a z motorů reagují se vzdušnou vlhkostí na kyseliny, které pak padají s deštěm.' } },
          ],
        },
      ],
      summary: [
        'Destilovaná voda neobsahuje rozpuštěné látky, pitná je zdravotně nezávadná, užitková se nesmí pít a odpadní se musí vyčistit.',
        'Tvrdost vody způsobují sloučeniny vápníku a hořčíku; tvrdá voda vytváří vodní kámen.',
        'Úpravna vody vyrábí pitnou vodu, čistírna odpadních vod čistí použitou vodu mechanicky a biologicky.',
        'Suchý vzduch obsahuje asi 78 % dusíku, 21 % kyslíku, 0,9 % argonu a 0,04 % oxidu uhličitého.',
        'K hoření je potřeba hořlavá látka, kyslík a zápalná teplota; hasíme odebráním aspoň jedné z nich.',
        'Ozonová vrstva nás chrání před UV zářením, přízemní ozon je škodlivá složka letního smogu.',
        'Kyselé deště způsobují oxid siřičitý a oxidy dusíku ze spalování.',
      ],
      quiz: [
        { kind: 'choice', q: 'Kterého plynu je ve vzduchu nejvíc?', options: ['dusíku', 'kyslíku', 'oxidu uhličitého', 'argonu'], answer: 0, explain: 'Dusík tvoří asi 78 % objemu vzduchu, kyslík asi 21 %.' },
        { kind: 'tf', q: 'Kyslík sám hoří.', answer: false, explain: 'Kyslík hoření podporuje, ale sám nehoří. Hoří hořlavá látka, která s kyslíkem reaguje.' },
        { kind: 'match', q: 'Přiřaď druh vody k jejímu popisu.', pairs: [['destilovaná voda', 'bez rozpuštěných látek, pro laboratoř'], ['užitková voda', 'na mytí a zalévání, ne k pití'], ['odpadní voda', 'znečištěná, míří do čistírny'], ['minerální voda', 'hodně rozpuštěných minerálních látek']], explain: 'Druhy vod se liší tím, kolik a jakých látek obsahují a k čemu se smějí použít.' },
        { kind: 'multi', q: 'Co tvoří požární trojúhelník?', options: ['hořlavá látka', 'kyslík', 'zápalná teplota', 'oxid uhličitý', 'voda'], answers: [0, 1, 2], explain: 'K hoření je nutná hořlavá látka, kyslík a dostatečná teplota. Oxid uhličitý a voda se naopak používají k hašení.' },
        { kind: 'choice', q: 'Čím je vhodné hasit zapojený počítač, který začal hořet?', options: ['sněhovým hasicím přístrojem ($CO2$)', 'vodou', 'pěnovým hasicím přístrojem', 'mokrým ručníkem'], answer: 0, explain: 'Voda i pěna vedou elektrický proud a hrozí úraz. Sněhový přístroj s oxidem uhličitým nezanechává vodu a elektronice neublíží.' },
        { kind: 'tf', q: 'Tvrdost vody způsobují rozpuštěné sloučeniny vápníku a hořčíku.', answer: true, explain: 'Právě sloučeniny vápníku a hořčíku se při vaření usazují jako vodní kámen.' },
        { kind: 'order', q: 'Seřaď zařízení čistírny odpadních vod tak, jak jimi voda protéká.', items: ['česle', 'lapák písku', 'usazovací nádrž', 'aktivační nádrž s bakteriemi', 'dosazovací nádrž'], explain: 'Nejdřív se odstraní hrubé nečistoty, pak písek a usaditelné látky. Následuje biologické čištění bakteriemi a nakonec se usadí kal.' },
        { kind: 'choice', q: 'Co způsobilo vznik ozonové díry nad Antarktidou?', options: ['freony z ledniček a sprejů', 'oxid siřičitý z elektráren', 'přízemní ozon z výfuků', 'oxid uhličitý z dýchání'], answer: 0, explain: 'Freony se dostaly až do stratosféry a tam rozkládaly ozon. Proto byla jejich výroba Montrealským protokolem zakázána.' },
      ],
    },
  },
  boss: [
    { kind: 'multi', q: 'Ve kterých dějích vzniká nová látka?', options: ['kynutí těsta s droždím', 'sublimace suchého ledu', 'rezavění hřebíku', 'rozpouštění soli v polévce', 'spálení dřeva v krbu'], answers: [0, 2, 4], explain: 'Kvasinky v těstě vytvářejí oxid uhličitý, na hřebíku vzniká rez a ze dřeva popel a plyny. Sublimace a rozpouštění jsou fyzikální změny.' },
    { kind: 'choice', q: 'Na lahvi lihu jsou piktogramy plamen a vykřičník. Jak s ním budeš zacházet?', options: ['Daleko od otevřeného ohně a s brýlemi – je hořlavý a dráždí oči.', 'Klidně u zapáleného kahanu, protože je jen dráždivý.', 'Ochutnám ho, protože líh je i v nápojích.', 'Zbytky vyleju do umyvadla, protože se ve vodě rozpouští.'], answer: 0, explain: 'Plamen znamená hořlavinu, vykřičník dráždivou látku. V laboratoři se nikdy nic neochutnává a zbytky patří do určených nádob.' },
    { kind: 'number', q: 'Kámen o hmotnosti 540 g ponoříš do odměrného válce, ve kterém je 300 ml vody. Hladina stoupne na 500 ml. Jaká je hustota kamene v g/cm³?', answer: 2.7, tolerance: 0.05, unit: 'g/cm³', explain: 'Objem kamene = 500 ml − 300 ml = 200 ml = 200 cm³. $ρ$ = 540 g : 200 cm³ = 2,7 g/cm³.' },
    { kind: 'choice', q: 'Ráno je na trávě rosa, v mrazivém ránu jinovatka. Které změny skupenství to jsou?', options: ['rosa – kapalnění, jinovatka – desublimace', 'rosa – tání, jinovatka – tuhnutí', 'rosa – kapalnění, jinovatka – tuhnutí', 'rosa – vypařování, jinovatka – sublimace'], answer: 0, explain: 'Rosa vzniká zkapalněním vodní páry ze vzduchu. Jinovatka vzniká, když se pára mění rovnou v led, bez kapalné fáze – to je desublimace.' },
    { kind: 'match', q: 'Zařaď látku do správné skupiny.', pairs: [['mosaz', 'stejnorodá směs (slitina)'], ['žula', 'různorodá směs'], ['síra', 'prvek'], ['destilovaná voda', 'sloučenina']], explain: 'Mosaz je slitina mědi a zinku, v žule vidíš různá zrnka, síru chemicky nerozložíš a vodu lze rozložit na vodík a kyslík.' },
    { kind: 'choice', q: 'Kterou jedinou metodou získáš z mořské vody čistou vodu i sůl zároveň?', options: ['destilací', 'filtrací', 'odpařováním na vzduchu', 'chromatografií'], answer: 0, explain: 'Při destilaci se voda zachytí jako destilát a sůl zůstane v baňce. Při odpařování na vzduchu vodu ztratíš a filtrace rozpuštěnou sůl neoddělí.' },
    { kind: 'order', q: 'Seřaď kroky, kterými rozdělíš směs jodu, kuchyňské soli a písku.', items: ['V digestoři oddělíš jod sublimací.', 'Zbytek zaliješ vodou a zamícháš.', 'Směs přefiltruješ – na filtru zůstane písek.', 'Filtrát odpaříš – zůstane sůl.'], explain: 'Jod musí jít pryč jako první, protože sublimuje. Pak využiješ rozpustnost soli: písek zachytí filtr a sůl získáš odpařením filtrátu.' },
    { kind: 'tf', q: 'Nasycený roztok dusičnanu draselného připravený při 20 °C se po zahřátí na 60 °C stane nenasyceným.', answer: true, explain: 'Rozpustnost dusičnanu draselného s teplotou prudce roste (z 31,6 g na 110 g ve 100 g vody), takže teplý roztok by rozpustil ještě mnohem víc látky.' },
    { kind: 'number', q: 'Ve 150 g vody při 80 °C připravíš nasycený roztok dusičnanu draselného a ochladíš ho na 20 °C. Kolik gramů krystalů se vyloučí? (Rozpustnost: 169 g při 80 °C, 31,6 g při 20 °C, obojí ve 100 g vody.)', answer: 206.1, tolerance: 1, unit: 'g', explain: 'Ve 100 g vody se vyloučí 169 g − 31,6 g = 137,4 g. Ve 150 g vody je to 1,5krát víc: 1,5 · 137,4 g = 206,1 g.' },
    { kind: 'number', q: 'Kolik gramů vody musíš odpařit z 500 g 4% roztoku, aby vznikl 10% roztok?', answer: 300, tolerance: 1, unit: 'g', explain: 'Látka: 0,04 · 500 g = 20 g. Roztok s $w$ = 0,10 bude mít hmotnost 20 g : 0,10 = 200 g. Odpařit je třeba 500 g − 200 g = 300 g vody.' },
    { kind: 'number', q: 'Kolik gramů 40% roztoku musíš smíchat se 300 g 10% roztoku, aby vznikl 20% roztok?', answer: 150, tolerance: 1, unit: 'g', explain: 'Křížovým pravidlem: 40% a 10% roztok se mísí v poměru (20 − 10) : (40 − 20) = 1 : 2. Na 300 g 10% roztoku tedy potřebuješ 150 g 40% roztoku. Kontrola: 60 g + 30 g = 90 g látky v 450 g, tj. 20 %.' },
    { kind: 'multi', q: 'Která tvrzení o vzduchu, hoření a ovzduší jsou pravdivá?', options: ['Ve 100 l suchého vzduchu je asi 21 l kyslíku.', 'Argonu je ve vzduchu víc než oxidu uhličitého.', 'Sněhový hasicí přístroj hasí vytlačením kyslíku a ochlazením.', 'Hořící olej nejrychleji uhasíš vodou.', 'Přízemní ozon nás chrání před UV zářením.'], answers: [0, 1, 2], explain: 'Argonu je asi 0,9 %, oxidu uhličitého jen 0,04 %. Hořící olej se vodou hasit nesmí a před UV zářením nás chrání ozon ve stratosféře, ne přízemní.' },
  ],
}

export default level
