import type { LevelContent } from '../../../core/types'

const level: LevelContent = {
  lessons: {
    // ───────────────────────────────────────────────────────────── l2-1
    'l2-1': {
      id: 'l2-1',
      title: 'Atomy, molekuly a ionty',
      goals: [
        'Rozlišit atom, molekulu a ion a poznat, jestli je ion kation, nebo anion',
        'Podle vzorce rozhodnout, jestli jde o chemický prvek, nebo sloučeninu',
        'Přečíst chemickou značku a jednoduchý vzorec a spočítat atomy podle indexu a koeficientu',
        'Popsat, jak se představa o atomech vyvíjela od Démokrita po Daltona',
      ],
      hook: 'Rozkrojíš kostku cukru napůl, pak zase napůl a pak znovu… Jak dlouho to jde? Řecký filozof Démokritos si před 2 400 lety myslel, že jednou narazíš na kousek, který už rozdělit nejde. A kupodivu měl skoro pravdu!',
      sections: [
        {
          title: 'Všechno je z částic',
          icon: 'atom',
          blocks: [
            { type: 'p', text: 'V úrovni 1 jsi poznal látky zvenku. Teď se podíváme dovnitř: každá látka se skládá z nepředstavitelně malých **částic**, které jsou v neustálém pohybu.' },
            { type: 'diagram', id: 'states', caption: 'Stejné částice, jiné uspořádání: pevná látka, kapalina a plyn' },
            { type: 'p', text: 'Tomuto pohledu se říká **částicový model látek**. Mezi částicemi je prostor a částice se hýbou, a to vysvětluje spoustu každodenních věcí:' },
            { type: 'iconlist', items: [
              { icon: 'sugar', title: 'Cukr se ve vodě rozpustí', text: 'jeho částice se rozptýlí mezi částice vody' },
              { icon: 'gas-cloud', title: 'Vůně parfému dojde až k tobě', text: 'částice vůně se samy rozletí po místnosti' },
              { icon: 'balloon', title: 'Plyn se dá stlačit', text: 'mezi částicemi plynu je hodně volného místa' },
            ] },
            { type: 'process', layout: 'flow', steps: [
              { icon: 'idea', title: 'Démokritos, 5. st. př. n. l.', text: 'Nejmenší částečky nazval *atomos*, řecky „nedělitelný“. Jen úvaha, bez jediného pokusu.' },
              { icon: 'balance-scale', title: 'John Dalton, 1808', text: 'Vědecká **atomová teorie** opřená o měření hmotností látek při reakcích.' },
              { icon: 'pencil', title: 'Berzelius, kolem 1813', text: 'Písmenné značky prvků, které používáme dodnes.' },
            ], caption: 'Od úvahy k vědě: jak se zrodila představa o atomech' },
            { type: 'p', text: 'Daltonova **atomová teorie** stála na čtyřech bodech:' },
            { type: 'iconlist', items: [
              { icon: 'atom', title: 'Látky jsou z atomů', text: 'atomy nelze rozdělit ani zničit' },
              { icon: 'balance-scale', title: 'Atomy jednoho prvku jsou stejné', text: 'atomy různých prvků se liší hmotností' },
              { icon: 'molecule', title: 'Sloučeniny mají stálý poměr', text: 'vznikají spojením atomů různých prvků v určitém poměru' },
              { icon: 'arrow-cycle', title: 'Reakce atomy jen přeskupí', text: 'žádný atom nevzniká ani nezaniká' },
            ] },
            { type: 'callout', variant: 'fact', title: 'Jak malý je atom?', text: 'Průměr atomu je zhruba 0,1 nm, tedy desetimiliontina milimetru. Řada deseti milionů atomů by měřila asi 1 mm.' },
            { type: 'callout', variant: 'mascot', text: 'Dalton se ve dvou bodech trochu spletl: atom rozdělit jde a atomy jednoho prvku nemusí být úplně stejné. Proč, zjistíš v dalších dvou lekcích. I tak mu patří velký potlesk!' },
            { type: 'check', question: { kind: 'choice', q: 'Kdo jako první postavil představu o atomech na výsledcích pokusů a měření?', options: ['John Dalton', 'Démokritos', 'Aristotelés', 'Isaac Newton'], answer: 0, explain: 'Démokritos atomy jen vymyslel úvahou. Dalton v roce 1808 vytvořil atomovou teorii opřenou o měření hmotností látek při reakcích.' } },
          ],
        },
        {
          title: 'Atom, molekula, ion',
          icon: 'ion-plus',
          blocks: [
            { type: 'p', text: 'Částice, ze kterých jsou látky složené, mají tři základní podoby. Budeš je potřebovat v celém kurzu.' },
            { type: 'particles', boxes: [
              { label: 'Atomy', items: [{ species: 'He', count: 6 }], state: 'gas', note: 'helium $He$' },
              { label: 'Molekuly', items: [{ species: 'H2O', count: 5 }], state: 'liquid', note: 'voda $H2O$' },
              { label: 'Ionty', items: [{ species: 'Na^+', count: 6 }, { species: 'Cl^-', count: 6 }], state: 'solid', note: 'sůl: $Na^+$ a $Cl^-$' },
            ] },
            { type: 'compare', columns: [
              { title: '**Atom**', icon: 'atom', tone: 'a', points: ['nejmenší částice chemického prvku', 'navenek **elektricky neutrální** (nemá náboj)', '$He$, $Ne$, $Fe$, $Na$'] },
              { title: '**Molekula**', icon: 'molecule', tone: 'b', points: ['dva nebo více atomů pevně spojených (chemicky vázaných)', 'také neutrální'] },
              { title: '**Ion**', icon: 'ion-plus', tone: 'c', points: ['částice s **elektrickým nábojem**', 'vzniká z atomu nebo molekuly, která získala, nebo ztratila elektrony', '$Na^+$, $Cl^-$'] },
            ] },
            { type: 'molecule', molecules: ['H2', 'O2', 'H2O', 'CO2'], labels: ['$H2$', '$O2$', '$H2O$', '$CO2$'], caption: 'Molekuly: skupinky pevně spojených atomů. Otoč si je!' },
            { type: 'p', text: '**Elektrony** jsou drobné záporně nabité částice v obalu atomu, podrobně je poznáš v příští lekci. Podle toho, jestli atom elektrony ztratí, nebo přijme, vznikne jeden ze dvou druhů iontů:' },
            { type: 'compare', columns: [
              { title: 'Kation', icon: 'ion-plus', tone: 'a', points: ['**kladný** náboj', 'atom elektrony **ztratil**', '$Na^+$, $Ca^{2+}$, $Fe^{3+}$'] },
              { title: 'Anion', icon: 'ion-minus', tone: 'b', points: ['**záporný** náboj', 'atom elektrony **přijal**', '$Cl^-$, $O^2-$, $S^2-$'] },
            ], caption: 'Náboj iontu se píše vpravo nahoru: číslo, pak znaménko' },
            { type: 'callout', variant: 'tip', title: 'Jak si to zapamatovat', text: '**K**ation je **k**ladný, **a**nion je záporný. Stačí si pamatovat to „ká – ká“.' },
            { type: 'p', text: '$Ca^{2+}$ znamená, že atom vápníku ztratil dva elektrony, $O^2-$, že atom kyslíku dva získal. Jednička se u náboje nepíše: $Na^+$, ne $Na^{1+}$.' },
            { type: 'check', question: { kind: 'multi', q: 'Které z částic jsou **anionty**?', options: ['$Cl^-$', '$Mg^{2+}$', '$S^2-$', '$CO2$', '$F^-$'], answers: [0, 2, 4], explain: 'Anionty mají záporný náboj: $Cl^-$, $S^2-$ a $F^-$. $Mg^{2+}$ je kation a $CO2$ je neutrální molekula.' } },
          ],
        },
        {
          title: 'Prvek a sloučenina pod lupou',
          icon: 'magnifier',
          blocks: [
            { type: 'p', text: 'V úrovni 1 jsi chemicky čisté látky dělil na prvky a sloučeniny. Teď uvidíš, v čem se liší na úrovni částic.' },
            { type: 'particles', boxes: [
              { label: 'Prvek z atomů', items: [{ species: 'He', count: 6 }], state: 'gas', note: 'helium $He$' },
              { label: 'Prvek z molekul', items: [{ species: 'O2', count: 5 }], state: 'gas', note: 'kyslík $O2$' },
              { label: 'Sloučenina', items: [{ species: 'CO2', count: 5 }], state: 'gas', note: 'oxid uhličitý $CO2$' },
              { label: 'Směs', items: [{ species: 'N2', count: 5 }, { species: 'O2', count: 2 }, { species: 'Ar', count: 1 }], state: 'gas', note: 'vzduch' },
            ] },
            { type: 'compare', columns: [
              { title: '**Chemický prvek**', icon: 'atom', tone: 'a', points: ['atomy **jednoho druhu**', 'samostatné atomy ($He$, $Fe$) nebo molekuly ($O2$, $O3$)', 'přesnou definici pomocí protonového čísla přidáme v lekci o izotopech'] },
              { title: '**Chemická sloučenina**', icon: 'molecule', tone: 'b', points: ['atomy **alespoň dvou různých prvků**', 'chemicky vázané ve stálém poměru', '$H2O$, $CO2$ nebo $NaCl$ z iontů $Na^+$ a $Cl^-$'] },
            ] },
            { type: 'molecule', molecules: ['O2', 'O3', 'H2O', 'CO2'], labels: ['kyslík: prvek', 'ozon: prvek', 'voda: sloučenina', 'oxid uhličitý: sloučenina'], caption: '$O2$ i $O3$ jsou pořád prvek kyslík, obsahují jen atomy kyslíku. Jak se sloučeniny jmenují, se naučíš v úrovni 3.' },
            { type: 'callout', variant: 'warning', title: 'Častá chyba', text: 'Molekula **není** totéž co sloučenina. Molekula $H2$ je molekula prvku vodíku. O sloučenině rozhoduje, kolik **různých** druhů atomů v látce je.' },
            { type: 'p', text: 'Ve **směsi** jsou částice různých látek jen **promíchané**, nejsou navzájem vázané. Vzduch obsahuje molekuly $N2$, $O2$, $CO2$ i atomy $Ar$ a každá z těch látek si zachovává svoje vlastnosti.' },
            { type: 'check', question: { kind: 'tf', q: 'Každá molekula je molekulou nějaké sloučeniny.', answer: false, explain: 'Molekuly tvoří i prvky, například $H2$, $O2$, $N2$ nebo $O3$. Sloučenina vyžaduje atomy aspoň dvou různých prvků.' } },
          ],
        },
        {
          title: 'Značky a vzorce: index a koeficient',
          icon: 'periodic-table',
          blocks: [
            { type: 'p', text: 'Každý prvek má svou **chemickou značku**: jedno nebo dvě písmena, většinou z latinského názvu. Systém zavedl švédský chemik **Jöns Jacob Berzelius** kolem roku 1813.' },
            { type: 'elements', symbols: ['Na', 'K', 'Fe', 'Cu', 'Ag', 'Au', 'Pb', 'Hg'], caption: 'natrium, kalium, ferrum, cuprum, argentum, aurum, plumbum, hydrargyrum' },
            { type: 'callout', variant: 'warning', title: 'Na velikosti písmen záleží', text: 'První písmeno je vždy velké, druhé malé. $Co$ je kobalt, kovový prvek. $CO$ je oxid uhelnatý, jedovatý plyn z molekul uhlíku a kyslíku.' },
            { type: 'p', text: '**Chemický vzorec** ukazuje, z jakých atomů se částice skládá. Dvě čísla v něm znamenají něco úplně jiného:' },
            { type: 'compare', columns: [
              { title: 'Index', icon: 'atom', tone: 'a', points: ['malé číslo vpravo dole', 'kolik atomů daného prvku je v **jedné** částici', 'jednička se nepíše'] },
              { title: 'Koeficient', icon: 'molecule', tone: 'b', points: ['velké číslo před vzorcem', 'kolik je **částic**', '$3H2O$ jsou tři molekuly vody'] },
            ] },
            { type: 'particles', boxes: [
              { label: '$2H$', items: [{ species: 'H', count: 2 }], note: 'dva samostatné atomy: 2 H' },
              { label: '$H2$', items: [{ species: 'H2', count: 1 }], note: 'jedna molekula: 2 H' },
              { label: '$2H2$', items: [{ species: 'H2', count: 2 }], note: 'dvě molekuly: 4 H' },
              { label: '$3H2O$', items: [{ species: 'H2O', count: 3 }], note: 'tři molekuly: 6 H a 3 O' },
            ], caption: 'Stejná písmena, různý počet atomů' },
            { type: 'example', problem: 'Kolik atomů kterého prvku obsahuje zápis $2CO2$?', steps: [
              'Koeficient 2 říká, že jde o dvě molekuly $CO2$.',
              'V jedné molekule je 1 atom C (index 1 se nepíše) a 2 atomy O.',
              'Vynásob koeficientem: C: 2 · 1 = 2, O: 2 · 2 = 4.',
            ], answer: '2 atomy uhlíku a 4 atomy kyslíku' },
            { type: 'p', text: 'U iontových látek vzorec udává jen **poměr** iontů. Kuchyňská sůl nemá molekuly: v $NaCl$ připadá na každý kation $Na^+$ jeden anion $Cl^-$.' },
            { type: 'particles', boxes: [
              { label: 'Krystal $NaCl$', items: [{ species: 'Na^+', count: 8 }, { species: 'Cl^-', count: 8 }], state: 'solid', note: 'ionty v poměru 1 : 1' },
            ] },
            { type: 'game', gameId: 'element-memory', text: 'Značky se nejlépe učí hrou. Zkus Pexeso prvků a spoj značky s českými názvy.' },
            { type: 'check', question: { kind: 'number', q: 'Kolik atomů kyslíku je celkem v zápisu $3CO2$?', answer: 6, tolerance: 0, explain: 'Tři molekuly $CO2$, v každé 2 atomy kyslíku: 3 · 2 = 6.' } },
            { type: 'check', question: { kind: 'text', q: 'Napiš chemickou značku železa.', accept: ['Fe'], caseSensitive: true, placeholder: 'značka', explain: 'Železo má značku $Fe$ z latinského *ferrum*. Pozor na velké a malé písmeno.' } },
          ],
        },
      ],
      summary: [
        'Látky se skládají z částic, které jsou v neustálém pohybu.',
        'Atom je nejmenší částice prvku a je elektricky neutrální; molekula je skupina vázaných atomů.',
        'Ion je nabitá částice: kation je kladný (atom ztratil elektrony), anion záporný (elektrony získal).',
        'Prvek obsahuje atomy jednoho druhu, sloučenina atomy aspoň dvou různých prvků. Molekulu mají i prvky, například $O2$.',
        'Index udává počet atomů v jedné částici, koeficient počet částic.',
        'Myšlenka atomů pochází od Démokrita, vědeckou atomovou teorii vytvořil Dalton (1808), značky prvků zavedl Berzelius.',
      ],
      quiz: [
        { kind: 'choice', q: 'Která z částic je **kation**?', options: ['$K^+$', '$Br^-$', '$N2$', '$Ar$'], answer: 0, explain: 'Kation je kladně nabitý: $K^+$ vznikl z atomu draslíku, který ztratil jeden elektron.' },
        { kind: 'tf', q: 'Kyslík $O2$ je sloučenina, protože jeho molekula má dva atomy.', answer: false, explain: 'Oba atomy jsou atomy kyslíku, jde tedy o prvek. Sloučenina potřebuje aspoň dva různé prvky.' },
        { kind: 'tf', q: 'Koeficient udává počet částic, index počet atomů daného prvku v jedné částici.', answer: true, explain: 'Přesně tak: v $3H2O$ je koeficient 3 (tři molekuly) a index 2 (dva vodíky v každé molekule).' },
        { kind: 'number', q: 'Kolik atomů vodíku je v zápisu $4H2O$?', answer: 8, tolerance: 0, explain: 'Čtyři molekuly vody, v každé 2 atomy vodíku: 4 · 2 = 8.' },
        { kind: 'multi', q: 'Které látky jsou **sloučeniny**?', options: ['$H2O$', '$N2$', '$CO2$', '$O3$', '$NaCl$'], answers: [0, 2, 4], explain: '$H2O$, $CO2$ a $NaCl$ obsahují atomy dvou různých prvků. $N2$ a $O3$ jsou prvky tvořené molekulami.' },
        { kind: 'match', q: 'Přiřaď ke značce název prvku.', pairs: [['Na', 'sodík'], ['K', 'draslík'], ['Cu', 'měď'], ['Ag', 'stříbro'], ['Pb', 'olovo']], explain: 'Značky pocházejí z latiny: natrium, kalium, cuprum, argentum, plumbum.' },
        { kind: 'text', q: 'Napiš chemickou značku zlata.', accept: ['Au'], caseSensitive: true, placeholder: 'značka', explain: 'Zlato je $Au$ z latinského *aurum*.' },
        { kind: 'order', q: 'Seřaď milníky od nejstaršího.', items: ['Démokritos: hmota se skládá z nedělitelných atomů', 'Dalton: atomová teorie opřená o měření', 'Berzelius: písmenné značky prvků'], explain: 'Démokritos žil v 5. století př. n. l., Dalton publikoval teorii v roce 1808 a Berzelius navrhl značky kolem roku 1813.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l2-2
    'l2-2': {
      id: 'l2-2',
      title: 'Stavba atomu: jádro a obal',
      goals: [
        'Popsat proton, neutron a elektron: kde jsou, jaký mají náboj a hmotnost',
        'Vysvětlit, jak malé je jádro ve srovnání s celým atomem',
        'Seřadit modely atomu od Thomsona po kvantový a říct, co který přinesl',
        'Zdůvodnit, proč je atom elektricky neutrální',
      ],
      hook: 'Kdyby se atom zvětšil na velikost fotbalového stadionu, jádro by uprostřed hřiště bylo velké asi jako špendlíková hlavička. A přesto v něm je skoro celá hmotnost. Takže z čeho jsi vlastně hlavně ty? Z prázdna!',
      sections: [
        {
          title: 'Tři částice uvnitř atomu',
          icon: 'nucleus',
          blocks: [
            { type: 'p', text: 'Dalton si atom představoval jako nedělitelnou kuličku. Dnes víme, že uprostřed je nepatrné **atomové jádro** a kolem něj **elektronový obal**.' },
            { type: 'compare', columns: [
              { title: '**Proton** $p^+$', icon: 'ion-plus', tone: 'a', points: ['v jádře', 'náboj **+1**', 'hmotnost 1,673·10^{−27} kg, relativně ≈ 1'] },
              { title: '**Neutron** $n^0$', icon: 'nucleus', tone: 'b', points: ['v jádře', 'bez náboje (**0**)', 'hmotnost 1,675·10^{−27} kg, relativně ≈ 1'] },
              { title: '**Elektron** $e^-$', icon: 'electron', tone: 'c', points: ['v elektronovém obalu', 'náboj **−1**', 'hmotnost 9,109·10^{−31} kg, relativně ≈ 1/1836'] },
            ], caption: 'Náboj je udán v násobcích elementárního náboje 1,602·10^{−19} C' },
            { type: 'callout', variant: 'remember', text: 'Protony a neutrony se společně nazývají **nukleony** (z latinského *nucleus*, jádro).' },
            { type: 'diagram', id: 'bohr', props: { z: 3 }, caption: 'Atom lithia: 3 protony a 4 neutrony v jádře, 3 elektrony v obalu' },
            { type: 'callout', variant: 'fact', title: 'Elektron je lehká váha', text: 'Proton je asi 1836krát těžší než elektron. Kdyby elektron vážil jako kočka (4 kg), proton by vážil přes 7 tun, jako pořádný náklaďák.' },
            { type: 'check', question: { kind: 'choice', q: 'Která částice atomu **nemá elektrický náboj**?', options: ['neutron', 'proton', 'elektron', 'jádro atomu'], answer: 0, explain: 'Neutron je neutrální, odtud i jeho název. Jádro jako celek je kladné, protože obsahuje protony.' } },
          ],
        },
        {
          title: 'Proč je atom neutrální',
          icon: 'balance-scale',
          blocks: [
            { type: 'p', text: 'Proton a elektron mají stejně velký náboj, jen opačného znaménka. Atom má **stejný počet protonů a elektronů**, a proto se náboje přesně vyruší.' },
            { type: 'formula', text: 'počet $p^+$ = počet $e^-$', caption: 'platí pro každý neutrální atom' },
            { type: 'elements', symbols: ['H', 'C', 'O'], caption: 'Vodík má 1 proton, uhlík 6, kyslík 8: počet protonů je „poznávací znamení“ prvku (víc v příští lekci)' },
            { type: 'p', text: 'Když atom elektrony získá, nebo ztratí, protonů zůstane stejně. Rovnováha se poruší a vznikne **ion**.' },
            { type: 'compare', columns: [
              { title: 'Atom $Na$', icon: 'atom', tone: 'a', points: ['11 protonů: +11', '11 elektronů: −11', 'celkový náboj **0**'] },
              { title: 'Kation $Na^+$', icon: 'ion-plus', tone: 'b', points: ['11 protonů: +11', '10 elektronů: −10 (jeden ztratil)', 'celkový náboj **+1**'] },
            ], caption: 'Sodík po ztrátě jednoho elektronu: +11 − 10 = +1' },
            { type: 'callout', variant: 'remember', text: 'Při vzniku iontu se mění **jen počet elektronů**. Počet protonů v jádře chemickou reakcí změnit nejde.' },
            { type: 'check', question: { kind: 'number', q: 'Neutrální atom chloru má 17 protonů. Kolik má elektronů?', answer: 17, tolerance: 0, explain: 'V neutrálním atomu je elektronů stejně jako protonů, tedy 17.' } },
          ],
        },
        {
          title: 'Jádro je nepatrné, atom je hlavně prázdno',
          icon: 'magnifier',
          blocks: [
            { type: 'p', text: 'Průměr atomu je řádově 10^{−10} m, průměr jádra jen asi 10^{−15} m. ==Jádro je tedy zhruba stotisíckrát menší než celý atom.==' },
            { type: 'diagram', id: 'atom-scale', caption: 'Atom zvětšený na fotbalový stadion (asi 100 m): jádro by bylo uprostřed hřiště velké jako špendlíková hlavička a elektrony by se pohybovaly až nad tribunami. Všechno mezi tím je prázdný prostor.' },
            { type: 'compare', columns: [
              { title: 'Celý atom', icon: 'atom', tone: 'a', points: ['objem tvoří hlavně obal s elektrony', 'skoro celý je prázdný prostor'] },
              { title: 'Jádro', icon: 'nucleus', tone: 'b', points: ['zabírá nepatrnou část objemu', 'nese **přes 99,9 %** hmotnosti atomu'] },
            ] },
            { type: 'callout', variant: 'fact', title: 'Nejhustší hmota', text: 'Jaderná hmota je tak hustá, že čajová lžička by vážila asi miliardu tun.' },
            { type: 'example', problem: 'Jádro nějakého atomu zvětšíme na kuličku o průměru 1 cm. Jak velký by byl celý atom, je-li asi 100 000× větší než jádro?', steps: [
              'Průměr atomu = 100 000 · 1 cm = 100 000 cm.',
              '100 000 cm = 1 000 m.',
            ], answer: 'Atom by měl průměr asi 1 km, tedy jako malá vesnice kolem jedné kuličky.' },
            { type: 'callout', variant: 'mascot', text: 'Když je atom skoro prázdný, proč nepropadneš židlí? Elektronové obaly tvých atomů a atomů židle se navzájem silně odpuzují. Sedíš vlastně na elektrickém polštáři!' },
            { type: 'check', question: { kind: 'number', q: 'Zvětšíme atom na průměr 100 m. Jaký průměr by mělo jádro, je-li asi 100 000× menší? Odpověz v milimetrech.', answer: 1, tolerance: 0, unit: 'mm', explain: '100 m = 100 000 mm. Když to vydělíš 100 000, vyjde 1 mm, zhruba špendlíková hlavička.' } },
          ],
        },
        {
          title: 'Jak jsme se to dozvěděli: modely atomu',
          icon: 'book',
          blocks: [
            { type: 'p', text: 'Do atomu nikdo nenahlédl přímo. Vědci si vytvářeli **modely**, zjednodušené představy, a ověřovali je pokusy. Když model s pokusem nesouhlasil, musel se změnit.' },
            { type: 'process', layout: 'flow', steps: [
              { icon: 'idea', title: 'Démokritos', text: '5. st. př. n. l.: nedělitelné *atomos*, jen úvaha' },
              { icon: 'balance-scale', title: 'Dalton, 1808', text: 'atom jako nedělitelná kulička' },
              { icon: 'electron', title: 'Thomson, 1897 a 1904', text: 'objevil elektron; **pudinkový model**: elektrony jako rozinky v kladné hmotě' },
              { icon: 'nucleus', title: 'Rutherford, 1911', text: 'malé, těžké, kladné **jádro**, kolem obíhají elektrony: **planetární model**' },
              { icon: 'atom', title: 'Bohr, 1913', text: 'elektrony jen na drahách s danou energií, ve **vrstvách**' },
              { icon: 'gas-cloud', title: 'Kvantový model, od 1926', text: 'Schrödinger a další: žádná přesná dráha, jen pravděpodobnost výskytu v **orbitalu**' },
            ], caption: 'Vývoj modelu atomu. Vrstvy a orbitaly podrobně poznáš v lekcích 4 a 5.' },
            { type: 'diagram', id: 'rutherford-experiment', caption: 'Rutherford ostřeloval zlatou fólii kladnými částicemi alfa. Většina prolétla, několik se odchýlilo a vzácně se některá odrazila zpět.' },
            { type: 'callout', variant: 'fact', title: 'Granát a hedvábný papír', text: 'Rutherford popsal odraz částic alfa (co to je, uvidíš v příští lekci) takto: „Bylo to, jako byste vystřelili dělostřelecký granát na hedvábný papír a on se odrazil zpátky a zasáhl vás.“ Vysvětlit to šlo jen malým hustým jádrem.' },
            { type: 'compare', columns: [
              { title: 'Thomson (pudink)', icon: 'electron', tone: 'a', points: ['přinesl: atom obsahuje elektrony', 'nevysvětlil: odrazy částic alfa od fólie'] },
              { title: 'Rutherford (planety)', icon: 'nucleus', tone: 'b', points: ['přinesl: malé kladné jádro', 'nevysvětlil: proč elektron nespadne do jádra'] },
              { title: 'Bohr (vrstvy)', icon: 'atom', tone: 'c', points: ['přinesl: vrstvy s danou energií', 'nevysvětlil: atomy s více elektrony; to zvládl až dnes platný kvantový model'] },
            ], caption: 'Každý model opravil slabinu předchozího' },
            { type: 'p', text: 'Proton Rutherford prokázal v roce 1919. Neutron objevil až v roce 1932 James **Chadwick**, protože částice bez náboje se hledá mnohem hůř.' },
            { type: 'check', question: { kind: 'order', q: 'Seřaď modely atomu od nejstaršího po nejnovější.', items: ['pudinkový model (Thomson)', 'planetární model s jádrem (Rutherford)', 'Bohrův model s vrstvami', 'kvantový model s orbitaly'], explain: 'Thomson 1904, Rutherford 1911, Bohr 1913 a kvantový model od roku 1926. Každý opravoval slabinu předchozího.' } },
          ],
        },
      ],
      summary: [
        'Atom tvoří jádro (protony a neutrony) a elektronový obal (elektrony).',
        'Proton má náboj +1, neutron 0, elektron −1; proton a neutron jsou asi 1836krát těžší než elektron.',
        'Neutrální atom má stejně protonů jako elektronů. Ion vzniká jen změnou počtu elektronů.',
        'Jádro je asi 100 000× menší než atom, ale nese přes 99,9 % jeho hmotnosti.',
        'Modely atomu se vyvíjely: Thomson (pudink) -> Rutherford (jádro) -> Bohr (vrstvy) -> kvantový model (orbitaly).',
      ],
      quiz: [
        { kind: 'choice', q: 'Kde je soustředěna téměř celá hmotnost atomu?', options: ['v jádře', 'v elektronovém obalu', 'rovnoměrně v celém objemu atomu', 'v elektronech'], answer: 0, explain: 'Protony a neutrony v jádře jsou asi 1836krát těžší než elektrony, takže jádro nese přes 99,9 % hmotnosti.' },
        { kind: 'tf', q: 'Elektron má přibližně stejnou hmotnost jako proton.', answer: false, explain: 'Elektron je asi 1836krát lehčí než proton. Stejnou hmotnost mají přibližně proton a neutron.' },
        { kind: 'text', q: 'Jak se společným názvem označují protony a neutrony?', accept: ['nukleony', 'nukleon'], placeholder: 'jedno slovo', explain: 'Protony a neutrony tvoří jádro (*nucleus*), proto se jim říká nukleony.' },
        { kind: 'number', q: 'Atom má v jádře 26 protonů a 30 neutronů. Kolik má elektronů, je-li neutrální?', answer: 26, tolerance: 0, explain: 'Počet elektronů v neutrálním atomu se rovná počtu protonů. Neutrony na to vliv nemají.' },
        { kind: 'match', q: 'Přiřaď vědce k jeho přínosu.', pairs: [['Thomson', 'objev elektronu, pudinkový model'], ['Rutherford', 'jádro atomu (pokus se zlatou fólií)'], ['Bohr', 'elektrony ve vrstvách s danou energií'], ['Chadwick', 'objev neutronu']], explain: 'Thomson 1897, Rutherford 1911, Bohr 1913, Chadwick 1932.' },
        { kind: 'multi', q: 'Co pozoroval Rutherford při ostřelování zlaté fólie částicemi alfa?', options: ['Většina částic prolétla fólií bez odchýlení.', 'Některé částice se odchýlily od původního směru.', 'Výjimečně se částice odrazila zpět.', 'Všechny částice se od fólie odrazily.', 'Fólie se rozpadla na elektrony.'], answers: [0, 1, 2], explain: 'Většina prolétla, protože atom je hlavně prázdný. Odchýlení a vzácné odrazy způsobilo malé kladné jádro.' },
        { kind: 'tf', q: 'Částice s 8 protony a 10 elektrony je elektricky neutrální atom.', answer: false, explain: 'Náboj je +8 − 10 = −2. Jde o anion $O^2-$, tedy ion kyslíku.' },
        { kind: 'order', q: 'Seřaď částice podle hmotnosti od nejlehčí.', items: ['elektron', 'proton', 'neutron'], explain: 'Elektron je nejlehčí (9,1·10^{−31} kg), proton má 1,673·10^{−27} kg a neutron je o chlup těžší, 1,675·10^{−27} kg.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l2-3
    'l2-3': {
      id: 'l2-3',
      title: 'Protonové číslo, nukleonové číslo a izotopy',
      goals: [
        'Z protonového a nukleonového čísla spočítat protony, neutrony a elektrony v atomu i v iontu',
        'Vysvětlit, co jsou izotopy, a přečíst zápis nuklidu $^{14}_{6}C$',
        'Spočítat relativní atomovou hmotnost jako vážený průměr izotopů',
        'Popsat záření α, β a γ, poločas přeměny a využití radioaktivity',
      ],
      hook: 'Uhlík v tuhě tvé tužky a uhlík v diamantu mají stejný počet protonů. Ale víš, že se i atomy uhlíku mezi sebou liší hmotností? A že díky tomu umíme určit, jak stará je egyptská mumie?',
      sections: [
        {
          title: 'Dvě čísla, která o atomu řeknou všechno',
          icon: 'nucleus',
          blocks: [
            { type: 'compare', columns: [
              { title: '**Protonové číslo** $Z$', icon: 'ion-plus', tone: 'a', points: ['počet **protonů** v jádře', 'určuje prvek: každý atom se $Z = 6$ je uhlík, se $Z = 8$ kyslík', 'píše se ke značce **dolů**'] },
              { title: '**Nukleonové číslo** $A$', icon: 'nucleus', tone: 'b', points: ['počet všech **nukleonů**: protonů a neutronů dohromady', 'z něj dopočítáš počet neutronů $N$ (neutronové číslo)', 'píše se ke značce **nahoru**'] },
            ] },
            { type: 'formula', text: '$A = Z + N$, tedy $N = A − Z$', caption: 'nukleonové číslo = protony + neutrony' },
            { type: 'p', text: 'Zápisu konkrétního druhu atomu s oběma čísly se říká **nuklid**.' },
            { type: 'formula', text: '$^{23}_{11}Na$', caption: 'nuklid sodíku: A = 23 nahoře, Z = 11 dole' },
            { type: 'callout', variant: 'remember', title: 'Teď už přesně', text: '**Chemický prvek** je látka složená z atomů se stejným protonovým číslem. Změníš-li počet protonů, změníš prvek.' },
            { type: 'example', problem: 'Kolik protonů, neutronů a elektronů má atom $^{23}_{11}Na$?', steps: [
              'Protony: $Z = 11$.',
              'Neutrony: $N = A − Z = 23 − 11 = 12$.',
              'Elektrony: atom je neutrální, takže počet elektronů = $Z = 11$.',
            ], answer: '11 protonů, 12 neutronů, 11 elektronů' },
            { type: 'diagram', id: 'bohr', props: { z: 11 }, caption: 'Kontrola obrázkem: atom $^{23}_{11}Na$ v Bohrově modelu' },
            { type: 'check', question: { kind: 'number', q: 'Kolik neutronů má atom $^{35}_{17}Cl$?', answer: 18, tolerance: 0, explain: '$N = A − Z = 35 − 17 = 18$.' } },
          ],
        },
        {
          title: 'Izotopy: stejný prvek, jiná hmotnost',
          icon: 'atom',
          blocks: [
            { type: 'p', text: '**Izotopy** jsou atomy téhož prvku (stejné $Z$), které se liší počtem neutronů, a tedy i nukleonovým číslem $A$. Chemicky se chovají skoro stejně, protože mají stejně elektronů.' },
            { type: 'diagram', id: 'hydrogen-isotopes', caption: 'Tři izotopy vodíku – jako jediné mají vlastní jména: protium, deuterium (D) a tritium (T). Vždy 1 proton a 1 elektron, ale 0, 1 nebo 2 neutrony. Tritium je radioaktivní.' },
            { type: 'table', caption: 'Izotopy uhlíku', headers: ['Nuklid', 'Neutronů', 'Výskyt v přírodě'], rows: [
              ['uhlík-12 $^{12}_{6}C$', '6', '98,9 %'],
              ['uhlík-13 $^{13}_{6}C$', '7', '1,1 %'],
              ['uhlík-14 $^{14}_{6}C$', '8', 'nepatrná stopa, radioaktivní'],
            ] },
            { type: 'callout', variant: 'fact', title: 'Těžká voda', text: 'Voda z deuteria, $D2O$, se jmenuje těžká voda. Vypadá úplně stejně jako obyčejná, ale kostka ledu z těžké vody v obyčejné vodě neplave, klesne ke dnu.' },
            { type: 'callout', variant: 'warning', title: 'Pozor', text: 'Izotopy se liší **jen počtem neutronů**. Kdyby se lišily počtem protonů, byly by to atomy různých prvků.' },
            { type: 'check', question: { kind: 'choice', q: 'Která dvojice nuklidů jsou izotopy téhož prvku?', options: ['$^{16}_{8}O$ a $^{18}_{8}O$', '$^{14}_{6}C$ a $^{14}_{7}N$', '$^{40}_{18}Ar$ a $^{40}_{20}Ca$', '$^{1}_{1}H$ a $^{4}_{2}He$'], answer: 0, explain: 'Izotopy mají stejné $Z$ a různé $A$. To splňují jen dva kyslíky se $Z = 8$. Ostatní dvojice jsou různé prvky.' } },
          ],
        },
        {
          title: 'Počítáme elektrony v iontech',
          icon: 'electron',
          blocks: [
            { type: 'p', text: 'Při vzniku iontu se mění jen počet elektronů, protony ani neutrony ne. Elektrony v iontu proto spočítáš z protonového čísla a náboje.' },
            { type: 'formula', text: 'počet $e^-$ = $Z$ − náboj iontu', caption: 'u kationtu odečítáš, u aniontu přičítáš (odečítáš záporné číslo)' },
            { type: 'iconlist', items: [
              { icon: 'ion-plus', title: '$Na^+$: 11 p, 10 e', text: 'ztratil 1 elektron' },
              { icon: 'ion-minus', title: '$Cl^-$: 17 p, 18 e', text: 'získal 1 elektron' },
              { icon: 'ion-minus', title: '$O^2-$: 8 p, 10 e', text: 'získal 2 elektrony' },
              { icon: 'ion-plus', title: '$Fe^{3+}$: 26 p, 23 e', text: 'ztratil 3 elektrony' },
            ] },
            { type: 'example', problem: 'Kolik protonů, neutronů a elektronů má ion $^{27}_{13}Al^{3+}$?', steps: [
              'Protony: $Z = 13$.',
              'Neutrony: $N = 27 − 13 = 14$.',
              'Elektrony: náboj +3 znamená, že chybějí 3 elektrony: 13 − 3 = 10.',
            ], answer: '13 protonů, 14 neutronů, 10 elektronů' },
            { type: 'diagram', id: 'bohr', props: { z: 13, ion: 3 }, caption: 'Kation $Al^{3+}$: 13 protonů, ale jen 10 elektronů' },
            { type: 'callout', variant: 'tip', text: 'Rychlá kontrola: sečti náboje. U $Al^{3+}$ je to +13 za protony a −10 za elektrony, dohromady +3. Sedí!' },
            { type: 'game', gameId: 'build-atom', text: 'Vyzkoušej si to v praxi: ve hře Postav atom skládáš z protonů, neutronů a elektronů zadaný atom nebo ion.' },
            { type: 'check', question: { kind: 'number', q: 'Kolik elektronů má ion $^{32}_{16}S^2-$?', answer: 18, tolerance: 0, explain: 'Síra má 16 protonů. Náboj 2− znamená 2 elektrony navíc: 16 + 2 = 18.' } },
          ],
        },
        {
          title: 'Relativní atomová hmotnost',
          icon: 'balance-scale',
          blocks: [
            { type: 'p', text: 'Vážit atomy v kilogramech je nepraktické. Chemici proto zavedli **atomovou hmotnostní konstantu** $m_{u}$: 1/12 hmotnosti atomu uhlíku-12, tedy 1,66·10^{−27} kg.' },
            { type: 'elements', symbols: ['H', 'C', 'O', 'Cl'], caption: '**Relativní atomová hmotnost** $A_{r}$ najdeš u každého prvku v tabulce' },
            { type: 'p', text: '$A_{r}$ říká, kolikrát je atom těžší než $m_{u}$, a je to bezrozměrné číslo. Chlor má 35,5, protože přírodní chlor je směs dvou izotopů a tabulka uvádí jejich **vážený průměr**: těžší slovo má izotop, kterého je víc.' },
            { type: 'compare', columns: [
              { title: '$^{35}Cl$', icon: 'atom', tone: 'a', points: ['17 protonů, 18 neutronů', 'asi **75 %** přírodního chloru'] },
              { title: '$^{37}Cl$', icon: 'atom', tone: 'b', points: ['17 protonů, 20 neutronů', 'asi **25 %** přírodního chloru'] },
            ], caption: 'Přírodní chlor je směs dvou izotopů' },
            { type: 'formula', text: 'A_{r} = A_{1} · x_{1} + A_{2} · x_{2} + …', caption: 'x = zastoupení izotopu jako desetinné číslo (75 % = 0,75)' },
            { type: 'example', title: 'Chlor', problem: 'Přírodní chlor obsahuje 75 % izotopu $^{35}Cl$ a 25 % izotopu $^{37}Cl$. Vypočítej jeho relativní atomovou hmotnost.', steps: [
              'Převeď procenta na desetinná čísla: 0,75 a 0,25.',
              'Vynásob každé nukleonové číslo jeho zastoupením: 35 · 0,75 = 26,25 a 37 · 0,25 = 9,25.',
              'Sečti: 26,25 + 9,25 = 35,5.',
            ], answer: '$A_{r}(Cl)$ = 35,5' },
            { type: 'callout', variant: 'tip', title: 'Kontrola selským rozumem', text: 'Výsledek musí ležet mezi hmotnostmi izotopů a blíž k tomu, kterého je víc. 35,5 je blíž k 35, sedí to. (Tabulkové hodnoty se mírně liší, protože skutečné hmotnosti izotopů nejsou přesně celá čísla.)' },
            { type: 'check', question: { kind: 'number', q: 'Bor obsahuje 20 % izotopu $^{10}B$ a 80 % izotopu $^{11}B$. Jaká je jeho relativní atomová hmotnost?', answer: 10.8, tolerance: 0.02, explain: '10 · 0,20 + 11 · 0,80 = 2 + 8,8 = 10,8. V tabulce najdeš 10,81.' } },
          ],
        },
        {
          title: 'Radioaktivita: záření α, β a γ',
          icon: 'hazard',
          blocks: [
            { type: 'p', text: 'Některá jádra jsou nestabilní, třeba mají příliš mnoho neutronů nebo jsou moc velká. Samovolně se mění na jiná a vysílají přitom **radioaktivní záření**, které objevil Henri Becquerel v roce 1896.' },
            { type: 'callout', variant: 'fact', title: 'Česká stopa', text: 'Marie Curie-Skłodowská a Pierre Curie objevili v roce 1898 nové prvky polonium a radium. Zpracovávali tuny odpadu z uranové rudy smolince z Jáchymova.' },
            { type: 'compare', columns: [
              { title: 'α (alfa)', icon: 'nucleus', tone: 'a', points: ['jádra helia $^{4}_{2}He$', 'náboj +2', 'zastaví ho list papíru, kůže', 'jádro: $Z$ − 2, $A$ − 4'] },
              { title: 'β (beta)', icon: 'electron', tone: 'b', points: ['elektrony vzniklé v jádře', 'náboj −1', 'zastaví ho hliníkový plech (pár mm)', 'jádro: $Z$ + 1, $A$ stejné'] },
              { title: 'γ (gama)', icon: 'lightning', tone: 'c', points: ['elektromagnetické záření s vysokou energií', 'bez náboje', 'zeslabí ho silná vrstva olova nebo betonu', 'jádro: $Z$ ani $A$ se nemění'] },
            ], caption: 'Čím těžší a nabitější částice, tím dřív ji látka zastaví' },
            { type: 'p', text: 'Při přeměně β se v jádře jeden neutron změní na proton a elektron, který jádro opustí. Tak se uhlík-14 mění na dusík-14:' },
            { type: 'formula', text: '$^{14}_{6}C -> ^{14}_{7}N + ^{0}_{−1}e$', caption: 'součet nukleonových i protonových čísel na obou stranách souhlasí' },
            { type: 'check', question: { kind: 'choice', q: 'Jak se změní protonové číslo jádra při přeměně β?', options: ['zvýší se o 1', 'sníží se o 2', 'nezmění se', 'sníží se o 1'], answer: 0, explain: 'Neutron v jádře se změní na proton a elektron odletí, takže $Z$ stoupne o 1 a $A$ zůstane stejné. Uhlík-14 se tak mění na dusík-14.' } },
          ],
        },
        {
          title: 'Poločas přeměny a využití radioaktivity',
          icon: 'stopwatch',
          blocks: [
            { type: 'p', text: '**Poločas přeměny** je doba, za kterou se přemění polovina jader vzorku. Pro uhlík-14 je to 5 730 let, pro jod-131 jen 8 dní.' },
            { type: 'diagram', id: 'half-life', caption: 'Po jednom poločasu zbývá polovina jader, po dvou čtvrtina, po třech osmina' },
            { type: 'iconlist', items: [
              { icon: 'tree', title: 'Radiouhlíková metoda', text: 'Živé organismy mají stálý podíl uhlíku-14, po smrti ho ubývá. Ze zbytku se určí stáří dřeva, kostí nebo látek.' },
              { icon: 'cell', title: 'Léčba nádorů', text: 'kobalt-60 ozařuje nádory' },
              { icon: 'syringe', title: 'Diagnostika a štítná žláza', text: 'technecium-99m a jod-131' },
              { icon: 'factory', title: 'Jaderné elektrárny', text: 'Temelín a Dukovany využívají uran-235' },
              { icon: 'warning', title: 'Hlásiče kouře', text: 'obsahují americium-241' },
            ] },
            { type: 'callout', variant: 'warning', title: 'Bezpečnost', text: 'Radioaktivní záření poškozuje živé buňky. Chrání tě **vzdálenost**, **čas** (co nejkratší) a **stínění**. Se zářiči pracují jen vyškolení odborníci.' },
            { type: 'check', question: { kind: 'number', q: 'Máš 80 g jodu-131 s poločasem přeměny 8 dní. Kolik gramů jodu-131 zbude po 24 dnech?', answer: 10, tolerance: 0, unit: 'g', explain: '24 dní jsou 3 poločasy: 80 g -> 40 g -> 20 g -> 10 g.' } },
          ],
        },
      ],
      summary: [
        'Protonové číslo $Z$ je počet protonů a určuje prvek; nukleonové číslo $A$ je počet protonů a neutronů.',
        'Počet neutronů je $N = A − Z$; počet elektronů v iontu je $Z$ minus náboj.',
        'Izotopy mají stejné $Z$, ale různý počet neutronů (protium, deuterium, tritium; uhlík-12 a uhlík-14).',
        'Relativní atomová hmotnost je vážený průměr izotopů, proto má chlor 35,5.',
        'Záření α jsou jádra helia, β elektrony z jádra, γ vysokoenergetické elektromagnetické záření.',
        'Za jeden poločas přeměny se přemění polovina jader; využívá se k datování i v medicíně.',
      ],
      quiz: [
        { kind: 'number', q: 'Kolik neutronů má atom $^{56}_{26}Fe$?', answer: 30, tolerance: 0, explain: '$N = A − Z = 56 − 26 = 30$.' },
        { kind: 'choice', q: 'Který nuklid je izotopem uhlíku $^{12}_{6}C$?', options: ['$^{13}_{6}C$', '$^{13}_{7}N$', '$^{12}_{7}N$', '$^{12}_{5}B$'], answer: 0, explain: 'Izotop musí mít stejné protonové číslo ($Z = 6$) a jiné nukleonové. Ostatní nuklidy jsou jiné prvky, i když mají stejné $A$.' },
        { kind: 'tf', q: 'Izotopy téhož prvku mají stejný počet neutronů.', answer: false, explain: 'Je to naopak: izotopy mají stejný počet protonů, ale liší se počtem neutronů.' },
        { kind: 'number', q: 'Kolik elektronů má kation $Ca^{2+}$? (Vápník má $Z = 20$.)', answer: 18, tolerance: 0, explain: 'Kation 2+ ztratil dva elektrony: 20 − 2 = 18.' },
        { kind: 'number', q: 'Lithium obsahuje 7,5 % izotopu $^{6}Li$ a 92,5 % izotopu $^{7}Li$. Spočítej jeho relativní atomovou hmotnost.', answer: 6.925, tolerance: 0.02, explain: '6 · 0,075 + 7 · 0,925 = 0,45 + 6,475 = 6,925. Tabulka uvádí 6,94.' },
        { kind: 'match', q: 'Přiřaď druh záření k tomu, co ho zastaví.', pairs: [['záření α', 'list papíru'], ['záření β', 'hliníkový plech'], ['záření γ', 'silná vrstva olova nebo betonu']], explain: 'Těžká a nabitá jádra helia (α) projdou nejméně, elektrony (β) víc a elektromagnetické záření γ je nejpronikavější.' },
        { kind: 'multi', q: 'Co platí pro nuklid $^{3}_{1}H$?', options: ['Je to tritium.', 'Má 2 neutrony.', 'Má 3 protony.', 'Je radioaktivní.', 'Je to jiný prvek než vodík.'], answers: [0, 1, 3], explain: 'Tritium má 1 proton a 3 − 1 = 2 neutrony a je radioaktivní. S jedním protonem je to pořád vodík.' },
        { kind: 'choice', q: 'Vzorek obsahuje 40 g radioaktivního izotopu. Kolik ho zbude po třech poločasech přeměny?', options: ['5 g', '10 g', '13,3 g', '0 g'], answer: 0, explain: 'Každý poločas se množství zmenší na polovinu: 40 g -> 20 g -> 10 g -> 5 g.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l2-4
    'l2-4': {
      id: 'l2-4',
      title: 'Elektronové vrstvy a valenční elektrony',
      goals: [
        'Rozmístit elektrony do vrstev K, L, M, N u prvků se $Z$ ≤ 20 a nakreslit Bohrův model',
        'Určit počet valenčních elektronů a zapsat Lewisovu značku atomu',
        'Vysvětlit pomocí oktetu, proč vzniká $Na^+$ a $Cl^-$',
        'Vysvětlit, co je ionizační energie',
      ],
      hook: 'Neon v zářivých reklamách nereaguje skoro s ničím. Sodík, jeho soused v tabulce, ve vodě prská a syčí. A rozdíl mezi nimi? Jediný elektron. Pojď zjistit, proč právě ten jeden rozhoduje.',
      sections: [
        {
          title: 'Elektrony bydlí ve vrstvách',
          icon: 'atom',
          blocks: [
            { type: 'p', text: 'Podle Bohrova modelu se elektrony pohybují kolem jádra jen v určitých **elektronových vrstvách** (slupkách). Čím dál je vrstva od jádra, tím vyšší energii její elektrony mají.' },
            { type: 'diagram', id: 'bohr', props: { z: 11 }, caption: 'Sodík (Z = 11): 2 elektrony v K, 8 v L, 1 v M' },
            { type: 'p', text: 'Vrstvy se číslují $n$ = 1, 2, 3, 4… nebo označují písmeny K, L, M, N… Každá vrstva pojme nejvýše 2n^{2} elektronů.' },
            { type: 'table', headers: ['Vrstva', '$n$', 'Maximum 2n^{2}', 'U prvků se Z ≤ 20'], rows: [
              ['K', '1', '2', '2'],
              ['L', '2', '8', '8'],
              ['M', '3', '18', '8'],
              ['N', '4', '32', '1–2 (jen K a Ca)'],
            ], caption: 'Poslední sloupec je model **2-8-8-2** pro prvních 20 prvků: vrstvy se plní odvnitř ven, od K nejblíž jádru.' },
            { type: 'callout', variant: 'warning', title: 'Proč jen 8 v M?', text: 'Vrstva M pojme až 18 elektronů. U draslíku a vápníku ale 19. a 20. elektron obsadí nejdřív vrstvu N. Proč, vysvětlí až orbitaly v příští lekci.' },
            { type: 'check', question: { kind: 'choice', q: 'Jak jsou rozmístěny elektrony v atomu hořčíku ($Z = 12$)?', options: ['2, 8, 2', '2, 10', '8, 4', '2, 2, 8'], answer: 0, explain: 'Zaplňuj odvnitř: K pojme 2, L 8, zbylé 2 elektrony jdou do M.' } },
          ],
        },
        {
          title: 'Jak nakreslit atom po vrstvách',
          icon: 'pencil',
          blocks: [
            { type: 'process', layout: 'flow', steps: [
              { icon: 'periodic-table', title: 'Najdi $Z$', text: 'u neutrálního atomu je to i počet elektronů' },
              { icon: 'electron', title: 'K: 2 elektrony' },
              { icon: 'electron', title: 'L: až 8' },
              { icon: 'electron', title: 'M: až 8' },
              { icon: 'electron', title: 'N: zbytek', text: 'nejvýš 2' },
            ], caption: 'Postup pro prvky se $Z$ ≤ 20' },
            { type: 'example', problem: 'Rozmísti elektrony atomu hliníku ($Z = 13$) do vrstev.', steps: [
              '13 elektronů celkem.',
              'K: 2, zbývá 11.',
              'L: 8, zbývá 3.',
              'M: 3, hotovo.',
            ], answer: 'Al: 2, 8, 3' },
            { type: 'table', headers: ['Prvek', '$Z$', 'K', 'L', 'M', 'N'], rows: [
              ['H', '1', '1', '', '', ''],
              ['C', '6', '2', '4', '', ''],
              ['O', '8', '2', '6', '', ''],
              ['Ne', '10', '2', '8', '', ''],
              ['Cl', '17', '2', '8', '7', ''],
              ['Ar', '18', '2', '8', '8', ''],
              ['Ca', '20', '2', '8', '8', '2'],
            ] },
            { type: 'diagram', id: 'bohr', props: { z: 17 }, caption: 'Chlor (Z = 17): 2, 8, 7. Poslední vrstvě chybí jediný elektron do osmi.' },
            { type: 'check', question: { kind: 'number', q: 'Kolik elektronů má atom fosforu ($Z = 15$) v poslední vrstvě?', answer: 5, tolerance: 0, explain: 'Rozmístění je 2, 8, 5. Ve vrstvě M je tedy 5 elektronů.' } },
          ],
        },
        {
          title: 'Valenční elektrony a Lewisovy značky',
          icon: 'electron',
          blocks: [
            { type: 'p', text: 'Elektrony v poslední (vnější) vrstvě se jmenují **valenční elektrony** a vrstva **valenční vrstva**. Jsou nejdál od jádra, a proto se účastní chemických reakcí a vazeb.' },
            { type: 'diagram', id: 'bohr', props: { z: 8 }, caption: 'Kyslík 2, 6: vnitřní 2 elektrony zůstávají stranou, 6 valenčních ve vrstvě L reaguje' },
            { type: 'p', text: 'Gilbert N. Lewis vymyslel jednoduchý zápis: kolem značky nakreslíš tolik teček, kolik má atom valenčních elektronů. Tečky dávej nejdřív po jedné na čtyři strany a teprve potom je spojuj do dvojic.' },
            { type: 'structure', art: [
              '         •     •     •    ••    ••',
              ' Li•    •C•   :N•   :O:   :F:  :Ne:',
              '         •     •     •     •    ••',
            ].join('\n'), caption: 'Lewisovy značky: Li má 1 valenční elektron, C 4, N 5, O 6, F 7 a Ne 8' },
            { type: 'callout', variant: 'tip', text: 'V lekci o periodické soustavě uvidíš, že počet valenčních elektronů prozradí už poloha prvku v tabulce. Prvky pod sebou mají stejný počet valenčních elektronů, a proto se chemicky podobají.' },
            { type: 'game', gameId: 'who-am-i', text: 'Zahraj si Kdo jsem? a hádej prvky podle nápověd typu „mám 7 valenčních elektronů a tři vrstvy“.' },
            { type: 'check', question: { kind: 'match', q: 'Přiřaď k prvku počet jeho valenčních elektronů.', pairs: [['Na (Z = 11)', '1'], ['C (Z = 6)', '4'], ['S (Z = 16)', '6'], ['Cl (Z = 17)', '7']], explain: 'Na 2, 8, 1; C 2, 4; S 2, 8, 6; Cl 2, 8, 7. Rozhoduje poslední vrstva.' } },
          ],
        },
        {
          title: 'Oktet: proč atomy tvoří ionty',
          icon: 'ion-plus',
          blocks: [
            { type: 'p', text: '**Vzácné plyny** skoro s ničím nereagují, protože mají zaplněnou valenční vrstvu: helium 2 elektrony, ostatní 8. Osmici valenčních elektronů se říká **elektronový oktet**.' },
            { type: 'elements', symbols: ['He', 'Ne', 'Ar'], caption: 'Helium 2, neon 2, 8 a argon 2, 8, 8: plná valenční vrstva' },
            { type: 'p', text: '==Atomy ostatních prvků se snaží dosáhnout stejně stabilního uspořádání jako nejbližší vzácný plyn.== Mohou elektrony odevzdat, nebo přijmout, a stát se iontem, anebo je sdílet ve vazbě (o tom v úrovni 3).' },
            { type: 'compare', columns: [
              { title: 'Kovy: 1–3 valenční e⁻', icon: 'ion-plus', tone: 'a', points: ['elektrony snadno **odevzdávají**', '$Na$ 2, 8, 1 -> $Na^+$ 2, 8 (jako Ne)', '$Mg$ 2, 8, 2 -> $Mg^{2+}$ 2, 8 (jako Ne)', 'tvoří **kationty**'] },
              { title: 'Nekovy: 5–7 valenčních e⁻', icon: 'ion-minus', tone: 'b', points: ['elektrony **přijímají**', '$O$ 2, 6 -> $O^2-$ 2, 8 (jako Ne)', '$Cl$ 2, 8, 7 -> $Cl^-$ 2, 8, 8 (jako Ar)', 'tvoří **anionty**'] },
            ] },
            { type: 'formula', text: '$Na -> Na^+ + e^-$ a $Cl + e^- -> Cl^-$', caption: 'sodík elektron odevzdá, chlor ho přijme' },
            { type: 'diagram', id: 'bohr', props: { z: 11, ion: 1 }, caption: 'Kation $Na^+$: po ztrátě valenčního elektronu zbyly vrstvy 2, 8 jako u neonu' },
            { type: 'diagram', id: 'bohr', props: { z: 17, ion: -1 }, caption: 'Anion $Cl^-$: po přijetí elektronu má vrstvy 2, 8, 8 jako argon' },
            { type: 'callout', variant: 'mascot', text: 'Sodík a chlor jsou jako dva kamarádi: jeden má jeden elektron navíc, druhému jeden chybí. Výsledek? Kuchyňská sůl na tvých hranolkách.' },
            { type: 'check', question: { kind: 'choice', q: 'Jaký ion nejspíš vytvoří atom hořčíku (2, 8, 2)?', options: ['$Mg^{2+}$', '$Mg^+$', '$Mg^2-$', '$Mg^{6-}$'], answer: 0, explain: 'Hořčíku se vyplatí odevzdat 2 valenční elektrony a získat uspořádání neonu 2, 8. Přijmout šest elektronů by bylo energeticky nevýhodné.' } },
          ],
        },
        {
          title: 'Ionizační energie',
          icon: 'lightning',
          blocks: [
            { type: 'p', text: '**Ionizační energie** je energie potřebná k odtržení nejslaběji vázaného elektronu z atomu v plynném stavu. Čím je menší, tím snadněji atom vytvoří kation. Vzácné plyny ji mají velmi vysokou, a proto netvoří ionty.' },
            { type: 'table', headers: ['Prvek', 'Vrstvy', '1. ionizační energie (kJ/mol)'], rows: [
              ['K', '2, 8, 8, 1', '419'],
              ['Na', '2, 8, 1', '496'],
              ['Mg', '2, 8, 2', '738'],
              ['Ar', '2, 8, 8', '1 521'],
              ['Ne', '2, 8', '2 081'],
              ['He', '2', '2 372'],
            ], caption: 'Jednotce kJ/mol porozumíš v úrovni 4; zatím stačí čísla porovnávat.' },
            { type: 'compare', columns: [
              { title: '1. elektron sodíku', icon: 'electron', tone: 'good', points: ['sám ve vrstvě M, daleko od jádra', 'vnitřní vrstvy ho před jádrem stíní', '**496 kJ/mol**: odtrhne se snadno -> $Na^+$'] },
              { title: '2. elektron sodíku', icon: 'nucleus', tone: 'bad', points: ['v zaplněné vrstvě L blízko jádra', '**4 562 kJ/mol**, skoro desetkrát víc', 'proto nikdy nevznikne $Na^{2+}$'] },
            ] },
            { type: 'diagram', id: 'bohr', props: { z: 12 }, caption: 'Hořčík 2, 8, 2: dva elektrony ve vnější vrstvě, pod nimi zaplněná vrstva L' },
            { type: 'callout', variant: 'fact', title: 'Důkaz vrstev', text: 'Hořčík má ionizační energie 738, 1 451 a pak najednou 7 733 kJ/mol. Obrovský skok po druhém elektronu prozrazuje, že dva elektrony jsou ve vnější vrstvě a další už ve vrstvě vnitřní. Tak se vrstvy opravdu dají „změřit“.' },
            { type: 'check', question: { kind: 'tf', q: 'Druhá ionizační energie sodíku je mnohem větší než první.', answer: true, explain: 'Druhý elektron by se musel vytrhnout ze zaplněné vrstvy L, která je blíž jádru. To stojí téměř desetkrát víc energie.' } },
          ],
        },
      ],
      summary: [
        'Elektrony obsazují vrstvy K, L, M, N; vrstva pojme nejvýše 2n^{2} elektronů.',
        'U prvků se $Z$ ≤ 20 platí model 2-8-8-2.',
        'Valenční elektrony jsou v poslední vrstvě a účastní se reakcí; Lewisova značka je znázorňuje tečkami.',
        'Vzácné plyny mají stabilní oktet (helium dvojici), ostatní atomy se k němu přibližují tvorbou iontů nebo vazeb.',
        'Kovy s 1–3 valenčními elektrony tvoří kationty, nekovy s 5–7 valenčními elektrony anionty.',
        'Ionizační energie je energie nutná k odtržení elektronu; nízká je u sodíku a draslíku, vysoká u vzácných plynů.',
      ],
      quiz: [
        { kind: 'choice', q: 'Jak jsou rozmístěny elektrony v atomu síry ($Z = 16$)?', options: ['2, 8, 6', '2, 6, 8', '2, 14', '8, 8'], answer: 0, explain: 'K pojme 2, L 8 a zbylých 6 elektronů jde do vrstvy M.' },
        { kind: 'number', q: 'Kolik valenčních elektronů má křemík ($Z = 14$)?', answer: 4, tolerance: 0, explain: 'Rozmístění 2, 8, 4: ve valenční vrstvě M jsou 4 elektrony.' },
        { kind: 'tf', q: 'Vrstva M může obsahovat nejvýše 8 elektronů.', answer: false, explain: 'Vrstva M ($n$ = 3) pojme až 2 · 3^{2} = 18 elektronů. Model 2-8-8 platí jen pro prvních 20 prvků.' },
        { kind: 'match', q: 'Přiřaď k atomu ion, který nejsnáze vytvoří.', pairs: [['Na', '$Na^+$'], ['Mg', '$Mg^{2+}$'], ['O', '$O^2-$'], ['Cl', '$Cl^-$']], explain: 'Každý z nich tak získá uspořádání nejbližšího vzácného plynu: Na, Mg a O jako neon, Cl jako argon.' },
        { kind: 'multi', q: 'Které částice mají elektrony rozmístěné stejně jako neon (2, 8)?', options: ['$Na^+$', '$Mg^{2+}$', '$F^-$', '$Cl^-$', '$K^+$'], answers: [0, 1, 2], explain: '$Na^+$, $Mg^{2+}$ a $F^-$ mají po 10 elektronech. $Cl^-$ a $K^+$ mají 18 elektronů, tedy uspořádání argonu.' },
        { kind: 'text', q: 'Napiš značku vzácného plynu, jehož uspořádání elektronů získá ion $Cl^-$.', accept: ['Ar'], caseSensitive: true, placeholder: 'značka', explain: '$Cl^-$ má 18 elektronů (2, 8, 8), stejně jako argon.' },
        { kind: 'choice', q: 'Proč sodík tak snadno tvoří kation $Na^+$?', options: ['Jeho jediný valenční elektron je daleko od jádra a má nízkou ionizační energii.', 'Sodík má v jádře málo neutronů.', 'Sodík potřebuje přijmout 7 elektronů do oktetu.', 'Valenční elektron sodíku je ve vrstvě K.'], answer: 0, explain: 'Osamocený elektron ve vrstvě M je stíněný vnitřními vrstvami a slabě vázaný, jeho odtržením sodík získá uspořádání neonu.' },
        { kind: 'order', q: 'Seřaď atomy podle první ionizační energie od nejmenší.', items: ['K', 'Na', 'Mg', 'Ne'], explain: 'Draslík (419) má valenční elektron nejdál od jádra, pak sodík (496), hořčík (738) a neon (2 081) se zaplněným oktetem.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l2-5
    'l2-5': {
      id: 'l2-5',
      title: 'Orbitaly a elektronová konfigurace',
      goals: [
        'Vysvětlit, co je orbital, a popsat význam čtyř kvantových čísel',
        'Napsat elektronovou konfiguraci atomu podle výstavbového principu, Pauliho principu a Hundova pravidla, i ve zkráceném zápisu',
        'Nakreslit rámečkový diagram a určit počet nepárových elektronů',
        'Znát výjimky Cr a Cu a zapsat konfiguraci iontu',
      ],
      hook: 'Bohrův model s elektrony na drahách je jako plánek metra: užitečný, ale skutečnost vypadá jinak. Elektron totiž žádnou dráhu nemá. Je to spíš obláček pravděpodobnosti. Zní to divně? Vítej v kvantovém světě!',
      sections: [
        {
          title: 'Orbital: kde se elektron nejspíš vyskytuje',
          icon: 'gas-cloud',
          blocks: [
            { type: 'p', text: 'Ve 20. letech 20. století fyzici zjistili, že u elektronu nelze zároveň přesně určit polohu i rychlost (**Heisenbergův princip neurčitosti**). Nemá proto smysl kreslit mu přesnou dráhu.' },
            { type: 'diagram', id: 'shells-vs-orbitals', caption: 'Tentýž atom uhlíku dvakrát. Vlevo Bohrův model: elektrony na přesných drahách ve vrstvách K a L. Vpravo kvantový model: tečky ukazují, kde se elektrony nejspíš vyskytují – v orbitalech 1s, 2s a 2p.' },
            { type: 'compare', columns: [
              { title: 'Bohrův model', icon: 'atom', tone: 'a', points: ['elektron obíhá po přesné dráze', 'vrstvy K, L, M…', 'jednoduchý a užitečný, jako plánek metra'] },
              { title: 'Kvantový model', icon: 'gas-cloud', tone: 'b', points: ['přesnou dráhu určit nelze', 'popisuje, **kde se elektron s jakou pravděpodobností vyskytuje**', 'oblast s velkou pravděpodobností výskytu (obvykle 90 %) je **orbital**'] },
            ] },
            { type: 'callout', variant: 'tip', title: 'Představ si to', text: 'Vyfoť včelu u úlu s hodně dlouhou expozicí. Na fotce nebude jedna včela, ale rozmazaný oblak, nejhustší tam, kde se zdržovala nejčastěji. Orbital je takový „oblak“ pro elektron.' },
            { type: 'keyterms', items: [
              { term: '**Orbital**', def: 'oblast, kde se elektron vyskytuje s velkou pravděpodobností; pojme nejvýš 2 elektrony.' },
              { term: '**Vrstva (slupka)**', def: 'orbitaly se stejným hlavním kvantovým číslem $n$; odpovídá vrstvám K, L, M… z Bohrova modelu.' },
              { term: '**Podslupka**', def: 'orbitaly stejného typu v jedné vrstvě, například tři orbitaly 2p.' },
            ] },
            { type: 'check', question: { kind: 'tf', q: 'Podle kvantového modelu obíhá elektron kolem jádra po přesné kruhové dráze.', answer: false, explain: 'Přesnou dráhu elektronu určit nelze. Kvantový model popisuje jen pravděpodobnost výskytu elektronu, tedy orbital.' } },
          ],
        },
        {
          title: 'Čtyři kvantová čísla a tvary orbitalů',
          icon: 'magnet',
          blocks: [
            { type: 'p', text: 'Každý elektron v atomu popisují čtyři **kvantová čísla**. Jsou jako jeho adresa: vrstva, typ orbitalu, konkrétní orbital a „otočení“ elektronu.' },
            { type: 'table', headers: ['Kvantové číslo', 'Hodnoty', 'Co určuje'], rows: [
              ['hlavní $n$', '1, 2, 3, …', 'energie a velikost orbitalu, číslo vrstvy'],
              ['vedlejší $l$', '0 až $n$ − 1', 'tvar orbitalu: 0 = s, 1 = p, 2 = d, 3 = f'],
              ['magnetické $m$', '−$l$ až +$l$', 'orientace orbitalu v prostoru, a tím počet orbitalů v podslupce'],
              ['spinové $s$', '+½, −½', 'spin elektronu, kreslíme šipkou ↑ nebo ↓'],
            ] },
            { type: 'diagram', id: 'orbital-shapes', caption: 'Na obrázku je orbital s – koule (v každé vrstvě jeden), tři orbitaly p – činky (prostorové osmičky) podél os x, y, z – a jeden z pěti orbitalů d, čtyřlístek mezi osami x a y. Čtyři orbitaly d jsou takové čtyřlístky, pátý je činka s prstencem; sedm orbitalů f má složité tvary.' },
            { type: 'table', headers: ['Podslupka', 'Počet orbitalů', 'Max. elektronů', 'Objevuje se od vrstvy'], rows: [
              ['s', '1', '2', '$n$ = 1'],
              ['p', '3', '6', '$n$ = 2'],
              ['d', '5', '10', '$n$ = 3'],
              ['f', '7', '14', '$n$ = 4'],
            ] },
            { type: 'callout', variant: 'fact', title: 'Proč zrovna s, p, d, f?', text: 'Písmena pocházejí z popisu čar ve spektrech: *sharp*, *principal*, *diffuse* a *fundamental* (ostrá, hlavní, rozmazaná, základní).' },
            { type: 'p', text: 'Teď už víš, proč vrstva pojme 2n^{2} elektronů: vrstva $n$ = 3 má podslupky 3s, 3p a 3d, tedy 1 + 3 + 5 = 9 orbitalů a v nich 18 elektronů.' },
            { type: 'check', question: { kind: 'number', q: 'Kolik elektronů nejvýše pojme podslupka d?', answer: 10, tolerance: 0, explain: 'Podslupka d má 5 orbitalů a do každého se vejdou 2 elektrony: 5 · 2 = 10.' } },
          ],
        },
        {
          title: 'Výstavbový princip: v jakém pořadí se orbitaly plní',
          icon: 'chart',
          blocks: [
            { type: 'p', text: '**Výstavbový princip** (anglicky *Aufbau*) říká, že elektrony obsazují orbitaly postupně **od nejnižší energie**. Energie ale neroste přesně po vrstvách, podslupky se překrývají.' },
            { type: 'formula', text: '1s -> 2s -> 2p -> 3s -> 3p -> 4s -> 3d -> 4p -> 5s -> 4d -> 5p -> 6s -> 4f -> 5d -> 6p -> 7s', caption: 'celé pořadí zaplňování orbitalů' },
            { type: 'p', text: 'Pořadí se nemusíš učit nazpaměť. Stačí **pravidlo n + l**: dřív se zaplní podslupka s menším součtem $n + l$, při stejném součtu ta s menším $n$. Orbital 4s má součet 4 + 0 = 4, orbital 3d 3 + 2 = 5, proto se 4s zaplní dřív.' },
            { type: 'structure', art: [
              '1s',
              '2s  2p',
              '3s  3p  3d',
              '4s  4p  4d  4f',
              '5s  5p  5d  5f',
              '6s  6p  6d',
              '7s  7p',
            ].join('\n'), caption: 'Diagonální pravidlo: čti po šikmých úhlopříčkách zprava shora doleva dolů: 1s | 2s | 2p 3s | 3p 4s | 3d 4p 5s | …' },
            { type: 'callout', variant: 'remember', text: '==Orbital 4s se zaplňuje dřív než 3d.== Proto mají draslík a vápník elektrony ve vrstvě N, i když je vrstva M ještě neplná.' },
            { type: 'check', question: { kind: 'order', q: 'Seřaď podslupky v pořadí, v jakém se zaplňují.', items: ['3s', '3p', '4s', '3d', '4p'], explain: 'Podle pravidla n + l: 3s (součet 3), 3p (4), 4s (také 4, ale větší n než 3p), 3d (5) a 4p (také 5, ale větší n než 3d).' } },
          ],
        },
        {
          title: 'Pauliho princip a Hundovo pravidlo',
          icon: 'arrow-cycle',
          blocks: [
            { type: 'compare', columns: [
              { title: 'Pauliho princip výlučnosti', icon: 'electron', tone: 'a', points: ['dva elektrony v atomu nemohou mít všechna čtyři kvantová čísla stejná', 'v jednom orbitalu jsou proto **nejvýš dva elektrony**, s opačným spinem ↑↓', 'takové dva elektrony tvoří **elektronový pár**'] },
              { title: 'Hundovo pravidlo', icon: 'idea', tone: 'b', points: ['platí pro orbitaly se stejnou energií, například tři orbitaly 2p', 'elektrony se nejdřív rozmístí **po jednom se stejným spinem**', 'párují se až potom'] },
            ] },
            { type: 'callout', variant: 'tip', title: 'Pravidlo autobusu', text: 'V autobuse si lidé nejdřív sedají každý na volnou dvojsedačku. K někomu si přisednou, až když volná dvojsedačka nezbude. Elektrony v orbitalech p nebo d se chovají stejně.' },
            { type: 'p', text: 'Konfiguraci proto často kreslíme jako **rámečkový diagram**: rámeček je orbital, šipka elektron. Elektron, který je v orbitalu sám, je **nepárový**; nepárové elektrony budou důležité pro vazby v úrovni 3.' },
            { type: 'diagram', id: 'orbitals', props: { z: 7 }, caption: 'Dusík 1s^{2} 2s^{2} 2p^{3}: tři elektrony 2p sedí každý ve svém orbitalu, dusík má 3 nepárové elektrony' },
            { type: 'diagram', id: 'orbitals', props: { z: 8 }, caption: 'Kyslík 1s^{2} 2s^{2} 2p^{4}: čtvrtý elektron 2p se musí spárovat, zbývají 2 nepárové elektrony' },
            { type: 'check', question: { kind: 'choice', q: 'Jak správně zakreslit dva elektrony 2p v atomu uhlíku?', options: ['[↑] [↑] [ ]', '[↑↓] [ ] [ ]', '[↑] [↓] [ ]', '[↑↓] [↑↓] [ ]'], answer: 0, explain: 'Podle Hundova pravidla obsadí elektrony dva různé orbitaly se stejným spinem. Poslední možnost má navíc 4 elektrony místo 2.' } },
          ],
        },
        {
          title: 'Píšeme elektronovou konfiguraci',
          icon: 'pencil',
          blocks: [
            { type: 'p', text: '**Elektronová konfigurace** je zápis rozmístění elektronů do podslupek. Počet elektronů v podslupce píšeš jako horní index: 2p^{4} jsou čtyři elektrony v podslupce 2p.' },
            { type: 'process', layout: 'flow', steps: [
              { icon: 'calculator', title: 'Spočítej elektrony', text: 'u atomu je to $Z$' },
              { icon: 'chart', title: 'Plň podslupky', text: 'podle výstavbového principu: s nejvýš 2, p 6, d 10' },
              { icon: 'check', title: 'Zkontroluj součet', text: 'součet horních indexů = počet elektronů' },
            ] },
            { type: 'example', title: 'Síra', problem: 'Napiš elektronovou konfiguraci síry ($Z = 16$).', steps: [
              '1s^{2} (2 elektrony, zbývá 14)',
              '2s^{2} 2p^{6} (dalších 8, zbývá 6)',
              '3s^{2} 3p^{4} (posledních 6)',
              'Kontrola: 2 + 2 + 6 + 2 + 4 = 16.',
            ], answer: 'S: 1s^{2} 2s^{2} 2p^{6} 3s^{2} 3p^{4}' },
            { type: 'diagram', id: 'orbitals', props: { z: 16 }, caption: 'Síra v rámečcích: v podslupce 3p jeden pár a dva nepárové elektrony' },
            { type: 'p', text: '**Zkrácený zápis:** vnitřní elektrony nahradíš značkou předchozího vzácného plynu v hranatých závorkách. Síra má před sebou neon (1s^{2} 2s^{2} 2p^{6}), takže S: [Ne] 3s^{2} 3p^{4}. Hned vidíš 6 valenčních elektronů.' },
            { type: 'example', title: 'Železo', problem: 'Napiš úplnou i zkrácenou konfiguraci železa ($Z = 26$).', steps: [
              '1s^{2} 2s^{2} 2p^{6} 3s^{2} 3p^{6} je 18 elektronů, to je konfigurace argonu.',
              'Pak 4s^{2} (20 elektronů).',
              'Zbylých 6 elektronů jde do 3d: 3d^{6}.',
            ], answer: 'Fe: 1s^{2} 2s^{2} 2p^{6} 3s^{2} 3p^{6} 4s^{2} 3d^{6} = [Ar] 4s^{2} 3d^{6}' },
            { type: 'callout', variant: 'tip', text: 'V některých učebnicích uvidíš zápis [Ar] 3d^{6} 4s^{2}, seřazený podle vrstev. Obě pořadí jsou správně, obsah je stejný.' },
            { type: 'game', gameId: 'electron-config', text: 'Ve hře Zaplň orbitaly rozmísťuješ šipky do rámečků. Dodrž výstavbový princip, Pauliho princip i Hundovo pravidlo!' },
            { type: 'check', question: { kind: 'text', q: 'Napiš zkrácenou elektronovou konfiguraci sodíku ($Z = 11$). Horní indexy piš jako obyčejné číslice, např. 2p6.', accept: ['[Ne]3s1', '[Ne] 3s1', '[Ne]3s^1', '[Ne] 3s^{1}', '1s2 2s2 2p6 3s1', '1s22s22p63s1'], caseSensitive: true, placeholder: '[?] …', explain: 'Sodík má o jeden elektron víc než neon: [Ne] 3s^{1}.' } },
          ],
        },
        {
          title: 'Výjimky a konfigurace iontů',
          icon: 'warning',
          blocks: [
            { type: 'p', text: 'Výstavbový princip má pár výjimek, nejznámější jsou **chrom** a **měď**. Zaplněná (d^{10}) nebo přesně z poloviny zaplněná (d^{5}) podslupka d je zvlášť stabilní, a tak jeden elektron „přeskočí“ ze 4s do 3d.' },
            { type: 'compare', columns: [
              { title: 'Chrom ($Z = 24$)', tone: 'a', points: ['podle pravidla by bylo: [Ar] 4s^{2} 3d^{4}', 've skutečnosti: **[Ar] 4s^{1} 3d^{5}**', 'napůl zaplněná 3d^{5}'] },
              { title: 'Měď ($Z = 29$)', tone: 'b', points: ['podle pravidla by bylo: [Ar] 4s^{2} 3d^{9}', 've skutečnosti: **[Ar] 4s^{1} 3d^{10}**', 'zcela zaplněná 3d^{10}'] },
            ] },
            { type: 'diagram', id: 'orbitals', props: { z: 24 }, caption: 'Chrom: šest nepárových elektronů, pět v 3d a jeden ve 4s' },
            { type: 'compare', columns: [
              { title: 'Anionty', icon: 'ion-minus', tone: 'a', points: ['elektrony **přidáš** do první volné podslupky', '$Cl^-$: [Ne] 3s^{2} 3p^{6}, konfigurace argonu'] },
              { title: 'Kationty', icon: 'ion-plus', tone: 'b', points: ['elektrony **odebíráš** z podslupky s **nejvyšším n**', 'hlavní skupiny: $Na^+$ je [Ne]', 'železo a další přechodné kovy ztrácejí nejdřív elektrony 4s, až potom 3d'] },
            ], caption: 'Konfigurace iontů' },
            { type: 'example', problem: 'Napiš konfiguraci iontů $Fe^{2+}$ a $Fe^{3+}$.', steps: [
              'Atom Fe: [Ar] 4s^{2} 3d^{6}.',
              '$Fe^{2+}$: odeber 2 elektrony ze 4s -> [Ar] 3d^{6}.',
              '$Fe^{3+}$: odeber ještě 1 elektron z 3d -> [Ar] 3d^{5}.',
            ], answer: '$Fe^{2+}$: [Ar] 3d^{6}, $Fe^{3+}$: [Ar] 3d^{5}' },
            { type: 'callout', variant: 'warning', title: 'Nejčastější chyba', text: 'Konfigurace $Fe^{2+}$ **není** [Ar] 4s^{2} 3d^{4}. Orbital 4s se plní první, ale při vzniku kationtu se také vyprazdňuje první.' },
            { type: 'check', question: { kind: 'choice', q: 'Jaká je elektronová konfigurace mědi ($Z = 29$)?', options: ['[Ar] 4s^{1} 3d^{10}', '[Ar] 4s^{2} 3d^{9}', '[Ar] 4s^{2} 3d^{10}', '[Kr] 4s^{1}'], answer: 0, explain: 'Měď je výjimka: zaplněná podslupka 3d^{10} je stabilnější, proto jeden elektron přejde ze 4s do 3d.' } },
          ],
        },
      ],
      summary: [
        'Orbital je oblast, kde se elektron vyskytuje s velkou pravděpodobností; pojme nejvýš 2 elektrony.',
        'Kvantová čísla $n$, $l$, $m$, $s$ určují vrstvu, tvar, orientaci orbitalu a spin elektronu.',
        'Orbital s má tvar koule, p činky; podslupky s, p, d, f pojmou 2, 6, 10 a 14 elektronů.',
        'Orbitaly se plní podle výstavbového principu (1s 2s 2p 3s 3p 4s 3d …); 4s se plní před 3d.',
        'Pauliho princip: v orbitalu jsou nejvýš 2 elektrony s opačným spinem. Hundovo pravidlo: nejdřív po jednom, pak párovat.',
        'Zkrácený zápis využívá vzácný plyn, např. S: [Ne] 3s^{2} 3p^{4}.',
        'Výjimky: Cr [Ar] 4s^{1} 3d^{5}, Cu [Ar] 4s^{1} 3d^{10}; kationty přechodných kovů ztrácejí nejdřív elektrony 4s.',
      ],
      quiz: [
        { kind: 'choice', q: 'Jaký tvar má orbital p?', options: ['činky (prostorové osmičky)', 'koule', 'čtyřlístku', 'plochého kruhu'], answer: 0, explain: 'Orbitaly p mají tvar činky a jsou tři, podél os x, y a z. Kulový je orbital s, čtyřlístky jsou orbitaly d.' },
        { kind: 'number', q: 'Kolik elektronů nejvýše pojme vrstva s hlavním kvantovým číslem $n$ = 3?', answer: 18, tolerance: 0, explain: '2n^{2} = 2 · 9 = 18. Vrstva má podslupky 3s, 3p a 3d: 2 + 6 + 10 = 18.' },
        { kind: 'tf', q: 'Orbital 4s se zaplňuje dřív než 3d.', answer: true, explain: 'Podle pravidla n + l má 4s součet 4, kdežto 3d součet 5, takže 4s má nižší energii a plní se první.' },
        { kind: 'order', q: 'Seřaď podslupky podle výstavbového principu.', items: ['2p', '3s', '3p', '4s', '3d'], explain: 'Pořadí zaplňování je 1s 2s 2p 3s 3p 4s 3d 4p…' },
        { kind: 'choice', q: 'Jaká je elektronová konfigurace fosforu ($Z = 15$)?', options: ['1s^{2} 2s^{2} 2p^{6} 3s^{2} 3p^{3}', '1s^{2} 2s^{2} 2p^{6} 3s^{2} 3p^{5}', '1s^{2} 2s^{2} 2p^{6} 3s^{1} 3p^{4}', '1s^{2} 2s^{2} 2p^{6} 3s^{2} 3d^{3}'], answer: 0, explain: 'Po neonu (10 elektronů) zbývá 5: dva do 3s a tři do 3p. Podslupka 3d přichází na řadu až po 4s.' },
        { kind: 'number', q: 'Kolik nepárových elektronů má atom dusíku ($Z = 7$) v základním stavu?', answer: 3, tolerance: 0, explain: 'Konfigurace 1s^{2} 2s^{2} 2p^{3}. Podle Hundova pravidla sedí tři elektrony 2p každý ve svém orbitalu, všechny tři jsou nepárové.' },
        { kind: 'multi', q: 'Které konfigurace jsou **správně**?', options: ['Cr: [Ar] 4s^{1} 3d^{5}', 'Cu: [Ar] 4s^{1} 3d^{10}', '$Fe^{2+}$: [Ar] 4s^{2} 3d^{4}', 'Ca: [Ar] 4s^{2}', '$Cl^-$: [Ne] 3s^{2} 3p^{5}'], answers: [0, 1, 3], explain: 'Cr a Cu jsou známé výjimky, Ca je v pořádku. $Fe^{2+}$ ztrácí nejdřív elektrony 4s, je to [Ar] 3d^{6}. $Cl^-$ má o elektron víc než atom: [Ne] 3s^{2} 3p^{6}.' },
        { kind: 'match', q: 'Přiřaď kvantové číslo k tomu, co určuje.', pairs: [['hlavní $n$', 'energie a velikost orbitalu (vrstva)'], ['vedlejší $l$', 'tvar orbitalu (s, p, d, f)'], ['magnetické $m$', 'orientace orbitalu v prostoru'], ['spinové $s$', 'spin elektronu (↑ nebo ↓)']], explain: 'Čtyři kvantová čísla tvoří „adresu“ elektronu: vrstva, typ orbitalu, konkrétní orbital a spin.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l2-6
    'l2-6': {
      id: 'l2-6',
      title: 'Periodická soustava prvků',
      goals: [
        'Vysvětlit periodický zákon a orientovat se ve skupinách, periodách a blocích s, p, d, f',
        'Pojmenovat hlavní skupiny a rozlišit kovy, nekovy a polokovy',
        'Popsat, jak se v tabulce mění atomový poloměr, ionizační energie, elektronegativita a kovový charakter',
        'Předpovědět vlastnosti prvku z jeho polohy v tabulce',
      ],
      hook: 'Mendělejev v roce 1869 nechal ve své tabulce prázdná políčka a tvrdil, že tam patří prvky, které ještě nikdo neobjevil. Dokonce předpověděl jejich vlastnosti. Do sedmnácti let byly objeveny tři z nich a sedělo to. Pojď se naučit číst tabulku jako mapu!',
      sections: [
        {
          title: 'Mendělejev a periodický zákon',
          icon: 'book',
          blocks: [
            { type: 'p', text: 'V polovině 19. století znali chemici asi 60 prvků a hledali v nich pořádek. Ruský chemik **Dmitrij Ivanovič Mendělejev** je v roce 1869 seřadil podle rostoucí atomové hmotnosti a prvky s podobnými vlastnostmi dal pod sebe.' },
            { type: 'process', layout: 'flow', steps: [
              { icon: 'book', title: '1869: Mendělejev', text: 'řadí prvky podle atomové hmotnosti, podobné pod sebe' },
              { icon: 'question', title: 'Volná místa', text: 'když se prvek nehodil, nechal políčko prázdné a předpověděl neznámý prvek' },
              { icon: 'magnifier', title: '1886: germanium', text: 'objevené „ekasilicium“ má předpovězené vlastnosti' },
              { icon: 'atom', title: '1913: Moseley', text: 'skutečným pořadovým číslem je **protonové číslo** $Z$' },
            ] },
            { type: 'compare', columns: [
              { title: 'Předpověď pro „ekasilicium“ (1871)', icon: 'question', tone: 'a', points: ['relativní atomová hmotnost 72', 'hustota 5,5 g/cm^{3}', 'šedý kov'] },
              { title: 'Germanium (objeveno 1886)', icon: 'magnifier', tone: 'good', points: ['relativní atomová hmotnost 72,6', 'hustota 5,35 g/cm^{3}', 'šedobílý polokov'] },
            ] },
            { type: 'p', text: 'Kvůli vlastnostem Mendělejev dokonce prohodil tellur a jod, přestože jod má menší atomovou hmotnost. Moseley později ukázal, že udělal dobře.' },
            { type: 'elements', symbols: ['Te', 'I'], caption: 'Tellur ($A_{r}$ 127,6) stojí před jodem ($A_{r}$ 126,9): rozhoduje protonové číslo 52 a 53' },
            { type: 'callout', variant: 'remember', title: 'Periodický zákon', text: 'Vlastnosti prvků jsou periodickou funkcí jejich **protonového čísla**. Jinými slovy: když prvky seřadíš podle $Z$, podobné vlastnosti se pravidelně opakují.' },
            { type: 'p', text: 'Příčinu už znáš: vlastnosti určují valenční elektrony a jejich uspořádání se po každém vzácném plynu opakuje.' },
            { type: 'check', question: { kind: 'tf', q: 'Moderní periodická tabulka řadí prvky podle rostoucí relativní atomové hmotnosti.', answer: false, explain: 'Řadí je podle protonového čísla $Z$. Proto je tellur ($A_{r}$ 127,6) před jodem ($A_{r}$ 126,9).' } },
          ],
        },
        {
          title: 'Skupiny a periody',
          icon: 'periodic-table',
          blocks: [
            { type: 'compare', columns: [
              { title: '**Perioda**', icon: 'chart', tone: 'a', points: ['vodorovný řádek, je jich sedm', 'číslo periody = počet elektronových vrstev', 'sodík ve 3. periodě má vrstvy K, L, M'] },
              { title: '**Skupina**', icon: 'periodic-table', tone: 'b', points: ['svislý sloupec, podle IUPAC číslované 1–18', 'v českých školách i starší značení: **hlavní skupiny** I.A–VIII.A (skupiny 1, 2 a 13–18) a vedlejší skupiny B', 'římské číslo u hlavních skupin = počet valenčních elektronů'] },
            ] },
            { type: 'diagram', id: 'periodic-mini', props: { highlight: 'groups' }, caption: 'Čísla skupin 1–18 jsou nad sloupci, periody jsou řádky. Barvy ukazují rodiny prvků; klepnutím na název v legendě je zvýrazníš.' },
            { type: 'iconlist', items: [
              { icon: 'explosion', title: '1 (I.A): alkalické kovy', text: 'Li, Na, K, Rb, Cs, Fr · ns^{1}' },
              { icon: 'bone', title: '2 (II.A): kovy alkalických zemin', text: 'Be, Mg, Ca, Sr, Ba, Ra · ns^{2}' },
              { icon: 'volcano', title: '16 (VI.A): chalkogeny', text: 'O, S, Se, Te, Po · ns^{2} np^{4}' },
              { icon: 'salt', title: '17 (VII.A): halogeny', text: 'F, Cl, Br, I, At · ns^{2} np^{5}' },
              { icon: 'bulb', title: '18 (VIII.A): vzácné plyny', text: 'He, Ne, Ar, Kr, Xe, Rn · ns^{2} np^{6} (He 1s^{2})' },
            ] },
            { type: 'callout', variant: 'warning', title: 'Pozor na vodík', text: 'Vodík stojí v 1. skupině, ale alkalický kov to není, je to plyn a nekov. Be a Mg se někdy mezi kovy alkalických zemin nepočítají, podle IUPAC k nim ale patří.' },
            { type: 'example', problem: 'Síra má konfiguraci [Ne] 3s^{2} 3p^{4}. Ve které periodě a skupině leží?', steps: [
              'Nejvyšší $n$ je 3, atom má tři vrstvy -> 3. perioda.',
              'Valenční elektrony: 2 + 4 = 6 -> VI.A, tedy skupina 16.',
            ], answer: 'Síra leží ve 3. periodě a 16. skupině (chalkogeny).' },
            { type: 'game', gameId: 'periodic-find', text: 'Vyzkoušej se ve hře Najdi prvek: co nejrychleji ťukni na zadaný prvek v tabulce.' },
            { type: 'check', question: { kind: 'choice', q: 'Který z prvků je **halogen**?', options: ['brom', 'síra', 'argon', 'draslík'], answer: 0, explain: 'Brom je v 17. skupině spolu s fluorem, chlorem a jodem. Síra je chalkogen, argon vzácný plyn a draslík alkalický kov.' } },
          ],
        },
        {
          title: 'Bloky s, p, d, f',
          icon: 'atom',
          blocks: [
            { type: 'p', text: 'Periodická tabulka je vlastně výstavbový princip rozložený do řádků. Podle toho, do které podslupky přibývá poslední elektron, se dělí na čtyři **bloky**.' },
            { type: 'diagram', id: 'periodic-mini', props: { highlight: 'blocks' }, caption: 'Bloky s, p, d a f' },
            { type: 'table', headers: ['Blok', 'Kde je', 'Šířka', 'Prvky'], rows: [
              ['s', 'skupiny 1 a 2 (+ helium)', '2 sloupce', 'alkalické kovy, kovy alkalických zemin, H, He'],
              ['p', 'skupiny 13–18', '6 sloupců', 'většina nekovů, polokovy, některé kovy (Al, Sn, Pb)'],
              ['d', 'skupiny 3–12', '10 sloupců', '**přechodné kovy**: Fe, Cu, Zn, Ag, Au…'],
              ['f', 'dva řádky pod tabulkou', '14 sloupců', 'lanthanoidy a aktinoidy (vnitřně přechodné prvky)'],
            ] },
            { type: 'callout', variant: 'remember', text: 'Šířka bloků 2, 6, 10 a 14 odpovídá přesně tomu, kolik elektronů pojmou podslupky s, p, d a f. Tabulka a orbitaly do sebe zapadají!' },
            { type: 'p', text: 'Helium patří do bloku s (1s^{2}), ale stojí nad neonem v 18. skupině: má zaplněnou valenční vrstvu a chová se jako vzácný plyn.' },
            { type: 'check', question: { kind: 'choice', q: 'Do kterého bloku patří železo ([Ar] 4s^{2} 3d^{6})?', options: ['d', 's', 'p', 'f'], answer: 0, explain: 'Poslední elektrony železa přibývají do podslupky 3d, proto je v bloku d mezi přechodnými kovy.' } },
          ],
        },
        {
          title: 'Kovy, nekovy a polokovy',
          icon: 'coin',
          blocks: [
            { type: 'p', text: 'Asi čtyři pětiny prvků jsou **kovy**, leží vlevo a uprostřed tabulky. **Nekovy** jsou vpravo nahoře (plus vodík). Mezi nimi vede „schodovitá“ hranice, podél níž leží **polokovy**.' },
            { type: 'diagram', id: 'periodic-mini', props: { highlight: 'metals' }, caption: 'Kovy, polokovy a nekovy. Schodovitá čára odděluje kovy od polokovů a nekovů.' },
            { type: 'compare', columns: [
              { title: 'Kovy', icon: 'coin', tone: 'a', points: ['kovový lesk', 'dobře vedou teplo a elektřinu', 'kujné, tažné', 'při 25 °C pevné, kromě rtuti', 'tvoří **kationty**'] },
              { title: 'Nekovy', icon: 'gas-cloud', tone: 'b', points: ['bez lesku, často barevné', 'většinou nevodí (izolanty)', 'pevné nekovy jsou křehké', 'plyny i pevné látky, brom je kapalina', 'tvoří **anionty**'] },
            ] },
            { type: 'elements', symbols: ['B', 'Si', 'Ge', 'As', 'Sb', 'Te'], caption: 'Polokovy: vlastnosti mají na pomezí kovů a nekovů' },
            { type: 'callout', variant: 'fact', title: 'Křemík v kapse', text: 'Polokov křemík je **polovodič**: elektřinu vede jen za určitých podmínek. Proto z něj vyrábíme čipy do mobilů a počítačů a podle něj se jmenuje kalifornské Silicon Valley.' },
            { type: 'callout', variant: 'mascot', text: 'Gallium taje při 29,8 °C, takže by ti roztálo v dlani. Kov, který se chová jako čokoláda! (Radši to ale nezkoušej, gallium zanechává na kůži šedé skvrny a patří do laboratoře.)' },
            { type: 'check', question: { kind: 'multi', q: 'Které z prvků jsou **polokovy**?', options: ['křemík', 'bor', 'hliník', 'arsen', 'síra'], answers: [0, 1, 3], explain: 'Bor, křemík a arsen leží na schodovité hranici mezi kovy a nekovy. Hliník je kov a síra nekov.' } },
          ],
        },
        {
          title: 'Trendy v tabulce',
          icon: 'chart',
          blocks: [
            { type: 'p', text: 'Poloha prvku prozradí, jak velký je jeho atom a jak snadno ztrácí nebo přitahuje elektrony. Stačí pochopit dva jednoduché důvody:' },
            { type: 'compare', columns: [
              { title: 'V periodě zleva doprava', icon: 'nucleus', tone: 'a', points: ['přibývají protony v jádře', 'elektrony jdou pořád do stejné vrstvy', 'jádro je přitahuje silněji, atom se **zmenšuje**'] },
              { title: 'Ve skupině shora dolů', icon: 'atom', tone: 'b', points: ['přibývají elektronové vrstvy', 'valenční elektrony jsou dál od jádra a stíněné vnitřními vrstvami', 'atom se **zvětšuje**'] },
            ] },
            { type: 'keyterms', items: [
              { term: 'Atomový poloměr', def: 'velikost atomu' },
              { term: 'Ionizační energie', def: 'energie na odtržení elektronu (z lekce o vrstvách)' },
              { term: 'Elektronegativita', def: '(anglicky *electronegativity*) schopnost atomu přitahovat elektrony ve vazbě. Nejvyšší má fluor (3,98), podrobně v úrovni 3.' },
              { term: 'Kovový charakter', def: 'jak snadno atom ztrácí elektrony a chová se jako kov' },
            ] },
            { type: 'diagram', id: 'periodic-mini', props: { highlight: 'trends' }, caption: 'Šipky ukazují, kterým směrem jednotlivé vlastnosti rostou; tmavší políčko znamená vyšší elektronegativitu.' },
            { type: 'table', headers: ['Prvek', 'Li', 'Na', 'K'], rows: [
              ['atomový poloměr (pm)', '152', '186', '227'],
              ['1. ionizační energie (kJ/mol)', '520', '496', '419'],
              ['elektronegativita', '0,98', '0,93', '0,82'],
            ], caption: 'Alkalické kovy shora dolů: atom roste, elektron se odtrhne snáz' },
            { type: 'callout', variant: 'tip', title: 'Směr k fluoru', text: 'Ionizační energie i elektronegativita rostou **směrem k fluoru** (vpravo nahoru). Atomový poloměr a kovový charakter rostou opačně, **směrem k franciu** (vlevo dolů). Vzácné plyny v trendech elektronegativity obvykle vynecháváme.' },
            { type: 'check', question: { kind: 'choice', q: 'Který z atomů má **největší** atomový poloměr?', options: ['K', 'Na', 'Mg', 'Cl'], answer: 0, explain: 'Draslík má nejvíc vrstev (4. perioda) a leží úplně vlevo. Na, Mg a Cl jsou ve 3. periodě a poloměr v ní zleva doprava klesá.' } },
          ],
        },
        {
          title: 'Předpovídáme vlastnosti podle polohy',
          icon: 'idea',
          blocks: [
            { type: 'p', text: 'Z polohy prvku odhadneš jeho vlastnosti, i když jsi o něm nikdy neslyšel. Přesně tak to dělal Mendělejev.' },
            { type: 'elements', symbols: ['K', 'Rb', 'S', 'Se'], caption: 'Rubidium stojí pod draslíkem, selen pod sírou: sousedé ve skupině si jsou podobní' },
            { type: 'example', title: 'Rubidium', problem: 'Rubidium (Rb) leží v 1. skupině a 5. periodě. Co o něm můžeš říct?', steps: [
              '1. skupina -> alkalický kov, 1 valenční elektron (5s^{1}).',
              'Snadno ho odevzdá -> tvoří kation $Rb^+$.',
              '5. perioda, pod draslíkem -> větší atom, nižší ionizační energie, ještě reaktivnější než draslík.',
            ], answer: 'Rb je měkký, velmi reaktivní kov, tvoří $Rb^+$ a s vodou reaguje prudčeji než K.' },
            { type: 'example', title: 'Selen', problem: 'Selen (Se) leží v 16. skupině a 4. periodě. Odhadni jeho vlastnosti.', steps: [
              '16. skupina -> chalkogen, 6 valenčních elektronů: [Ar] 4s^{2} 3d^{10} 4p^{4}.',
              'Do oktetu chybějí 2 elektrony -> tvoří anion $Se^2-$, stejně jako síra $S^2-$.',
              'Stojí pod sírou -> nekov, podobný síře, s o něco větším atomem.',
            ], answer: 'Se je nekov podobný síře, tvoří anion $Se^2-$.' },
            { type: 'callout', variant: 'warning', title: 'Bezpečnost', text: 'Alkalické kovy prudce reagují s vodou a vzniká přitom hořlavý vodík. Uchovávají se pod petrolejem a pokusy s nimi se dělají jen s ochrannými brýlemi, za ochranným štítem a v malém množství. Víc o jejich chemii v úrovni 7.' },
            { type: 'check', question: { kind: 'text', q: 'Který prvek leží ve 3. periodě a 2. skupině? Napiš jeho značku.', accept: ['Mg'], caseSensitive: true, placeholder: 'značka', explain: 'Hořčík $Mg$: tři vrstvy (2, 8, 2) a dva valenční elektrony.' } },
          ],
        },
      ],
      summary: [
        'Periodický zákon: vlastnosti prvků se periodicky opakují v závislosti na protonovém čísle.',
        'Perioda (řádek) udává počet vrstev, skupina (sloupec) u hlavních skupin počet valenčních elektronů.',
        'Skupina 1 jsou alkalické kovy, 2 kovy alkalických zemin, 16 chalkogeny, 17 halogeny a 18 vzácné plyny.',
        'Tabulka se dělí na bloky s, p, d, f podle podslupky, do které přibývá poslední elektron.',
        'Kovy jsou vlevo a uprostřed, nekovy vpravo nahoře, polokovy (B, Si, Ge, As, Sb, Te) na hranici.',
        'Atomový poloměr a kovový charakter rostou doleva dolů, ionizační energie a elektronegativita doprava nahoru.',
      ],
      quiz: [
        { kind: 'match', q: 'Přiřaď skupinu k jejímu názvu.', pairs: [['1. skupina', 'alkalické kovy'], ['2. skupina', 'kovy alkalických zemin'], ['16. skupina', 'chalkogeny'], ['17. skupina', 'halogeny'], ['18. skupina', 'vzácné plyny']], explain: 'Tyto názvy se používají běžně, vyplatí se je umět nazpaměť.' },
        { kind: 'tf', q: 'Atomový poloměr v periodě zleva doprava roste.', answer: false, explain: 'Klesá. Protonů přibývá, elektrony jdou do stejné vrstvy a silnější jádro je přitáhne blíž.' },
        { kind: 'choice', q: 'Který prvek leží ve 4. periodě a 17. skupině?', options: ['brom', 'chlor', 'jod', 'krypton'], answer: 0, explain: 'Halogeny jsou F (2. perioda), Cl (3.), Br (4.) a I (5.). Krypton je ve 4. periodě, ale v 18. skupině.' },
        { kind: 'multi', q: 'Které prvky patří do bloku d?', options: ['Fe', 'Cu', 'Zn', 'Ca', 'Al'], answers: [0, 1, 2], explain: 'Železo, měď a zinek jsou přechodné kovy (skupiny 3–12). Vápník patří do bloku s, hliník do bloku p.' },
        { kind: 'order', q: 'Seřaď prvky podle elektronegativity od nejmenší.', items: ['Na', 'Al', 'S', 'Cl', 'F'], explain: 'Elektronegativita roste směrem k fluoru: Na 0,93, Al 1,61, S 2,58, Cl 3,16, F 3,98.' },
        { kind: 'number', q: 'Prvek má konfiguraci [Ne] 3s^{2} 3p^{5}. Ve které skupině (číslování 1–18) leží?', answer: 17, tolerance: 0, explain: '7 valenčních elektronů v bloku p znamená VII.A, tedy 17. skupinu. Je to chlor.' },
        { kind: 'choice', q: 'Co můžeš předpovědět o cesiu (Cs, 1. skupina, 6. perioda)?', options: ['Je to velmi reaktivní kov, který snadno tvoří kation $Cs^+$.', 'Je to nereaktivní plyn.', 'Je to nekov, který tvoří anion $Cs^-$.', 'Je to polokov používaný v čipech.'], answer: 0, explain: 'Cesium je alkalický kov s jedním valenčním elektronem daleko od jádra. Má velmi nízkou ionizační energii a patří k nejreaktivnějším kovům.' },
        { kind: 'tf', q: 'Křemík patří mezi polokovy a používá se jako polovodič v čipech.', answer: true, explain: 'Křemík leží na hranici kovů a nekovů a jeho polovodivost je základem elektroniky.' },
      ],
    },
  },

  boss: [
    { kind: 'number', q: 'Kolik elektronů a neutronů **dohromady** má ion $^{81}_{35}Br^-$?', answer: 82, tolerance: 0, explain: 'Elektrony: 35 + 1 = 36. Neutrony: 81 − 35 = 46. Dohromady 36 + 46 = 82.' },
    { kind: 'number', q: 'Přírodní chlor má $A_{r}$ = 35,5 a skládá se jen z izotopů $^{35}Cl$ a $^{37}Cl$. Kolik procent tvoří izotop $^{35}Cl$? (Počítej s nukleonovými čísly.)', answer: 75, tolerance: 0.5, unit: '%', explain: 'Označ podíl $^{35}Cl$ jako x: 35x + 37(1 − x) = 35,5, tedy 37 − 2x = 35,5 a x = 0,75, čili 75 %.' },
    { kind: 'choice', q: 'Která částice má 16 protonů, 16 neutronů a 18 elektronů?', options: ['$^{32}_{16}S^2-$', '$^{32}_{16}S$', '$^{34}_{16}S^2-$', '$^{34}_{18}Ar$'], answer: 0, explain: '16 protonů je síra, 16 + 16 = 32 nukleonů a 18 elektronů znamená o dva víc než protonů, tedy náboj 2−.' },
    { kind: 'tf', q: 'Ion $Fe^{3+}$ má elektronovou konfiguraci [Ar] 3d^{5}.', answer: true, explain: 'Fe je [Ar] 4s^{2} 3d^{6}. Kation ztrácí nejdřív oba elektrony 4s a pak jeden z 3d, zbude [Ar] 3d^{5}.' },
    { kind: 'choice', q: 'Který prvek má konfiguraci [Ar] 4s^{1} 3d^{10}?', options: ['Cu', 'K', 'Zn', 'Ga'], answer: 0, explain: 'Je to 18 + 1 + 10 = 29 elektronů, tedy měď, známá výjimka z výstavbového principu.' },
    { kind: 'multi', q: 'Které částice mají stejný počet elektronů jako atom argonu?', options: ['$S^2-$', '$K^+$', '$Ca^{2+}$', '$Na^+$', '$F^-$'], answers: [0, 1, 2], explain: 'Argon má 18 elektronů. $S^2-$ (16 + 2), $K^+$ (19 − 1) a $Ca^{2+}$ (20 − 2) mají také 18. $Na^+$ a $F^-$ mají 10.' },
    { kind: 'order', q: 'Seřaď atomy podle atomového poloměru od nejmenšího.', items: ['F', 'Cl', 'Na', 'K'], explain: 'F je nahoře vpravo, Cl pod ním má o vrstvu víc. Na je ve stejné periodě jako Cl, ale úplně vlevo, takže je větší. K má o vrstvu víc než Na.' },
    { kind: 'number', q: 'Kolik procent původního množství uhlíku-14 zbude ve vzorku po 22 920 letech? (Poločas přeměny je 5 730 let.)', answer: 6.25, tolerance: 0.1, unit: '%', explain: '22 920 : 5 730 = 4 poločasy. Zbude (1/2)^{4} = 1/16, tedy 6,25 %.' },
    { kind: 'match', q: 'Přiřaď elektronovou konfiguraci k prvku.', pairs: [['[He] 2s^{2} 2p^{4}', 'O'], ['[Ne] 3s^{2}', 'Mg'], ['[Ne] 3s^{2} 3p^{5}', 'Cl'], ['[Ar] 4s^{1}', 'K'], ['[Ar] 4s^{1} 3d^{5}', 'Cr']], explain: 'Sečti elektrony: O 8, Mg 12, Cl 17, K 19, Cr 24. Chrom je výjimka s napůl zaplněnou podslupkou 3d.' },
    { kind: 'choice', q: 'Uran-238 ($^{238}_{92}U$) vyzáří částici α. Jaké jádro vznikne?', options: ['$^{234}_{90}Th$', '$^{238}_{93}Np$', '$^{234}_{92}U$', '$^{236}_{90}Th$'], answer: 0, explain: 'Částice α je jádro helia $^{4}_{2}He$: nukleonové číslo klesne o 4 (238 -> 234) a protonové o 2 (92 -> 90), a $Z = 90$ je thorium.' },
    { kind: 'text', q: 'Kdo jsem? Mám tři elektronové vrstvy a čtyři valenční elektrony, jsem polokov a vyrábějí se ze mě čipy. Napiš mou značku.', accept: ['Si'], caseSensitive: true, placeholder: 'značka', explain: 'Tři vrstvy = 3. perioda, 4 valenční elektrony = 14. skupina. To je křemík: 2, 8, 4.' },
    { kind: 'tf', q: 'Atom chloru má menší první ionizační energii než atom sodíku.', answer: false, explain: 'Je to naopak. Ve 3. periodě ionizační energie zleva doprava roste, chlor drží své elektrony mnohem pevněji než sodík.' },
  ],
}

export default level
