import type { LevelContent } from '../../../core/types'

const level: LevelContent = {
  lessons: {
    // ───────────────────────────────────────────────────────────── l2-1
    'l2-1': {
      id: 'l2-1',
      title: 'Atomy, molekuly a ionty',
      goals: [
        'Rozlišit atom, molekulu a ion a poznat, jestli je ion kation, nebo anion',
        'Podle vzorce rozhodnout, jestli jde o chemický prvek, nebo sloučeninu',
        'Přečíst chemickou značku a jednoduchý vzorec a spočítat atomy podle indexu a koeficientu',
        'Popsat, jak se představa o atomech vyvíjela od Démokrita po Daltona',
      ],
      hook: 'Rozkrojíš kostku cukru napůl, pak zase napůl a pak znovu… Jak dlouho to jde? Řecký filozof Démokritos si před 2 400 lety myslel, že jednou narazíš na kousek, který už rozdělit nejde. A kupodivu měl skoro pravdu!',
      sections: [
        {
          title: 'Všechno je z částic',
          blocks: [
            { type: 'p', text: 'V úrovni 1 jsi poznal látky zvenku: jejich barvu, hustotu, teplotu tání. Teď se podíváme dovnitř. Každá látka se skládá z nepředstavitelně malých **částic**, které jsou v neustálém pohybu.' },
            { type: 'diagram', id: 'states', caption: 'Stejné částice, jiné uspořádání: pevná látka, kapalina a plyn' },
            { type: 'p', text: 'Tomuto pohledu se říká **částicový model látek**. Vysvětluje, proč se cukr ve vodě rozpustí, proč vůně parfému dojde až k tobě nebo proč se plyn dá stlačit: mezi částicemi je prostor a částice se hýbou.' },
            { type: 'p', text: 'Na myšlenku, že hmota není dělitelná donekonečna, přišel už **Démokritos** (5. století př. n. l.). Nejmenší částečky nazval *atomos*, což řecky znamená „nedělitelný“. Byla to ale jen úvaha, bez jediného pokusu.' },
            { type: 'p', text: 'Vědecky atomy „vzkřísil“ až anglický chemik **John Dalton** v roce 1808. Jeho **atomová teorie** říkala:' },
            { type: 'list', items: [
              'Každá látka se skládá z atomů, které nelze rozdělit ani zničit.',
              'Atomy jednoho prvku jsou stejné, atomy různých prvků se liší hmotností.',
              'Sloučeniny vznikají spojením atomů různých prvků v určitém stálém poměru.',
              'Při chemické reakci se atomy jen přeskupují, žádný nevzniká ani nezaniká.',
            ] },
            { type: 'callout', variant: 'fact', title: 'Jak malý je atom?', text: 'Průměr atomu je zhruba 0,1 nm, tedy desetimiliontina milimetru. Kdybys vedle sebe do řady položil deset milionů atomů, měřila by ta řada asi 1 mm.' },
            { type: 'callout', variant: 'mascot', text: 'Dalton se ve dvou bodech trochu spletl: atom rozdělit jde a atomy jednoho prvku nemusí být úplně stejné. Proč, zjistíš v dalších dvou lekcích. I tak mu patří velký potlesk!' },
            { type: 'check', question: { kind: 'choice', q: 'Kdo jako první postavil představu o atomech na výsledcích pokusů a měření?', options: ['John Dalton', 'Démokritos', 'Aristotelés', 'Isaac Newton'], answer: 0, explain: 'Démokritos atomy jen vymyslel úvahou. Dalton v roce 1808 vytvořil atomovou teorii opřenou o měření hmotností látek při reakcích.' } },
          ],
        },
        {
          title: 'Atom, molekula, ion',
          blocks: [
            { type: 'p', text: 'Částice, ze kterých jsou látky složené, mají tři základní podoby. Nauč se je rozlišovat, budeš je potřebovat v celém kurzu.' },
            { type: 'keyterms', items: [
              { term: '**Atom**', def: 'nejmenší částice chemického prvku. Navenek je **elektricky neutrální** (nemá náboj).' },
              { term: '**Molekula**', def: 'částice složená ze dvou nebo více atomů, které jsou navzájem pevně spojené (chemicky vázané). Je také neutrální.' },
              { term: '**Ion**', def: 'částice s **elektrickým nábojem**. Vzniká z atomu nebo molekuly, která získala, nebo ztratila elektrony.' },
            ] },
            { type: 'p', text: '**Elektrony** jsou drobné záporně nabité částice v obalu atomu, podrobně je poznáš v příští lekci. Když atom elektron **ztratí**, převáží kladný náboj a vznikne **kation**. Když elektron **přijme**, vznikne záporný **anion**.' },
            { type: 'table', headers: ['Částice', 'Náboj', 'Příklady'], rows: [
              ['atom', 'žádný', '$He$, $Ne$, $Fe$, $Na$'],
              ['molekula', 'žádný', '$H2$, $O2$, $H2O$, $CO2$'],
              ['kation', 'kladný', '$Na^+$, $Ca^{2+}$, $Fe^{3+}$'],
              ['anion', 'záporný', '$Cl^-$, $O^2-$, $S^2-$'],
            ], caption: 'Náboj iontu se píše vpravo nahoru: číslo, pak znaménko' },
            { type: 'callout', variant: 'tip', title: 'Jak si to zapamatovat', text: '**K**ation je **k**ladný, **a**nion je záporný. Stačí si pamatovat to „ká – ká“.' },
            { type: 'p', text: 'Zápis $Ca^{2+}$ znamená, že atom vápníku ztratil dva elektrony. Zápis $O^2-$ znamená, že atom kyslíku dva elektrony získal. Jednička se u náboje nepíše: $Na^+$, ne $Na^{1+}$.' },
            { type: 'check', question: { kind: 'multi', q: 'Které z částic jsou **anionty**?', options: ['$Cl^-$', '$Mg^{2+}$', '$S^2-$', '$CO2$', '$F^-$'], answers: [0, 2, 4], explain: 'Anionty mají záporný náboj: $Cl^-$, $S^2-$ a $F^-$. $Mg^{2+}$ je kation a $CO2$ je neutrální molekula.' } },
          ],
        },
        {
          title: 'Prvek a sloučenina pod lupou',
          blocks: [
            { type: 'p', text: 'V úrovni 1 jsi chemicky čisté látky dělil na prvky a sloučeniny. Teď umíš říct, v čem se liší na úrovni částic.' },
            { type: 'keyterms', items: [
              { term: '**Chemický prvek**', def: 'látka složená z atomů **jednoho druhu**. Přesnou definici pomocí protonového čísla přidáme v lekci o izotopech.' },
              { term: '**Chemická sloučenina**', def: 'látka složená z atomů **alespoň dvou různých prvků**, které jsou chemicky vázané ve stálém poměru.' },
            ] },
            { type: 'p', text: 'Prvek může být tvořen samostatnými atomy (helium $He$, železo $Fe$), ale i molekulami. Kyslík ve vzduchu tvoří dvouatomové molekuly $O2$, ozon molekuly $O3$. Obě látky jsou pořád prvek, protože obsahují jen atomy kyslíku.' },
            { type: 'table', headers: ['Látka', 'Vzorec', 'Z jakých částic', 'Prvek, nebo sloučenina?'], rows: [
              ['helium', '$He$', 'atomy', 'prvek'],
              ['kyslík', '$O2$', 'molekuly', 'prvek'],
              ['ozon', '$O3$', 'molekuly', 'prvek'],
              ['voda', '$H2O$', 'molekuly', 'sloučenina'],
              ['oxid uhličitý', '$CO2$', 'molekuly', 'sloučenina'],
              ['chlorid sodný (kuchyňská sůl)', '$NaCl$', 'ionty $Na^+$ a $Cl^-$', 'sloučenina'],
            ], caption: 'Jak se sloučeniny jmenují a proč, se naučíš v úrovni 3' },
            { type: 'callout', variant: 'warning', title: 'Častá chyba', text: 'Molekula **není** totéž co sloučenina. Molekula $H2$ je molekula prvku vodíku. O tom, jestli jde o sloučeninu, rozhoduje, kolik **různých** druhů atomů v látce je.' },
            { type: 'p', text: 'A kde jsou směsi? Ve směsi jsou částice různých látek jen **promíchané**, nejsou navzájem vázané. Vzduch obsahuje molekuly $N2$, $O2$, $CO2$ i atomy $Ar$, ale každá z těch látek si zachovává svoje vlastnosti.' },
            { type: 'check', question: { kind: 'tf', q: 'Každá molekula je molekulou nějaké sloučeniny.', answer: false, explain: 'Molekuly tvoří i prvky, například $H2$, $O2$, $N2$ nebo $O3$. Sloučenina vyžaduje atomy aspoň dvou různých prvků.' } },
          ],
        },
        {
          title: 'Značky a vzorce: index a koeficient',
          blocks: [
            { type: 'p', text: 'Každý prvek má svou **chemickou značku**: jedno nebo dvě písmena, většinou z latinského názvu. Systém zavedl švédský chemik **Jöns Jacob Berzelius** kolem roku 1813 a používáme ho dodnes.' },
            { type: 'elements', symbols: ['Na', 'K', 'Fe', 'Cu', 'Ag', 'Au', 'Pb', 'Hg'], caption: 'natrium, kalium, ferrum, cuprum, argentum, aurum, plumbum, hydrargyrum' },
            { type: 'callout', variant: 'warning', title: 'Na velikosti písmen záleží', text: 'První písmeno je vždy velké, druhé malé. $Co$ je kobalt, kovový prvek. $CO$ je oxid uhelnatý, jedovatý plyn z molekul uhlíku a kyslíku.' },
            { type: 'p', text: '**Chemický vzorec** ukazuje, z jakých atomů se částice skládá. **Index** (malé číslo vpravo dole) říká, kolik atomů daného prvku je v **jedné** částici. Jednička se nepíše. **Koeficient** (velké číslo před vzorcem) říká, kolik je **částic**.' },
            { type: 'table', headers: ['Zápis', 'Co znamená', 'Atomů celkem'], rows: [
              ['$2H$', 'dva samostatné atomy vodíku', '2 H'],
              ['$H2$', 'jedna molekula vodíku ze dvou atomů', '2 H'],
              ['$2H2$', 'dvě molekuly vodíku', '4 H'],
              ['$3H2O$', 'tři molekuly vody', '6 H a 3 O'],
            ] },
            { type: 'example', problem: 'Kolik atomů kterého prvku obsahuje zápis $2CO2$?', steps: [
              'Koeficient 2 říká, že jde o dvě molekuly $CO2$.',
              'V jedné molekule je 1 atom C (index 1 se nepíše) a 2 atomy O.',
              'Vynásob koeficientem: C: 2 · 1 = 2, O: 2 · 2 = 4.',
            ], answer: '2 atomy uhlíku a 4 atomy kyslíku' },
            { type: 'p', text: 'U iontových látek vzorec udává jen **poměr** iontů. Kuchyňská sůl nemá molekuly; ve vzorci $NaCl$ čteme, že na každý kation $Na^+$ připadá jeden anion $Cl^-$.' },
            { type: 'game', gameId: 'element-memory', text: 'Značky se nejlépe učí hrou. Zkus Pexeso prvků a spoj značky s českými názvy.' },
            { type: 'check', question: { kind: 'number', q: 'Kolik atomů kyslíku je celkem v zápisu $3CO2$?', answer: 6, tolerance: 0, explain: 'Tři molekuly $CO2$, v každé 2 atomy kyslíku: 3 · 2 = 6.' } },
            { type: 'check', question: { kind: 'text', q: 'Napiš chemickou značku železa.', accept: ['Fe'], caseSensitive: true, placeholder: 'značka', explain: 'Železo má značku $Fe$ z latinského *ferrum*. Pozor na velké a malé písmeno.' } },
          ],
        },
      ],
      summary: [
        'Látky se skládají z částic, které jsou v neustálém pohybu.',
        'Atom je nejmenší částice prvku a je elektricky neutrální; molekula je skupina vázaných atomů.',
        'Ion je nabitá částice: kation je kladný (atom ztratil elektrony), anion záporný (elektrony získal).',
        'Prvek obsahuje atomy jednoho druhu, sloučenina atomy aspoň dvou různých prvků. Molekulu mají i prvky, například $O2$.',
        'Index udává počet atomů v jedné částici, koeficient počet částic.',
        'Myšlenka atomů pochází od Démokrita, vědeckou atomovou teorii vytvořil Dalton (1808), značky prvků zavedl Berzelius.',
      ],
      quiz: [
        { kind: 'choice', q: 'Která z částic je **kation**?', options: ['$K^+$', '$Br^-$', '$N2$', '$Ar$'], answer: 0, explain: 'Kation je kladně nabitý: $K^+$ vznikl z atomu draslíku, který ztratil jeden elektron.' },
        { kind: 'tf', q: 'Kyslík $O2$ je sloučenina, protože jeho molekula má dva atomy.', answer: false, explain: 'Oba atomy jsou atomy kyslíku, jde tedy o prvek. Sloučenina potřebuje aspoň dva různé prvky.' },
        { kind: 'tf', q: 'Koeficient udává počet částic, index počet atomů daného prvku v jedné částici.', answer: true, explain: 'Přesně tak: v $3H2O$ je koeficient 3 (tři molekuly) a index 2 (dva vodíky v každé molekule).' },
        { kind: 'number', q: 'Kolik atomů vodíku je v zápisu $4H2O$?', answer: 8, tolerance: 0, explain: 'Čtyři molekuly vody, v každé 2 atomy vodíku: 4 · 2 = 8.' },
        { kind: 'multi', q: 'Které látky jsou **sloučeniny**?', options: ['$H2O$', '$N2$', '$CO2$', '$O3$', '$NaCl$'], answers: [0, 2, 4], explain: '$H2O$, $CO2$ a $NaCl$ obsahují atomy dvou různých prvků. $N2$ a $O3$ jsou prvky tvořené molekulami.' },
        { kind: 'match', q: 'Přiřaď ke značce název prvku.', pairs: [['Na', 'sodík'], ['K', 'draslík'], ['Cu', 'měď'], ['Ag', 'stříbro'], ['Pb', 'olovo']], explain: 'Značky pocházejí z latiny: natrium, kalium, cuprum, argentum, plumbum.' },
        { kind: 'text', q: 'Napiš chemickou značku zlata.', accept: ['Au'], caseSensitive: true, placeholder: 'značka', explain: 'Zlato je $Au$ z latinského *aurum*.' },
        { kind: 'order', q: 'Seřaď milníky od nejstaršího.', items: ['Démokritos: hmota se skládá z nedělitelných atomů', 'Dalton: atomová teorie opřená o měření', 'Berzelius: písmenné značky prvků'], explain: 'Démokritos žil v 5. století př. n. l., Dalton publikoval teorii v roce 1808 a Berzelius navrhl značky kolem roku 1813.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l2-2
    'l2-2': {
      id: 'l2-2',
      title: 'Stavba atomu: jádro a obal',
      goals: [
        'Popsat proton, neutron a elektron: kde jsou, jaký mají náboj a hmotnost',
        'Vysvětlit, jak malé je jádro ve srovnání s celým atomem',
        'Seřadit modely atomu od Thomsona po kvantový a říct, co který přinesl',
        'Zdůvodnit, proč je atom elektricky neutrální',
      ],
      hook: 'Kdyby se atom zvětšil na velikost fotbalového stadionu, jádro by uprostřed hřiště bylo velké asi jako špendlíková hlavička. A přesto v něm je skoro celá hmotnost. Takže z čeho jsi vlastně hlavně ty? Z prázdna!',
      sections: [
        {
          title: 'Tři částice uvnitř atomu',
          blocks: [
            { type: 'p', text: 'Dalton si atom představoval jako nedělitelnou kuličku. Dnes víme, že má vnitřní stavbu. Uprostřed je nepatrné **atomové jádro**, kolem něj **elektronový obal**.' },
            { type: 'keyterms', items: [
              { term: '**Proton** $p^+$', def: 'částice v jádře s kladným nábojem.' },
              { term: '**Neutron** $n^0$', def: 'částice v jádře bez náboje, hmotností skoro stejná jako proton.' },
              { term: '**Elektron** $e^-$', def: 'lehoučká záporně nabitá částice v elektronovém obalu.' },
              { term: '**Nukleony**', def: 'společný název pro protony a neutrony (z latinského *nucleus*, jádro).' },
            ] },
            { type: 'table', headers: ['Částice', 'Kde je', 'Náboj', 'Hmotnost', 'Relativně'], rows: [
              ['proton $p^+$', 'jádro', '+1', '1,673·10^{−27} kg', '≈ 1'],
              ['neutron $n^0$', 'jádro', '0', '1,675·10^{−27} kg', '≈ 1'],
              ['elektron $e^-$', 'obal', '−1', '9,109·10^{−31} kg', '≈ 1/1836'],
            ], caption: 'Náboj je udán v násobcích elementárního náboje 1,602·10^{−19} C' },
            { type: 'diagram', id: 'bohr', props: { z: 3 }, caption: 'Atom lithia: 3 protony a 4 neutrony v jádře, 3 elektrony v obalu' },
            { type: 'callout', variant: 'fact', title: 'Elektron je lehká váha', text: 'Proton je asi 1836krát těžší než elektron. Kdyby elektron vážil jako kočka (4 kg), proton by vážil přes 7 tun, jako pořádný náklaďák.' },
            { type: 'check', question: { kind: 'choice', q: 'Která částice atomu **nemá elektrický náboj**?', options: ['neutron', 'proton', 'elektron', 'jádro atomu'], answer: 0, explain: 'Neutron je neutrální, odtud i jeho název. Jádro jako celek je kladné, protože obsahuje protony.' } },
          ],
        },
        {
          title: 'Proč je atom neutrální',
          blocks: [
            { type: 'p', text: 'Proton a elektron mají náboj stejně velký, jen opačného znaménka. Atom má **stejný počet protonů a elektronů**, a proto se náboje přesně vyruší.' },
            { type: 'formula', text: 'počet $p^+$ = počet $e^-$', caption: 'platí pro každý neutrální atom' },
            { type: 'p', text: 'Počet protonů je pro každý prvek jiný a je to jeho „poznávací znamení“: vodík má 1 proton, uhlík 6, kyslík 8. O tom podrobně v příští lekci.' },
            { type: 'p', text: 'Když atom elektrony získá, nebo ztratí, protonů zůstane stejně. Rovnováha se poruší a vznikne **ion**, jak už znáš z minulé lekce.' },
            { type: 'example', problem: 'Atom sodíku má 11 protonů. Kolik má elektronů? Co vznikne, když jeden elektron ztratí?', steps: [
              'Neutrální atom: počet elektronů = počet protonů = 11.',
              'Po ztrátě jednoho elektronu: 11 protonů (+11) a 10 elektronů (−10).',
              'Celkový náboj: +11 − 10 = +1.',
            ], answer: 'Neutrální atom má 11 elektronů, po ztrátě jednoho vznikne kation $Na^+$.' },
            { type: 'callout', variant: 'remember', text: 'Při vzniku iontu se mění **jen počet elektronů**. Počet protonů v jádře chemickou reakcí změnit nejde.' },
            { type: 'check', question: { kind: 'number', q: 'Neutrální atom chloru má 17 protonů. Kolik má elektronů?', answer: 17, tolerance: 0, explain: 'V neutrálním atomu je elektronů stejně jako protonů, tedy 17.' } },
          ],
        },
        {
          title: 'Jádro je nepatrné, atom je hlavně prázdno',
          blocks: [
            { type: 'p', text: 'Průměr atomu je řádově 10^{−10} m. Průměr jádra je jen asi 10^{−15} m. ==Jádro je tedy zhruba stotisíckrát menší než celý atom.==' },
            { type: 'callout', variant: 'fact', title: 'Atom velký jako stadion', text: 'Zvětši atom na velikost fotbalového stadionu. Jádro by pak bylo uprostřed hřiště velké jako špendlíková hlavička a elektrony by se pohybovaly až někde nad tribunami. Všechno mezi tím je prázdný prostor.' },
            { type: 'p', text: 'Přitom v jádře je víc než 99,9 % hmotnosti atomu. Jaderná hmota je proto neuvěřitelně hustá: čajová lžička by vážila asi miliardu tun.' },
            { type: 'example', problem: 'Jádro nějakého atomu zvětšíme na kuličku o průměru 1 cm. Jak velký by byl celý atom, je-li asi 100 000× větší než jádro?', steps: [
              'Průměr atomu = 100 000 · 1 cm = 100 000 cm.',
              '100 000 cm = 1 000 m.',
            ], answer: 'Atom by měl průměr asi 1 km, tedy jako malá vesnice kolem jedné kuličky.' },
            { type: 'callout', variant: 'mascot', text: 'Když je atom skoro prázdný, proč nepropadneš židlí? Elektronové obaly tvých atomů a atomů židle se navzájem silně odpuzují. Sedíš vlastně na elektrickém polštáři!' },
            { type: 'check', question: { kind: 'number', q: 'Zvětšíme atom na průměr 100 m. Jaký průměr by mělo jádro, je-li asi 100 000× menší? Odpověz v milimetrech.', answer: 1, tolerance: 0, unit: 'mm', explain: '100 m = 100 000 mm. Když to vydělíš 100 000, vyjde 1 mm, zhruba špendlíková hlavička.' } },
          ],
        },
        {
          title: 'Jak jsme se to dozvěděli: modely atomu',
          blocks: [
            { type: 'p', text: 'Do atomu nikdo nenahlédl přímo. Vědci si vytvářeli **modely**, zjednodušené představy, a pokusy je ověřovali. Když model s pokusem nesouhlasil, musel se změnit.' },
            { type: 'list', ordered: true, items: [
              '**Thomson (1897, 1904):** objevil elektron. Atom si představoval jako kladnou hmotu, v níž jsou elektrony rozptýlené jako rozinky v pudinku, odtud **pudinkový model**.',
              '**Rutherford (1911):** ostřeloval tenoučkou zlatou fólii kladnými částicemi alfa (co to je, uvidíš v příští lekci). Většina prolétla, několik se odchýlilo a vzácně se některá odrazila zpět. Závěr: v atomu je malé, těžké, kladně nabité **jádro** a kolem něj obíhají elektrony (**planetární model**).',
              '**Bohr (1913):** elektrony obíhají jen po určitých drahách s přesně danou energií, ve **vrstvách**. Tento model použijeme v lekci o elektronových vrstvách.',
              '**Kvantový model (od roku 1926, Schrödinger a další):** elektron nemá přesnou dráhu. Víme jen, kde se s jakou pravděpodobností vyskytuje, v **orbitalu**. Ten poznáš v lekci o orbitalech.',
            ] },
            { type: 'callout', variant: 'fact', title: 'Granát a hedvábný papír', text: 'Rutherford popsal odraz částic alfa takto: „Bylo to, jako byste vystřelili dělostřelecký granát na hedvábný papír a on se odrazil zpátky a zasáhl vás.“ Vysvětlit to šlo jen malým hustým jádrem.' },
            { type: 'p', text: 'Proton Rutherford prokázal v roce 1919. Neutron objevil až v roce 1932 James **Chadwick**, protože částice bez náboje se hledá mnohem hůř.' },
            { type: 'table', headers: ['Model', 'Co přinesl', 'Co nevysvětlil'], rows: [
              ['pudinkový (Thomson)', 'atom obsahuje elektrony', 'odrazy částic alfa od fólie'],
              ['planetární (Rutherford)', 'malé kladné jádro', 'proč elektron nespadne do jádra'],
              ['Bohrův', 'vrstvy s danou energií', 'atomy s více elektrony'],
              ['kvantový', 'orbitaly, pravděpodobnost', 'dnes platný model'],
            ] },
            { type: 'diagram', id: 'bohr', props: { z: 6 }, caption: 'Bohrův model atomu uhlíku: elektrony ve dvou vrstvách' },
            { type: 'check', question: { kind: 'order', q: 'Seřaď modely atomu od nejstaršího po nejnovější.', items: ['pudinkový model (Thomson)', 'planetární model s jádrem (Rutherford)', 'Bohrův model s vrstvami', 'kvantový model s orbitaly'], explain: 'Thomson 1904, Rutherford 1911, Bohr 1913 a kvantový model od roku 1926. Každý opravoval slabinu předchozího.' } },
          ],
        },
      ],
      summary: [
        'Atom tvoří jádro (protony a neutrony) a elektronový obal (elektrony).',
        'Proton má náboj +1, neutron 0, elektron −1; proton a neutron jsou asi 1836krát těžší než elektron.',
        'Neutrální atom má stejně protonů jako elektronů. Ion vzniká jen změnou počtu elektronů.',
        'Jádro je asi 100 000× menší než atom, ale nese přes 99,9 % jeho hmotnosti.',
        'Modely atomu se vyvíjely: Thomson (pudink) -> Rutherford (jádro) -> Bohr (vrstvy) -> kvantový model (orbitaly).',
      ],
      quiz: [
        { kind: 'choice', q: 'Kde je soustředěna téměř celá hmotnost atomu?', options: ['v jádře', 'v elektronovém obalu', 'rovnoměrně v celém objemu atomu', 'v elektronech'], answer: 0, explain: 'Protony a neutrony v jádře jsou asi 1836krát těžší než elektrony, takže jádro nese přes 99,9 % hmotnosti.' },
        { kind: 'tf', q: 'Elektron má přibližně stejnou hmotnost jako proton.', answer: false, explain: 'Elektron je asi 1836krát lehčí než proton. Stejnou hmotnost mají přibližně proton a neutron.' },
        { kind: 'text', q: 'Jak se společným názvem označují protony a neutrony?', accept: ['nukleony', 'nukleon'], placeholder: 'jedno slovo', explain: 'Protony a neutrony tvoří jádro (*nucleus*), proto se jim říká nukleony.' },
        { kind: 'number', q: 'Atom má v jádře 26 protonů a 30 neutronů. Kolik má elektronů, je-li neutrální?', answer: 26, tolerance: 0, explain: 'Počet elektronů v neutrálním atomu se rovná počtu protonů. Neutrony na to vliv nemají.' },
        { kind: 'match', q: 'Přiřaď vědce k jeho přínosu.', pairs: [['Thomson', 'objev elektronu, pudinkový model'], ['Rutherford', 'jádro atomu (pokus se zlatou fólií)'], ['Bohr', 'elektrony ve vrstvách s danou energií'], ['Chadwick', 'objev neutronu']], explain: 'Thomson 1897, Rutherford 1911, Bohr 1913, Chadwick 1932.' },
        { kind: 'multi', q: 'Co pozoroval Rutherford při ostřelování zlaté fólie částicemi alfa?', options: ['Většina částic prolétla fólií bez odchýlení.', 'Některé částice se odchýlily od původního směru.', 'Výjimečně se částice odrazila zpět.', 'Všechny částice se od fólie odrazily.', 'Fólie se rozpadla na elektrony.'], answers: [0, 1, 2], explain: 'Většina prolétla, protože atom je hlavně prázdný. Odchýlení a vzácné odrazy způsobilo malé kladné jádro.' },
        { kind: 'tf', q: 'Částice s 8 protony a 10 elektrony je elektricky neutrální atom.', answer: false, explain: 'Náboj je +8 − 10 = −2. Jde o anion $O^2-$, tedy ion kyslíku.' },
        { kind: 'order', q: 'Seřaď částice podle hmotnosti od nejlehčí.', items: ['elektron', 'proton', 'neutron'], explain: 'Elektron je nejlehčí (9,1·10^{−31} kg), proton má 1,673·10^{−27} kg a neutron je o chlup těžší, 1,675·10^{−27} kg.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l2-3
    'l2-3': {
      id: 'l2-3',
      title: 'Protonové číslo, nukleonové číslo a izotopy',
      goals: [
        'Z protonového a nukleonového čísla spočítat protony, neutrony a elektrony v atomu i v iontu',
        'Vysvětlit, co jsou izotopy, a přečíst zápis nuklidu $^{14}_{6}C$',
        'Spočítat relativní atomovou hmotnost jako vážený průměr izotopů',
        'Popsat záření α, β a γ, poločas přeměny a využití radioaktivity',
      ],
      hook: 'Uhlík v tuhě tvé tužky a uhlík v diamantu mají stejný počet protonů. Ale víš, že se i atomy uhlíku mezi sebou liší hmotností? A že díky tomu umíme určit, jak stará je egyptská mumie?',
      sections: [
        {
          title: 'Dvě čísla, která o atomu řeknou všechno',
          blocks: [
            { type: 'p', text: '**Protonové číslo** $Z$ udává počet protonů v jádře. Právě ono určuje, o jaký prvek jde. Každý atom se $Z = 6$ je uhlík, každý atom se $Z = 8$ je kyslík.' },
            { type: 'p', text: '**Nukleonové číslo** $A$ udává počet všech nukleonů, tedy protonů a neutronů dohromady. Počet neutronů $N$ (neutronové číslo) pak snadno dopočítáš.' },
            { type: 'formula', text: '$A = Z + N$, tedy $N = A − Z$', caption: 'nukleonové číslo = protony + neutrony' },
            { type: 'p', text: 'Obě čísla se píšou ke značce prvku: nukleonové nahoru, protonové dolů. Takovému zápisu konkrétního druhu atomu se říká **nuklid**.' },
            { type: 'formula', text: '$^{23}_{11}Na$', caption: 'A = 23 nahoře, Z = 11 dole: sodík s 11 protony a 12 neutrony' },
            { type: 'callout', variant: 'remember', title: 'Teď už přesně', text: '**Chemický prvek** je látka složená z atomů se stejným protonovým číslem. Změníš-li počet protonů, změníš prvek.' },
            { type: 'example', problem: 'Kolik protonů, neutronů a elektronů má atom $^{23}_{11}Na$?', steps: [
              'Protony: $Z = 11$.',
              'Neutrony: $N = A − Z = 23 − 11 = 12$.',
              'Elektrony: atom je neutrální, takže počet elektronů = $Z = 11$.',
            ], answer: '11 protonů, 12 neutronů, 11 elektronů' },
            { type: 'check', question: { kind: 'number', q: 'Kolik neutronů má atom $^{35}_{17}Cl$?', answer: 18, tolerance: 0, explain: '$N = A − Z = 35 − 17 = 18$.' } },
          ],
        },
        {
          title: 'Izotopy: stejný prvek, jiná hmotnost',
          blocks: [
            { type: 'p', text: '**Izotopy** jsou atomy téhož prvku (stejné $Z$), které se liší počtem neutronů, a tedy i nukleonovým číslem $A$. Chemicky se chovají skoro stejně, protože mají stejně elektronů.' },
            { type: 'p', text: 'Jen izotopy vodíku mají vlastní jména:' },
            { type: 'table', headers: ['Izotop', 'Zápis', 'Protony', 'Neutrony', 'Výskyt'], rows: [
              ['protium', '$^{1}_{1}H$', '1', '0', '99,98 %'],
              ['deuterium (D)', '$^{2}_{1}H$', '1', '1', '0,02 %'],
              ['tritium (T)', '$^{3}_{1}H$', '1', '2', 'stopy, radioaktivní'],
            ] },
            { type: 'p', text: 'Ostatní izotopy pojmenujeme podle nukleonového čísla: uhlík-12 $^{12}_{6}C$ (98,9 %), uhlík-13 $^{13}_{6}C$ (1,1 %) a radioaktivní uhlík-14 $^{14}_{6}C$, kterého je jen nepatrná stopa.' },
            { type: 'callout', variant: 'fact', title: 'Těžká voda', text: 'Voda z deuteria, $D2O$, se jmenuje těžká voda. Vypadá úplně stejně jako obyčejná, ale kostka ledu z těžké vody v obyčejné vodě neplave, klesne ke dnu.' },
            { type: 'callout', variant: 'warning', title: 'Pozor', text: 'Izotopy se liší **jen počtem neutronů**. Kdyby se lišily počtem protonů, byly by to atomy různých prvků.' },
            { type: 'check', question: { kind: 'choice', q: 'Která dvojice nuklidů jsou izotopy téhož prvku?', options: ['$^{16}_{8}O$ a $^{18}_{8}O$', '$^{14}_{6}C$ a $^{14}_{7}N$', '$^{40}_{18}Ar$ a $^{40}_{20}Ca$', '$^{1}_{1}H$ a $^{4}_{2}He$'], answer: 0, explain: 'Izotopy mají stejné $Z$ a různé $A$. To splňují jen dva kyslíky se $Z = 8$. Ostatní dvojice jsou různé prvky.' } },
          ],
        },
        {
          title: 'Počítáme elektrony v iontech',
          blocks: [
            { type: 'p', text: 'Ion vzniká přijetím nebo odevzdáním elektronů. Protony ani neutrony se nemění. Počet elektronů v iontu tedy spočítáš z protonového čísla a náboje.' },
            { type: 'formula', text: 'počet $e^-$ = $Z$ − náboj iontu', caption: 'u kationtu odečítáš, u aniontu přičítáš (odečítáš záporné číslo)' },
            { type: 'table', headers: ['Částice', 'Protony', 'Elektrony', 'Proč'], rows: [
              ['$Na^+$', '11', '10', 'ztratil 1 elektron'],
              ['$Cl^-$', '17', '18', 'získal 1 elektron'],
              ['$O^2-$', '8', '10', 'získal 2 elektrony'],
              ['$Fe^{3+}$', '26', '23', 'ztratil 3 elektrony'],
            ] },
            { type: 'example', problem: 'Kolik protonů, neutronů a elektronů má ion $^{27}_{13}Al^{3+}$?', steps: [
              'Protony: $Z = 13$.',
              'Neutrony: $N = 27 − 13 = 14$.',
              'Elektrony: náboj +3 znamená, že chybějí 3 elektrony: 13 − 3 = 10.',
            ], answer: '13 protonů, 14 neutronů, 10 elektronů' },
            { type: 'callout', variant: 'tip', text: 'Rychlá kontrola: sečti náboje. U $Al^{3+}$ je to +13 za protony a −10 za elektrony, dohromady +3. Sedí!' },
            { type: 'game', gameId: 'build-atom', text: 'Vyzkoušej si to v praxi: ve hře Postav atom skládáš z protonů, neutronů a elektronů zadaný atom nebo ion.' },
            { type: 'check', question: { kind: 'number', q: 'Kolik elektronů má ion $^{32}_{16}S^2-$?', answer: 18, tolerance: 0, explain: 'Síra má 16 protonů. Náboj 2− znamená 2 elektrony navíc: 16 + 2 = 18.' } },
          ],
        },
        {
          title: 'Relativní atomová hmotnost',
          blocks: [
            { type: 'p', text: 'Atomy jsou tak lehké, že vážit je v kilogramech je nepraktické. Chemici proto zavedli malou jednotku: **atomovou hmotnostní konstantu** $m_{u}$, což je 1/12 hmotnosti atomu uhlíku-12. Platí $m_{u}$ = 1,66·10^{−27} kg.' },
            { type: 'p', text: '**Relativní atomová hmotnost** $A_{r}$ říká, kolikrát je atom těžší než $m_{u}$. Je to bezrozměrné číslo a najdeš ho v periodické tabulce u každého prvku.' },
            { type: 'p', text: 'Proč má chlor v tabulce 35,5, a ne celé číslo? Protože přírodní chlor je směs dvou izotopů: asi 75 % $^{35}Cl$ a 25 % $^{37}Cl$. Hodnota v tabulce je jejich **vážený průměr**: těžší slovo má izotop, kterého je víc.' },
            { type: 'formula', text: 'A_{r} = A_{1} · x_{1} + A_{2} · x_{2} + …', caption: 'x = zastoupení izotopu jako desetinné číslo (75 % = 0,75)' },
            { type: 'example', title: 'Chlor', problem: 'Přírodní chlor obsahuje 75 % izotopu $^{35}Cl$ a 25 % izotopu $^{37}Cl$. Vypočítej jeho relativní atomovou hmotnost.', steps: [
              'Převeď procenta na desetinná čísla: 0,75 a 0,25.',
              'Vynásob každé nukleonové číslo jeho zastoupením: 35 · 0,75 = 26,25 a 37 · 0,25 = 9,25.',
              'Sečti: 26,25 + 9,25 = 35,5.',
            ], answer: '$A_{r}(Cl)$ = 35,5' },
            { type: 'callout', variant: 'tip', title: 'Kontrola selským rozumem', text: 'Výsledek musí ležet mezi hmotnostmi izotopů a blíž k tomu, kterého je víc. 35,5 je blíž k 35, sedí to. (Přesné tabulkové hodnoty se od našich výpočtů mírně liší, protože skutečné hmotnosti izotopů nejsou přesně celá čísla.)' },
            { type: 'check', question: { kind: 'number', q: 'Bor obsahuje 20 % izotopu $^{10}B$ a 80 % izotopu $^{11}B$. Jaká je jeho relativní atomová hmotnost?', answer: 10.8, tolerance: 0.02, explain: '10 · 0,20 + 11 · 0,80 = 2 + 8,8 = 10,8. V tabulce najdeš 10,81.' } },
          ],
        },
        {
          title: 'Radioaktivita: když se jádro rozpadá',
          blocks: [
            { type: 'p', text: 'Některá jádra jsou nestabilní, například mají příliš mnoho neutronů nebo jsou prostě moc velká. Taková jádra se samovolně mění na jiná a vysílají přitom **radioaktivní záření**. Objevil ho Henri Becquerel v roce 1896.' },
            { type: 'callout', variant: 'fact', title: 'Česká stopa', text: 'Marie Curie-Skłodowská a Pierre Curie objevili v roce 1898 nové prvky polonium a radium. Zpracovávali tuny odpadu z uranové rudy smolince z Jáchymova.' },
            { type: 'table', headers: ['Záření', 'Co to je', 'Náboj', 'Co ho zastaví', 'Změna jádra'], rows: [
              ['α (alfa)', 'jádra helia $^{4}_{2}He$', '+2', 'list papíru, kůže', '$Z$ − 2, $A$ − 4'],
              ['β (beta)', 'elektrony vzniklé v jádře', '−1', 'hliníkový plech (pár mm)', '$Z$ + 1, $A$ stejné'],
              ['γ (gama)', 'elektromagnetické záření s vysokou energií', '0', 'zeslabí silná vrstva olova nebo betonu', 'beze změny $Z$ a $A$'],
            ] },
            { type: 'p', text: 'Při přeměně β se v jádře jeden neutron změní na proton a elektron, který jádro opustí. Tak se uhlík-14 mění na dusík-14:' },
            { type: 'formula', text: '$^{14}_{6}C -> ^{14}_{7}N + ^{0}_{−1}e$', caption: 'součet nukleonových i protonových čísel na obou stranách souhlasí' },
            { type: 'p', text: '**Poločas přeměny** je doba, za kterou se přemění polovina jader vzorku. Pro uhlík-14 je to 5 730 let, pro jod-131 jen 8 dní. Po dvou poločasech zbývá čtvrtina, po třech osmina.' },
            { type: 'list', items: [
              '**Radiouhlíková metoda:** živé organismy mají v sobě stálý podíl uhlíku-14. Po smrti ubývá, a z toho, kolik ho zbylo, se určí stáří dřeva, kostí nebo látek.',
              '**Medicína:** kobalt-60 ozařuje nádory, technecium-99m a jod-131 pomáhají v diagnostice a léčbě štítné žlázy.',
              '**Energetika a technika:** jaderné elektrárny Temelín a Dukovany využívají uran-235, hlásiče kouře obsahují americium-241.',
            ] },
            { type: 'callout', variant: 'warning', title: 'Bezpečnost', text: 'Radioaktivní záření poškozuje živé buňky. Chrání tě **vzdálenost**, **čas** (co nejkratší) a **stínění**. Se zářiči pracují jen vyškolení odborníci.' },
            { type: 'check', question: { kind: 'number', q: 'Máš 80 g jodu-131 s poločasem přeměny 8 dní. Kolik gramů jodu-131 zbude po 24 dnech?', answer: 10, tolerance: 0, unit: 'g', explain: '24 dní jsou 3 poločasy: 80 g -> 40 g -> 20 g -> 10 g.' } },
          ],
        },
      ],
      summary: [
        'Protonové číslo $Z$ je počet protonů a určuje prvek; nukleonové číslo $A$ je počet protonů a neutronů.',
        'Počet neutronů je $N = A − Z$; počet elektronů v iontu je $Z$ minus náboj.',
        'Izotopy mají stejné $Z$, ale různý počet neutronů (protium, deuterium, tritium; uhlík-12 a uhlík-14).',
        'Relativní atomová hmotnost je vážený průměr izotopů, proto má chlor 35,5.',
        'Záření α jsou jádra helia, β elektrony z jádra, γ vysokoenergetické elektromagnetické záření.',
        'Za jeden poločas přeměny se přemění polovina jader; využívá se k datování i v medicíně.',
      ],
      quiz: [
        { kind: 'number', q: 'Kolik neutronů má atom $^{56}_{26}Fe$?', answer: 30, tolerance: 0, explain: '$N = A − Z = 56 − 26 = 30$.' },
        { kind: 'choice', q: 'Který nuklid je izotopem uhlíku $^{12}_{6}C$?', options: ['$^{13}_{6}C$', '$^{13}_{7}N$', '$^{12}_{7}N$', '$^{12}_{5}B$'], answer: 0, explain: 'Izotop musí mít stejné protonové číslo ($Z = 6$) a jiné nukleonové. Ostatní nuklidy jsou jiné prvky, i když mají stejné $A$.' },
        { kind: 'tf', q: 'Izotopy téhož prvku mají stejný počet neutronů.', answer: false, explain: 'Je to naopak: izotopy mají stejný počet protonů, ale liší se počtem neutronů.' },
        { kind: 'number', q: 'Kolik elektronů má kation $Ca^{2+}$? (Vápník má $Z = 20$.)', answer: 18, tolerance: 0, explain: 'Kation 2+ ztratil dva elektrony: 20 − 2 = 18.' },
        { kind: 'number', q: 'Lithium obsahuje 7,5 % izotopu $^{6}Li$ a 92,5 % izotopu $^{7}Li$. Spočítej jeho relativní atomovou hmotnost.', answer: 6.925, tolerance: 0.02, explain: '6 · 0,075 + 7 · 0,925 = 0,45 + 6,475 = 6,925. Tabulka uvádí 6,94.' },
        { kind: 'match', q: 'Přiřaď druh záření k tomu, co ho zastaví.', pairs: [['záření α', 'list papíru'], ['záření β', 'hliníkový plech'], ['záření γ', 'silná vrstva olova nebo betonu']], explain: 'Těžká a nabitá jádra helia (α) projdou nejméně, elektrony (β) víc a elektromagnetické záření γ je nejpronikavější.' },
        { kind: 'multi', q: 'Co platí pro nuklid $^{3}_{1}H$?', options: ['Je to tritium.', 'Má 2 neutrony.', 'Má 3 protony.', 'Je radioaktivní.', 'Je to jiný prvek než vodík.'], answers: [0, 1, 3], explain: 'Tritium má 1 proton a 3 − 1 = 2 neutrony a je radioaktivní. S jedním protonem je to pořád vodík.' },
        { kind: 'choice', q: 'Vzorek obsahuje 40 g radioaktivního izotopu. Kolik ho zbude po třech poločasech přeměny?', options: ['5 g', '10 g', '13,3 g', '0 g'], answer: 0, explain: 'Každý poločas se množství zmenší na polovinu: 40 g -> 20 g -> 10 g -> 5 g.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l2-4
    'l2-4': {
      id: 'l2-4',
      title: 'Elektronové vrstvy a valenční elektrony',
      goals: [
        'Rozmístit elektrony do vrstev K, L, M, N u prvků se $Z$ ≤ 20 a nakreslit Bohrův model',
        'Určit počet valenčních elektronů a zapsat Lewisovu značku atomu',
        'Vysvětlit pomocí oktetu, proč vzniká $Na^+$ a $Cl^-$',
        'Vysvětlit, co je ionizační energie',
      ],
      hook: 'Neon v zářivých reklamách nereaguje skoro s ničím. Sodík, jeho soused v tabulce, ve vodě prská a syčí. A rozdíl mezi nimi? Jediný elektron. Pojď zjistit, proč právě ten jeden rozhoduje.',
      sections: [
        {
          title: 'Elektrony bydlí ve vrstvách',
          blocks: [
            { type: 'p', text: 'Podle Bohrova modelu se elektrony pohybují kolem jádra jen v určitých **elektronových vrstvách** (slupkách). Čím dál je vrstva od jádra, tím vyšší energii její elektrony mají.' },
            { type: 'p', text: 'Vrstvy se číslují $n$ = 1, 2, 3, 4… nebo označují písmeny K, L, M, N… Každá vrstva pojme nejvýše 2n^{2} elektronů.' },
            { type: 'table', headers: ['Vrstva', '$n$', 'Maximum 2n^{2}', 'U prvků se Z ≤ 20'], rows: [
              ['K', '1', '2', '2'],
              ['L', '2', '8', '8'],
              ['M', '3', '18', '8'],
              ['N', '4', '32', '1–2 (jen K a Ca)'],
            ] },
            { type: 'p', text: 'Elektrony zaplňují vrstvy odvnitř ven. Pro prvních 20 prvků platí jednoduchý model **2-8-8-2**: do K se vejdou 2, do L 8, do M zatím 8 a zbytek jde do N.' },
            { type: 'callout', variant: 'warning', title: 'Proč jen 8 v M?', text: 'Vrstva M pojme až 18 elektronů. U draslíku a vápníku ale 19. a 20. elektron obsadí nejdřív vrstvu N. Proč, vysvětlí až orbitaly v příští lekci.' },
            { type: 'diagram', id: 'bohr', props: { z: 11 }, caption: 'Sodík (Z = 11): 2 elektrony v K, 8 v L, 1 v M' },
            { type: 'check', question: { kind: 'choice', q: 'Jak jsou rozmístěny elektrony v atomu hořčíku ($Z = 12$)?', options: ['2, 8, 2', '2, 10', '8, 4', '2, 2, 8'], answer: 0, explain: 'Zaplňuj odvnitř: K pojme 2, L 8, zbylé 2 elektrony jdou do M.' } },
          ],
        },
        {
          title: 'Jak nakreslit atom po vrstvách',
          blocks: [
            { type: 'list', ordered: true, items: [
              'Najdi protonové číslo $Z$. U neutrálního atomu je to i počet elektronů.',
              'Do vrstvy K dej 2 elektrony.',
              'Do vrstvy L dej až 8 elektronů.',
              'Do vrstvy M dej až 8 elektronů.',
              'Zbytek (nejvýš 2) dej do vrstvy N.',
            ] },
            { type: 'example', problem: 'Rozmísti elektrony atomu hliníku ($Z = 13$) do vrstev.', steps: [
              '13 elektronů celkem.',
              'K: 2, zbývá 11.',
              'L: 8, zbývá 3.',
              'M: 3, hotovo.',
            ], answer: 'Al: 2, 8, 3' },
            { type: 'table', headers: ['Prvek', '$Z$', 'K', 'L', 'M', 'N'], rows: [
              ['H', '1', '1', '', '', ''],
              ['C', '6', '2', '4', '', ''],
              ['O', '8', '2', '6', '', ''],
              ['Ne', '10', '2', '8', '', ''],
              ['Cl', '17', '2', '8', '7', ''],
              ['Ar', '18', '2', '8', '8', ''],
              ['Ca', '20', '2', '8', '8', '2'],
            ] },
            { type: 'diagram', id: 'bohr', props: { z: 17 }, caption: 'Chlor (Z = 17): 2, 8, 7. Poslední vrstvě chybí jediný elektron do osmi.' },
            { type: 'check', question: { kind: 'number', q: 'Kolik elektronů má atom fosforu ($Z = 15$) v poslední vrstvě?', answer: 5, tolerance: 0, explain: 'Rozmístění je 2, 8, 5. Ve vrstvě M je tedy 5 elektronů.' } },
          ],
        },
        {
          title: 'Valenční elektrony a Lewisovy značky',
          blocks: [
            { type: 'p', text: 'Elektrony v poslední (vnější) vrstvě se jmenují **valenční elektrony** a vrstva se jmenuje **valenční vrstva**. Jsou nejdál od jádra, a proto se účastní chemických reakcí a vazeb. Vnitřní elektrony zůstávají stranou.' },
            { type: 'p', text: 'Americký chemik Gilbert N. Lewis vymyslel jednoduchý zápis: kolem značky prvku nakreslíš tolik teček, kolik má atom valenčních elektronů. Tečky rozmísťuj nejdřív po jedné na čtyři strany a teprve potom je spojuj do dvojic.' },
            { type: 'structure', art: [
              '         •     •     •    ••    ••',
              ' Li•    •C•   :N•   :O:   :F:  :Ne:',
              '         •     •     •     •    ••',
            ].join('\n'), caption: 'Lewisovy značky: Li má 1 valenční elektron, C 4, N 5, O 6, F 7 a Ne 8' },
            { type: 'callout', variant: 'tip', text: 'V lekci o periodické soustavě uvidíš, že počet valenčních elektronů prozradí už poloha prvku v tabulce. Prvky pod sebou mají stejný počet valenčních elektronů, a proto se chemicky podobají.' },
            { type: 'game', gameId: 'who-am-i', text: 'Zahraj si Kdo jsem? a hádej prvky podle nápověd typu „mám 7 valenčních elektronů a tři vrstvy“.' },
            { type: 'check', question: { kind: 'match', q: 'Přiřaď k prvku počet jeho valenčních elektronů.', pairs: [['Na (Z = 11)', '1'], ['C (Z = 6)', '4'], ['S (Z = 16)', '6'], ['Cl (Z = 17)', '7']], explain: 'Na 2, 8, 1; C 2, 4; S 2, 8, 6; Cl 2, 8, 7. Rozhoduje poslední vrstva.' } },
          ],
        },
        {
          title: 'Oktet: proč atomy tvoří ionty',
          blocks: [
            { type: 'p', text: '**Vzácné plyny** (helium, neon, argon…) skoro s ničím nereagují. Mají totiž zaplněnou valenční vrstvu: helium 2 elektrony, ostatní 8 elektronů. Osmici valenčních elektronů se říká **elektronový oktet**.' },
            { type: 'p', text: '==Atomy ostatních prvků se snaží dosáhnout stejně stabilního uspořádání jako nejbližší vzácný plyn.== Jednou z cest je elektrony odevzdat, nebo přijmout, a stát se iontem. Druhou cestou je elektrony sdílet ve vazbě, o tom v úrovni 3.' },
            { type: 'table', headers: ['Atom', 'Vrstvy', 'Ion', 'Vrstvy iontu', 'Jako'], rows: [
              ['Na', '2, 8, 1', '$Na^+$', '2, 8', 'Ne'],
              ['Mg', '2, 8, 2', '$Mg^{2+}$', '2, 8', 'Ne'],
              ['O', '2, 6', '$O^2-$', '2, 8', 'Ne'],
              ['Cl', '2, 8, 7', '$Cl^-$', '2, 8, 8', 'Ar'],
            ] },
            { type: 'formula', text: '$Na -> Na^+ + e^-$ a $Cl + e^- -> Cl^-$', caption: 'sodík elektron odevzdá, chlor ho přijme' },
            { type: 'diagram', id: 'bohr', props: { z: 11, ion: 1 }, caption: 'Kation $Na^+$: po ztrátě valenčního elektronu zbyly vrstvy 2, 8 jako u neonu' },
            { type: 'diagram', id: 'bohr', props: { z: 17, ion: -1 }, caption: 'Anion $Cl^-$: po přijetí elektronu má vrstvy 2, 8, 8 jako argon' },
            { type: 'callout', variant: 'remember', text: 'Atomy s 1–3 valenčními elektrony (hlavně kovy) je snadno **odevzdávají** a tvoří **kationty**. Atomy s 5–7 valenčními elektrony (nekovy) elektrony **přijímají** a tvoří **anionty**.' },
            { type: 'callout', variant: 'mascot', text: 'Sodík a chlor jsou jako dva kamarádi: jeden má jeden elektron navíc, druhému jeden chybí. Výsledek? Kuchyňská sůl na tvých hranolkách.' },
            { type: 'check', question: { kind: 'choice', q: 'Jaký ion nejspíš vytvoří atom hořčíku (2, 8, 2)?', options: ['$Mg^{2+}$', '$Mg^+$', '$Mg^2-$', '$Mg^{6-}$'], answer: 0, explain: 'Hořčíku se vyplatí odevzdat 2 valenční elektrony a získat uspořádání neonu 2, 8. Přijmout šest elektronů by bylo energeticky nevýhodné.' } },
          ],
        },
        {
          title: 'Ionizační energie',
          blocks: [
            { type: 'p', text: 'Odtrhnout elektron od atomu stojí energii. **Ionizační energie** je energie potřebná k odtržení nejslaběji vázaného elektronu z atomu v plynném stavu. Čím je menší, tím snadněji atom vytvoří kation.' },
            { type: 'table', headers: ['Prvek', 'Vrstvy', '1. ionizační energie (kJ/mol)'], rows: [
              ['K', '2, 8, 8, 1', '419'],
              ['Na', '2, 8, 1', '496'],
              ['Mg', '2, 8, 2', '738'],
              ['Ar', '2, 8, 8', '1 521'],
              ['Ne', '2, 8', '2 081'],
              ['He', '2', '2 372'],
            ], caption: 'Jednotce kJ/mol porozumíš v úrovni 4; zatím stačí čísla porovnávat.' },
            { type: 'p', text: 'Valenční elektron sodíku je daleko od jádra a vnitřní vrstvy ho před jádrem stíní. Odtrhne se snadno. Vzácné plyny mají naopak ionizační energii velmi vysokou, a proto netvoří ionty.' },
            { type: 'p', text: 'Zajímavé je, co se stane, když od sodíku chceš odtrhnout **druhý** elektron. Ten už patří do zaplněné vrstvy L blízko jádra. Druhá ionizační energie sodíku je 4 562 kJ/mol, skoro desetkrát víc než první. Proto sodík tvoří jen $Na^+$, nikdy $Na^{2+}$.' },
            { type: 'callout', variant: 'fact', title: 'Důkaz vrstev', text: 'Hořčík má ionizační energie 738, 1 451 a pak najednou 7 733 kJ/mol. Obrovský skok po druhém elektronu prozrazuje, že dva elektrony jsou ve vnější vrstvě a další už jsou ve vrstvě vnitřní. Tak se vrstvy opravdu dají „změřit“.' },
            { type: 'check', question: { kind: 'tf', q: 'Druhá ionizační energie sodíku je mnohem větší než první.', answer: true, explain: 'Druhý elektron by se musel vytrhnout ze zaplněné vrstvy L, která je blíž jádru. To stojí téměř desetkrát víc energie.' } },
          ],
        },
      ],
      summary: [
        'Elektrony obsazují vrstvy K, L, M, N; vrstva pojme nejvýše 2n^{2} elektronů.',
        'U prvků se $Z$ ≤ 20 platí model 2-8-8-2.',
        'Valenční elektrony jsou v poslední vrstvě a účastní se reakcí; Lewisova značka je znázorňuje tečkami.',
        'Vzácné plyny mají stabilní oktet (helium dvojici), ostatní atomy se k němu přibližují tvorbou iontů nebo vazeb.',
        'Kovy s 1–3 valenčními elektrony tvoří kationty, nekovy s 5–7 valenčními elektrony anionty.',
        'Ionizační energie je energie nutná k odtržení elektronu; nízká je u sodíku a draslíku, vysoká u vzácných plynů.',
      ],
      quiz: [
        { kind: 'choice', q: 'Jak jsou rozmístěny elektrony v atomu síry ($Z = 16$)?', options: ['2, 8, 6', '2, 6, 8', '2, 14', '8, 8'], answer: 0, explain: 'K pojme 2, L 8 a zbylých 6 elektronů jde do vrstvy M.' },
        { kind: 'number', q: 'Kolik valenčních elektronů má křemík ($Z = 14$)?', answer: 4, tolerance: 0, explain: 'Rozmístění 2, 8, 4: ve valenční vrstvě M jsou 4 elektrony.' },
        { kind: 'tf', q: 'Vrstva M může obsahovat nejvýše 8 elektronů.', answer: false, explain: 'Vrstva M ($n$ = 3) pojme až 2 · 3^{2} = 18 elektronů. Model 2-8-8 platí jen pro prvních 20 prvků.' },
        { kind: 'match', q: 'Přiřaď k atomu ion, který nejsnáze vytvoří.', pairs: [['Na', '$Na^+$'], ['Mg', '$Mg^{2+}$'], ['O', '$O^2-$'], ['Cl', '$Cl^-$']], explain: 'Každý z nich tak získá uspořádání nejbližšího vzácného plynu: Na, Mg a O jako neon, Cl jako argon.' },
        { kind: 'multi', q: 'Které částice mají elektrony rozmístěné stejně jako neon (2, 8)?', options: ['$Na^+$', '$Mg^{2+}$', '$F^-$', '$Cl^-$', '$K^+$'], answers: [0, 1, 2], explain: '$Na^+$, $Mg^{2+}$ a $F^-$ mají po 10 elektronech. $Cl^-$ a $K^+$ mají 18 elektronů, tedy uspořádání argonu.' },
        { kind: 'text', q: 'Napiš značku vzácného plynu, jehož uspořádání elektronů získá ion $Cl^-$.', accept: ['Ar'], caseSensitive: true, placeholder: 'značka', explain: '$Cl^-$ má 18 elektronů (2, 8, 8), stejně jako argon.' },
        { kind: 'choice', q: 'Proč sodík tak snadno tvoří kation $Na^+$?', options: ['Jeho jediný valenční elektron je daleko od jádra a má nízkou ionizační energii.', 'Sodík má v jádře málo neutronů.', 'Sodík potřebuje přijmout 7 elektronů do oktetu.', 'Valenční elektron sodíku je ve vrstvě K.'], answer: 0, explain: 'Osamocený elektron ve vrstvě M je stíněný vnitřními vrstvami a slabě vázaný, jeho odtržením sodík získá uspořádání neonu.' },
        { kind: 'order', q: 'Seřaď atomy podle první ionizační energie od nejmenší.', items: ['K', 'Na', 'Mg', 'Ne'], explain: 'Draslík (419) má valenční elektron nejdál od jádra, pak sodík (496), hořčík (738) a neon (2 081) se zaplněným oktetem.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l2-5
    'l2-5': {
      id: 'l2-5',
      title: 'Orbitaly a elektronová konfigurace',
      goals: [
        'Vysvětlit, co je orbital, a popsat význam čtyř kvantových čísel',
        'Napsat elektronovou konfiguraci atomu podle výstavbového principu, Pauliho principu a Hundova pravidla, i ve zkráceném zápisu',
        'Nakreslit rámečkový diagram a určit počet nepárových elektronů',
        'Znát výjimky Cr a Cu a zapsat konfiguraci iontu',
      ],
      hook: 'Bohrův model s elektrony na drahách je jako plánek metra: užitečný, ale skutečnost vypadá jinak. Elektron totiž žádnou dráhu nemá. Je to spíš obláček pravděpodobnosti. Zní to divně? Vítej v kvantovém světě!',
      sections: [
        {
          title: 'Orbital: kde se elektron nejspíš vyskytuje',
          blocks: [
            { type: 'p', text: 'Ve 20. letech 20. století fyzici zjistili, že u elektronu nelze zároveň přesně určit polohu i rychlost (**Heisenbergův princip neurčitosti**). Nemá proto smysl kreslit mu přesnou dráhu.' },
            { type: 'p', text: 'Místo toho popisujeme, **kde se elektron s jakou pravděpodobností vyskytuje**. Oblast kolem jádra, ve které elektron najdeme s velkou pravděpodobností (obvykle se bere 90 %), se nazývá **orbital**.' },
            { type: 'callout', variant: 'tip', title: 'Představ si to', text: 'Vyfoť včelu u úlu s hodně dlouhou expozicí. Na fotce nebude jedna včela, ale rozmazaný oblak. Tam, kde je nejhustší, se včela zdržovala nejčastěji. Orbital je takový „oblak“ pro elektron.' },
            { type: 'keyterms', items: [
              { term: '**Orbital**', def: 'oblast, kde se elektron vyskytuje s velkou pravděpodobností; pojme nejvýš 2 elektrony.' },
              { term: '**Vrstva (slupka)**', def: 'orbitaly se stejným hlavním kvantovým číslem $n$; odpovídá vrstvám K, L, M… z Bohrova modelu.' },
              { term: '**Podslupka**', def: 'orbitaly stejného typu v jedné vrstvě, například tři orbitaly 2p.' },
            ] },
            { type: 'check', question: { kind: 'tf', q: 'Podle kvantového modelu obíhá elektron kolem jádra po přesné kruhové dráze.', answer: false, explain: 'Přesnou dráhu elektronu určit nelze. Kvantový model popisuje jen pravděpodobnost výskytu elektronu, tedy orbital.' } },
          ],
        },
        {
          title: 'Čtyři kvantová čísla a tvary orbitalů',
          blocks: [
            { type: 'p', text: 'Každý elektron v atomu je popsán čtyřmi **kvantovými čísly**. Jsou to něco jako jeho adresa: vrstva, typ orbitalu, konkrétní orbital a „otočení“ elektronu.' },
            { type: 'table', headers: ['Kvantové číslo', 'Hodnoty', 'Co určuje'], rows: [
              ['hlavní $n$', '1, 2, 3, …', 'energii a velikost orbitalu, číslo vrstvy'],
              ['vedlejší $l$', '0 až $n$ − 1', 'tvar orbitalu: 0 = s, 1 = p, 2 = d, 3 = f'],
              ['magnetické $m$', '−$l$ až +$l$', 'orientaci orbitalu v prostoru, a tím počet orbitalů v podslupce'],
              ['spinové $s$', '+½, −½', 'spin elektronu, kreslíme šipkou ↑ nebo ↓'],
            ] },
            { type: 'list', items: [
              '**Orbital s** má tvar koule. V každé vrstvě je jeden.',
              '**Orbitaly p** mají tvar činky (prostorové osmičky). Jsou tři, orientované podél os x, y, z.',
              '**Orbitaly d** jsou čtyřlístky (jeden z nich je činka s prstencem). Je jich pět.',
              '**Orbitaly f** mají složité tvary a je jich sedm.',
            ] },
            { type: 'table', headers: ['Podslupka', 'Počet orbitalů', 'Max. elektronů', 'Objevuje se od vrstvy'], rows: [
              ['s', '1', '2', '$n$ = 1'],
              ['p', '3', '6', '$n$ = 2'],
              ['d', '5', '10', '$n$ = 3'],
              ['f', '7', '14', '$n$ = 4'],
            ] },
            { type: 'callout', variant: 'fact', title: 'Proč zrovna s, p, d, f?', text: 'Písmena pocházejí z popisu čar ve spektrech: *sharp*, *principal*, *diffuse* a *fundamental* (ostrá, hlavní, rozmazaná, základní).' },
            { type: 'p', text: 'Teď už víš, proč vrstva pojme 2n^{2} elektronů: vrstva $n$ = 3 má podslupky 3s, 3p a 3d, tedy 1 + 3 + 5 = 9 orbitalů a v nich 18 elektronů.' },
            { type: 'check', question: { kind: 'number', q: 'Kolik elektronů nejvýše pojme podslupka d?', answer: 10, tolerance: 0, explain: 'Podslupka d má 5 orbitalů a do každého se vejdou 2 elektrony: 5 · 2 = 10.' } },
          ],
        },
        {
          title: 'Výstavbový princip: v jakém pořadí se orbitaly plní',
          blocks: [
            { type: 'p', text: '**Výstavbový princip** (anglicky *Aufbau*) říká, že elektrony obsazují orbitaly postupně **od nejnižší energie**. Energie ale neroste přesně po vrstvách. Podslupky se překrývají.' },
            { type: 'formula', text: '1s -> 2s -> 2p -> 3s -> 3p -> 4s -> 3d -> 4p -> 5s -> 4d -> 5p -> 6s -> 4f -> 5d -> 6p -> 7s', caption: 'pořadí zaplňování orbitalů' },
            { type: 'p', text: 'Pořadí si nemusíš pamatovat nazpaměť. Stačí **pravidlo n + l**: dřív se zaplní podslupka s menším součtem $n + l$. Při stejném součtu dostane přednost ta s menším $n$. Orbital 4s má součet 4 + 0 = 4, orbital 3d 3 + 2 = 5, proto se 4s zaplní dřív.' },
            { type: 'structure', art: [
              '1s',
              '2s  2p',
              '3s  3p  3d',
              '4s  4p  4d  4f',
              '5s  5p  5d  5f',
              '6s  6p  6d',
              '7s  7p',
            ].join('\n'), caption: 'Diagonální pravidlo: čti po šikmých úhlopříčkách zprava shora doleva dolů: 1s | 2s | 2p 3s | 3p 4s | 3d 4p 5s | …' },
            { type: 'callout', variant: 'remember', text: '==Orbital 4s se zaplňuje dřív než 3d.== Proto mají draslík a vápník elektrony ve vrstvě N, i když je vrstva M ještě neplná.' },
            { type: 'check', question: { kind: 'order', q: 'Seřaď podslupky v pořadí, v jakém se zaplňují.', items: ['3s', '3p', '4s', '3d', '4p'], explain: 'Podle pravidla n + l: 3s (součet 3), 3p (4), 4s (také 4, ale větší n než 3p), 3d (5) a 4p (také 5, ale větší n než 3d).' } },
          ],
        },
        {
          title: 'Pauliho princip a Hundovo pravidlo',
          blocks: [
            { type: 'p', text: '**Pauliho princip výlučnosti:** v atomu nemohou mít dva elektrony všechna čtyři kvantová čísla stejná. Důsledek: v jednom orbitalu jsou **nejvýš dva elektrony**, a to s opačným spinem (↑↓). Takové dva elektrony tvoří **elektronový pár**.' },
            { type: 'p', text: '**Hundovo pravidlo:** v orbitalech se stejnou energií (například ve třech orbitalech 2p) se elektrony nejdřív rozmístí **po jednom se stejným spinem** a teprve potom se párují.' },
            { type: 'callout', variant: 'tip', title: 'Pravidlo autobusu', text: 'V autobuse si lidé nejdřív sedají každý na volnou dvojsedačku. K někomu si přisednou, až když volná dvojsedačka nezbude. Elektrony v orbitalech p nebo d se chovají stejně.' },
            { type: 'p', text: 'Elektronovou konfiguraci proto často kreslíme jako **rámečkový diagram**: každý rámeček je jeden orbital a šipky jsou elektrony. Elektron, který je v orbitalu sám, se nazývá **nepárový**. Nepárové elektrony budou důležité pro vazby v úrovni 3.' },
            { type: 'diagram', id: 'orbitals', props: { z: 7 }, caption: 'Dusík 1s^{2} 2s^{2} 2p^{3}: tři elektrony 2p sedí každý ve svém orbitalu, dusík má 3 nepárové elektrony' },
            { type: 'diagram', id: 'orbitals', props: { z: 8 }, caption: 'Kyslík 1s^{2} 2s^{2} 2p^{4}: čtvrtý elektron 2p se musí spárovat, zbývají 2 nepárové elektrony' },
            { type: 'check', question: { kind: 'choice', q: 'Jak správně zakreslit dva elektrony 2p v atomu uhlíku?', options: ['[↑] [↑] [ ]', '[↑↓] [ ] [ ]', '[↑] [↓] [ ]', '[↑↓] [↑↓] [ ]'], answer: 0, explain: 'Podle Hundova pravidla obsadí elektrony dva různé orbitaly se stejným spinem. Poslední možnost má navíc 4 elektrony místo 2.' } },
          ],
        },
        {
          title: 'Píšeme elektronovou konfiguraci',
          blocks: [
            { type: 'p', text: '**Elektronová konfigurace** je zápis rozmístění elektronů do podslupek. Počet elektronů v podslupce píšeš jako horní index: 2p^{4} znamená čtyři elektrony v podslupce 2p.' },
            { type: 'list', ordered: true, items: [
              'Zjisti počet elektronů (u atomu = $Z$).',
              'Plň podslupky podle výstavbového principu, s nejvýš 2, p 6, d 10.',
              'Zkontroluj, že součet horních indexů je roven počtu elektronů.',
            ] },
            { type: 'example', title: 'Síra', problem: 'Napiš elektronovou konfiguraci síry ($Z = 16$).', steps: [
              '1s^{2} (2 elektrony, zbývá 14)',
              '2s^{2} 2p^{6} (dalších 8, zbývá 6)',
              '3s^{2} 3p^{4} (posledních 6)',
              'Kontrola: 2 + 2 + 6 + 2 + 4 = 16.',
            ], answer: 'S: 1s^{2} 2s^{2} 2p^{6} 3s^{2} 3p^{4}' },
            { type: 'p', text: '**Zkrácený zápis:** vnitřní elektrony nahradíš značkou předchozího vzácného plynu v hranatých závorkách. Síra má před sebou neon (1s^{2} 2s^{2} 2p^{6}), takže S: [Ne] 3s^{2} 3p^{4}. Hned vidíš 6 valenčních elektronů.' },
            { type: 'example', title: 'Železo', problem: 'Napiš úplnou i zkrácenou konfiguraci železa ($Z = 26$).', steps: [
              '1s^{2} 2s^{2} 2p^{6} 3s^{2} 3p^{6} je 18 elektronů, to je konfigurace argonu.',
              'Pak 4s^{2} (20 elektronů).',
              'Zbylých 6 elektronů jde do 3d: 3d^{6}.',
            ], answer: 'Fe: 1s^{2} 2s^{2} 2p^{6} 3s^{2} 3p^{6} 4s^{2} 3d^{6} = [Ar] 4s^{2} 3d^{6}' },
            { type: 'callout', variant: 'tip', text: 'V některých učebnicích uvidíš zápis [Ar] 3d^{6} 4s^{2}, seřazený podle vrstev. Obě pořadí jsou správně, obsah je stejný.' },
            { type: 'game', gameId: 'electron-config', text: 'Ve hře Zaplň orbitaly rozmísťuješ šipky do rámečků. Dodrž výstavbový princip, Pauliho princip i Hundovo pravidlo!' },
            { type: 'check', question: { kind: 'text', q: 'Napiš zkrácenou elektronovou konfiguraci sodíku ($Z = 11$). Horní indexy piš jako obyčejné číslice, např. 2p6.', accept: ['[Ne]3s1', '[Ne] 3s1', '[Ne]3s^1', '[Ne] 3s^{1}', '1s2 2s2 2p6 3s1', '1s22s22p63s1'], caseSensitive: true, placeholder: '[?] …', explain: 'Sodík má o jeden elektron víc než neon: [Ne] 3s^{1}.' } },
          ],
        },
        {
          title: 'Výjimky a konfigurace iontů',
          blocks: [
            { type: 'p', text: 'Výstavbový princip funguje skvěle, ale má pár výjimek. Nejznámější jsou **chrom** a **měď**. Zaplněná (d^{10}) nebo přesně z poloviny zaplněná (d^{5}) podslupka d je totiž zvlášť stabilní, a tak jeden elektron „přeskočí“ ze 4s do 3d.' },
            { type: 'table', headers: ['Prvek', 'Podle pravidla by bylo', 'Ve skutečnosti'], rows: [
              ['Cr ($Z = 24$)', '[Ar] 4s^{2} 3d^{4}', '[Ar] 4s^{1} 3d^{5}'],
              ['Cu ($Z = 29$)', '[Ar] 4s^{2} 3d^{9}', '[Ar] 4s^{1} 3d^{10}'],
            ] },
            { type: 'diagram', id: 'orbitals', props: { z: 24 }, caption: 'Chrom: šest nepárových elektronů, pět v 3d a jeden ve 4s' },
            { type: 'p', text: '**Anionty:** elektrony přidáš do první volné podslupky. $Cl^-$: [Ne] 3s^{2} 3p^{6}, což je konfigurace argonu.' },
            { type: 'p', text: '**Kationty:** elektrony odebíráš z podslupky s **nejvyšším n**. U prvků hlavních skupin je to jasné, $Na^+$ je [Ne]. U železa a dalších přechodných kovů ale odcházejí nejdřív elektrony 4s, až potom 3d.' },
            { type: 'example', problem: 'Napiš konfiguraci iontů $Fe^{2+}$ a $Fe^{3+}$.', steps: [
              'Atom Fe: [Ar] 4s^{2} 3d^{6}.',
              '$Fe^{2+}$: odeber 2 elektrony ze 4s -> [Ar] 3d^{6}.',
              '$Fe^{3+}$: odeber ještě 1 elektron z 3d -> [Ar] 3d^{5}.',
            ], answer: '$Fe^{2+}$: [Ar] 3d^{6}, $Fe^{3+}$: [Ar] 3d^{5}' },
            { type: 'callout', variant: 'warning', title: 'Nejčastější chyba', text: 'Konfigurace $Fe^{2+}$ **není** [Ar] 4s^{2} 3d^{4}. Orbital 4s se plní první, ale při vzniku kationtu se také vyprazdňuje první.' },
            { type: 'check', question: { kind: 'choice', q: 'Jaká je elektronová konfigurace mědi ($Z = 29$)?', options: ['[Ar] 4s^{1} 3d^{10}', '[Ar] 4s^{2} 3d^{9}', '[Ar] 4s^{2} 3d^{10}', '[Kr] 4s^{1}'], answer: 0, explain: 'Měď je výjimka: zaplněná podslupka 3d^{10} je stabilnější, proto jeden elektron přejde ze 4s do 3d.' } },
          ],
        },
      ],
      summary: [
        'Orbital je oblast, kde se elektron vyskytuje s velkou pravděpodobností; pojme nejvýš 2 elektrony.',
        'Kvantová čísla $n$, $l$, $m$, $s$ určují vrstvu, tvar, orientaci orbitalu a spin elektronu.',
        'Orbital s má tvar koule, p činky; podslupky s, p, d, f pojmou 2, 6, 10 a 14 elektronů.',
        'Orbitaly se plní podle výstavbového principu (1s 2s 2p 3s 3p 4s 3d …); 4s se plní před 3d.',
        'Pauliho princip: v orbitalu jsou nejvýš 2 elektrony s opačným spinem. Hundovo pravidlo: nejdřív po jednom, pak párovat.',
        'Zkrácený zápis využívá vzácný plyn, např. S: [Ne] 3s^{2} 3p^{4}.',
        'Výjimky: Cr [Ar] 4s^{1} 3d^{5}, Cu [Ar] 4s^{1} 3d^{10}; kationty přechodných kovů ztrácejí nejdřív elektrony 4s.',
      ],
      quiz: [
        { kind: 'choice', q: 'Jaký tvar má orbital p?', options: ['činky (prostorové osmičky)', 'koule', 'čtyřlístku', 'plochého kruhu'], answer: 0, explain: 'Orbitaly p mají tvar činky a jsou tři, podél os x, y a z. Kulový je orbital s, čtyřlístky jsou orbitaly d.' },
        { kind: 'number', q: 'Kolik elektronů nejvýše pojme vrstva s hlavním kvantovým číslem $n$ = 3?', answer: 18, tolerance: 0, explain: '2n^{2} = 2 · 9 = 18. Vrstva má podslupky 3s, 3p a 3d: 2 + 6 + 10 = 18.' },
        { kind: 'tf', q: 'Orbital 4s se zaplňuje dřív než 3d.', answer: true, explain: 'Podle pravidla n + l má 4s součet 4, kdežto 3d součet 5, takže 4s má nižší energii a plní se první.' },
        { kind: 'order', q: 'Seřaď podslupky podle výstavbového principu.', items: ['2p', '3s', '3p', '4s', '3d'], explain: 'Pořadí zaplňování je 1s 2s 2p 3s 3p 4s 3d 4p…' },
        { kind: 'choice', q: 'Jaká je elektronová konfigurace fosforu ($Z = 15$)?', options: ['1s^{2} 2s^{2} 2p^{6} 3s^{2} 3p^{3}', '1s^{2} 2s^{2} 2p^{6} 3s^{2} 3p^{5}', '1s^{2} 2s^{2} 2p^{6} 3s^{1} 3p^{4}', '1s^{2} 2s^{2} 2p^{6} 3s^{2} 3d^{3}'], answer: 0, explain: 'Po neonu (10 elektronů) zbývá 5: dva do 3s a tři do 3p. Podslupka 3d přichází na řadu až po 4s.' },
        { kind: 'number', q: 'Kolik nepárových elektronů má atom dusíku ($Z = 7$) v základním stavu?', answer: 3, tolerance: 0, explain: 'Konfigurace 1s^{2} 2s^{2} 2p^{3}. Podle Hundova pravidla sedí tři elektrony 2p každý ve svém orbitalu, všechny tři jsou nepárové.' },
        { kind: 'multi', q: 'Které konfigurace jsou **správně**?', options: ['Cr: [Ar] 4s^{1} 3d^{5}', 'Cu: [Ar] 4s^{1} 3d^{10}', '$Fe^{2+}$: [Ar] 4s^{2} 3d^{4}', 'Ca: [Ar] 4s^{2}', '$Cl^-$: [Ne] 3s^{2} 3p^{5}'], answers: [0, 1, 3], explain: 'Cr a Cu jsou známé výjimky, Ca je v pořádku. $Fe^{2+}$ ztrácí nejdřív elektrony 4s, je to [Ar] 3d^{6}. $Cl^-$ má o elektron víc než atom: [Ne] 3s^{2} 3p^{6}.' },
        { kind: 'match', q: 'Přiřaď kvantové číslo k tomu, co určuje.', pairs: [['hlavní $n$', 'energie a velikost orbitalu (vrstva)'], ['vedlejší $l$', 'tvar orbitalu (s, p, d, f)'], ['magnetické $m$', 'orientace orbitalu v prostoru'], ['spinové $s$', 'spin elektronu (↑ nebo ↓)']], explain: 'Čtyři kvantová čísla tvoří „adresu“ elektronu: vrstva, typ orbitalu, konkrétní orbital a spin.' },
      ],
    },

    // ───────────────────────────────────────────────────────────── l2-6
    'l2-6': {
      id: 'l2-6',
      title: 'Periodická soustava prvků',
      goals: [
        'Vysvětlit periodický zákon a orientovat se ve skupinách, periodách a blocích s, p, d, f',
        'Pojmenovat hlavní skupiny a rozlišit kovy, nekovy a polokovy',
        'Popsat, jak se v tabulce mění atomový poloměr, ionizační energie, elektronegativita a kovový charakter',
        'Předpovědět vlastnosti prvku z jeho polohy v tabulce',
      ],
      hook: 'Mendělejev v roce 1869 nechal ve své tabulce prázdná políčka a tvrdil, že tam patří prvky, které ještě nikdo neobjevil. Dokonce předpověděl jejich vlastnosti. Do sedmnácti let byly objeveny tři z nich a sedělo to. Pojď se naučit číst tabulku jako mapu!',
      sections: [
        {
          title: 'Mendělejev a periodický zákon',
          blocks: [
            { type: 'p', text: 'V polovině 19. století znali chemici asi 60 prvků a hledali v nich pořádek. Ruský chemik **Dmitrij Ivanovič Mendělejev** je v roce 1869 seřadil podle rostoucí atomové hmotnosti a prvky s podobnými vlastnostmi dal pod sebe.' },
            { type: 'p', text: 'Byl odvážný: když se prvek do sloupce nehodil, raději nechal **volné místo** a předpověděl, že tam patří dosud neznámý prvek. Kvůli vlastnostem dokonce prohodil tellur a jod, přestože jod má menší atomovou hmotnost.' },
            { type: 'table', headers: ['Vlastnost', 'Předpověď pro „ekasilicium“ (1871)', 'Germanium (objeveno 1886)'], rows: [
              ['relativní atomová hmotnost', '72', '72,6'],
              ['hustota', '5,5 g/cm^{3}', '5,35 g/cm^{3}'],
              ['barva', 'šedý kov', 'šedobílý polokov'],
            ] },
            { type: 'p', text: 'Dnes víme, proč Mendělejev s tellurem a jodem udělal dobře. V roce 1913 Henry Moseley ukázal, že skutečným pořadovým číslem je **protonové číslo** $Z$. Moderní **periodický zákon** zní:' },
            { type: 'callout', variant: 'remember', text: 'Vlastnosti prvků jsou periodickou funkcí jejich **protonového čísla**. Jinými slovy: když prvky seřadíš podle $Z$, podobné vlastnosti se pravidelně opakují.' },
            { type: 'p', text: 'Příčinu už znáš: vlastnosti určují valenční elektrony a jejich uspořádání se po každém vzácném plynu opakuje.' },
            { type: 'check', question: { kind: 'tf', q: 'Moderní periodická tabulka řadí prvky podle rostoucí relativní atomové hmotnosti.', answer: false, explain: 'Řadí je podle protonového čísla $Z$. Proto je tellur ($A_{r}$ 127,6) před jodem ($A_{r}$ 126,9).' } },
          ],
        },
        {
          title: 'Skupiny a periody',
          blocks: [
            { type: 'p', text: '**Perioda** je vodorovný řádek. Je jich sedm a číslo periody udává, kolik elektronových vrstev atom má. Sodík ve 3. periodě má vrstvy K, L, M.' },
            { type: 'p', text: '**Skupina** je svislý sloupec. Podle IUPAC se skupiny číslují 1–18. V českých školách se používá i starší značení: **hlavní skupiny** I.A–VIII.A (skupiny 1, 2 a 13–18) a vedlejší skupiny B. Římské číslo u hlavních skupin udává počet valenčních elektronů.' },
            { type: 'diagram', id: 'periodic-mini', props: { highlight: 'groups' }, caption: 'Skupiny (sloupce) a periody (řádky)' },
            { type: 'table', headers: ['Skupina', 'Název', 'Prvky', 'Valenční elektrony'], rows: [
              ['1 (I.A)', 'alkalické kovy', 'Li, Na, K, Rb, Cs, Fr', 'ns^{1}'],
              ['2 (II.A)', 'kovy alkalických zemin', 'Be, Mg, Ca, Sr, Ba, Ra', 'ns^{2}'],
              ['16 (VI.A)', 'chalkogeny', 'O, S, Se, Te, Po', 'ns^{2} np^{4}'],
              ['17 (VII.A)', 'halogeny', 'F, Cl, Br, I, At', 'ns^{2} np^{5}'],
              ['18 (VIII.A)', 'vzácné plyny', 'He, Ne, Ar, Kr, Xe, Rn', 'ns^{2} np^{6} (He 1s^{2})'],
            ], caption: 'Vodík stojí v 1. skupině, ale alkalický kov to není, je to plyn a nekov. Be a Mg se někdy mezi kovy alkalických zemin nepočítají, podle IUPAC k nim ale patří.' },
            { type: 'elements', symbols: ['Li', 'Na', 'K', 'F', 'Cl', 'Br', 'I', 'He', 'Ne', 'Ar'], caption: 'Alkalické kovy, halogeny a vzácné plyny' },
            { type: 'example', problem: 'Síra má konfiguraci [Ne] 3s^{2} 3p^{4}. Ve které periodě a skupině leží?', steps: [
              'Nejvyšší $n$ je 3, atom má tři vrstvy -> 3. perioda.',
              'Valenční elektrony: 2 + 4 = 6 -> VI.A, tedy skupina 16.',
            ], answer: 'Síra leží ve 3. periodě a 16. skupině (chalkogeny).' },
            { type: 'game', gameId: 'periodic-find', text: 'Vyzkoušej se ve hře Najdi prvek: co nejrychleji ťukni na zadaný prvek v tabulce.' },
            { type: 'check', question: { kind: 'choice', q: 'Který z prvků je **halogen**?', options: ['brom', 'síra', 'argon', 'draslík'], answer: 0, explain: 'Brom je v 17. skupině spolu s fluorem, chlorem a jodem. Síra je chalkogen, argon vzácný plyn a draslík alkalický kov.' } },
          ],
        },
        {
          title: 'Bloky s, p, d, f',
          blocks: [
            { type: 'p', text: 'Periodická tabulka je vlastně výstavbový princip rozložený do řádků. Podle toho, do které podslupky přibývá poslední elektron, se dělí na čtyři **bloky**.' },
            { type: 'diagram', id: 'periodic-mini', props: { highlight: 'blocks' }, caption: 'Bloky s, p, d a f' },
            { type: 'table', headers: ['Blok', 'Kde je', 'Šířka', 'Prvky'], rows: [
              ['s', 'skupiny 1 a 2 (+ helium)', '2 sloupce', 'alkalické kovy, kovy alkalických zemin, H, He'],
              ['p', 'skupiny 13–18', '6 sloupců', 'většina nekovů, polokovy, některé kovy (Al, Sn, Pb)'],
              ['d', 'skupiny 3–12', '10 sloupců', '**přechodné kovy**: Fe, Cu, Zn, Ag, Au…'],
              ['f', 'dva řádky pod tabulkou', '14 sloupců', 'lanthanoidy a aktinoidy (vnitřně přechodné prvky)'],
            ] },
            { type: 'callout', variant: 'remember', text: 'Šířka bloků 2, 6, 10 a 14 odpovídá přesně tomu, kolik elektronů pojmou podslupky s, p, d a f. Tabulka a orbitaly do sebe zapadají!' },
            { type: 'p', text: 'Helium patří do bloku s (1s^{2}), ale v tabulce stojí nad neonem v 18. skupině, protože má stejně zaplněnou valenční vrstvu a chová se jako vzácný plyn.' },
            { type: 'check', question: { kind: 'choice', q: 'Do kterého bloku patří železo ([Ar] 4s^{2} 3d^{6})?', options: ['d', 's', 'p', 'f'], answer: 0, explain: 'Poslední elektrony železa přibývají do podslupky 3d, proto je v bloku d mezi přechodnými kovy.' } },
          ],
        },
        {
          title: 'Kovy, nekovy a polokovy',
          blocks: [
            { type: 'p', text: 'Asi čtyři pětiny prvků jsou **kovy**. Leží vlevo a uprostřed tabulky. **Nekovy** jsou vpravo nahoře (plus vodík). Mezi nimi vede „schodovitá“ hranice, podél níž leží **polokovy**.' },
            { type: 'diagram', id: 'periodic-mini', props: { highlight: 'metals' }, caption: 'Kovy, polokovy a nekovy' },
            { type: 'table', headers: ['Vlastnost', 'Kovy', 'Nekovy'], rows: [
              ['vzhled', 'kovový lesk', 'bez lesku, často barevné'],
              ['vodivost', 'dobře vedou teplo a elektřinu', 'většinou nevodí (izolanty)'],
              ['mechanické', 'kujné, tažné', 'pevné nekovy jsou křehké'],
              ['skupenství (25 °C)', 'pevné, kromě rtuti', 'plyny, pevné látky, brom je kapalina'],
              ['ionty', 'tvoří kationty', 'tvoří anionty'],
            ] },
            { type: 'elements', symbols: ['B', 'Si', 'Ge', 'As', 'Sb', 'Te'], caption: 'Polokovy: vlastnosti mají na pomezí kovů a nekovů' },
            { type: 'callout', variant: 'fact', title: 'Křemík v kapse', text: 'Polokov křemík je **polovodič**: elektřinu vede jen za určitých podmínek. Právě proto z něj vyrábíme čipy do mobilů a počítačů. Údolí firem v Kalifornii se podle něj jmenuje Silicon Valley.' },
            { type: 'callout', variant: 'mascot', text: 'Gallium taje při 29,8 °C, takže by ti roztálo v dlani. Kov, který se chová jako čokoláda! (Radši to ale nezkoušej, gallium zanechává na kůži šedé skvrny a patří do laboratoře.)' },
            { type: 'check', question: { kind: 'multi', q: 'Které z prvků jsou **polokovy**?', options: ['křemík', 'bor', 'hliník', 'arsen', 'síra'], answers: [0, 1, 3], explain: 'Bor, křemík a arsen leží na schodovité hranici mezi kovy a nekovy. Hliník je kov a síra nekov.' } },
          ],
        },
        {
          title: 'Trendy v tabulce',
          blocks: [
            { type: 'p', text: 'Poloha prvku v tabulce prozradí, jak velký je jeho atom a jak snadno ztrácí nebo přitahuje elektrony. Stačí pochopit dva jednoduché důvody.' },
            { type: 'list', items: [
              '**V periodě zleva doprava** přibývají protony v jádře, ale elektrony jdou pořád do stejné vrstvy. Jádro je přitahuje silněji, atom se zmenšuje.',
              '**Ve skupině shora dolů** přibývají elektronové vrstvy. Valenční elektrony jsou dál od jádra a jsou stíněné vnitřními vrstvami, atom se zvětšuje.',
            ] },
            { type: 'keyterms', items: [
              { term: '**Atomový poloměr**', def: 'velikost atomu; v periodě klesá, ve skupině roste.' },
              { term: '**Ionizační energie**', def: 'energie na odtržení elektronu (znáš z lekce o vrstvách); v periodě roste, ve skupině klesá.' },
              { term: '**Elektronegativita**', def: '(anglicky *electronegativity*) schopnost atomu přitahovat elektrony ve vazbě; v periodě roste, ve skupině klesá. Nejvyšší má fluor (3,98). Podrobně v úrovni 3.' },
              { term: '**Kovový charakter**', def: 'jak snadno atom ztrácí elektrony a chová se jako kov; roste doleva a dolů.' },
            ] },
            { type: 'diagram', id: 'periodic-mini', props: { highlight: 'trends' }, caption: 'Směry, kterými rostou jednotlivé vlastnosti' },
            { type: 'table', headers: ['Prvek', 'Li', 'Na', 'K'], rows: [
              ['atomový poloměr (pm)', '152', '186', '227'],
              ['1. ionizační energie (kJ/mol)', '520', '496', '419'],
              ['elektronegativita', '0,98', '0,93', '0,82'],
            ], caption: 'Alkalické kovy shora dolů: atom roste, elektron se odtrhne snáz' },
            { type: 'callout', variant: 'tip', title: 'Směr k fluoru', text: 'Ionizační energie i elektronegativita rostou **směrem k fluoru** (vpravo nahoru). Atomový poloměr a kovový charakter rostou opačně, **směrem k franciu** (vlevo dolů). Vzácné plyny v trendech elektronegativity obvykle vynecháváme.' },
            { type: 'check', question: { kind: 'choice', q: 'Který z atomů má **největší** atomový poloměr?', options: ['K', 'Na', 'Mg', 'Cl'], answer: 0, explain: 'Draslík má nejvíc vrstev (4. perioda) a leží úplně vlevo. Na, Mg a Cl jsou ve 3. periodě a poloměr v ní zleva doprava klesá.' } },
          ],
        },
        {
          title: 'Předpovídáme vlastnosti podle polohy',
          blocks: [
            { type: 'p', text: 'Síla periodické tabulky je v tom, že z polohy prvku odhadneš jeho vlastnosti, i když jsi o něm nikdy neslyšel. Přesně tak to dělal Mendělejev.' },
            { type: 'example', title: 'Rubidium', problem: 'Rubidium (Rb) leží v 1. skupině a 5. periodě. Co o něm můžeš říct?', steps: [
              '1. skupina -> alkalický kov, 1 valenční elektron (5s^{1}).',
              'Snadno ho odevzdá -> tvoří kation $Rb^+$.',
              '5. perioda, pod draslíkem -> větší atom, nižší ionizační energie, ještě reaktivnější než draslík.',
            ], answer: 'Rb je měkký, velmi reaktivní kov, tvoří $Rb^+$ a s vodou reaguje prudčeji než K.' },
            { type: 'example', title: 'Selen', problem: 'Selen (Se) leží v 16. skupině a 4. periodě. Odhadni jeho vlastnosti.', steps: [
              '16. skupina -> chalkogen, 6 valenčních elektronů: [Ar] 4s^{2} 3d^{10} 4p^{4}.',
              'Do oktetu chybějí 2 elektrony -> tvoří anion $Se^2-$, stejně jako síra $S^2-$.',
              'Stojí pod sírou -> nekov, podobný síře, s o něco větším atomem.',
            ], answer: 'Se je nekov podobný síře, tvoří anion $Se^2-$.' },
            { type: 'callout', variant: 'warning', title: 'Bezpečnost', text: 'Alkalické kovy prudce reagují s vodou a vzniká přitom hořlavý vodík. Uchovávají se pod petrolejem a pokusy s nimi se dělají jen s ochrannými brýlemi, za ochranným štítem a v malém množství. Víc o jejich chemii v úrovni 7.' },
            { type: 'check', question: { kind: 'text', q: 'Který prvek leží ve 3. periodě a 2. skupině? Napiš jeho značku.', accept: ['Mg'], caseSensitive: true, placeholder: 'značka', explain: 'Hořčík $Mg$: tři vrstvy (2, 8, 2) a dva valenční elektrony.' } },
          ],
        },
      ],
      summary: [
        'Periodický zákon: vlastnosti prvků se periodicky opakují v závislosti na protonovém čísle.',
        'Perioda (řádek) udává počet vrstev, skupina (sloupec) u hlavních skupin počet valenčních elektronů.',
        'Skupina 1 jsou alkalické kovy, 2 kovy alkalických zemin, 16 chalkogeny, 17 halogeny a 18 vzácné plyny.',
        'Tabulka se dělí na bloky s, p, d, f podle podslupky, do které přibývá poslední elektron.',
        'Kovy jsou vlevo a uprostřed, nekovy vpravo nahoře, polokovy (B, Si, Ge, As, Sb, Te) na hranici.',
        'Atomový poloměr a kovový charakter rostou doleva dolů, ionizační energie a elektronegativita doprava nahoru.',
      ],
      quiz: [
        { kind: 'match', q: 'Přiřaď skupinu k jejímu názvu.', pairs: [['1. skupina', 'alkalické kovy'], ['2. skupina', 'kovy alkalických zemin'], ['16. skupina', 'chalkogeny'], ['17. skupina', 'halogeny'], ['18. skupina', 'vzácné plyny']], explain: 'Tyto názvy se používají běžně, vyplatí se je umět nazpaměť.' },
        { kind: 'tf', q: 'Atomový poloměr v periodě zleva doprava roste.', answer: false, explain: 'Klesá. Protonů přibývá, elektrony jdou do stejné vrstvy a silnější jádro je přitáhne blíž.' },
        { kind: 'choice', q: 'Který prvek leží ve 4. periodě a 17. skupině?', options: ['brom', 'chlor', 'jod', 'krypton'], answer: 0, explain: 'Halogeny jsou F (2. perioda), Cl (3.), Br (4.) a I (5.). Krypton je ve 4. periodě, ale v 18. skupině.' },
        { kind: 'multi', q: 'Které prvky patří do bloku d?', options: ['Fe', 'Cu', 'Zn', 'Ca', 'Al'], answers: [0, 1, 2], explain: 'Železo, měď a zinek jsou přechodné kovy (skupiny 3–12). Vápník patří do bloku s, hliník do bloku p.' },
        { kind: 'order', q: 'Seřaď prvky podle elektronegativity od nejmenší.', items: ['Na', 'Al', 'S', 'Cl', 'F'], explain: 'Elektronegativita roste směrem k fluoru: Na 0,93, Al 1,61, S 2,58, Cl 3,16, F 3,98.' },
        { kind: 'number', q: 'Prvek má konfiguraci [Ne] 3s^{2} 3p^{5}. Ve které skupině (číslování 1–18) leží?', answer: 17, tolerance: 0, explain: '7 valenčních elektronů v bloku p znamená VII.A, tedy 17. skupinu. Je to chlor.' },
        { kind: 'choice', q: 'Co můžeš předpovědět o cesiu (Cs, 1. skupina, 6. perioda)?', options: ['Je to velmi reaktivní kov, který snadno tvoří kation $Cs^+$.', 'Je to nereaktivní plyn.', 'Je to nekov, který tvoří anion $Cs^-$.', 'Je to polokov používaný v čipech.'], answer: 0, explain: 'Cesium je alkalický kov s jedním valenčním elektronem daleko od jádra. Má velmi nízkou ionizační energii a patří k nejreaktivnějším kovům.' },
        { kind: 'tf', q: 'Křemík patří mezi polokovy a používá se jako polovodič v čipech.', answer: true, explain: 'Křemík leží na hranici kovů a nekovů a jeho polovodivost je základem elektroniky.' },
      ],
    },
  },

  boss: [
    { kind: 'number', q: 'Kolik elektronů a neutronů **dohromady** má ion $^{81}_{35}Br^-$?', answer: 82, tolerance: 0, explain: 'Elektrony: 35 + 1 = 36. Neutrony: 81 − 35 = 46. Dohromady 36 + 46 = 82.' },
    { kind: 'number', q: 'Přírodní chlor má $A_{r}$ = 35,5 a skládá se jen z izotopů $^{35}Cl$ a $^{37}Cl$. Kolik procent tvoří izotop $^{35}Cl$? (Počítej s nukleonovými čísly.)', answer: 75, tolerance: 0.5, unit: '%', explain: 'Označ podíl $^{35}Cl$ jako x: 35x + 37(1 − x) = 35,5, tedy 37 − 2x = 35,5 a x = 0,75, čili 75 %.' },
    { kind: 'choice', q: 'Která částice má 16 protonů, 16 neutronů a 18 elektronů?', options: ['$^{32}_{16}S^2-$', '$^{32}_{16}S$', '$^{34}_{16}S^2-$', '$^{34}_{18}Ar$'], answer: 0, explain: '16 protonů je síra, 16 + 16 = 32 nukleonů a 18 elektronů znamená o dva víc než protonů, tedy náboj 2−.' },
    { kind: 'tf', q: 'Ion $Fe^{3+}$ má elektronovou konfiguraci [Ar] 3d^{5}.', answer: true, explain: 'Fe je [Ar] 4s^{2} 3d^{6}. Kation ztrácí nejdřív oba elektrony 4s a pak jeden z 3d, zbude [Ar] 3d^{5}.' },
    { kind: 'choice', q: 'Který prvek má konfiguraci [Ar] 4s^{1} 3d^{10}?', options: ['Cu', 'K', 'Zn', 'Ga'], answer: 0, explain: 'Je to 18 + 1 + 10 = 29 elektronů, tedy měď, známá výjimka z výstavbového principu.' },
    { kind: 'multi', q: 'Které částice mají stejný počet elektronů jako atom argonu?', options: ['$S^2-$', '$K^+$', '$Ca^{2+}$', '$Na^+$', '$F^-$'], answers: [0, 1, 2], explain: 'Argon má 18 elektronů. $S^2-$ (16 + 2), $K^+$ (19 − 1) a $Ca^{2+}$ (20 − 2) mají také 18. $Na^+$ a $F^-$ mají 10.' },
    { kind: 'order', q: 'Seřaď atomy podle atomového poloměru od nejmenšího.', items: ['F', 'Cl', 'Na', 'K'], explain: 'F je nahoře vpravo, Cl pod ním má o vrstvu víc. Na je ve stejné periodě jako Cl, ale úplně vlevo, takže je větší. K má o vrstvu víc než Na.' },
    { kind: 'number', q: 'Kolik procent původního množství uhlíku-14 zbude ve vzorku po 22 920 letech? (Poločas přeměny je 5 730 let.)', answer: 6.25, tolerance: 0.1, unit: '%', explain: '22 920 : 5 730 = 4 poločasy. Zbude (1/2)^{4} = 1/16, tedy 6,25 %.' },
    { kind: 'match', q: 'Přiřaď elektronovou konfiguraci k prvku.', pairs: [['[He] 2s^{2} 2p^{4}', 'O'], ['[Ne] 3s^{2}', 'Mg'], ['[Ne] 3s^{2} 3p^{5}', 'Cl'], ['[Ar] 4s^{1}', 'K'], ['[Ar] 4s^{1} 3d^{5}', 'Cr']], explain: 'Sečti elektrony: O 8, Mg 12, Cl 17, K 19, Cr 24. Chrom je výjimka s napůl zaplněnou podslupkou 3d.' },
    { kind: 'choice', q: 'Uran-238 ($^{238}_{92}U$) vyzáří částici α. Jaké jádro vznikne?', options: ['$^{234}_{90}Th$', '$^{238}_{93}Np$', '$^{234}_{92}U$', '$^{236}_{90}Th$'], answer: 0, explain: 'Částice α je jádro helia $^{4}_{2}He$: nukleonové číslo klesne o 4 (238 -> 234) a protonové o 2 (92 -> 90), a $Z = 90$ je thorium.' },
    { kind: 'text', q: 'Kdo jsem? Mám tři elektronové vrstvy a čtyři valenční elektrony, jsem polokov a vyrábějí se ze mě čipy. Napiš mou značku.', accept: ['Si'], caseSensitive: true, placeholder: 'značka', explain: 'Tři vrstvy = 3. perioda, 4 valenční elektrony = 14. skupina. To je křemík: 2, 8, 4.' },
    { kind: 'tf', q: 'Atom chloru má menší první ionizační energii než atom sodíku.', answer: false, explain: 'Je to naopak. Ve 3. periodě ionizační energie zleva doprava roste, chlor drží své elektrony mnohem pevněji než sodík.' },
  ],
}

export default level
