import type { Lesson } from '../../../core/types'

/** Level 6, second half: kinetics and equilibria (l6-4, l6-5, l6-6). Spread into ./l6.ts. */
export const lessonsB: Record<string, Lesson> = {
    // ───────────────────────────────────────────────────────────── l6-4
    'l6-4': {
      id: 'l6-4',
      title: 'Rychlost reakce, rychlostní rovnice a katalýza',
      goals: [
        'Definovat rychlost reakce, popsat, jak se měří, a spočítat ji ze změny koncentrace',
        'Srážkovou teorií a Maxwellovým–Boltzmannovým rozdělením zdůvodnit vliv koncentrace, teploty, povrchu a katalyzátoru',
        'Z tabulky počátečních rychlostí určit řády reakce, rychlostní rovnici, rychlostní konstantu k a její jednotku',
        'Spočítat poločas reakce 1. řádu a vysvětlit rychlost určující krok a Arrheniovu rovnici',
      ],
      hook: 'Benzín v nádrži s kyslíkem ze vzduchu sám od sebe nehoří, i když by to energeticky šlo. Stačí ale jiskra, a je hotovo. Proč některé reakce trvají roky a jiné zlomek sekundy?',
      sections: [
        {
          title: 'Co je rychlost reakce a jak ji měřit',
          icon: 'stopwatch',
          blocks: [
            { type: 'p', text: '**Rychlost reakce** v udává, jak rychle ubývá reaktantů nebo přibývá produktů. Měříme ji jako změnu koncentrace za jednotku času.' },
            { type: 'formula', text: 'v = − Δc(reaktant) / Δt = Δc(produkt) / Δt', caption: 'jednotka mol·dm^{−3}·s^{−1}; minus u reaktantu proto, že jeho koncentrace klesá' },
            { type: 'diagram', id: 'rate-curve', caption: 'Koncentrace reaktantu klesá nejdřív rychle, pak čím dál pomaleji. Rychlost je strmost křivky a s časem se zmenšuje.' },
            { type: 'particles', boxes: [
              { label: 'na začátku', items: [{ species: 'H2O2', count: 8 }], state: 'solution' },
              { label: 'o chvíli později', items: [{ species: 'H2O2', count: 4 }, { species: 'H2O', count: 4 }, { species: 'O2', count: 2 }], state: 'solution' },
            ], arrows: true, caption: 'Rozklad $2H2O2 -> 2H2O + O2$: reaktantu ubývá, jeho částice se srážejí méně často a reakce zpomaluje.' },
            { type: 'example', title: 'Rozklad peroxidu vodíku', problem: 'Koncentrace $H2O2$ klesla za 60 s z 0,80 mol/dm³ na 0,50 mol/dm³. Jaká byla průměrná rychlost rozkladu?', steps: [
              'Δc = 0,50 − 0,80 = −0,30 mol/dm³',
              'v = −Δc / Δt = 0,30 mol/dm³ / 60 s',
              'v = 0,0050 mol·dm^{−3}·s^{−1}',
            ], answer: 'Průměrná rychlost byla 0,0050 mol·dm^{−3}·s^{−1} (5,0·10^{−3} mol·dm^{−3}·s^{−1}).' },
            { type: 'p', text: 'Koncentraci přímo „vidět“ nejde. V praxi proto sleduješ v čase veličinu, která se s ní mění:' },
            { type: 'iconlist', items: [
              { icon: 'balloon', title: 'Objem plynu', text: 'plynová injekční stříkačka zachytí vznikající $O2$, $H2$ nebo $CO2$' },
              { icon: 'balance-scale', title: 'Úbytek hmotnosti', text: 'unikající plyn odlehčí baňku na vahách' },
              { icon: 'test-tube', title: 'Změna barvy', text: 'kolorimetr měří, jak rychle roztok bledne nebo tmavne' },
              { icon: 'plug', title: 'Vodivost a pH', text: 'mění se, když ubývá nebo přibývá iontů' },
              { icon: 'burette', title: 'Odběr vzorků a titrace', text: 'vzorek se ochladí nebo zředí, aby se reakce „zastavila“, a pak se ztitruje' },
            ] },
            { type: 'callout', variant: 'tip', title: 'Počáteční rychlost', text: 'Nejspolehlivější údaj je **počáteční rychlost** v_{0}: strmost tečny ke křivce v čase t = 0. Na začátku přesně znáš koncentrace a produkty ještě nepřekážejí. Z počátečních rychlostí se určují rychlostní rovnice, uvidíš dále.' },
            { type: 'check', question: { kind: 'number', q: 'Koncentrace produktu vzrostla za 30 s z 0 na 0,12 mol/dm³. Jaká byla průměrná rychlost jeho vzniku?', answer: 0.004, tolerance: 0.0002, unit: 'mol·dm⁻³·s⁻¹', explain: 'v = Δc / Δt = 0,12 mol/dm³ / 30 s = 0,004 mol·dm^{−3}·s^{−1}.' } },
          ],
        },
        {
          title: 'Srážková teorie a aktivační energie',
          icon: 'explosion',
          blocks: [
            { type: 'p', text: 'Aby molekuly zreagovaly, musí se srazit. Většina srážek je ale neúčinná: molekuly se od sebe jen odrazí.' },
            { type: 'compare', columns: [
              { title: '**Účinná srážka**', icon: 'check', tone: 'good', points: ['částice mají dost energie, alespoň tolik, kolik je **aktivační energie** E_{a}', 'srazí se ve **správné orientaci**, tou částí molekuly, kde vzniká nová vazba', 'vznikne aktivovaný komplex, pak produkty'] },
              { title: 'Neúčinná srážka', icon: 'cross', tone: 'bad', points: ['energie je menší než E_{a}', 'nebo se částice potkají špatnou stranou', 'molekuly se jen odrazí'] },
            ], caption: 'Účinná srážka musí splnit obě podmínky najednou.' },
            { type: 'keyterms', items: [
              { term: '**Aktivační energie** E_{a}', def: 'nejmenší energie, kterou musí srážející se částice mít, aby reakce proběhla. Je to „kopec“, přes který se musí dostat.' },
              { term: '**Aktivovaný komplex**', def: 'nestálé uskupení atomů na vrcholu energetického kopce: staré vazby se trhají, nové vznikají.' },
            ] },
            { type: 'diagram', id: 'energy-profile', props: { kind: 'exo' }, caption: 'I exotermní reakce musí nejdřív vyšplhat přes aktivační energii. Teprve pak „sjede“ dolů a teplo uvolní.' },
            { type: 'p', text: 'Z lekce o Gibbsově energii víš, že hoření benzínu je samovolné (ΔG < 0). Termodynamika ale říká jen, **jestli** reakce může proběhnout. **Jak rychle**, určuje kinetika a hlavně výška E_{a}. Benzín je proto kineticky stálý.' },
            { type: 'callout', variant: 'mascot', text: 'Sirka taky nehoří sama od sebe. Škrtnutím jí dodáš aktivační energii, a pak už teplo z hoření zapaluje další a další molekuly.' },
            { type: 'callout', variant: 'remember', text: '==Čím menší aktivační energie, tím víc srážek je účinných a tím rychleji reakce běží.== Na velikosti ΔH rychlost přímo nezávisí.' },
            { type: 'check', question: { kind: 'choice', q: 'Proč směs benzínových par a vzduchu při pokojové teplotě sama nevzplane, přestože hoření je silně exotermní?', options: ['aktivační energie je vysoká a při pokojové teplotě ji má jen nepatrný podíl molekul', 'reakce je ve skutečnosti endotermní', 'kyslík se s benzínem nemůže srazit', 'produkty hoření mají vyšší energii než reaktanty'], answer: 0, explain: 'Exotermnost (ΔH) říká, kolik energie se uvolní, ne jak rychle. Rychlost brzdí vysoká aktivační energie, kterou dodá až jiskra.' } },
          ],
        },
        {
          title: 'Co reakci zrychlí',
          icon: 'speed',
          blocks: [
            { type: 'iconlist', items: [
              { icon: 'gas-cloud', title: 'Vyšší **koncentrace** (u plynů tlak)', text: 'víc částic v objemu, častější srážky. Doutnající tříska v čistém kyslíku vzplane.' },
              { icon: 'thermometer', title: 'Vyšší **teplota**', text: 'částice jsou rychlejší a mnohem víc jich má energii ≥ E_{a}. V lednici se jídlo kazí pomaleji.' },
              { icon: 'powder', title: 'Větší **povrch** (rozmělnění)', text: 'víc částic je „na ráně“ ke srážce. Moučný prach vybuchuje, pytel mouky ne.' },
              { icon: 'catalyst', title: '**Katalyzátor**', text: 'otevře cestu s nižší aktivační energií. Katalyzátor ve výfuku, enzymy.' },
              { icon: 'periodic-table', title: '**Povaha látek**', text: 'různě pevné vazby, různé E_{a}. Sodík s vodou reaguje bouřlivě, železo pomalu.' },
            ] },
            { type: 'particles', boxes: [
              { label: 'zředěná kyselina', items: [{ species: 'H3O+', count: 3 }, { species: 'H2O', count: 9 }], state: 'solution', note: 'málo srážek' },
              { label: 'koncentrovaná kyselina', items: [{ species: 'H3O+', count: 9 }, { species: 'H2O', count: 6 }], state: 'solution', note: 'víc srážek za sekundu' },
            ], caption: 'Víc částic v témže objemu = častější srážky = rychlejší reakce.' },
            { type: 'diagram', id: 'maxwell-boltzmann', caption: 'Maxwellovo–Boltzmannovo rozdělení energií molekul: při vyšší teplotě se křivka zploští a posune doprava a mnohem víc molekul má energii alespoň E_{a}. Plocha pod křivkou (počet molekul) zůstává stejná.' },
            { type: 'p', text: 'Nejsilněji působí teplota. Pro mnoho reakcí kolem pokojové teploty platí **van ’t Hoffovo pravidlo**:' },
            { type: 'formula', text: 'zvýšení teploty o 10 °C -> rychlost vzroste 2× až 4×', caption: 'při ohřátí o n × 10 °C vzroste rychlost γ^{n}krát, kde γ je 2 až 4' },
            { type: 'example', title: 'Kuře v lednici a na stole', problem: 'Reakce, které kazí maso, zrychlí při zvýšení teploty o 10 °C asi dvakrát. Kolikrát rychleji se kazí maso na stole (25 °C) než v lednici (5 °C)?', steps: [
              'Rozdíl teplot: 25 °C − 5 °C = 20 °C, to jsou dva desetistupňové kroky.',
              'Každý krok rychlost zdvojnásobí: 2 · 2 = 2^{2} = 4.',
            ], answer: 'Na stole se maso kazí asi čtyřikrát rychleji.' },
            { type: 'callout', variant: 'warning', title: 'Prachové výbuchy', text: 'Jemný prach mouky, cukru, uhlí nebo dřeva rozvířený ve vzduchu má obrovský povrch. Jiskra v mlýně nebo v dole může způsobit ničivý výbuch. Proto se v těchto provozech přísně hlídá prach i zdroje jisker.' },
            { type: 'game', gameId: 'quickfire', text: 'Teplota, povrch, nebo katalyzátor? V bleskové výzvě si otestuj, jak rychle poznáš, co reakci zrychlí.' },
            { type: 'check', question: { kind: 'number', q: 'Reakce zrychlí při ohřátí o 10 °C třikrát. Kolikrát se zrychlí při ohřátí z 20 °C na 40 °C?', answer: 9, tolerance: 0, unit: '×', explain: 'Dva desetistupňové kroky: 3 · 3 = 3^{2} = 9.' } },
          ],
        },
        {
          title: 'Katalyzátory a enzymy',
          icon: 'catalyst',
          blocks: [
            { type: 'p', text: '**Katalyzátor** je látka, která reakci zrychlí, ale sama se v ní trvale nespotřebuje. Otevře jinou reakční cestu s **nižší aktivační energií**.' },
            { type: 'diagram', id: 'energy-profile', props: { kind: 'exo', catalyst: true }, caption: 'Katalyzovaná cesta (nižší kopec) má menší aktivační energii. Počáteční i konečný stav, a tedy i ΔH, zůstávají stejné.' },
            { type: 'compare', columns: [
              { title: 'Bez katalyzátoru', icon: 'mountain', tone: 'b', points: ['vysoký kopec E_{a}', 'málo účinných srážek', 'reakce běží pomalu'] },
              { title: 'S katalyzátorem', icon: 'catalyst', tone: 'good', points: ['jiná cesta s nižší E_{a}', 'zrychlí přímou i zpětnou reakci', '**nemění ΔH** ani výtěžek v rovnováze (víc v další lekci)', 'sám se nespotřebuje'] },
            ] },
            { type: 'iconlist', items: [
              { icon: 'flask', title: '**Homogenní katalýza**', text: 'katalyzátor je ve stejné fázi jako reaktanty, např. kyselina v roztoku při esterifikaci' },
              { icon: 'factory', title: '**Heterogenní katalýza**', text: 'pevný katalyzátor, reakce běží na jeho povrchu: platina ve výfuku, železo při výrobě amoniaku' },
              { icon: 'enzyme', title: '**Enzymy**', text: 'bílkovinné katalyzátory v živých organismech, nesmírně účinné a specifické' },
              { icon: 'bread', title: '**Inhibitor**', text: 'reakci naopak zpomaluje, například konzervační látky v potravinách' },
            ] },
            { type: 'p', text: '**Katalyzátor ve výfuku** je keramická voštinka potažená platinou, palladiem a rhodiem. Za provozní teploty (asi od 300 °C) mění jedovaté plyny na neškodné.' },
            { type: 'reaction', equation: '2CO + 2NO -> 2CO2 + N2', caption: 'Trojcestný katalyzátor odstraňuje $CO$ ($2CO + O2 -> 2CO2$), oxidy dusíku i nespálené uhlovodíky.' },
            { type: 'callout', variant: 'fact', text: 'Olovo ze starého benzínu povrch katalyzátoru „otráví“ a zablokuje. I proto se olovnatý benzín přestal prodávat, u nás v roce 2001.' },
            { type: 'reaction', equation: '2H2O2 -> 2H2O + O2', caption: 'Enzym katalasa v játrech nebo v bramboře rozkládá peroxid vodíku. Proto rána po nalití peroxidu pění.' },
            { type: 'callout', variant: 'warning', text: 'Enzymy nejlépe pracují kolem 37 °C. Při vysoké teplotě se bílkovina nevratně poškodí (denaturuje) a enzym přestane fungovat. Proto je velmi vysoká horečka nebezpečná.' },
            { type: 'check', question: { kind: 'multi', q: 'Co katalyzátor dělá?', options: ['snižuje aktivační energii', 'zrychluje přímou i zpětnou reakci', 'mění reakční entalpii ΔH', 'se v reakci trvale spotřebovává', 'otevírá jinou reakční cestu'], answers: [0, 1, 4], explain: 'Katalyzátor otevře cestu s nižší E_{a}, a tak zrychlí obě směry reakce. ΔH nemění a na konci zůstane nespotřebovaný.' } },
          ],
        },
        {
          title: 'Rychlostní rovnice a řád reakce',
          icon: 'chart',
          blocks: [
            { type: 'p', text: 'Jak přesně závisí rychlost na koncentracích, popisuje **rychlostní (kinetická) rovnice**. Pro reakci látek A a B má tvar:' },
            { type: 'formula', text: 'v = k · $[A]^{m}$ · $[B]^{n}$', caption: 'k – rychlostní konstanta, m a n – dílčí řády reakce, m + n – celkový řád' },
            { type: 'keyterms', items: [
              { term: '**Rychlostní konstanta** k', def: 'číslo charakteristické pro reakci; nezávisí na koncentracích, ale roste s teplotou a s přítomností katalyzátoru.' },
              { term: '**Dílčí řád reakce**', def: 'exponent u koncentrace dané látky v rychlostní rovnici, obvykle 0, 1 nebo 2.' },
              { term: '**Celkový řád**', def: 'součet všech dílčích řádů, tady m + n.' },
            ] },
            { type: 'compare', columns: [
              { title: '0. řád: v = k', icon: 'stopwatch', tone: 'c', points: ['dvojnásobná koncentrace', '-> rychlost se **nezmění** (2^{0} = 1)'] },
              { title: '1. řád: v = k · $[A]$', icon: 'speed', tone: 'a', points: ['dvojnásobná koncentrace', '-> **dvojnásobná** rychlost (2^{1} = 2)'] },
              { title: '2. řád: v = k · $[A]^2$', icon: 'explosion', tone: 'b', points: ['dvojnásobná koncentrace', '-> **čtyřnásobná** rychlost (2^{2} = 4)'] },
            ] },
            { type: 'diagram', id: 'reaction-orders', caption: 'Závislost rychlosti na koncentraci A: u 0. řádu vodorovná přímka, u 1. řádu přímka z počátku, u 2. řádu parabola. Vpravo úbytek látky při reakci 1. řádu: za každý poločas ubude polovina.' },
            { type: 'callout', variant: 'warning', title: 'Řád se zjišťuje pokusem', text: 'Řády reakce **nemusí** odpovídat koeficientům v rovnici. Rozklad $2N2O5 -> 4NO2 + O2$ je prvního řádu: v = k · $[N2O5]$, i když v rovnici stojí dvojka.' },
            { type: 'p', text: '**Metoda počátečních rychlostí:** provedeš několik pokusů a pokaždé změníš koncentraci **jen jedné** látky. Z toho, kolikrát se změní počáteční rychlost, vyčteš její řád.' },
            { type: 'table', headers: ['Pokus', '$[A]$ / mol·dm^{−3}', '$[B]$ / mol·dm^{−3}', 'v_{0} / mol·dm^{−3}·s^{−1}'], rows: [
              ['1', '0,10', '0,10', '2,0·10^{−4}'],
              ['2', '0,20', '0,10', '8,0·10^{−4}'],
              ['3', '0,10', '0,20', '4,0·10^{−4}'],
            ], caption: 'Naměřené počáteční rychlosti reakce A + B -> produkty' },
            { type: 'example', title: 'Řád reakce z počátečních rychlostí', problem: 'Z tabulky urči řády vzhledem k A a B, rychlostní rovnici a konstantu k i s jednotkou.', steps: [
              'Pokus 1 -> 2: $[A]$ se zdvojnásobí, $[B]$ stejná, rychlost vzroste 4× = 2^{2}. Řád vzhledem k A je 2.',
              'Pokus 1 -> 3: $[B]$ se zdvojnásobí, rychlost vzroste 2× = 2^{1}. Řád vzhledem k B je 1.',
              'Rychlostní rovnice: v = k · $[A]^2$ · $[B]$, celkový řád 2 + 1 = 3.',
              'Z pokusu 1: k = v / ($[A]^2$ · $[B]$) = 2,0·10^{−4} / (0,10^{2} · 0,10) = 2,0·10^{−4} / 1,0·10^{−3} = 0,20',
              'Jednotka: (mol·dm^{−3}·s^{−1}) / (mol·dm^{−3})^{3} = dm^{6}·mol^{−2}·s^{−1}',
              'Kontrola: při $[A]$ = $[B]$ = 0,20 mol/dm³ by mělo být v = 0,20 · 0,20^{2} · 0,20 = 1,6·10^{−3}, tedy 2^{2} · 2 = 8× víc než v pokusu 1.',
            ], answer: 'v = 0,20 dm^{6}·mol^{−2}·s^{−1} · $[A]^2$ · $[B]$; 2. řád vzhledem k A, 1. řád vzhledem k B.' },
            { type: 'table', headers: ['Celkový řád', 'Rychlostní rovnice', 'Jednotka k'], rows: [
              ['0', 'v = k', 'mol·dm^{−3}·s^{−1}'],
              ['1', 'v = k · $[A]$', 's^{−1}'],
              ['2', 'v = k · $[A]^2$ nebo k · $[A]$ · $[B]$', 'dm^{3}·mol^{−1}·s^{−1}'],
              ['3', 'v = k · $[A]^2$ · $[B]$', 'dm^{6}·mol^{−2}·s^{−1}'],
            ], caption: 'Jednotku k vždy odvodíš tak, aby v vyšla v mol·dm^{−3}·s^{−1}.' },
            { type: 'callout', variant: 'fact', title: 'Nultý řád v tvém těle', text: 'Játra odbourávají alkohol přibližně stálou rychlostí, asi 0,1 g na kilogram hmotnosti za hodinu. Enzym je „přetížený“, a tak je rychlost na koncentraci alkoholu v krvi skoro nezávislá: reakce nultého řádu. Proto vystřízlivění nejde urychlit.' },
            { type: 'check', question: { kind: 'number', q: 'Rychlostní rovnice je v = k · $[A]^2$ · $[B]$. Kolikrát se změní rychlost, když koncentraci A zdvojnásobíš a koncentraci B snížíš na polovinu?', answer: 2, tolerance: 0, unit: '×', explain: 'Faktor pro A: 2^{2} = 4, faktor pro B: 0,5. Celkem 4 · 0,5 = 2, reakce se zrychlí dvakrát.' } },
          ],
        },
        {
          title: 'Poločas, mechanismus a Arrheniova rovnice',
          icon: 'stopwatch',
          blocks: [
            { type: 'p', text: '**Poločas reakce** t_{1/2} je doba, za kterou klesne koncentrace reaktantu na polovinu. U reakce **1. řádu** je stálý: nezávisí na tom, kolik látky zrovna máš.' },
            { type: 'formula', text: 't_{1/2} = ln 2 / k ≈ 0,693 / k', caption: 'platí pro reakci 1. řádu; k v s^{−1} dá poločas v sekundách' },
            { type: 'example', title: 'Poločas rozkladu', problem: 'Rozklad látky A je reakcí 1. řádu s k = 1,5·10^{−3} s^{−1}. Urči poločas. Za jak dlouho klesne $[A]$ z 0,80 na 0,10 mol/dm³?', steps: [
              't_{1/2} = 0,693 / 1,5·10^{−3} s^{−1} = 462 s ≈ 7,7 min',
              '0,80 -> 0,40 -> 0,20 -> 0,10 mol/dm³: to jsou 3 poločasy (0,80 / 2^{3} = 0,10).',
              't = 3 · 462 s = 1 386 s',
            ], answer: 'Poločas je asi 7,7 min; na 0,10 mol/dm³ klesne koncentrace za 1 386 s, tedy asi 23 min.' },
            { type: 'callout', variant: 'tip', text: 'Radioaktivní rozpad z úrovně 2 je také děj 1. řádu, proto tam platilo m = m_{0} / 2^{n}. Stálý poločas je poznávací znamení 1. řádu. U reakce 2. řádu se poločas s ubývající koncentrací prodlužuje.' },
            { type: 'p', text: 'Většina reakcí neproběhne jednou srážkou, ale v několika **elementárních krocích**. Jejich sled je **reakční mechanismus**. Celkovou rychlost určuje **nejpomalejší krok**, tzv. **rychlost určující krok**.' },
            { type: 'process', layout: 'flow', steps: [
              { icon: 'stopwatch', title: '1. krok (pomalý)', text: '$NO2 + NO2 -> NO3 + NO$' },
              { icon: 'speed', title: '2. krok (rychlý)', text: '$NO3 + CO -> NO2 + CO2$' },
              { icon: 'check', title: 'Součet', text: '$NO2 + CO -> NO + CO2$; meziprodukt $NO3$ se vykrátí' },
            ], caption: 'Mechanismus reakce $NO2$ s $CO$ (pod 225 °C). Jako fronta u jediné pokladny: rychlost celého nákupu určuje nejpomalejší místo.' },
            { type: 'reaction', equation: 'NO2 + CO -> NO + CO2', caption: 'Naměřená rychlostní rovnice: v = k · $[NO2]^2$. Oxid uhelnatý v ní chybí (0. řád), protože do reakce vstupuje až po pomalém kroku.' },
            { type: 'callout', variant: 'remember', text: '==V rychlostní rovnici vystupují jen látky, které se účastní rychlost určujícího kroku (nebo kroků před ním).== Podobně jodace propanonu v kyselém prostředí má v = k · $[CH3COCH3]$ · $[H^+]$ a na koncentraci jodu nezávisí.' },
            { type: 'p', text: 'Jak rychlostní konstanta závisí na teplotě, popisuje **Arrheniova rovnice**. Stačí ji chápat kvalitativně:' },
            { type: 'formula', text: 'k = A · e^{−Ea / (R·T)}', caption: 'A – frekvenční faktor (četnost a orientace srážek), Ea – aktivační energie v J/mol, R = 8,314 J·mol^{−1}·K^{−1}, T – teplota v K' },
            { type: 'list', items: [
              '**Vyšší teplota** -> exponent je méně záporný -> k roste exponenciálně, ne lineárně.',
              '**Nižší E_{a}** (katalyzátor) -> k je větší při téže teplotě.',
              'Čím **větší E_{a}**, tím citlivěji reakce na teplotu reaguje. Pro E_{a} ≈ 50 kJ/mol vychází kolem 25 °C zrychlení asi 2× na 10 °C, odtud van ’t Hoffovo pravidlo.',
              'Z měření k při několika teplotách se E_{a} určuje graficky: závislost ln k na 1/T je přímka se směrnicí −E_{a}/R.',
            ] },
            { type: 'check', question: { kind: 'number', q: 'Reakce 1. řádu má rychlostní konstantu k = 0,0231 min^{−1}. Jaký je její poločas?', answer: 30, tolerance: 0.5, unit: 'min', explain: 't_{1/2} = 0,693 / k = 0,693 / 0,0231 min^{−1} = 30 min.' } },
          ],
        },
      ],
      summary: [
        'Rychlost reakce je změna koncentrace za čas; měří se přes objem plynu, hmotnost, barvu, vodivost nebo titrací vzorků a nejlépe jako počáteční rychlost.',
        'Podle srážkové teorie reagují jen srážky s dostatečnou energií (alespoň E_{a}) a správnou orientací; Maxwellovo–Boltzmannovo rozdělení ukazuje, proč teplota působí tak silně.',
        'Reakci zrychlí vyšší koncentrace, vyšší teplota (asi 2–4× na každých 10 °C), větší povrch a katalyzátor, který snižuje E_{a} a nemění ΔH.',
        'Rychlostní rovnice v = k · $[A]^{m}$ · $[B]^{n}$ má řády zjištěné pokusem (metodou počátečních rychlostí), ne opsané z koeficientů.',
        'Jednotka k závisí na celkovém řádu: 1. řád s^{−1}, 2. řád dm^{3}·mol^{−1}·s^{−1}.',
        'Reakce 1. řádu má stálý poločas t_{1/2} = 0,693 / k.',
        'Celkovou rychlost určuje nejpomalejší krok mechanismu; podle Arrheniovy rovnice k exponenciálně roste s teplotou a klesá s rostoucí E_{a}.',
      ],
      quiz: [
        { kind: 'choice', q: 'Jak katalyzátor zrychluje reakci?', options: ['snižuje aktivační energii', 'zvyšuje teplotu reakční směsi', 'zvětšuje reakční entalpii', 'posouvá rovnováhu k produktům'], answer: 0, explain: 'Katalyzátor otevře reakční cestu s nižší aktivační energií, takže je víc srážek účinných.' },
        { kind: 'multi', q: 'Které změny zvýší rychlost reakce hořčíku s kyselinou chlorovodíkovou?', options: ['použít hořčíkový prášek místo pásku', 'použít koncentrovanější kyselinu', 'ohřát kyselinu', 'použít větší kádinku', 'kyselinu zředit vodou'], answers: [0, 1, 2], explain: 'Prášek zvětší povrch, koncentrovanější kyselina zvýší četnost srážek a teplo zvýší podíl částic s energií ≥ E_{a}. Větší kádinka nic nemění a ředění reakci zpomalí.' },
        { kind: 'tf', q: 'Řád reakce vzhledem k látce je vždy roven jejímu stechiometrickému koeficientu v rovnici.', answer: false, explain: 'Řády se určují pokusem. Například rozklad $2N2O5$ je prvního řádu, přestože má v rovnici koeficient 2.' },
        { kind: 'match', q: 'Přiřaď celkový řád reakce k jednotce rychlostní konstanty k.', pairs: [
          ['0. řád', 'mol·dm^{−3}·s^{−1}'],
          ['1. řád', 's^{−1}'],
          ['2. řád', 'dm^{3}·mol^{−1}·s^{−1}'],
        ], explain: 'Jednotka k musí dát rychlost v mol·dm^{−3}·s^{−1}. U 1. řádu se koncentrace vykrátí a zbude s^{−1}, u 2. řádu musí k navíc „vykrátit“ jednu koncentraci.' },
        { kind: 'number', q: 'Reakce 1. řádu má poločas 20 min. Kolik procent výchozí látky zbude po 1 hodině?', answer: 12.5, tolerance: 0.1, unit: '%', explain: 'Hodina jsou 3 poločasy: 100 % -> 50 % -> 25 % -> 12,5 %.' },
        { kind: 'choice', q: 'Reakce 2A + B -> P probíhá ve dvou krocích: A + B -> X (pomalý) a X + A -> P (rychlý). Jaká je její rychlostní rovnice?', options: ['v = k · $[A]$ · $[B]$', 'v = k · $[A]^2$ · $[B]$', 'v = k · $[X]$ · $[A]$', 'v = k · $[A]^2$'], answer: 0, explain: 'Rychlost určuje pomalý první krok, v němž se srazí jedna částice A s jednou částicí B. Druhé A vstupuje až v rychlém kroku, a proto se v rovnici neobjeví.' },
        { kind: 'tf', q: 'Podle Arrheniovy rovnice roste rychlostní konstanta s teplotou přibližně lineárně.', answer: false, explain: 'Závislost je exponenciální: k = A · e^{−Ea/(R·T)}. Proto i malé zvýšení teploty reakci výrazně zrychlí.' },
      ],
    },
    // ───────────────────────────────────────────────────────────── l6-5
    'l6-5': {
      id: 'l6-5',
      title: 'Chemická rovnováha, Le Chatelier a Kc',
      goals: [
        'Vysvětlit dynamickou rovnováhu a Le Chatelierovým principem předpovědět vliv koncentrace, tlaku, teploty a katalyzátoru',
        'Zdůvodnit podmínky výroby amoniaku a kyseliny sírové',
        'Zapsat výraz pro K_{c} i u heterogenních rovnováh a spočítat rovnovážné složení pomocí tabulky ICE',
        'Porovnáním Q a K předpovědět, kam se reakce pohne, a vysvětlit, proč K mění jen teplota',
      ],
      hook: 'Otevřeš láhev minerálky, zasyčí to a vyrazí bublinky. Zavřeš ji a bublinky přestanou. Minerálka neumí myslet, a přesto jako by „věděla“, co má dělat. Pojď poznat princip, který řídí rovnováhy od limonády až po výrobu hnojiv, a naučit se je i spočítat.',
      sections: [
        {
          title: 'Vratné reakce a dynamická rovnováha',
          icon: 'equilibrium',
          blocks: [
            { type: 'p', text: 'Mnoho reakcí může běžet oběma směry. Takové reakce jsou **vratné** a píšeme je s dvojitou šipkou. Příkladem je hnědý oxid dusičitý $NO2$, jehož molekuly se spojují po dvou na bezbarvý dimer $N2O4$ (tetraoxid didusíku).' },
            { type: 'reaction', equation: 'N2O4 <=> 2NO2', caption: 'bezbarvý $N2O4$ ⇌ hnědý $NO2$' },
            { type: 'molecule', molecules: ['NO2'], labels: ['$NO2$: lomená molekula s nepárovým elektronem, proto se ráda páruje'] },
            { type: 'p', text: 'Na začátku běží přímá reakce rychle, protože reaktantů je hodně. Jak přibývá produktů, zrychluje se zpětná reakce. Nakonec jsou obě rychlosti **stejné**.' },
            { type: 'particles', boxes: [
              { label: 'na začátku', items: [{ species: 'N2O4', count: 6 }], state: 'gas' },
              { label: 'v rovnováze', items: [{ species: 'N2O4', count: 3 }, { species: 'NO2', count: 6 }], state: 'gas', note: 'stále se rozpadají i spojují, stejně rychle' },
            ], arrows: true, caption: 'V rovnováze se počty částic už nemění, i když reakce běží dál oběma směry.' },
            { type: 'keyterms', items: [
              { term: '**Chemická rovnováha**', def: 'stav, kdy je rychlost přímé reakce rovna rychlosti zpětné reakce; koncentrace látek se nemění.' },
              { term: '**Dynamická rovnováha**', def: 'na úrovni molekul reakce běží pořád dál oběma směry, jen se jejich účinky navzájem ruší.' },
              { term: '**Poloha rovnováhy**', def: 'jestli v rovnovážné směsi převažují produkty („rovnováha vpravo“), nebo reaktanty („vlevo“).' },
            ] },
            { type: 'callout', variant: 'mascot', text: 'Představ si jezdicí schody, po kterých běžíš nahoru stejně rychle, jako jedou dolů. Stojíš pořád na stejném místě, ale rozhodně neodpočíváš. Tak vypadá dynamická rovnováha.' },
            { type: 'callout', variant: 'warning', text: 'V rovnováze nemusí být koncentrace reaktantů a produktů **stejné**. Stejné jsou jen **rychlosti** obou směrů. Koncentrace jsou pouze **stálé**.' },
            { type: 'check', question: { kind: 'tf', q: 'Když se ustaví chemická rovnováha, reakce se zastaví.', answer: false, explain: 'Rovnováha je dynamická: přímá i zpětná reakce běží dál stejnou rychlostí, proto se koncentrace nemění.' } },
          ],
        },
        {
          title: 'Le Chatelierův princip',
          icon: 'balance-scale',
          blocks: [
            { type: 'p', text: 'Co se stane, když rovnováhu „zatřeseš“? Odpověď dává **Le Chatelierův princip** (princip pohyblivé rovnováhy).' },
            { type: 'callout', variant: 'remember', title: 'Le Chatelierův princip', text: '==Porušíme-li rovnováhu vnějším zásahem, soustava se posune tak, aby účinek zásahu zmenšila.==' },
            { type: 'diagram', id: 'equilibrium-seesaw', caption: 'Rovnováha $N2O4 <=> 2NO2$ jako houpačka: přidáš na jednu stranu, a soustava přelije část látky na druhou. Vyzkoušej i zahřátí, ochlazení a vyšší tlak.' },
            { type: 'compare', columns: [
              { title: 'Posun **doprava** (k produktům)', icon: 'arrow-cycle', tone: 'a', points: ['**přidáš reaktant** -> soustava ho část spotřebuje', '**odebereš produkt** -> soustava ho doplní'] },
              { title: 'Posun **doleva** (k reaktantům)', icon: 'arrow-cycle', tone: 'b', points: ['**přidáš produkt**', 'odebereš reaktant'] },
            ], caption: 'Změna koncentrace' },
            { type: 'example', title: 'Barvy podle kyselosti', problem: 'V roztoku platí $2CrO4^{2-} + 2H^+ <=> Cr2O7^{2-} + H2O$ (žlutý chroman ⇌ oranžový dichroman). Co uvidíš, když do žlutého roztoku chromanu draselného přikápneš kyselinu a potom hydroxid?', steps: [
              'Kyselina přidá ionty $H^+$, tedy reaktant. Rovnováha se posune doprava a roztok zoranžoví.',
              'Hydroxid ionty $H^+$ neutralizuje ($H^+ + OH^- -> H2O$), tedy reaktant odebere. Rovnováha se posune doleva a roztok znovu zežloutne.',
            ], answer: 'Po kyselině oranžová (dichroman), po hydroxidu zpátky žlutá (chroman). Sloučeniny šestimocného chromu jsou jedovaté a karcinogenní, pokus proto předvádí jen učitel v rukavicích a brýlích.' },
            { type: 'p', text: '**Tlak** ovlivňuje jen rovnováhy s plyny. Zvýšíš-li tlak (zmenšíš objem), soustava se posune na stranu s **menším počtem molů plynu**. U $H2(g) + I2(g) <=> 2HI(g)$ jsou na obou stranách 2 moly plynu, a tlak proto rovnováhu neposune.' },
            { type: 'particles', boxes: [
              { label: '$N2 + 3H2$: 4 moly plynu', items: [{ species: 'N2', count: 2 }, { species: 'H2', count: 6 }], state: 'gas' },
              { label: '$2NH3$: 2 moly plynu', items: [{ species: 'NH3', count: 4 }], state: 'gas', note: 'méně molekul = nižší tlak' },
            ], arrows: true, caption: 'Pod vyšším tlakem se vyplatí mít méně molekul plynu, rovnováha se posune k amoniaku.' },
            { type: 'compare', columns: [
              { title: 'Zvýšení teploty', icon: 'heat', tone: 'a', points: ['podporuje **endotermní** směr (soustava teplo „spotřebuje“)', '$N2O4 <=> 2NO2$ (ΔH = +57 kJ/mol): přibude hnědého $NO2$, baňka v horké vodě ztmavne'] },
              { title: 'Snížení teploty', icon: 'cold', tone: 'b', points: ['podporuje **exotermní** směr', '$N2O4 <=> 2NO2$: přibude bezbarvého $N2O4$, v ledové lázni se směs skoro odbarví'] },
            ], caption: 'Změna teploty posouvá rovnováhu podle znaménka ΔH' },
            { type: 'table', headers: ['Zásah', 'Posun rovnováhy', 'Změní se K?'], rows: [
              ['přidání reaktantu, odebrání produktu', 'doprava', 'ne'],
              ['přidání produktu, odebrání reaktantu', 'doleva', 'ne'],
              ['zvýšení tlaku', 'ke straně s menším počtem molů plynu', 'ne'],
              ['zvýšení teploty', 've směru endotermní reakce', 'ano'],
              ['snížení teploty', 've směru exotermní reakce', 'ano'],
              ['katalyzátor', 'žádný posun, rovnováhy se jen dosáhne dřív', 'ne'],
            ], caption: 'Le Chatelierův princip v kostce. K je rovnovážná konstanta, spočítat ji naučíme níže v této lekci.' },
            { type: 'callout', variant: 'remember', text: 'Katalyzátor zrychlí přímou i zpětnou reakci stejně. Polohu rovnováhy **nezmění**, jen se k ní dostaneš rychleji.' },
            { type: 'check', question: { kind: 'multi', q: 'Rovnováha $2SO2(g) + O2(g) <=> 2SO3(g)$ má ΔH = −197 kJ/mol. Které zásahy zvýší rovnovážný podíl $SO3$?', options: ['zvýšení tlaku', 'snížení teploty', 'přidání kyslíku', 'přidání katalyzátoru', 'zvýšení teploty'], answers: [0, 1, 2], explain: 'Vpravo jsou 2 moly plynu, vlevo 3, takže tlak pomáhá. Přímá reakce je exotermní, takže pomáhá chlazení. Kyslík je reaktant. Katalyzátor rovnováhu neposune a ohřátí ji posune doleva.' } },
          ],
        },
        {
          title: 'Rovnováha v továrně, v láhvi a v krvi',
          icon: 'factory',
          blocks: [
            { type: 'p', text: 'Průmysl hledá kompromis mezi **výtěžkem** (poloha rovnováhy) a **rychlostí** (jak rychle se k ní dojde). Nejslavnějším příkladem je výroba amoniaku Haberovým–Boschovým procesem.' },
            { type: 'diagram', id: 'haber-process', caption: 'Haberův–Boschův proces: dusík ze vzduchu a vodík ze zemního plynu stlačí kompresor, v reaktoru s železným katalyzátorem vzniká amoniak ($N2 + 3H2 <=> 2NH3$, ΔH = −92 kJ/mol), v chladiči zkapalní a nezreagované plyny se vracejí zpět.' },
            { type: 'list', items: [
              '**Tlak asi 20 MPa**, 200× víc než atmosférický: vpravo jsou jen 2 moly plynu místo 4, výtěžek roste. Vyšší tlak by byl příliš drahý a nebezpečný.',
              '**Teplota 400–450 °C**: nízká teplota by dala víc amoniaku, ale reakce by byla nesnesitelně pomalá; je to kompromis.',
              '**Železný katalyzátor** zrychlí ustavení rovnováhy, výtěžek nezmění.',
              '**Odebírání amoniaku**: směs se ochladí, amoniak zkapalní a odteče, a rovnováha se tak stále posouvá doprava.',
              '**Recyklace**: při jednom průchodu zůstane asi 85 % dusíku a vodíku nezreagovaných, a proto se vracejí do reaktoru.',
            ] },
            { type: 'callout', variant: 'fact', text: 'Z amoniaku se vyrábějí hnojiva, která živí zhruba polovinu lidstva. Odhaduje se, že asi polovina atomů dusíku v tvém těle prošla někdy továrnou na amoniak.' },
            { type: 'p', text: 'Podobně se optimalizuje **kontaktní způsob výroby kyseliny sírové**. Klíčová oxidace $SO2$ běží s katalyzátorem $V2O5$ při asi 450 °C a tlaku jen mírně nad atmosférickým, protože přeměna je i tak přes 99 %.' },
            { type: 'reaction', equation: '2SO2 + O2 <=> 2SO3', caption: 'ΔH = −197 kJ/mol. Vzniklý $SO3$ se pohlcuje v koncentrované $H2SO4$, ne přímo ve vodě: reakce s vodou je tak exotermní, že by vznikla žíravá mlha kyseliny.' },
            { type: 'particles', boxes: [
              { label: 'zavřená láhev', items: [{ species: 'CO2', count: 7 }, { species: 'H2O', count: 8 }], state: 'solution', note: 'vysoký tlak $CO2$ nad hladinou' },
              { label: 'otevřená láhev', items: [{ species: 'CO2', count: 2 }, { species: 'H2O', count: 8 }], state: 'solution', note: 'plyn uniká v bublinkách' },
            ], arrows: true, caption: 'Rovnováha $CO2(g) <=> CO2(aq)$: po otevření klesne tlak $CO2$ nad hladinou a rovnováha se posune doleva. Rozpouštění $CO2$ je exotermní, proto teplá limonáda vyčpí rychleji.' },
            { type: 'process', layout: 'cycle', steps: [
              { icon: 'lungs', title: 'Plíce', text: 'kyslíku je hodně, rovnováha $Hb + 4O2 <=> Hb(O2)4$ je vpravo, hemoglobin se nasytí' },
              { icon: 'heart', title: 'Krevní oběh', text: 'srdce žene okysličenou krev do těla' },
              { icon: 'muscle', title: 'Svaly', text: 'kyslíku je málo, rovnováha se posune doleva a Hb ho uvolní přesně tam, kde je potřeba' },
              { icon: 'blood', title: 'Zpět k plicím', text: 'odkysličená krev se vrací pro další kyslík' },
            ], caption: 'Le Chatelier v tvém krevním oběhu' },
            { type: 'callout', variant: 'warning', title: 'Oxid uhelnatý', text: 'Oxid uhelnatý se na hemoglobin váže asi 200× pevněji než kyslík a vytlačí ho. Otrava $CO$ z vadných karem nebo kotlů je proto smrtelně nebezpečná. Léčí se dýcháním čistého kyslíku, který podle Le Chateliera $CO$ z hemoglobinu postupně vytlačí.' },
            { type: 'game', gameId: 'swipe', text: 'Doprava, doleva, nebo nikam? Procvič si Le Chatelierův princip v rychlé hře „Pravda, nebo lež?“.' },
            { type: 'check', question: { kind: 'choice', q: 'Proč se amoniak nevyrábí při pokojové teplotě, když by tam byl rovnovážný výtěžek nejvyšší?', options: ['reakce by byla příliš pomalá', 'při nízké teplotě by rovnováha byla vlevo', 'katalyzátor funguje jen za vysokého tlaku', 'amoniak by se rozložil'], answer: 0, explain: 'Nízká teplota posouvá exotermní rovnováhu doprava, ale rychlost reakce by byla zanedbatelná. Teplota 400–450 °C je kompromis mezi výtěžkem a rychlostí.' } },
          ],
        },
        {
          title: 'Rovnovážná konstanta K_{c}',
          icon: 'calculator',
          blocks: [
            { type: 'p', text: 'Polohu rovnováhy lze vyjádřit jedním číslem, **rovnovážnou konstantou**. Pro obecnou reakci $aA + bB <=> cC + dD$ platí **Guldbergův–Waageův zákon** (zákon působení aktivních hmot):' },
            { type: 'formula', text: 'K_{c} = $[C]^{c}·[D]^{d} / ([A]^{a}·[B]^{b})$', caption: 'hranaté závorky = rovnovážné koncentrace v mol/dm³; koeficienty z rovnice jsou exponenty' },
            { type: 'iconlist', items: [
              { icon: 'calculator', title: 'Produkty nahoře', text: 'produkty jsou v čitateli, reaktanty ve jmenovateli' },
              { icon: 'crystal', title: 'Bez pevných látek a čistých kapalin', text: 'jejich „koncentrace“ se nemění, a proto se do výrazu **nepíšou**; totéž platí pro vodu jako rozpouštědlo' },
              { icon: 'thermometer', title: 'Jen teplota', text: 'K_{c} závisí **jen na teplotě**; koncentrace, tlak ani katalyzátor ji nezmění' },
              { icon: 'arrow-cycle', title: 'Obrácená reakce', text: 'K′ = 1 / K_{c}' },
            ] },
            { type: 'example', title: 'Zápis K_{c}, i pro heterogenní rovnováhy', problem: 'Zapiš K_{c} pro: a) $N2(g) + 3H2(g) <=> 2NH3(g)$, b) $CaCO3(s) <=> CaO(s) + CO2(g)$, c) $C(s) + H2O(g) <=> CO(g) + H2(g)$.', steps: [
              'a) Všechno jsou plyny: K_{c} = $[NH3]^2 / ([N2]·[H2]^3)$',
              'b) $CaCO3$ a $CaO$ jsou pevné látky, vypadnou: K_{c} = $[CO2]$',
              'c) Uhlík je pevný a vypadne, ale vodní pára je plyn a ve výrazu zůstane: K_{c} = $[CO]·[H2] / [H2O]$',
            ], answer: 'Ve výrazu zůstávají jen plyny a rozpuštěné látky. Rovnováhy s více fázemi se nazývají **heterogenní**.' },
            { type: 'reaction', equation: 'CaCO3 <=> CaO + CO2', caption: 'Pálení vápna: K_{c} = $[CO2]$. V uzavřené peci se při dané teplotě ustaví vždy stejná koncentrace $CO2$, ať je vápence kilo, nebo tuna.' },
            { type: 'compare', columns: [
              { title: 'K ≫ 1 (např. 10^{10})', icon: 'check', tone: 'good', points: ['rovnováha je silně **vpravo**', 'reakce proběhne téměř úplně', 'neutralizace silné kyseliny'] },
              { title: 'K ≈ 1', icon: 'equilibrium', tone: 'a', points: ['srovnatelná množství reaktantů i produktů', 'esterifikace (K ≈ 4)'] },
              { title: 'K ≪ 1 (např. 10^{−10})', icon: 'cross', tone: 'bad', points: ['rovnováha je silně **vlevo**', 'produktů je jen stopa', 'rozpouštění $AgCl$'] },
            ], caption: 'Co prozradí velikost K. O rychlosti reakce neříká nic.' },
            { type: 'example', title: 'Výpočet K_{c} z rovnovážných koncentrací', problem: 'Pro $H2(g) + I2(g) <=> 2HI(g)$ byly při 450 °C naměřeny rovnovážné koncentrace $[H2]$ = 0,020 mol/dm³, $[I2]$ = 0,020 mol/dm³, $[HI]$ = 0,14 mol/dm³. Vypočítej K_{c}.', steps: [
              'Výraz: K_{c} = $[HI]^2 / ([H2]·[I2])$',
              'Dosadíme: K_{c} = 0,14^{2} / (0,020 · 0,020) = 0,0196 / 0,000 40',
              'K_{c} = 49 (jednotky se tu vykrátí)',
            ], answer: 'K_{c} = 49, v rovnováze převažuje jodovodík.' },
            { type: 'callout', variant: 'tip', title: 'K_{p} pro plyny', text: 'U plynů se místo koncentrací často dosazují parciální tlaky: K_{p} = $p(NH3)^2 / (p(N2)·p(H2)^3)$. Výraz se píše stejně, jen hodnota K_{p} se od K_{c} obecně liší (pokud se mění počet molů plynu).' },
            { type: 'check', question: { kind: 'choice', q: 'Jaký je výraz pro K_{c} reakce $N2(g) + 3H2(g) <=> 2NH3(g)$?', options: ['$[NH3]^2 / ([N2]·[H2]^3)$', '$[N2]·[H2]^3 / [NH3]^2$', '$2[NH3] / ([N2]·3[H2])$', '$[NH3] / ([N2]·[H2])$'], answer: 0, explain: 'Produkty do čitatele, reaktanty do jmenovatele, stechiometrické koeficienty se stanou exponenty.' } },
          ],
        },
        {
          title: 'Výpočty s tabulkou ICE',
          icon: 'chart',
          blocks: [
            { type: 'p', text: 'Obvykle neznáš všechny rovnovážné koncentrace, ale jen výchozí stav a K (nebo jednu naměřenou koncentraci). Pak pomůže tabulka **ICE** (z angl. *initial – change – equilibrium*): počátek, změna, rovnováha.' },
            { type: 'process', layout: 'flow', steps: [
              { icon: 'pencil', title: 'Rovnice', text: 'zapiš vyčíslenou rovnici a výraz pro K_{c}' },
              { icon: 'flask', title: 'Počátek', text: 'výchozí koncentrace (produkty často 0)' },
              { icon: 'arrow-cycle', title: 'Změna', text: '−x, +x, +2x… přesně podle koeficientů' },
              { icon: 'equilibrium', title: 'Rovnováha', text: 'počátek + změna' },
              { icon: 'calculator', title: 'Dosaď a vyřeš', text: 'rovnovážné výrazy dosaď do K_{c} a spočítej x' },
            ], caption: 'Postup výpočtu rovnovážného složení' },
            { type: 'table', headers: ['c / mol·dm^{−3}', '$PCl5$', '$PCl3$', '$Cl2$'], rows: [
              ['počátek', '0,100', '0', '0'],
              ['změna', '−x', '+x', '+x'],
              ['rovnováha', '0,100 − x', 'x', 'x'],
            ], caption: 'Tabulka ICE pro rozklad $PCl5 <=> PCl3 + Cl2$' },
            { type: 'example', title: 'K_{c} z jedné naměřené koncentrace', problem: 'Do nádoby dáme $PCl5$ o koncentraci 0,100 mol/dm³ a zahřejeme. V rovnováze je $[Cl2]$ = 0,040 mol/dm³. Vypočítej K_{c} reakce $PCl5(g) <=> PCl3(g) + Cl2(g)$.', steps: [
              'Z tabulky: x = $[Cl2]$ = 0,040 mol/dm³, takže i $[PCl3]$ = 0,040 mol/dm³.',
              '$[PCl5]$ = 0,100 − 0,040 = 0,060 mol/dm³',
              'K_{c} = $[PCl3]·[Cl2] / [PCl5]$ = 0,040 · 0,040 / 0,060 = 0,0016 / 0,060',
            ], answer: 'K_{c} ≈ 0,027 mol/dm³. Rovnováha je spíš vlevo.' },
            { type: 'molecule', molecules: ['acetic-acid', 'ethanol', 'ethyl-acetate'], labels: ['kyselina octová', 'ethanol', 'ethylacetát (ester)'], caption: 'Esterifikace: $CH3COOH + C2H5OH <=> CH3COOC2H5 + H2O$, K_{c} ≈ 4. Voda tu není rozpouštědlo, ale produkt, a proto ve výrazu je.' },
            { type: 'example', title: 'Kolik esteru vznikne?', problem: 'Smícháme 1,00 mol kyseliny octové a 1,00 mol ethanolu. Pro esterifikaci je K_{c} = 4,0. Kolik molů esteru bude v rovnováze?', steps: [
              'ICE: počátek kyselina 1,00, alkohol 1,00, ester 0, voda 0; změna −x, −x, +x, +x.',
              'V rovnováze: kyselina 1,00 − x, alkohol 1,00 − x, ester x, voda x. Objem se ve výrazu vykrátí.',
              'K_{c} = x^{2} / (1,00 − x)^{2} = 4,0, odmocníme: x / (1,00 − x) = 2,0',
              'x = 2,0 − 2,0x -> 3,0x = 2,0 -> x = 0,67 mol',
            ], answer: 'V rovnováze vznikne asi 0,67 mol esteru, tedy dvě třetiny teoretického množství.' },
            { type: 'callout', variant: 'fact', title: 'Le Chatelier v číslech', text: 'Když k 1,00 mol kyseliny dáš 3,00 mol ethanolu, vyjde z téže K_{c} = 4,0 asi 0,90 mol esteru místo 0,67. Nadbytek levnějšího reaktantu výtěžek opravdu zvýší.' },
            { type: 'callout', variant: 'tip', text: 'Když je výraz dokonalý čtverec, odmocni ho. Jinak vznikne kvadratická rovnice. Vždy zkontroluj, že x vyšlo menší než výchozí množství: záporná koncentrace je jistá chyba.' },
            { type: 'check', question: { kind: 'number', q: 'Pro $CO(g) + H2O(g) <=> CO2(g) + H2(g)$ je při určité teplotě K_{c} = 9,0. Na počátku je $[CO]$ = $[H2O]$ = 1,00 mol/dm³. Jaká bude rovnovážná koncentrace $CO2$?', answer: 0.75, tolerance: 0.01, unit: 'mol/dm³', explain: 'ICE: x^{2} / (1,00 − x)^{2} = 9,0, odmocnina: x / (1,00 − x) = 3,0, tedy x = 3,0 − 3,0x, 4,0x = 3,0 a x = 0,75 mol/dm³.' } },
          ],
        },
        {
          title: 'Reakční kvocient Q: kam se reakce pohne',
          icon: 'arrow-cycle',
          blocks: [
            { type: 'p', text: '**Reakční kvocient** Q má stejný tvar jako K_{c}, ale dosazuješ do něj koncentrace v **libovolném okamžiku**, ne nutně v rovnováze. Porovnáním Q s K poznáš, kam reakce poběží.' },
            { type: 'compare', columns: [
              { title: 'Q < K', icon: 'arrow-cycle', tone: 'a', points: ['produktů je méně, než odpovídá rovnováze', 'reakce běží **doprava**'] },
              { title: 'Q = K', icon: 'equilibrium', tone: 'good', points: ['soustava je v rovnováze', 'složení se nemění'] },
              { title: 'Q > K', icon: 'arrow-cycle', tone: 'b', points: ['produktů je víc, než odpovídá rovnováze', 'reakce běží **doleva**'] },
            ], caption: 'Soustava se vždy vydá tím směrem, kterým se Q přibližuje ke K.' },
            { type: 'example', title: 'Je směs v rovnováze?', problem: 'Pro $H2(g) + I2(g) <=> 2HI(g)$ je při 450 °C K_{c} = 49. Ve směsi je $[H2]$ = 0,10 mol/dm³, $[I2]$ = 0,10 mol/dm³ a $[HI]$ = 0,50 mol/dm³. Kam reakce poběží?', steps: [
              'Q = $[HI]^2 / ([H2]·[I2])$ = 0,50^{2} / (0,10 · 0,10) = 0,25 / 0,010',
              'Q = 25',
              'Q = 25 < K = 49',
            ], answer: 'Směs není v rovnováze. Reakce poběží doprava a jodovodíku přibude, dokud Q nevzroste na 49.' },
            { type: 'p', text: 'Takhle se dá Le Chatelierův princip vysvětlit i početně. Přidáš-li reaktant, zvětší se jmenovatel, Q klesne pod K a reakce běží doprava, dokud se Q nevyrovná s K. **Samotná K se nezmění.**' },
            { type: 'callout', variant: 'remember', text: '==Hodnotu K mění jen teplota.== Koncentrace a tlak mění Q, katalyzátor jen rychlost. U exotermní reakce K s rostoucí teplotou klesá, u endotermní roste.' },
            { type: 'table', headers: ['Teplota', 'K_{c} pro $N2 + 3H2 <=> 2NH3$'], rows: [
              ['25 °C', 'asi 4·10^{8}'],
              ['400 °C', 'asi 0,5'],
              ['500 °C', 'asi 0,06'],
            ], caption: 'Syntéza amoniaku je exotermní, a proto její K s rostoucí teplotou prudce klesá (hodnoty v dm^{6}·mol^{−2}).' },
            { type: 'callout', variant: 'fact', text: 'S lekcí o Gibbsově energii to souvisí vztahem ΔG° = −R·T·ln K: velmi záporná ΔG° znamená obrovskou K a rovnováhu vpravo.' },
            { type: 'check', question: { kind: 'choice', q: 'Pro reakci s K_{c} = 0,50 má směs v určitém okamžiku Q = 2,0. Co se bude dít?', options: ['reakce poběží doleva, dokud Q neklesne na 0,50', 'reakce poběží doprava', 'nic, směs je v rovnováze', 'K vzroste na 2,0'], answer: 0, explain: 'Q > K znamená, že produktů je víc, než odpovídá rovnováze. Převáží zpětná reakce a Q klesá, dokud se nevyrovná s K.' } },
          ],
        },
      ],
      summary: [
        'U vratné reakce se ustaví dynamická rovnováha: přímá a zpětná reakce běží stejnou rychlostí a koncentrace se nemění.',
        'Podle Le Chatelierova principu soustava na vnější zásah reaguje tak, aby jeho účinek zmenšila; vyšší tlak posouvá rovnováhu ke straně s méně moly plynu, vyšší teplota podporuje endotermní směr a katalyzátor polohu rovnováhy nemění.',
        'Haberův–Boschův proces používá vysoký tlak, kompromisní teplotu 400–450 °C, železný katalyzátor a odebírání amoniaku.',
        'Rovnovážná konstanta K_{c} je poměr rovnovážných koncentrací produktů a reaktantů umocněných na koeficienty; pevné látky a čisté kapaliny se do ní nepíšou.',
        'Velká K znamená rovnováhu vpravo, malá vlevo; u plynů se používá i K_{p} s parciálními tlaky.',
        'Rovnovážné složení spočítáš tabulkou ICE: počátek, změna podle koeficientů, rovnováha.',
        'Porovnáním Q s K poznáš směr reakce (Q < K doprava, Q > K doleva); hodnotu K mění jen teplota.',
      ],
      quiz: [
        { kind: 'choice', q: 'Co platí v chemické rovnováze?', options: ['rychlost přímé a zpětné reakce je stejná', 'koncentrace reaktantů a produktů jsou stejné', 'reakce se zastavila', 'všechny reaktanty se přeměnily na produkty'], answer: 0, explain: 'V rovnováze jsou stejné rychlosti obou směrů. Koncentrace jsou stálé, ale obecně různé.' },
        { kind: 'tf', q: 'Přidáním katalyzátoru se rovnováha posune k produktům.', answer: false, explain: 'Katalyzátor zrychlí oba směry stejně, rovnováhy se dosáhne dřív, ale její poloha se nezmění.' },
        { kind: 'match', q: 'Přiřaď zásah k posunu rovnováhy $N2(g) + 3H2(g) <=> 2NH3(g)$, ΔH < 0.', pairs: [
          ['zvýšení tlaku', 'doprava'],
          ['zvýšení teploty', 'doleva'],
          ['přidání katalyzátoru', 'nijak'],
        ], explain: 'Tlak posouvá k menšímu počtu molů plynu, ohřátí podporuje endotermní zpětnou reakci a katalyzátor polohu rovnováhy nemění.' },
        { kind: 'choice', q: 'Jaký je výraz pro K_{c} rovnováhy $CaCO3(s) <=> CaO(s) + CO2(g)$?', options: ['$[CO2]$', '$[CaO]·[CO2] / [CaCO3]$', '$1 / [CO2]$', '$[CaCO3] / ([CaO]·[CO2])$'], answer: 0, explain: 'Pevné látky se do výrazu nepíšou, jejich „koncentrace“ je stálá. Zůstane jen plynný $CO2$ v čitateli.' },
        { kind: 'number', q: 'Do nádoby o objemu 1,00 dm³ dáme 0,200 mol $N2O4$. Po ustavení rovnováhy $N2O4(g) <=> 2NO2(g)$ je $[NO2]$ = 0,040 mol/dm³. Vypočítej K_{c}.', answer: 0.0089, tolerance: 0.0003, explain: 'Na 0,040 mol/dm³ $NO2$ se spotřebuje 0,020 mol/dm³ $N2O4$, zbude 0,180. K_{c} = 0,040^{2} / 0,180 = 0,0016 / 0,180 ≈ 0,0089.' },
        { kind: 'choice', q: 'Pro $H2 + I2 <=> 2HI$ je K_{c} = 49. Ve směsi je $[H2]$ = $[I2]$ = 0,10 mol/dm³ a $[HI]$ = 1,0 mol/dm³. Kam poběží reakce?', options: ['doleva, protože Q = 100 > K', 'doprava, protože Q = 100 > K', 'doprava, protože Q = 10 < K', 'nikam, směs je v rovnováze'], answer: 0, explain: 'Q = 1,0^{2} / (0,10 · 0,10) = 100. To je víc než K = 49, jodovodíku je nadbytek a část se rozloží zpět na $H2$ a $I2$.' },
        { kind: 'tf', q: 'Když do rovnovážné směsi přidáš reaktant, rovnovážná konstanta se zvětší.', answer: false, explain: 'Přidání reaktantu změní jen Q (klesne pod K), reakce proto běží doprava. Hodnota K zůstane stejná, mění ji jen teplota.' },
      ],
    },
    // ───────────────────────────────────────────────────────────── l6-6
    'l6-6': {
      id: 'l6-6',
      title: 'Slabé kyseliny, pufry a součin rozpustnosti',
      goals: [
        'Pomocí K_{a}, pK_{a}, K_{b} a pK_{b} porovnat sílu slabých kyselin a zásad a využít vztah pK_{a} + pK_{b} = 14',
        'Spočítat pH roztoku slabé kyseliny i slabé zásady a posoudit, kdy přibližný vzorec platí',
        'Vysvětlit, jak funguje pufr, a spočítat jeho pH Hendersonovou–Hasselbalchovou rovnicí',
        'Ze součinu rozpustnosti K_{s} spočítat rozpustnost, posoudit vliv společného iontu a předpovědět, zda vznikne sraženina',
      ],
      hook: 'Vypiješ litr limonády s kyselinou citronovou a pH tvé krve se skoro nehne. Za to vděčíš pufru. A proč se ti v konvici usazuje vodní kámen, zatímco sůl se rozpustí beze zbytku? Obojí dnes spočítáš.',
      sections: [
        {
          title: 'Slabé kyseliny a zásady: K_{a} a K_{b}',
          icon: 'lemon',
          blocks: [
            { type: 'p', text: 'Z úrovně 5 víš, že slabá kyselina se ve vodě ionizuje jen částečně. Ionizace je rovnováha, a proto ji popíšeš rovnovážnou konstantou z minulé lekce. Voda je rozpouštědlo, do výrazu ji nepíšeš.' },
            { type: 'formula', text: '$HA + H2O <=> H3O^+ + A^-$' },
            { type: 'particles', boxes: [
              { label: 'silná kyselina $HCl$', items: [{ species: 'H3O+', count: 6 }, { species: 'Cl^-', count: 6 }], state: 'solution', note: 'ionizovaná téměř úplně' },
              { label: 'slabá kyselina $CH3COOH$', items: [{ species: 'acetic-acid', count: 5 }, { species: 'H3O+', count: 1 }, { species: 'CH3COO^-', count: 1 }], state: 'solution', note: 'ionizovaná jen z malé části' },
            ], caption: 'Stejná koncentrace, ale velmi různý počet iontů $H3O^+$' },
            { type: 'formula', text: 'K_{a} = $[H3O^+]·[A^-] / [HA]$ · pK_{a} = −log K_{a}', caption: '**disociační konstanta kyseliny** a její záporný logaritmus' },
            { type: 'table', headers: ['Kyselina', 'Vzorec', 'K_{a}', 'pK_{a}'], rows: [
              ['fosforečná (1. stupeň)', '$H3PO4$', '7,1·10^{−3}', '2,15'],
              ['fluorovodíková', '$HF$', '6,8·10^{−4}', '3,17'],
              ['mravenčí', '$HCOOH$', '1,8·10^{−4}', '3,75'],
              ['octová', '$CH3COOH$', '1,7·10^{−5}', '4,76'],
              ['uhličitá (1. stupeň)', '$H2CO3$', '4,5·10^{−7}', '6,35'],
              ['amonný kation', '$NH4^+$', '5,6·10^{−10}', '9,25'],
            ], caption: 'Hodnoty při 25 °C. Silné kyseliny ($HCl$, $HNO3$) mají K_{a} tak velké, že se v tabulkách neuvádí.' },
            { type: 'callout', variant: 'remember', text: '==Čím menší pK_{a} (a větší K_{a}), tím silnější kyselina.== Rozdíl o 1 v pK_{a} znamená desetkrát jinou K_{a}.' },
            { type: 'p', text: 'Stejně popíšeš slabou zásadu. Amoniak přijme od vody proton a vzniknou hydroxidové ionty:' },
            { type: 'particles', boxes: [
              { label: 'roztok amoniaku', items: [{ species: 'NH3', count: 6 }, { species: 'NH4+', count: 1 }, { species: 'OH-', count: 1 }, { species: 'H2O', count: 5 }], state: 'solution', note: 'protonuje se jen malá část' },
            ], caption: '$NH3 + H2O <=> NH4^+ + OH^-$' },
            { type: 'formula', text: 'K_{b} = $[NH4^+]·[OH^-] / [NH3]$ = 1,8·10^{−5} · pK_{b} = 4,75', caption: '**disociační konstanta zásady**; čím menší pK_{b}, tím silnější zásada' },
            { type: 'formula', text: 'K_{a} · K_{b} = K_{w} = 1,0·10^{−14} -> pK_{a} + pK_{b} = 14', caption: 'platí pro konjugovaný pár kyselina–zásada ve vodě při 25 °C' },
            { type: 'example', title: 'Konjugované páry', problem: 'Jaké je pK_{b} octanového aniontu $CH3COO^-$ (pK_{a} kyseliny octové = 4,76)? A jaké je pK_{a} amonného kationtu, víš-li, že pro $NH3$ je pK_{b} = 4,75?', steps: [
              'pK_{b}($CH3COO^-$) = 14 − 4,76 = 9,24, tedy K_{b} = 10^{−9,24} = 5,8·10^{−10}',
              'pK_{a}($NH4^+$) = 14 − 4,75 = 9,25, což souhlasí s tabulkou',
            ], answer: 'Octan je velmi slabá zásada (pK_{b} = 9,24). Čím slabší kyselina, tím silnější její konjugovaná zásada.' },
            { type: 'check', question: { kind: 'number', q: 'pK_{a} kyseliny fluorovodíkové je 3,17. Jaké je pK_{b} fluoridového aniontu $F^-$?', answer: 10.83, tolerance: 0.01, explain: '$HF$ a $F^-$ tvoří konjugovaný pár: pK_{b} = 14 − 3,17 = 10,83.' } },
          ],
        },
        {
          title: 'pH slabé kyseliny a slabé zásady',
          icon: 'calculator',
          blocks: [
            { type: 'p', text: 'U silné kyseliny platí $[H3O^+]$ = c, takže pH = −log c. Slabá kyselina se ionizuje jen z malé části, a pH proto vychází vyšší.' },
            { type: 'process', layout: 'flow', steps: [
              { icon: 'ion-plus', title: 'Ionty', text: 'z každé ionizované molekuly vznikne jeden $H3O^+$ a jeden $A^-$: $[H3O^+]$ = $[A^-]$ = x' },
              { icon: 'molecule', title: 'Zbytek kyseliny', text: 'ionizuje se jen malý podíl, proto $[HA]$ = c − x ≈ c' },
              { icon: 'calculator', title: 'Dosaď do K_{a}', text: 'K_{a} = x^{2} / c, tedy x = √(K_{a} · c)' },
              { icon: 'chart', title: 'Zlogaritmuj', text: 'a vynásob −1' },
            ], caption: 'Odvození přibližného vzorce' },
            { type: 'formula', text: 'pH = ½ · (pK_{a} − log c)', caption: 'přibližný vzorec pro slabou kyselinu o koncentraci c (v mol/dm³)' },
            { type: 'example', title: 'Kyselina octová a ocet', problem: 'Vypočítej pH roztoku kyseliny octové o koncentraci 0,10 mol/dm³ (pK_{a} = 4,76) a pH octa (asi 1,0 mol/dm³). Porovnej s $HCl$ 0,10 mol/dm³.', steps: [
              '0,10 mol/dm³: pH = ½ · (4,76 − (−1)) = ½ · 5,76 = 2,88',
              'Kontrola předpokladu: $[H3O^+]$ = 10^{−2,88} = 1,3·10^{−3} mol/dm³, to je jen 1,3 % z 0,10 mol/dm³. Přiblížení platí.',
              'Ocet 1,0 mol/dm³: log 1,0 = 0, pH = ½ · 4,76 = 2,38',
              '$HCl$ 0,10 mol/dm³: pH = −log 0,10 = 1,00',
            ], answer: 'Kyselina octová 0,10 mol/dm³ má pH ≈ 2,88, ocet asi 2,4. Stejně koncentrovaná $HCl$ má skoro 100× víc iontů $H3O^+$.' },
            { type: 'callout', variant: 'warning', title: 'Kdy přiblížení platí', text: 'Předpoklad c − x ≈ c je dobrý, když se ionizuje **méně než asi 5 %** kyseliny. To nastává zhruba při c / K_{a} > 400. U poměrně silných kyselin (malé pK_{a}) nebo velmi zředěných roztoků musíš řešit kvadratickou rovnici.' },
            { type: 'example', title: 'Když přiblížení selže', problem: 'Vypočítej pH roztoku $H3PO4$ o koncentraci 0,010 mol/dm³ (K_{a} = 7,1·10^{−3}; počítej jen 1. stupeň).', steps: [
              'Přibližně: x = √(7,1·10^{−3} · 0,010) = 8,4·10^{−3} mol/dm³, to je 84 % z c. Přiblížení neplatí!',
              'Přesně: K_{a} = x^{2} / (c − x), tedy x^{2} + K_{a}·x − K_{a}·c = 0',
              'x = (−K_{a} + √(K_{a}^{2} + 4·K_{a}·c)) / 2 = (−0,0071 + √(5,0·10^{−5} + 2,84·10^{−4})) / 2 = 5,6·10^{−3} mol/dm³',
              'pH = −log (5,6·10^{−3}) = 2,25',
            ], answer: 'pH ≈ 2,25. Přibližný vzorec by dal 2,07, tedy chybu skoro 0,2 jednotky.' },
            { type: 'p', text: 'U **slabé zásady** počítáš úplně stejně, jen s ionty $OH^-$ a s K_{b}: nejdřív pOH, pak pH = 14 − pOH.' },
            { type: 'formula', text: 'pOH = ½ · (pK_{b} − log c) · pH = 14 − pOH', caption: 'přibližný vzorec pro slabou zásadu' },
            { type: 'example', title: 'Roztok amoniaku', problem: 'Vypočítej pH roztoku amoniaku o koncentraci 0,10 mol/dm³ (pK_{b} = 4,75).', steps: [
              'pOH = ½ · (4,75 − (−1)) = ½ · 5,75 = 2,875',
              'pH = 14 − 2,875 = 11,125',
              'Kontrola: $[OH^-]$ = 10^{−2,875} = 1,3·10^{−3} mol/dm³, jen 1,3 % z c. Přiblížení platí.',
            ], answer: 'pH ≈ 11,13. Hydroxid sodný o stejné koncentraci by měl pH 13.' },
            { type: 'diagram', id: 'ph-scale', props: { marks: [{ ph: 1, label: '$HCl$ 0,10 mol/dm³' }, { ph: 2.88, label: '$CH3COOH$ 0,10 mol/dm³' }, { ph: 11.13, label: '$NH3$ 0,10 mol/dm³' }, { ph: 13, label: '$NaOH$ 0,10 mol/dm³' }] }, caption: 'Při stejné koncentraci jsou slabá kyselina i slabá zásada o 2 jednotky pH blíž k neutrální 7 než silné.' },
            { type: 'check', question: { kind: 'number', q: 'Vypočítej pH roztoku kyseliny octové o koncentraci 0,010 mol/dm³ (pK_{a} = 4,76).', answer: 3.38, tolerance: 0.02, explain: 'pH = ½ · (4,76 − log 0,010) = ½ · (4,76 + 2) = 3,38. Ionizuje se asi 4 %, přiblížení ještě platí.' } },
          ],
        },
        {
          title: 'Pufry: tlumiče změn pH',
          icon: 'test-tube',
          blocks: [
            { type: 'p', text: '**Pufr** (tlumivý roztok) je roztok, jehož pH se po přidání malého množství kyseliny nebo zásady téměř nezmění. Tvoří ho **slabá kyselina a její konjugovaná zásada** (sůl), nebo slabá zásada a její sůl.' },
            { type: 'iconlist', items: [
              { icon: 'lemon', title: 'Acetátový pufr', text: '$CH3COOH$ + $CH3COONa$, pH kolem 4,8' },
              { icon: 'flask', title: 'Amonný pufr', text: '$NH3$ + $NH4Cl$, pH kolem 9,3' },
              { icon: 'cell', title: 'Fosfátový pufr', text: '$NaH2PO4$ + $Na2HPO4$, pH kolem 7,2' },
            ] },
            { type: 'diagram', id: 'buffer-action', caption: 'Stejná dávka kyseliny nebo zásady do vody a do acetátového pufru. Pufr má zásobu obou forem: přidané $H^+$ zachytí acetát, přidané $OH^-$ kyselina octová. Silná kyselina či zásada se tak mění na slabou, a pH se proto skoro nehne.' },
            { type: 'formula', text: 'pH = pK_{a} + log ($[A^-] / [HA]$)', caption: '**Hendersonova–Hasselbalchova rovnice**' },
            { type: 'example', title: 'pH acetátového pufru', problem: 'Pufr obsahuje 0,10 mol/dm³ $CH3COOH$ a 0,20 mol/dm³ $CH3COONa$. Jaké má pH? (pK_{a} = 4,76)', steps: [
              'Poměr $[A^-] / [HA]$ = 0,20 / 0,10 = 2,0',
              'pH = 4,76 + log 2,0 = 4,76 + 0,30',
              'pH = 5,06',
            ], answer: 'pH pufru je 5,06.' },
            { type: 'example', title: 'Pufr v akci', problem: 'Do 1 dm³ pufru s 0,10 mol $CH3COOH$ a 0,10 mol $CH3COONa$ přidáme 0,010 mol $HCl$. Jak se změní pH?', steps: [
              'Před přidáním: pH = 4,76 + log (0,10 / 0,10) = 4,76.',
              '$HCl$ zreaguje s acetátem: $CH3COO^-$ ubude na 0,09 mol, $CH3COOH$ přibude na 0,11 mol.',
              'pH = 4,76 + log (0,09 / 0,11) = 4,76 − 0,09 = 4,67.',
              'Pro srovnání: 0,010 mol $HCl$ v 1 dm³ čisté vody by snížilo pH ze 7 na 2.',
            ], answer: 'pH pufru klesne jen o 0,09 (ze 4,76 na 4,67), zatímco ve vodě by kleslo o 5 jednotek.' },
            { type: 'diagram', id: 'titration-curve', props: { kind: 'weak-strong' }, caption: 'Titrace slabé kyseliny silnou zásadou. Plochá část křivky je pufrační oblast. V polovině neutralizace je $[A^-]$ = $[HA]$, a tedy pH = pK_{a}. Bod ekvivalence leží nad pH 7.' },
            { type: 'callout', variant: 'tip', text: 'Pufr funguje nejlépe v rozsahu pH = pK_{a} ± 1. Chceš-li pufr s pH 7, vyber kyselinu s pK_{a} blízko 7, třeba $H2PO4^-$ (pK_{a} = 7,21).' },
            { type: 'p', text: '**Krev** udržuje pH v úzkém rozmezí **7,35–7,45** (pod ním acidóza, nad ním alkalóza). Hlavním krevním pufrem je hydrogenuhličitanový: $CO2 + H2O <=> H2CO3 <=> H^+ + HCO3^-$. Poměr $[HCO3^-] / [H2CO3]$ je asi 20 : 1 a pro krev se počítá s účinnou pK_{a} = 6,1, takže pH = 6,1 + log 20 = 7,40. Plíce řídí $CO2$ během minut, ledviny $HCO3^-$ během hodin až dnů.' },
            { type: 'callout', variant: 'fact', title: 'Hyperventilace', text: 'Při panice člověk rychle a zhluboka dýchá a vydýchá příliš mnoho $CO2$. Rovnováha se posune doleva, pH krve stoupne (alkalóza), brní prsty a točí se hlava. Pomáhá zklidnit a zpomalit dech.' },
            { type: 'check', question: { kind: 'number', q: 'Jaké pH má pufr s 0,050 mol/dm³ $CH3COOH$ a 0,50 mol/dm³ $CH3COONa$? (pK_{a} = 4,76)', answer: 5.76, tolerance: 0.02, explain: 'Poměr $[A^-] / [HA]$ = 0,50 / 0,050 = 10, log 10 = 1, pH = 4,76 + 1 = 5,76.' } },
          ],
        },
        {
          title: 'Součin rozpustnosti K_{s}',
          icon: 'crystal',
          blocks: [
            { type: 'p', text: 'Rovnováha se ustavuje i mezi málo rozpustnou solí a jejím nasyceným roztokem. Je to heterogenní rovnováha, pevnou látku do výrazu nepíšeš. Zbude **součin rozpustnosti** K_{s}.' },
            { type: 'formula', text: '$AgCl(s) <=> Ag^+(aq) + Cl^-(aq)$ · K_{s} = $[Ag^+]·[Cl^-]$', caption: 'sůl typu AB' },
            { type: 'formula', text: '$CaF2(s) <=> Ca^{2+}(aq) + 2F^-(aq)$ · K_{s} = $[Ca^{2+}]·[F^-]^2$', caption: 'sůl typu AB_{2}: koeficient se stane exponentem, stejně jako u K_{c}' },
            { type: 'particles', boxes: [
              { label: 'nasycený roztok $AgCl$', items: [{ species: 'AgCl', count: 6 }, { species: 'Ag^+', count: 2 }, { species: 'Cl^-', count: 2 }], state: 'solution', note: 'pevná sůl ⇌ ionty v roztoku' },
            ], caption: 'Na dně leží pevný $AgCl$, v roztoku je jen nepatrně iontů. Rozpouštění a srážení běží stejně rychle.' },
            { type: 'example', title: 'Rozpustnost z K_{s}: sůl typu AB', problem: 'K_{s}($AgCl$) = 1,8·10^{−10}. Kolik $AgCl$ se rozpustí v 1 dm³ vody? ($M$ = 143,5 g/mol)', steps: [
              'Rozpustí-li se s mol/dm³, je $[Ag^+]$ = $[Cl^-]$ = s.',
              'K_{s} = s · s = s^{2} = 1,8·10^{−10}',
              's = √(1,8·10^{−10}) = 1,3·10^{−5} mol/dm³',
              'm = 1,3·10^{−5} mol · 143,5 g/mol = 1,9·10^{−3} g',
            ], answer: 'Rozpustí se jen asi 1,3·10^{−5} mol, tedy necelé 2 mg $AgCl$ na litr.' },
            { type: 'example', title: 'Rozpustnost z K_{s}: sůl typu AB_{2}', problem: 'K_{s}($CaF2$) = 3,9·10^{−11}. Jaká je rozpustnost fluoridu vápenatého? ($M$ = 78 g/mol)', steps: [
              'Rozpustí-li se s mol/dm³, je $[Ca^{2+}]$ = s a $[F^-]$ = 2s.',
              'K_{s} = s · (2s)^{2} = 4s^{3} = 3,9·10^{−11}',
              's = ∛(3,9·10^{−11} / 4) = ∛(9,75·10^{−12}) = 2,1·10^{−4} mol/dm³',
              'm = 2,1·10^{−4} mol · 78 g/mol = 0,017 g',
            ], answer: 'Rozpustnost $CaF2$ je 2,1·10^{−4} mol/dm³, asi 17 mg na litr.' },
            { type: 'example', title: 'K_{s} z rozpustnosti', problem: 'V 1 dm³ vody se rozpustí 2,4 mg síranu barnatého ($M$ = 233 g/mol). Vypočítej K_{s}($BaSO4$).', steps: [
              's = 0,0024 g / 233 g/mol = 1,03·10^{−5} mol/dm³',
              '$[Ba^{2+}]$ = $[SO4^{2-}]$ = s',
              'K_{s} = s^{2} = (1,03·10^{−5})^{2} = 1,1·10^{−10}',
            ], answer: 'K_{s}($BaSO4$) ≈ 1,1·10^{−10}, přesně jako v tabulce.' },
            { type: 'table', headers: ['Sůl', 'Typ', 'K_{s} (25 °C)', 'Rozpustnost / mol·dm^{−3}'], rows: [
              ['$CaCO3$', 'AB', '3,4·10^{−9}', '5,8·10^{−5}'],
              ['$AgCl$', 'AB', '1,8·10^{−10}', '1,3·10^{−5}'],
              ['$BaSO4$', 'AB', '1,1·10^{−10}', '1,0·10^{−5}'],
              ['$AgI$', 'AB', '8,3·10^{−17}', '9,1·10^{−9}'],
              ['$CaF2$', 'AB_{2}', '3,9·10^{−11}', '2,1·10^{−4}'],
              ['$Ag2CrO4$', 'A_{2}B', '1,1·10^{−12}', '6,5·10^{−5}'],
            ], caption: 'Rozpustnost je vypočtená z K_{s} pro čistou vodu.' },
            { type: 'callout', variant: 'warning', title: 'Porovnávej jen soli stejného typu', text: '$Ag2CrO4$ má menší K_{s} než $AgCl$, a přesto je asi 5× **rozpustnější**. Podle K_{s} přímo porovnáš jen soli stejného typu (AB s AB). Jinak spočítej rozpustnost s.' },
            { type: 'callout', variant: 'fact', text: 'Ionty barya jsou jedovaté, a přesto pacienti před rentgenem polykají kaši síranu barnatého. $BaSO4$ je tak nerozpustný, že se ho vstřebá zanedbatelně, a přitom krásně zobrazí trávicí trubici.' },
            { type: 'check', question: { kind: 'choice', q: 'Sůl typu $AB2$ (např. $CaF2$) má součin rozpustnosti K_{s}. Jak z něj spočítáš rozpustnost s?', options: ['s = ∛(K_{s} / 4)', 's = √(K_{s})', 's = K_{s} / 2', 's = ∛(K_{s})'], answer: 0, explain: 'Z s mol soli vznikne s mol $A^{2+}$ a 2s mol $B^-$. K_{s} = s · (2s)^{2} = 4s^{3}, a proto s = ∛(K_{s} / 4).' } },
          ],
        },
        {
          title: 'Společný ion a vznik sraženiny',
          icon: 'test-tube',
          blocks: [
            { type: 'p', text: 'Co když sůl nerozpouštíš v čisté vodě, ale v roztoku, který už jeden z jejích iontů obsahuje? Podle Le Chateliera se rovnováha posune doleva a sůl se rozpustí **méně**. To je **vliv společného iontu**.' },
            { type: 'particles', boxes: [
              { label: 'nasycený roztok $AgCl$', items: [{ species: 'AgCl', count: 5 }, { species: 'Ag^+', count: 2 }, { species: 'Cl^-', count: 2 }], state: 'solution' },
              { label: 'po přidání $NaCl$', items: [{ species: 'AgCl', count: 6 }, { species: 'Ag^+', count: 1 }, { species: 'Cl^-', count: 4 }, { species: 'Na^+', count: 3 }], state: 'solution', note: 'část $AgCl$ se vysráží' },
            ], arrows: true, caption: 'Přidaný chlorid posune rovnováhu $AgCl(s) <=> Ag^+ + Cl^-$ doleva.' },
            { type: 'example', title: 'Rozpustnost se společným iontem', problem: 'Jaká je rozpustnost $AgCl$ v roztoku $NaCl$ o koncentraci 0,10 mol/dm³? (K_{s} = 1,8·10^{−10})', steps: [
              '$[Cl^-]$ = 0,10 + s ≈ 0,10 mol/dm³ (s je nepatrné)',
              'K_{s} = $[Ag^+]·[Cl^-]$ = s · 0,10',
              's = 1,8·10^{−10} / 0,10 = 1,8·10^{−9} mol/dm³',
              'V čisté vodě je s = 1,3·10^{−5} mol/dm³; 1,3·10^{−5} / 1,8·10^{−9} ≈ 7 000',
            ], answer: 'V roztoku $NaCl$ se $AgCl$ rozpustí asi 7 000× méně než ve vodě.' },
            { type: 'callout', variant: 'tip', text: 'V analytické chemii se proto sraženina promývá zředěným roztokem se společným iontem, ne čistou vodou. Méně se jí rozpustí a výsledek vážení je přesnější.' },
            { type: 'p', text: 'Vznikne po smíchání dvou roztoků sraženina? Spočítej **iontový součin** Q: stejný výraz jako K_{s}, ale s koncentracemi **hned po smíchání**.' },
            { type: 'compare', columns: [
              { title: 'Q < K_{s}', icon: 'drop', tone: 'a', points: ['roztok je **nenasycený**', 'sraženina nevznikne, další sůl by se ještě rozpustila'] },
              { title: 'Q = K_{s}', icon: 'equilibrium', tone: 'good', points: ['roztok je právě **nasycený**', 'rovnováha'] },
              { title: 'Q > K_{s}', icon: 'crystal', tone: 'b', points: ['roztok je **přesycený**', 'vylučuje se **sraženina**, dokud Q neklesne na K_{s}'] },
            ], caption: 'Stejná logika jako Q a K z minulé lekce' },
            { type: 'example', title: 'Vznikne sraženina?', problem: 'Smícháš stejné objemy roztoku $AgNO3$ a $NaCl$, oba o koncentraci 1,0·10^{−3} mol/dm³. Vznikne sraženina $AgCl$? (K_{s} = 1,8·10^{−10})', steps: [
              'Smícháním stejných objemů se objem zdvojnásobí a každá koncentrace klesne na polovinu: $[Ag^+]$ = $[Cl^-]$ = 5,0·10^{−4} mol/dm³.',
              'Q = 5,0·10^{−4} · 5,0·10^{−4} = 2,5·10^{−7}',
              'Q = 2,5·10^{−7} > K_{s} = 1,8·10^{−10}',
            ], answer: 'Ano, bílá sraženina $AgCl$ vznikne i v takto zředěných roztocích. Proto je dusičnan stříbrný citlivým důkazem chloridů.' },
            { type: 'reaction', equation: 'AgNO3 + NaCl -> AgCl + NaNO3', caption: 'Iontově: $Ag^+(aq) + Cl^-(aq) -> AgCl(s)$; ionty $Na^+$ a $NO3^-$ jsou jen přihlížející.' },
            { type: 'example', title: 'Kdy se začne srážet?', problem: 'V roztoku je $[Ba^{2+}]$ = 1,0·10^{−3} mol/dm³. Při jaké koncentraci síranu se začne srážet $BaSO4$? (K_{s} = 1,1·10^{−10})', steps: [
              'Srážení začne, když Q dosáhne K_{s}: $[Ba^{2+}]·[SO4^{2-}]$ = 1,1·10^{−10}',
              '$[SO4^{2-}]$ = 1,1·10^{−10} / 1,0·10^{−3} = 1,1·10^{−7} mol/dm³',
            ], answer: 'Stačí nepatrných 1,1·10^{−7} mol/dm³ síranu. Nad touto koncentrací je Q > K_{s} a $BaSO4$ se sráží.' },
            { type: 'callout', variant: 'fact', title: 'Ledvinové kameny', text: 'Když v moči překročí iontový součin šťavelanu vápenatého jeho K_{s}, začnou se tvořit krystalky a z nich ledvinové kameny. Proto lékaři radí hodně pít: zředění sníží Q pod K_{s}.' },
            { type: 'game', gameId: 'quickfire', text: 'pK_{a}, pufry, K_{s}? Vyzkoušej si celou úroveň v bleskové výzvě na čas.' },
            { type: 'check', question: { kind: 'tf', q: 'Když je iontový součin Q menší než součin rozpustnosti K_{s}, vylučuje se sraženina.', answer: false, explain: 'Při Q < K_{s} je roztok nenasycený a sůl se může ještě rozpouštět. Sraženina vzniká až při Q > K_{s}.' } },
          ],
        },
      ],
      summary: [
        'Síla slabé kyseliny se vyjadřuje K_{a} nebo pK_{a}, síla slabé zásady K_{b} nebo pK_{b}; menší pK znamená silnější kyselinu či zásadu.',
        'Pro konjugovaný pár ve vodě při 25 °C platí K_{a} · K_{b} = K_{w}, tedy pK_{a} + pK_{b} = 14.',
        'pH slabé kyseliny je přibližně ½ · (pK_{a} − log c), u slabé zásady stejně spočítáš pOH; přiblížení platí, když se ionizuje méně než asi 5 %.',
        'Pufr je směs slabé kyseliny a její konjugované zásady; jeho pH udává Hendersonova–Hasselbalchova rovnice pH = pK_{a} + log ($[A^-] / [HA]$).',
        'Krev udržuje pH 7,35–7,45 hydrogenuhličitanovým pufrem, který řídí plíce a ledviny.',
        'Součin rozpustnosti K_{s} je rovnovážná konstanta rozpouštění málo rozpustné soli; pro sůl AB je s = √K_{s}, pro AB_{2} je s = ∛(K_{s} / 4).',
        'Společný ion rozpustnost snižuje a sraženina vzniká, když iontový součin Q překročí K_{s}.',
      ],
      quiz: [
        { kind: 'tf', q: 'Čím menší je pK_{a} kyseliny, tím je kyselina silnější.', answer: true, explain: 'pK_{a} = −log K_{a}; menší pK_{a} znamená větší K_{a}, tedy víc ionizovaných molekul.' },
        { kind: 'choice', q: 'Která z částic je nejsilnější zásada? (pK_{a} konjugovaných kyselin: $HF$ 3,17, $CH3COOH$ 4,76, $H2CO3$ 6,35, $NH4^+$ 9,25)', options: ['$NH3$', '$HCO3^-$', '$CH3COO^-$', '$F^-$'], answer: 0, explain: 'pK_{b} = 14 − pK_{a}. Nejslabší kyselina ($NH4^+$, pK_{a} = 9,25) má nejsilnější konjugovanou zásadu: $NH3$ s pK_{b} = 4,75.' },
        { kind: 'multi', q: 'Které směsi mohou fungovat jako pufr?', options: ['$CH3COOH$ + $CH3COONa$', '$NH3$ + $NH4Cl$', '$HCl$ + $NaCl$', '$NaH2PO4$ + $Na2HPO4$', '$NaOH$ + $NaCl$'], answers: [0, 1, 3], explain: 'Pufr potřebuje slabou kyselinu a její konjugovanou zásadu. $HCl$ i $NaOH$ jsou silné, a jejich směsi se solí proto pufry nejsou.' },
        { kind: 'number', q: 'Vypočítej pH roztoku amoniaku o koncentraci 0,010 mol/dm³ (pK_{b} = 4,75).', answer: 10.63, tolerance: 0.02, explain: 'pOH = ½ · (4,75 − log 0,010) = ½ · (4,75 + 2) = 3,375; pH = 14 − 3,375 = 10,625 ≈ 10,63.' },
        { kind: 'choice', q: 'Jaký je výraz pro součin rozpustnosti jodidu olovnatého $PbI2$?', options: ['K_{s} = $[Pb^{2+}]·[I^-]^2$', 'K_{s} = $[Pb^{2+}]·[I^-]$', 'K_{s} = $[Pb^{2+}]·[I^-]^2 / [PbI2]$', 'K_{s} = $[Pb^{2+}]·2[I^-]$'], answer: 0, explain: '$PbI2(s) <=> Pb^{2+} + 2I^-$. Pevná sůl se do výrazu nepíše a koeficient 2 se stane exponentem.' },
        { kind: 'tf', q: 'Chlorid stříbrný je v roztoku chloridu sodného rozpustnější než v čisté vodě.', answer: false, explain: 'Chlorid je společný ion. Posune rovnováhu $AgCl(s) <=> Ag^+ + Cl^-$ doleva, takže se $AgCl$ rozpustí méně.' },
        { kind: 'choice', q: 'Smícháš stejné objemy roztoků $CaCl2$ (0,020 mol/dm³) a $NaF$ (0,0020 mol/dm³). K_{s}($CaF2$) = 3,9·10^{−11}. Vznikne sraženina?', options: ['ano, Q = 1,0·10^{−8} > K_{s}', 'ne, Q = 1,0·10^{−8} < K_{s}', 'ne, fluorid vápenatý je dobře rozpustný', 'nelze rozhodnout bez znalosti objemů'], answer: 0, explain: 'Po smíchání je $[Ca^{2+}]$ = 0,010 a $[F^-]$ = 0,0010 mol/dm³. Q = 0,010 · 0,0010^{2} = 1,0·10^{−8}, což je víc než K_{s}, a proto se $CaF2$ vysráží.' },
      ],
    },
}
