/**
 * Short fun facts in the first person ("Jsem…"), used as a hint in "Kdo jsem?".
 * They must never contain the element's name or symbol.
 */
export const FACTS: Record<string, string> = {
  H: 'Jsem nejlehčí prvek a ve vesmíru mě je ze všech nejvíc – tvořím většinu hmoty hvězd.',
  He: 'Jsem lehčí než vzduch, a tak se mnou plní balónky a vzducholodě. Ve vesmíru jsem druhý nejrozšířenější prvek.',
  Li: 'Jsem nejlehčí kov, plavu i na oleji. Najdeš mě v bateriích mobilů a elektroaut.',
  Be: 'Zrcadla vesmírného dalekohledu Jamese Webba jsou ze mě, potažená tenkou vrstvou zlata.',
  B: 'Jedna moje sloučenina se přidává do domácího slizu a díky mně vydrží varné laboratorní sklo prudké změny teplot.',
  C: 'Jako diamant jsem nejtvrdší přírodní látka, jako tuha v tužce naopak měkce píšu po papíře.',
  N: 'Tvořím asi 78 % vzduchu. Kuchaři mě v kapalném stavu používají k bleskovému mražení zmrzliny.',
  O: 'Tvořím asi 21 % vzduchu. Beze mě by nehořel oheň a nedalo by se dýchat.',
  F: 'Mám největší elektronegativitu ze všech prvků. Moje sloučeniny chrání zuby v zubní pastě.',
  Ne: 'Když mnou prochází elektrický proud, svítím oranžovočerveně – proto mě mají staré reklamní trubice.',
  Na: 'Jsem tak měkký kov, že mě nakrájíš nožem, a s vodou prudce reaguji. S chlorem tvořím kuchyňskou sůl.',
  Mg: 'Hořím oslnivě bílým plamenem a sedím uprostřed molekuly chlorofylu v zelených listech.',
  Al: 'Jsem nejrozšířenější kov v zemské kůře. Ze mě je alobal i plechovky od limonád.',
  Si: 'Po kyslíku jsem druhý nejrozšířenější prvek zemské kůry a jsem základem počítačových čipů.',
  P: 'Moje bílá forma na vzduchu sama vzplane, červenou najdeš na škrtátku krabičky od zápalek.',
  S: 'Jsem žlutá pevná látka. Zkažená vejce páchnou po mé sloučenině s vodíkem.',
  Cl: 'Jako plyn jsem žlutozelený a jedovatý, ale moje sloučeniny dezinfikují vodu v bazénech.',
  Ar: 'Jsem třetí nejhojnější plyn ve vzduchu (skoro 1 %) a chráním vlákna žárovek, aby neshořela.',
  K: 'Je mě hodně v banánech. S vodou reaguji tak prudce, že to vzplane fialovým plamenem.',
  Ca: 'Stavím tvoje kosti a zuby a jsem ve vápenci, křídě i mramoru.',
  Ti: 'Jsem pevný jako ocel, ale skoro o polovinu lehčí. Dělají ze mě kloubní náhrady i rámy kol.',
  Cr: 'Díky mně nerezová ocel nerezaví a pochromované kliky se lesknou jako zrcadlo.',
  Mn: 'Moje sloučenina hypermangan barví vodu do fialova a dezinfikuje rány.',
  Fe: 'Jsem nejpoužívanější kov na světě a v hemoglobinu přenáším kyslík v tvé krvi.',
  Co: 'Moje sloučeniny barví sklo a porcelán sytě modrou barvou.',
  Ni: 'Jsem v jedno- a dvoueurových mincích a patřím mezi kovy, které přitahuje magnet.',
  Cu: 'Skvěle vedu elektrický proud, proto jsem v kabelech. Socha Svobody zezelenala díky mé zelené patině.',
  Zn: 'Chráním železo před rezavěním – ocelové plechy se mnou potahují. S mědí tvořím mosaz.',
  Ga: 'Taju už při 30 °C, takže se roztavím v teplé dlani.',
  Ge: 'Mendělejev předpověděl moje vlastnosti dřív, než mě kdokoli objevil. Nesu jméno země, kde mě našli.',
  As: 'Jsem proslulý jed, oblíbený v detektivkách Agathy Christie.',
  Br: 'Jsem jeden ze dvou prvků, které jsou za pokojové teploty kapalné – hnědočervená a páchnoucí kapalina.',
  Kr: 'Jsem vzácný plyn a Supermanova planeta nese skoro stejné jméno jako já.',
  Sr: 'V ohňostrojích barvím plamen sytě červeně.',
  Ag: 'Vedu elektrický proud a teplo nejlépe ze všech kovů. Ze mě jsou šperky, příbory i olympijské medaile za druhé místo.',
  Sn: 'Pájí se mnou elektronika a tenkou vrstvou chráním plechovky od konzerv před rezavěním.',
  I: 'Když mě zahřeješ, fialově černé krystaly se rovnou mění na fialové páry. Přidávají mě do soli kvůli štítné žláze.',
  Xe: 'Svítím v jasných výbojkách světlometů aut a jsem palivem iontových motorů vesmírných sond.',
  Cs: 'Kmity mých atomů v atomových hodinách určují, jak dlouho trvá jedna sekunda.',
  Ba: 'Moje sloučenina se pije před rentgenem žaludku a v ohňostrojích barvím plamen zeleně.',
  W: 'Mám nejvyšší teplotu tání ze všech kovů, přes 3 400 °C, proto ze mě byla vlákna žárovek.',
  Pt: 'Jsem vzácný kov v autokatalyzátorech, které čistí výfukové plyny.',
  Au: 'Nereaguji se vzduchem ani s vodou, takže poklady ze mě se lesknou i po tisících let.',
  Hg: 'Jsem jediný kov, který je za pokojové teploty kapalný. Dřív jsem býval v teploměrech.',
  Pb: 'Jsem těžký a měkký kov a stíním rentgenové záření. Staří Římané ze mě dělali vodovodní trubky.',
  Bi: 'Moje krystaly tvoří duhově zbarvené schodovité kostičky.',
  Po: 'Objevila mě Marie Curie-Skłodowská a pojmenovala mě po své vlasti.',
  Rn: 'Jsem radioaktivní vzácný plyn, který se může hromadit ve sklepech domů.',
  Ra: 'Objevili mě manželé Curieovi a kdysi jsem světélkoval na cifernících hodinek.',
  U: 'Štěpením mých jader vyrábějí jaderné elektrárny elektřinu. Dřív se mě hodně těžilo v Jáchymově.',
}
