/**
 * Country codes the map block accepts (Natural Earth ADM0_A3, equal to ISO 3166-1 alpha-3 for almost every state)
 * with their Czech names, and the 14 Czech regions (ISO 3166-2). Generated from Natural Earth 1:50m admin-0;
 * the map data in src/geo/data uses the same codes. Kept small: the validator imports it.
 */
export const COUNTRY_NAMES: Record<string, string> = {
  ABW: "Aruba",
  AFG: "Afghánistán",
  AGO: "Angola",
  AIA: "Anguilla",
  ALB: "Albánie",
  ALD: "Ålandy",
  AND: "Andorra",
  ARE: "Spojené arabské emiráty",
  ARG: "Argentina",
  ARM: "Arménie",
  ASM: "Americká Samoa",
  ATA: "Antarktida",
  ATC: "Austrálie",
  ATF: "Francouzská jižní území",
  ATG: "Antigua a Barbuda",
  AUS: "Austrálie",
  AUT: "Rakousko",
  AZE: "Ázerbájdžán",
  BDI: "Burundi",
  BEL: "Belgie",
  BEN: "Benin",
  BFA: "Burkina Faso",
  BGD: "Bangladéš",
  BGR: "Bulharsko",
  BHR: "Bahrajn",
  BHS: "Bahamy",
  BIH: "Bosna a Hercegovina",
  BLM: "Svatý Bartoloměj",
  BLR: "Bělorusko",
  BLZ: "Belize",
  BMU: "Bermudy",
  BOL: "Bolívie",
  BRA: "Brazílie",
  BRB: "Barbados",
  BRN: "Brunej",
  BTN: "Bhútán",
  BWA: "Botswana",
  CAF: "Středoafrická republika",
  CAN: "Kanada",
  CHE: "Švýcarsko",
  CHL: "Chile",
  CHN: "Čína",
  CIV: "Pobřeží slonoviny",
  CMR: "Kamerun",
  COD: "Demokratická republika Kongo",
  COG: "Kongo",
  COK: "Cookovy ostrovy",
  COL: "Kolumbie",
  COM: "Komory",
  CPV: "Kapverdy",
  CRI: "Kostarika",
  CUB: "Kuba",
  CUW: "Curaçao",
  CYM: "Kajmanské ostrovy",
  CYN: "Severní Kypr",
  CYP: "Kypr",
  CZE: "Česko",
  DEU: "Německo",
  DJI: "Džibutsko",
  DMA: "Dominika",
  DNK: "Dánsko",
  DOM: "Dominikánská republika",
  DZA: "Alžírsko",
  ECU: "Ekvádor",
  EGY: "Egypt",
  ERI: "Eritrea",
  ESP: "Španělsko",
  EST: "Estonsko",
  ETH: "Etiopie",
  FIN: "Finsko",
  FJI: "Fidži",
  FLK: "Falklandské ostrovy",
  FRA: "Francie",
  FRO: "Faerské ostrovy",
  FSM: "Mikronésie",
  GAB: "Gabon",
  GBR: "Spojené království",
  GEO: "Gruzie",
  GGY: "Guernsey",
  GHA: "Ghana",
  GIN: "Guinea",
  GMB: "Gambie",
  GNB: "Guinea-Bissau",
  GNQ: "Rovníková Guinea",
  GRC: "Řecko",
  GRD: "Grenada",
  GRL: "Grónsko",
  GTM: "Guatemala",
  GUM: "Guam",
  GUY: "Guyana",
  HKG: "Hongkong – ZAO Číny",
  HMD: "Heardův ostrov a McDonaldovy ostrovy",
  HND: "Honduras",
  HRV: "Chorvatsko",
  HTI: "Haiti",
  HUN: "Maďarsko",
  IDN: "Indonésie",
  IMN: "Ostrov Man",
  IND: "Indie",
  IOA: "Austrálie",
  IOT: "Britské indickooceánské území",
  IRL: "Irsko",
  IRN: "Írán",
  IRQ: "Irák",
  ISL: "Island",
  ISR: "Izrael",
  ITA: "Itálie",
  JAM: "Jamajka",
  JEY: "Jersey",
  JOR: "Jordánsko",
  JPN: "Japonsko",
  KAS: "Siačenský ledovec",
  KAZ: "Kazachstán",
  KEN: "Keňa",
  KGZ: "Kyrgyzstán",
  KHM: "Kambodža",
  KIR: "Kiribati",
  KNA: "Svatý Kryštof a Nevis",
  KOR: "Jižní Korea",
  KOS: "Kosovo",
  KWT: "Kuvajt",
  LAO: "Laos",
  LBN: "Libanon",
  LBR: "Libérie",
  LBY: "Libye",
  LCA: "Svatá Lucie",
  LIE: "Lichtenštejnsko",
  LKA: "Srí Lanka",
  LSO: "Lesotho",
  LTU: "Litva",
  LUX: "Lucembursko",
  LVA: "Lotyšsko",
  MAC: "Macao – ZAO Číny",
  MAF: "Svatý Martin (Francie)",
  MAR: "Maroko",
  MCO: "Monako",
  MDA: "Moldavsko",
  MDG: "Madagaskar",
  MDV: "Maledivy",
  MEX: "Mexiko",
  MHL: "Marshallovy ostrovy",
  MKD: "Severní Makedonie",
  MLI: "Mali",
  MLT: "Malta",
  MMR: "Myanmar",
  MNE: "Černá Hora",
  MNG: "Mongolsko",
  MNP: "Severní Mariany",
  MOZ: "Mosambik",
  MRT: "Mauritánie",
  MSR: "Montserrat",
  MUS: "Mauricius",
  MWI: "Malawi",
  MYS: "Malajsie",
  NAM: "Namibie",
  NCL: "Nová Kaledonie",
  NER: "Niger",
  NFK: "Norfolk",
  NGA: "Nigérie",
  NIC: "Nikaragua",
  NIU: "Niue",
  NLD: "Nizozemsko",
  NOR: "Norsko",
  NPL: "Nepál",
  NRU: "Nauru",
  NZL: "Nový Zéland",
  OMN: "Omán",
  PAK: "Pákistán",
  PAN: "Panama",
  PCN: "Pitcairnovy ostrovy",
  PER: "Peru",
  PHL: "Filipíny",
  PLW: "Palau",
  PNG: "Papua-Nová Guinea",
  POL: "Polsko",
  PRI: "Portoriko",
  PRK: "Severní Korea",
  PRT: "Portugalsko",
  PRY: "Paraguay",
  PSX: "Palestina",
  PYF: "Francouzská Polynésie",
  QAT: "Katar",
  ROU: "Rumunsko",
  RUS: "Rusko",
  RWA: "Rwanda",
  SAH: "Západní Sahara",
  SAU: "Saúdská Arábie",
  SDN: "Súdán",
  SDS: "Jižní Súdán",
  SEN: "Senegal",
  SGP: "Singapur",
  SGS: "Jižní Georgie a Jižní Sandwichovy ostrovy",
  SHN: "Svatá Helena",
  SLB: "Šalamounovy ostrovy",
  SLE: "Sierra Leone",
  SLV: "Salvador",
  SMR: "San Marino",
  SOL: "Somaliland",
  SOM: "Somálsko",
  SPM: "Saint-Pierre a Miquelon",
  SRB: "Srbsko",
  STP: "Svatý Tomáš a Princův ostrov",
  SUR: "Surinam",
  SVK: "Slovensko",
  SVN: "Slovinsko",
  SWE: "Švédsko",
  SWZ: "Eswatini",
  SXM: "Svatý Martin (Nizozemsko)",
  SYC: "Seychely",
  SYR: "Sýrie",
  TCA: "Turks a Caicos",
  TCD: "Čad",
  TGO: "Togo",
  THA: "Thajsko",
  TJK: "Tádžikistán",
  TKM: "Turkmenistán",
  TLS: "Východní Timor",
  TON: "Tonga",
  TTO: "Trinidad a Tobago",
  TUN: "Tunisko",
  TUR: "Turecko",
  TUV: "Tuvalu",
  TWN: "Tchaj-wan",
  TZA: "Tanzanie",
  UGA: "Uganda",
  UKR: "Ukrajina",
  URY: "Uruguay",
  USA: "Spojené státy americké",
  UZB: "Uzbekistán",
  VAT: "Vatikán",
  VCT: "Svatý Vincenc a Grenadiny",
  VEN: "Venezuela",
  VGB: "Britské Panenské ostrovy",
  VIR: "Americké Panenské ostrovy",
  VNM: "Vietnam",
  VUT: "Vanuatu",
  WLF: "Wallis a Futuna",
  WSM: "Samoa",
  YEM: "Jemen",
  ZAF: "Jihoafrická republika",
  ZMB: "Zambie",
  ZWE: "Zimbabwe",
}

/** Czech regions (kraje), ISO 3166-2 codes. */
export const CZ_REGION_NAMES: Record<string, string> = {
  "CZ-10": "Hlavní město Praha",
  "CZ-20": "Středočeský kraj",
  "CZ-31": "Jihočeský kraj",
  "CZ-32": "Plzeňský kraj",
  "CZ-41": "Karlovarský kraj",
  "CZ-42": "Ústecký kraj",
  "CZ-51": "Liberecký kraj",
  "CZ-52": "Královéhradecký kraj",
  "CZ-53": "Pardubický kraj",
  "CZ-63": "Kraj Vysočina",
  "CZ-64": "Jihomoravský kraj",
  "CZ-71": "Olomoucký kraj",
  "CZ-72": "Zlínský kraj",
  "CZ-80": "Moravskoslezský kraj",
}
