/**
 * Lazy loading and decoding of the map data modules (src/geo/data/*.ts, generated by scripts/geo/build-geo.mjs).
 * Each module becomes its own chunk; nothing in src/geo/data may be imported any other way.
 */
import type { MapView } from '../core/types'
import type { CountryModule, PlatesModule } from './types'

const LOADERS: Record<MapView, () => Promise<{ default: CountryModule }>> = {
  world: () => import('./data/world'),
  europe: () => import('./data/europe'),
  'central-europe': () => import('./data/central-europe'),
  czechia: () => import('./data/czechia'),
  africa: () => import('./data/africa'),
  asia: () => import('./data/asia'),
  'middle-east': () => import('./data/middle-east'),
  'north-america': () => import('./data/north-america'),
  'latin-america': () => import('./data/latin-america'),
  oceania: () => import('./data/oceania'),
  arctic: () => import('./data/arctic'),
  antarctica: () => import('./data/antarctica'),
}

/** A decoded shape: rings as flat [lon, lat, lon, lat, …] arrays, plus their arc references and bounds. */
export interface Shape {
  code: string
  refs: number[][]
  rings: Float64Array[]
  /** lon/lat bounds [w, s, e, n] */
  bbox: [number, number, number, number]
}
export interface Line {
  name: string
  rank: number
  parts: Float64Array[]
}
export interface GeoData {
  view: MapView
  q: number
  /** decoded arcs, flat lon/lat */
  arcs: Float64Array[]
  /** arc indices on the clip frame / antimeridian (never stroked) */
  frame: Set<number>
  countries: Map<string, Shape>
  regions: Map<string, Shape>
  labels: Record<string, [number, number]>
  lakes: Line[]
  rivers: Line[]
}
export interface PlatesData {
  lines: { name: string; subduction: boolean; pts: Float64Array }[]
}

const ALPH = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_'
const VAL = new Int8Array(128).fill(-1)
for (let i = 0; i < ALPH.length; i++) VAL[ALPH.charCodeAt(i)] = i

/** Decodes a coordinate string (zigzag varint deltas, base64url) into flat lon/lat degrees. */
export function decode(s: string, q: number): Float64Array {
  const ints: number[] = []
  let v = 0
  let mul = 1
  for (let i = 0; i < s.length; i++) {
    const c = VAL[s.charCodeAt(i)]
    v += (c & 31) * mul
    if (c & 32) mul *= 32
    else {
      ints.push(v % 2 ? -(v + 1) / 2 : v / 2)
      v = 0
      mul = 1
    }
  }
  const out = new Float64Array(ints.length)
  let x = 0
  let y = 0
  for (let i = 0; i + 1 < ints.length; i += 2) {
    x += ints[i]
    y += ints[i + 1]
    out[i] = Math.round(x * q * 1e6) / 1e6
    out[i + 1] = Math.round(y * q * 1e6) / 1e6
  }
  return out
}

/** Joins arcs (refs: i or ~i reversed) into one ring, without the closing point. */
export function ringOf(arcs: Float64Array[], refs: number[]): Float64Array {
  let n = 0
  for (const r of refs) n += arcs[r < 0 ? ~r : r].length - 2
  const out = new Float64Array(Math.max(0, n))
  let o = 0
  for (const r of refs) {
    const a = arcs[r < 0 ? ~r : r]
    const m = a.length / 2
    // every arc's last point is the next arc's first: skip it
    for (let j = 0; j < m - 1; j++) {
      const k = r < 0 ? m - 1 - j : j
      out[o++] = a[2 * k]
      out[o++] = a[2 * k + 1]
    }
  }
  return out
}

function shapes(list: [string, number[][]][] | undefined, arcs: Float64Array[]): Map<string, Shape> {
  const m = new Map<string, Shape>()
  for (const [code, refs] of list ?? []) {
    const rings = refs.map((r) => ringOf(arcs, r))
    const bbox: [number, number, number, number] = [Infinity, Infinity, -Infinity, -Infinity]
    for (const r of rings)
      for (let i = 0; i < r.length; i += 2) {
        if (r[i] < bbox[0]) bbox[0] = r[i]
        if (r[i] > bbox[2]) bbox[2] = r[i]
        if (r[i + 1] < bbox[1]) bbox[1] = r[i + 1]
        if (r[i + 1] > bbox[3]) bbox[3] = r[i + 1]
      }
    m.set(code, { code, refs, rings, bbox })
  }
  return m
}

/** Decodes a raw module (exported for tests and tools). */
export function decodeModule(view: MapView, mod: CountryModule): GeoData {
  const arcs = mod.arcs.map((s) => decode(s, mod.q))
  const line = ([name, rank, parts]: [string, number, string[]]): Line => ({ name, rank, parts: parts.map((p) => decode(p, mod.q)) })
  return {
    view,
    q: mod.q,
    arcs,
    frame: new Set(mod.frame),
    countries: shapes(mod.countries, arcs),
    regions: shapes(mod.regions, arcs),
    labels: mod.labels,
    lakes: mod.lakes.map(line),
    rivers: mod.rivers.map(line),
  }
}

const cache = new Map<MapView, GeoData>()
const pending = new Map<MapView, Promise<GeoData>>()

/** Loads (once) and decodes the data of a view. */
export function loadView(view: MapView): Promise<GeoData> {
  const hit = cache.get(view)
  if (hit) return Promise.resolve(hit)
  let p = pending.get(view)
  if (!p) {
    const loader = LOADERS[view]
    if (!loader) return Promise.reject(new Error(`unknown map view ${view}`))
    p = loader().then((m) => {
      const d = decodeModule(view, m.default)
      cache.set(view, d)
      return d
    })
    p.catch(() => pending.delete(view))
    pending.set(view, p)
  }
  return p
}

/** The view's data if it is already loaded (synchronous; for rendering and hit tests). */
export function peekView(view: MapView): GeoData | undefined {
  return cache.get(view)
}

let plates: PlatesData | undefined
let platesP: Promise<PlatesData> | undefined

/** PB2002 plate boundaries (Bird 2003), loaded once. */
export function loadPlates(): Promise<PlatesData> {
  if (plates) return Promise.resolve(plates)
  platesP ??= import('./data/plates').then((m) => {
    const mod: PlatesModule = m.default
    plates = { lines: mod.lines.map(([name, sub, s]) => ({ name, subduction: sub === 1, pts: decode(s, mod.q) })) }
    return plates
  })
  return platesP
}
export function peekPlates(): PlatesData | undefined {
  return plates
}
