import type { Course } from '../../core/types'

/**
 * Chemistry course outline. The full syllabus with curriculum alignment
 * lives in spec/courses/chemie/syllabus.md – keep both in sync.
 * Lesson bodies are lazy-loaded per level from ./levels/lN.ts.
 */
export const chemie: Course = {
  id: 'chemie',
  title: 'Chemie',
  tagline: 'Od první zkumavky až po organiku a biochemii.',
  color: '#a8561a',
  available: true,
  levels: [
    {
      id: 'l1',
      number: 1,
      title: 'Svět látek',
      subtitle: 'Co je chemie, vlastnosti látek, směsi a roztoky',
      stage: 'ZŠ 8. třída · IGCSE 1',
      color: '#b8483a',
      symbol: 'H',
      games: ['swipe', 'quickfire'],
      load: () => import('./levels/l1').then((m) => m.default),
      lessons: [
        { id: 'l1-1', title: 'Co je chemie a jak bezpečně pracovat', minutes: 12 },
        { id: 'l1-2', title: 'Vlastnosti látek a skupenství', minutes: 14 },
        { id: 'l1-3', title: 'Směsi a chemicky čisté látky', minutes: 12 },
        { id: 'l1-4', title: 'Jak oddělit složky směsí', minutes: 15 },
        { id: 'l1-5', title: 'Roztoky a hmotnostní zlomek', minutes: 16 },
        { id: 'l1-6', title: 'Voda a vzduch', minutes: 14 },
      ],
    },
    {
      id: 'l2',
      number: 2,
      title: 'Uvnitř atomu',
      subtitle: 'Částice, stavba atomu, elektronový obal a periodická tabulka',
      stage: 'ZŠ 8. třída → gymnázium 1',
      color: '#bd6a26',
      symbol: 'He',
      games: ['build-atom', 'periodic-find', 'element-memory', 'electron-config', 'who-am-i'],
      load: () => import('./levels/l2').then((m) => m.default),
      lessons: [
        { id: 'l2-1', title: 'Atomy, molekuly a ionty', minutes: 12 },
        { id: 'l2-2', title: 'Stavba atomu: jádro a obal', minutes: 14 },
        { id: 'l2-3', title: 'Protonové číslo, nukleonové číslo a izotopy', minutes: 15 },
        { id: 'l2-4', title: 'Elektronové vrstvy a valenční elektrony', minutes: 14 },
        { id: 'l2-5', title: 'Orbitaly a elektronová konfigurace', minutes: 18 },
        { id: 'l2-6', title: 'Periodická soustava prvků', minutes: 16 },
      ],
    },
    {
      id: 'l3',
      number: 3,
      title: 'Vazby a názvosloví',
      subtitle: 'Jak se atomy spojují a jak sloučeniny pojmenovat',
      stage: 'ZŠ 8.–9. třída → gymnázium 1',
      color: '#9c7a12',
      symbol: 'Li',
      games: ['ion-builder', 'naming', 'quickfire'],
      load: () => import('./levels/l3').then((m) => m.default),
      lessons: [
        { id: 'l3-1', title: 'Proč se atomy spojují: elektronegativita', minutes: 12 },
        { id: 'l3-2', title: 'Kovalentní vazba a tvary molekul', minutes: 17 },
        { id: 'l3-3', title: 'Iontová a kovová vazba', minutes: 14 },
        { id: 'l3-4', title: 'Mezimolekulové síly a vlastnosti látek', minutes: 14 },
        { id: 'l3-5', title: 'Oxidační číslo a chemické vzorce', minutes: 15 },
        { id: 'l3-6', title: 'Názvosloví dvouprvkových sloučenin', minutes: 18 },
      ],
    },
    {
      id: 'l4',
      number: 4,
      title: 'Reakce a výpočty',
      subtitle: 'Chemické rovnice, mol a chemické počty',
      stage: 'ZŠ 8.–9. třída → gymnázium 1–2',
      color: '#56834a',
      symbol: 'Be',
      games: ['balance', 'molar-mass', 'quickfire'],
      load: () => import('./levels/l4').then((m) => m.default),
      lessons: [
        { id: 'l4-1', title: 'Chemická reakce a zákon zachování hmotnosti', minutes: 12 },
        { id: 'l4-2', title: 'Vyčíslování chemických rovnic', minutes: 16 },
        { id: 'l4-3', title: 'Typy chemických reakcí', minutes: 14 },
        { id: 'l4-4', title: 'Látkové množství a molární hmotnost', minutes: 17 },
        { id: 'l4-5', title: 'Koncentrace roztoků a ředění', minutes: 17 },
        { id: 'l4-6', title: 'Výpočty z chemických rovnic', minutes: 18 },
      ],
    },
    {
      id: 'l5',
      number: 5,
      title: 'Kyseliny, zásady a soli',
      subtitle: 'pH, indikátory, neutralizace a názvosloví kyselin a solí',
      stage: 'ZŠ 9. třída → gymnázium 2',
      color: '#2c7a72',
      symbol: 'B',
      games: ['ph-lab', 'titration', 'naming', 'swipe'],
      load: () => import('./levels/l5').then((m) => m.default),
      lessons: [
        { id: 'l5-1', title: 'Kyseliny a jejich názvosloví', minutes: 17 },
        { id: 'l5-2', title: 'Hydroxidy a zásady', minutes: 13 },
        { id: 'l5-3', title: 'pH a indikátory', minutes: 15 },
        { id: 'l5-4', title: 'Neutralizace a titrace', minutes: 16 },
        { id: 'l5-5', title: 'Soli a jejich názvosloví', minutes: 17 },
        { id: 'l5-6', title: 'Teorie kyselin a zásad podle Brønsteda', minutes: 15 },
      ],
    },
    {
      id: 'l6',
      number: 6,
      title: 'Energie, rychlost a rovnováha',
      subtitle: 'Redoxní děje, elektrochemie, termochemie, kinetika a rovnováhy',
      stage: 'Gymnázium 2 · A-level / AP',
      color: '#3f6699',
      symbol: 'C',
      games: ['quickfire', 'swipe'],
      load: () => import('./levels/l6').then((m) => m.default),
      lessons: [
        { id: 'l6-1', title: 'Redoxní reakce', minutes: 17 },
        { id: 'l6-2', title: 'Elektrochemie: články a elektrolýza', minutes: 17 },
        { id: 'l6-3', title: 'Termochemie a Hessův zákon', minutes: 17 },
        { id: 'l6-4', title: 'Rychlost reakce a katalýza', minutes: 15 },
        { id: 'l6-5', title: 'Chemická rovnováha a Le Chatelierův princip', minutes: 16 },
        { id: 'l6-6', title: 'Rovnovážná konstanta, slabé kyseliny a pufry', minutes: 19 },
      ],
    },
    {
      id: 'l7',
      number: 7,
      title: 'Chemie prvků',
      subtitle: 'Anorganická chemie: od vodíku po přechodné kovy',
      stage: 'Gymnázium 2–3 · IGCSE / A-level',
      color: '#555a9e',
      symbol: 'N',
      games: ['who-am-i', 'periodic-find', 'naming', 'quickfire'],
      load: () => import('./levels/l7').then((m) => m.default),
      lessons: [
        { id: 'l7-1', title: 'Vodík, kyslík a voda', minutes: 15 },
        { id: 'l7-2', title: 'Halogeny a vzácné plyny', minutes: 15 },
        { id: 'l7-3', title: 'Síra, dusík a fosfor', minutes: 17 },
        { id: 'l7-4', title: 'Uhlík a křemík', minutes: 14 },
        { id: 'l7-5', title: 'Alkalické kovy a kovy alkalických zemin', minutes: 15 },
        { id: 'l7-6', title: 'Hliník, železo, měď a přechodné kovy', minutes: 18 },
      ],
    },
    {
      id: 'l8',
      number: 8,
      title: 'Organická chemie',
      subtitle: 'Uhlovodíky, deriváty, reakce a polymery',
      stage: 'Gymnázium 3 · A-level / AP',
      color: '#7a5290',
      symbol: 'O',
      games: ['functional-groups', 'quickfire', 'swipe'],
      load: () => import('./levels/l8').then((m) => m.default),
      lessons: [
        { id: 'l8-1', title: 'Uhlík v organice: vzorce a izomerie', minutes: 16 },
        { id: 'l8-2', title: 'Alkany a cykloalkany', minutes: 17 },
        { id: 'l8-3', title: 'Alkeny, alkyny a aromáty', minutes: 17 },
        { id: 'l8-4', title: 'Halogenderiváty, alkoholy, fenoly a ethery', minutes: 17 },
        { id: 'l8-5', title: 'Karbonylové sloučeniny, kyseliny a estery', minutes: 18 },
        { id: 'l8-6', title: 'Dusíkaté deriváty, reakční mechanismy a polymery', minutes: 19 },
      ],
    },
    {
      id: 'l9',
      number: 9,
      title: 'Biochemie a chemie kolem nás',
      subtitle: 'Molekuly života a chemie v každodenním světě',
      stage: 'Gymnázium 3–4 · maturita',
      color: '#a84d6c',
      symbol: 'F',
      games: ['functional-groups', 'quickfire', 'swipe'],
      load: () => import('./levels/l9').then((m) => m.default),
      lessons: [
        { id: 'l9-1', title: 'Sacharidy', minutes: 16 },
        { id: 'l9-2', title: 'Lipidy', minutes: 14 },
        { id: 'l9-3', title: 'Aminokyseliny a bílkoviny', minutes: 17 },
        { id: 'l9-4', title: 'Enzymy, vitaminy a hormony', minutes: 15 },
        { id: 'l9-5', title: 'Nukleové kyseliny', minutes: 15 },
        { id: 'l9-6', title: 'Chemie v životě: léčiva, paliva a životní prostředí', minutes: 17 },
      ],
    },
  ],
}
