import { describe, expect, it } from 'vitest'
import { parseFormula } from '../../courses/chemie/data/formula'
import { GAME_BY_ID } from '../registry'
import { ANIONS, CATIONS, ionMarkup } from '../shared/ions'
import {
  LIGANDS,
  MULT,
  PARTNER,
  adjective,
  complexIon,
  feminine,
  genitive,
  hydroxide,
  salt,
  type BinaryPartner,
  type Ligand,
} from '../shared/nomenclature'
import { ORG_CAT_LABEL } from './organic'
import { LEVELS, MIX, NAMING_LEVELS, buildQuestions, itemsFor, markupOf, pool, specFor, type NItem } from './questions'

const all = Object.values(pool()).flat()
const organicCats = new Set(Object.keys(ORG_CAT_LABEL))
const inorganic = all.filter((it) => !organicCats.has(it.cat))

/** Hand-written items whose names are not generated by nomenclature.ts. */
const TRIVIAL: Record<string, string> = {
  HCl: 'chlorovodík',
  HF: 'fluorovodík',
  HBr: 'bromovodík',
  HI: 'jodovodík',
  H2S: 'sulfan',
  NH3: 'amoniak',
  CH4: 'methan',
  H2O2: 'peroxid vodíku',
}
const BINARY_ACID: Record<string, string> = {
  HF: 'kyselina fluorovodíková',
  HCl: 'kyselina chlorovodíková',
  HBr: 'kyselina bromovodíková',
  HI: 'kyselina jodovodíková',
  H2S: 'kyselina sulfanová',
}

/** All complex ions nomenclature.ts can make with 1–6 ligands of one kind. */
const COMPLEXES = ['Cu', 'Ag', 'Fe', 'Al', 'Zn', 'Co', 'Ni'].flatMap((m) =>
  [1, 2, 3].flatMap((ox) =>
    (Object.keys(LIGANDS) as Ligand[]).flatMap((l) =>
      [2, 4, 6].flatMap((n) => (ox + n * LIGANDS[l].charge === 0 ? [] : [complexIon(m, ox, l, n)])),
    ),
  ),
)

/**
 * Recomputes the formula of an inorganic item from its NAME with nomenclature.ts
 * (and the ion tables), independently of how the item was built.
 */
function formulaFromName(it: NItem): string {
  const name = it.name
  if (TRIVIAL[it.formula] === name) return it.formula
  if (it.cat === 'binaryAcid') return Object.entries(BINARY_ACID).find(([, n]) => n === name)![0]
  if (it.cat === 'ion') {
    const ion = [...CATIONS, ...ANIONS].find((x) => x.ion === name)!
    return ionMarkup(ion)
  }
  if (it.cat === 'complex') {
    const ion = COMPLEXES.find((x) => x.ion === name)
    if (ion) return ionMarkup(ion)
    const [a, b] = name.split(' ')
    const cc = COMPLEXES.find((x) => x.adj === b)
    if (cc) return salt(cc, ANIONS.find((x) => x.stem === a)!).formula
    const ca = COMPLEXES.find((x) => x.stem === a)!
    return salt(CATIONS.find((x) => x.adj === b)!, ca).formula
  }
  if (it.cat === 'hydrate') {
    const m = name.match(/^(\w+?)hydrát (\S+) (\S+)$/)!
    const n = MULT.indexOf(m[1])
    const saltName = [m[2], m[3]]
    const base = formulaFromName({ ...it, cat: 'salt', name: `${saltName[0].replace(/u$/, '')} ${saltName[1].replace(/ého$/, 'ý')}` })
    expect(genitive(`${saltName[0].replace(/u$/, '')} ${saltName[1].replace(/ého$/, 'ý')}`)).toBe(saltName.join(' '))
    return `${base}·${n > 1 ? n : ''}H2O`
  }
  if (it.cat === 'acid') {
    // kyselina X: central atom from the formula, oxidation number from H + x − 2·O = 0
    const atoms = parseFormula(it.formula)
    const el = Object.keys(atoms).find((e) => e !== 'H' && e !== 'O')!
    const ox = 2 * atoms.O - atoms.H
    expect(name).toBe(`kyselina ${feminine(adjective(el, ox))}`)
    return it.formula
  }
  if (it.cat === 'peroxide') {
    const adj = name.split(' ')[1]
    const c = CATIONS.find((x) => x.adj === adj)!
    return `${c.formula}${c.charge === 1 ? 2 : ''}O2`
  }
  const [noun, adj] = name.split(' ')
  if (it.cat === 'hydroxide') return hydroxide(CATIONS.find((x) => x.adj === adj)!).formula
  // binary compound: find the partner by its noun, the element by the adjective
  const partner = (Object.keys(PARTNER) as BinaryPartner[]).find((p) => PARTNER[p].noun === noun)
  if (partner && (it.cat === 'oxide' || it.cat === 'halide' || it.cat === 'sulfide' || it.cat === 'hydride' || it.cat === 'nitride')) {
    const atoms = parseFormula(it.formula)
    const el = Object.keys(atoms).find((e) => e !== partner)!
    const ox = -(atoms[partner] * PARTNER[partner].ox) / atoms[el]
    expect(Number.isInteger(ox), it.formula).toBe(true)
    expect(adj).toBe(adjective(el, ox))
    return it.formula
  }
  // salts and hydrogen salts
  const a = ANIONS.find((x) => x.stem === noun)!
  const c = CATIONS.find((x) => x.adj === adj)!
  return salt(c, a).formula
}

describe('naming question pool', () => {
  it('matches the registry levels', () => {
    expect(Object.keys(GAME_BY_ID.naming.courses.chemie!).map(Number)).toEqual([...NAMING_LEVELS])
    expect(Object.keys(LEVELS).map(Number)).toEqual([...NAMING_LEVELS])
  })

  it('every formula parses (bonds and ring notes aside)', () => {
    for (const it of all) {
      const f = it.formula.replace(/ \(kruh\)$/, '').replace(/[-=≡]/g, '')
      expect(() => parseFormula(f), it.formula).not.toThrow()
    }
  })

  it.each(inorganic.map((it) => [it.cat, it.name, it] as const))('%s %s: name and formula agree with nomenclature.ts', (_, __, it) => {
    expect(formulaFromName(it)).toBe(it.cat === 'ion' || (it.cat === 'complex' && it.display) ? it.display : it.formula)
  })

  it('complex salts are electroneutral and use square brackets', () => {
    for (const it of all.filter((x) => x.cat === 'complex' && !x.display)) {
      expect(it.formula).toMatch(/\[.*\]/)
      expect(() => parseFormula(it.formula)).not.toThrow()
    }
    expect(all.find((x) => x.name === 'hexakyanidoželeznatan draselný')?.formula).toBe('K4[Fe(CN)6]')
    expect(all.find((x) => x.name === 'tetraamminměďnatý kation')?.display).toBe('$[Cu(NH3)4]^2+$')
  })

  it('multiple-choice items have 3 distinct wrong names, none equal to the right one', () => {
    for (const it of all) {
      if (it.only === 'toFormula') continue
      expect(it.wrong.length, it.name).toBeGreaterThanOrEqual(3)
      expect(new Set(it.wrong.slice(0, 3)).size).toBe(3)
      expect(it.wrong).not.toContain(it.name)
    }
  })

  it('a wrong name is never the right name of the same formula elsewhere', () => {
    const namesByFormula = new Map<string, Set<string>>()
    for (const it of all) {
      const k = markupOf(it)
      namesByFormula.set(k, (namesByFormula.get(k) ?? new Set()).add(it.name))
    }
    for (const it of all) for (const w of it.wrong) expect(namesByFormula.get(markupOf(it))!.has(w), `${it.name}: ${w}`).toBe(false)
  })

  it('formula choices have 3 distinct wrong formulas', () => {
    for (const it of all.filter((x) => x.wrongFormulas)) {
      expect(new Set(it.wrongFormulas).size).toBe(3)
      expect(it.wrongFormulas).not.toContain(markupOf(it))
    }
  })
})

describe('levels', () => {
  const cats = (l?: number) => Object.keys(specFor(l).weights).sort()

  it('level 3: binary compounds, hydrides, peroxides and nitrides', () => {
    expect(cats(3)).toEqual(['halide', 'hydride', 'nitride', 'oxide', 'peroxide', 'sulfide'])
  })

  it('level 5: acids, hydroxides, salts, hydrogen salts and hydrates without level-7 anions', () => {
    expect(cats(5)).toEqual(['acid', 'binaryAcid', 'hydrate', 'hydrogenSalt', 'hydroxide', 'salt'])
    const items = Object.values(itemsFor(5)).flat()
    for (const it of items) {
      for (const el of ['Si', 'B', 'Se']) expect(parseFormula(it.formula)[el], it.name).toBeUndefined()
      for (const g of ['CrO4', 'Cr2O7', 'CN', 'S2O3', 'IO']) expect(it.formula, it.name).not.toContain(g)
    }
    expect(items.length).toBeGreaterThan(60)
  })

  it('level 7: all inorganic categories including ions and complexes', () => {
    expect(cats(7)).toContain('complex')
    expect(cats(7)).toContain('ion')
    for (const c of cats(7)) expect(organicCats.has(c)).toBe(false)
    expect(Object.values(itemsFor(7)).flat().filter((x) => x.cat === 'complex').length).toBeGreaterThanOrEqual(15)
  })

  it('level 8: organic only, both directions as multiple choice', () => {
    for (const c of cats(8)) expect(organicCats.has(c)).toBe(true)
    const items = Object.values(itemsFor(8)).flat()
    expect(items.length).toBeGreaterThanOrEqual(40)
    for (const it of items) expect(it.wrongFormulas?.length).toBe(3)
  })

  it('free play and unsupported levels mix all levels', () => {
    expect(specFor(undefined)).toBe(MIX)
    expect(specFor(4)).toBe(MIX)
    expect(cats(undefined)).toEqual([...new Set(NAMING_LEVELS.flatMap((l) => cats(l)))].sort())
  })

  it.each([...NAMING_LEVELS, undefined].map((l) => [l]))('builds 10 unique valid questions (level %s)', (level) => {
    for (let i = 0; i < 30; i++) {
      const qs = buildQuestions(level)
      expect(qs.length).toBe(10)
      expect(new Set(qs.map((q) => q.item.formula + q.item.name)).size).toBe(10)
      const allowed = cats(level)
      for (const q of qs) {
        expect(allowed).toContain(q.item.cat)
        if (q.dir === 'toName') {
          expect(q.options.length).toBe(4)
          expect(q.answer).toBe(q.item.name)
        }
        if (q.options.length) {
          expect(new Set(q.options).size).toBe(4)
          expect(q.options).toContain(q.answer)
        }
        if (q.dir === 'toFormula' && q.item.wrongFormulas) expect(q.answer).toBe(markupOf(q.item))
        if (q.dir === 'toFormula' && !q.item.wrongFormulas) expect(q.options).toEqual([])
        if (q.item.only) expect(q.dir).toBe(q.item.only)
      }
    }
  })
})
