/**
 * Molecule library: every id of MOLECULES (catalog.ts) with a Czech name, a formula
 * (as used in lessons, parseable by parseFormula) and 3D coordinates in Å.
 * Coordinates are generated by small VSEPR helpers (see geometry.ts), not typed by hand.
 * Aromatic bonds have order 1.5; Kekulé structures are used for fused heterocycles.
 */
import { MOLECULES, type MoleculeId } from '../catalog'
import { parseFormula } from '../../courses/chemie/data/formula'
import {
  MolBuilder,
  deg,
  polar,
  vadd,

  vscale,
  vsub,
  type Atom,
  type Bond,
  type BondOrder,
  type Vec3,
} from './geometry'

export type { Atom, Bond } from './geometry'

export interface MoleculeData {
  id: string
  /** Czech name */
  name: string
  /** formula for display via <Md> (charges as ^2-) */
  formula: string
  atoms: Atom[]
  bonds: Bond[]
  /** net charge (ions) */
  charge: number
}

interface Def {
  name: string
  formula: string
  build: () => MolBuilder
}

const b = () => new MolBuilder()

// ------------------------------------------------------------------ helpers
function diatomic(e1: string, e2: string, order: BondOrder = 1, q1 = 0, q2 = 0) {
  const m = b()
  const a = m.add(e1, [0, 0, 0], { charge: q1 })
  m.grow(a, e2, [1, 0, 0], { order, charge: q2 })
  return m
}

/** Bent X–A–Y with the given angle; returns builder with centre 0. */
function bent(center: string, e1: string, e2: string, angle: number, o1: BondOrder = 1, o2: BondOrder = 1, qc = 0, q1 = 0, q2 = 0) {
  const m = b()
  const c = m.add(center, [0, 0, 0], { charge: qc })
  m.grow(c, e1, polar(-90 + angle / 2), { order: o1, charge: q1 })
  m.grow(c, e2, polar(-90 - angle / 2), { order: o2, charge: q2 })
  return m
}

/** Benzene ring (aromatic) in the xy-plane; returns [builder, ring ids]. */
function benzene(m: MolBuilder, center: Vec3 = [0, 0, 0], start = 90): number[] {
  return m.ring(['C', 'C', 'C', 'C', 'C', 'C'], { len: 1.39, orders: [1.5, 1.5, 1.5, 1.5, 1.5, 1.5], center, start })
}

/** Carboxyl group on atom `c` (which must be trigonal). */
function carboxyl(m: MolBuilder, c: number) {
  m.setGeo(c, 'tri')
  m.sub(c, 'O', { order: 2 })
  m.sub(c, 'O')
}

/** Chair six-ring: atoms at 0°, −60°, …; z alternates starting with `first`. */
function chair(m: MolBuilder, els: string[], first: 1 | -1 = -1): number[] {
  const h = 0.25
  return m.ring(els, { radius: 1.44, start: 0, zs: els.map((_, k) => (k % 2 ? -first : first) * h) })
}

/** Linear alkane CnH2n+2 as a zig-zag (also used for species not in the catalog). */
export function alkane(n: number): MolBuilder {
  const m = b()
  m.zig(Array.from({ length: n }, () => 'C'))
  return m.hs()
}

function pyranose(anomer: 'alpha' | 'beta') {
  const m = b()
  // C1 C2 C3 C4 C5 O5 clockwise from above; 4C1 chair: C1 down, C4 up
  const [c1, c2, c3, c4, c5] = chair(m, ['C', 'C', 'C', 'C', 'C', 'O'], -1)
  m.sub(c1, 'O', { pick: anomer === 'beta' ? 'up' : 'down' })
  m.sub(c2, 'O', { pick: 'down' })
  m.sub(c3, 'O', { pick: 'up' })
  m.sub(c4, 'O', { pick: 'down' })
  const c6 = m.sub(c5, 'C', { pick: 'up' })
  m.sub(c6, 'O')
  return m.hs()
}

/** Furanose ring O, C_a … C_d (Haworth: O at the back), slight envelope. */
function furanoseRing(m: MolBuilder) {
  return m.ring(['O', 'C', 'C', 'C', 'C'], { len: 1.45, start: 90, zs: [0, 0, 0.1, 0.45, 0] })
}

/** Purine skeleton N1 C2 N3 C4 C5 C6 + N7 C8 N9 with the given bond orders. */
function purine(m: MolBuilder, six: BondOrder[], five: BondOrder[]) {
  const ring = m.ring(['N', 'C', 'N', 'C', 'C', 'C'], { len: 1.37, orders: six, start: 150 })
  const [, , , c4, c5] = ring
  const [n7, c8, n9] = m.fuse(c4, c5, ['N', 'C', 'N'], m.centroid(ring), five)
  return { n1: ring[0], c2: ring[1], n3: ring[2], c4, c5, c6: ring[5], n7, c8, n9 }
}

/** Pyrimidine ring N1 C2 N3 C4 C5 C6. */
function pyrimidine(m: MolBuilder, orders: BondOrder[]) {
  const [n1, c2, n3, c4, c5, c6] = m.ring(['N', 'C', 'N', 'C', 'C', 'C'], { len: 1.38, orders, start: 150 })
  return { n1, c2, n3, c4, c5, c6 }
}

function cholesterol() {
  const m = b()
  const L = 1.456 // planar edge; the pucker brings bonds to ~1.54 Å
  // ring A in polygon order C10 C1 C2 C3 C4 C5
  const [c10, c1, c2, c3, c4, c5] = m.ring(['C', 'C', 'C', 'C', 'C', 'C'], { len: L, start: 30 })
  void c1
  void c2
  void c4
  const ringA = [c10, c1, c2, c3, c4, c5]
  const [c9, c8, c7, c6] = m.fuse(c5, c10, ['C', 'C', 'C', 'C'], m.centroid(ringA))
  const ringB = [c5, c10, c9, c8, c7, c6]
  const [c14, c13, c12, c11] = m.fuse(c9, c8, ['C', 'C', 'C', 'C'], m.centroid(ringB))
  const ringC = [c9, c8, c14, c13, c12, c11]
  const [c17, c16, c15] = m.fuse(c14, c13, ['C', 'C', 'C'], m.centroid(ringC))
  void c15
  void c16
  void c7
  void c12
  // C5=C6 double bond
  const db = m.bonds.find((x) => (x.a === c5 && x.b === c6) || (x.a === c6 && x.b === c5))!
  db.order = 2
  // pucker the six-rings (they form a bipartite honeycomb): C10 and C13 up
  const six = new Set([...ringA, ...ringB, ...ringC])
  const side = new Map<number, number>([[c10, 1]])
  const queue = [c10]
  while (queue.length) {
    const x = queue.shift()!
    for (const y of m.nbrs(x)) if (six.has(y) && !side.has(y)) {
      side.set(y, -side.get(x)!)
      queue.push(y)
    }
  }
  for (const [x, s] of side) m.atoms[x].p = [m.atoms[x].p[0], m.atoms[x].p[1], s * 0.25]
  // angular methyls (β, up), 3β-OH, side chain at C17 (β)
  m.sub(c10, 'C')
  m.sub(c13, 'C')
  m.sub(c3, 'O', { pick: 'up' })
  // side chain leaves C17 roughly in the ring plane, tilted to the β face
  const [d1, d2] = m.freeDirs(c17, 'tet')
  const c20 = m.grow(c17, 'C', vadd(vadd(d1, d2), [0, 0, 0.35]))
  const c22 = m.sub(c20, 'C', { pick: 0 })
  m.sub(c20, 'C', { pick: 0 })
  const c23 = m.sub(c22, 'C')
  const c24 = m.sub(c23, 'C')
  const c25 = m.sub(c24, 'C')
  m.sub(c25, 'C', { pick: 1 })
  m.sub(c25, 'C', { pick: 0 })
  return m.hs()
}

// ------------------------------------------------------------------ definitions
const DEFS: Record<MoleculeId, Def> = {
  // elements & diatomics
  H2: { name: 'vodík', formula: 'H2', build: () => diatomic('H', 'H') },
  O2: { name: 'kyslík', formula: 'O2', build: () => diatomic('O', 'O', 2) },
  N2: { name: 'dusík', formula: 'N2', build: () => diatomic('N', 'N', 3) },
  Cl2: { name: 'chlor', formula: 'Cl2', build: () => diatomic('Cl', 'Cl') },
  F2: { name: 'fluor', formula: 'F2', build: () => diatomic('F', 'F') },
  Br2: { name: 'brom', formula: 'Br2', build: () => diatomic('Br', 'Br') },
  I2: { name: 'jod', formula: 'I2', build: () => diatomic('I', 'I') },
  O3: { name: 'ozon', formula: 'O3', build: () => bent('O', 'O', 'O', 117, 2, 1, 1, 0, -1) },
  P4: {
    name: 'bílý fosfor',
    formula: 'P4',
    build: () => {
      const m = b()
      const a = 2.21 / (2 * Math.SQRT2)
      const ids = ([
        [a, a, a],
        [a, -a, -a],
        [-a, a, -a],
        [-a, -a, a],
      ] as Vec3[]).map((p) => m.add('P', p))
      for (let i = 0; i < 4; i++) for (let j = i + 1; j < 4; j++) m.bond(ids[i], ids[j])
      return m
    },
  },
  S8: {
    name: 'síra (cyklooktasíra)',
    formula: 'S8',
    build: () => {
      const m = b()
      // crown: S–S 2.05 Å, S–S–S ≈ 108°
      return m.ring(Array(8).fill('S'), { radius: 2.346, zs: [0.495, -0.495, 0.495, -0.495, 0.495, -0.495, 0.495, -0.495] }), m
    },
  },

  // small inorganic
  H2O: { name: 'voda', formula: 'H2O', build: () => bent('O', 'H', 'H', 104.5) },
  CO2: {
    name: 'oxid uhličitý',
    formula: 'CO2',
    build: () => {
      const m = b()
      const c = m.add('C')
      m.grow(c, 'O', [1, 0, 0], { order: 2 })
      m.grow(c, 'O', [-1, 0, 0], { order: 2 })
      return m
    },
  },
  CO: { name: 'oxid uhelnatý', formula: 'CO', build: () => diatomic('C', 'O', 3, -1, 1) },
  NH3: { name: 'amoniak', formula: 'NH3', build: () => withAtom('N').hs() },
  CH4: { name: 'methan', formula: 'CH4', build: () => withAtom('C').hs() },
  HCl: { name: 'chlorovodík', formula: 'HCl', build: () => diatomic('H', 'Cl') },
  HF: { name: 'fluorovodík', formula: 'HF', build: () => diatomic('H', 'F') },
  H2S: { name: 'sulfan (sirovodík)', formula: 'H2S', build: () => bent('S', 'H', 'H', 92) },
  SO2: { name: 'oxid siřičitý', formula: 'SO2', build: () => bent('S', 'O', 'O', 119, 2, 2) },
  SO3: {
    name: 'oxid sírový',
    formula: 'SO3',
    build: () => {
      const m = b()
      const s = m.add('S', [0, 0, 0], { geo: 'tri' })
      for (let k = 0; k < 3; k++) m.sub(s, 'O', { order: 2 })
      return m
    },
  },
  NO: { name: 'oxid dusnatý', formula: 'NO', build: () => {
    const m = b()
    const n = m.add('N', [0, 0, 0], { radical: 1 })
    m.grow(n, 'O', [1, 0, 0], { order: 2, len: 1.15 })
    return m
  } },
  NO2: {
    name: 'oxid dusičitý',
    formula: 'NO2',
    build: () => {
      const m = bent('N', 'O', 'O', 134, 2, 1, 1, 0, -1)
      m.atoms[0].radical = 1
      return m
    },
  },
  N2O: {
    name: 'oxid dusný',
    formula: 'N2O',
    build: () => {
      const m = b()
      const n = m.add('N', [0, 0, 0], { charge: 1 })
      m.grow(n, 'N', [-1, 0, 0], { order: 3 })
      m.grow(n, 'O', [1, 0, 0], { charge: -1, len: 1.19 })
      return m
    },
  },
  H2O2: {
    name: 'peroxid vodíku',
    formula: 'H2O2',
    build: () => {
      const m = b()
      const o1 = m.add('O')
      const o2 = m.grow(o1, 'O', [1, 0, 0])
      const t = deg(95)
      m.grow(o1, 'H', [Math.cos(t), Math.sin(t), 0])
      m.grow(o2, 'H', [-Math.cos(t), Math.sin(t) * Math.cos(deg(111)), Math.sin(t) * Math.sin(deg(111))])
      return m
    },
  },
  BF3: { name: 'fluorid boritý', formula: 'BF3', build: () => star('B', 'F', [polar(90), polar(210), polar(330)]) },
  PCl5: {
    name: 'chlorid fosforečný',
    formula: 'PCl5',
    build: () => {
      const m = star('P', 'Cl', [polar(0), polar(120), polar(240)])
      m.grow(0, 'Cl', [0, 0, 1], { len: 2.14 })
      m.grow(0, 'Cl', [0, 0, -1], { len: 2.14 })
      return m
    },
  },
  SF6: {
    name: 'fluorid sírový',
    formula: 'SF6',
    build: () =>
      star('S', 'F', [
        [1, 0, 0],
        [-1, 0, 0],
        [0, 1, 0],
        [0, -1, 0],
        [0, 0, 1],
        [0, 0, -1],
      ]),
  },
  CCl4: { name: 'tetrachlormethan', formula: 'CCl4', build: () => tetra('C', ['Cl', 'Cl', 'Cl', 'Cl']) },
  CH2Cl2: { name: 'dichlormethan', formula: 'CH2Cl2', build: () => tetra('C', ['Cl', 'Cl']).hs() },
  CCl2F2: { name: 'dichlordifluormethan (freon)', formula: 'CCl2F2', build: () => tetra('C', ['Cl', 'Cl', 'F', 'F']) },
  XeF4: {
    name: 'fluorid xenoničitý',
    formula: 'XeF4',
    build: () => star('Xe', 'F', [polar(0), polar(90), polar(180), polar(270)]),
  },
  BeCl2: {
    name: 'chlorid beryllnatý',
    formula: 'BeCl2',
    build: () =>
      star('Be', 'Cl', [
        [1, 0, 0],
        [-1, 0, 0],
      ]),
  },

  // ions
  'H3O+': { name: 'oxoniový kation', formula: 'H3O^+', build: () => withAtom('O', 1).hs() },
  'NH4+': { name: 'amonný kation', formula: 'NH4^+', build: () => withAtom('N', 1).hs() },
  'OH-': { name: 'hydroxidový anion', formula: 'OH^-', build: () => withAtom('O', -1).hs() },
  'NO3-': {
    name: 'dusičnanový anion',
    formula: 'NO3^-',
    build: () => {
      const m = b()
      const n = m.add('N', [0, 0, 0], { charge: 1, geo: 'tri' })
      m.sub(n, 'O', { order: 2, len: 1.25 })
      m.sub(n, 'O', { charge: -1, len: 1.25 })
      m.sub(n, 'O', { charge: -1, len: 1.25 })
      return m
    },
  },
  'SO4^2-': {
    name: 'síranový anion',
    formula: 'SO4^2-',
    build: () => oxo('S', [2, 2, 1, 1], [0, 0, -1, -1], 1.49),
  },
  'CO3^2-': {
    name: 'uhličitanový anion',
    formula: 'CO3^2-',
    build: () => {
      const m = b()
      const c = m.add('C', [0, 0, 0], { geo: 'tri' })
      m.sub(c, 'O', { order: 2, len: 1.29 })
      m.sub(c, 'O', { charge: -1, len: 1.29 })
      m.sub(c, 'O', { charge: -1, len: 1.29 })
      return m
    },
  },
  'PO4^3-': {
    name: 'fosforečnanový anion',
    formula: 'PO4^3-',
    build: () => oxo('P', [2, 1, 1, 1], [0, -1, -1, -1], 1.54),
  },
  'HCO3-': {
    name: 'hydrogenuhličitanový anion',
    formula: 'HCO3^-',
    build: () => {
      const m = b()
      const c = m.add('C', [0, 0, 0], { geo: 'tri' })
      m.sub(c, 'O', { order: 2 })
      m.sub(c, 'O', { charge: -1, len: 1.28 })
      m.sub(c, 'O', { len: 1.36 })
      return m.hs()
    },
  },

  // acids
  H2SO4: { name: 'kyselina sírová', formula: 'H2SO4', build: () => oxo('S', [2, 2, 1, 1], [0, 0, 0, 0]).hs() },
  HNO3: {
    name: 'kyselina dusičná',
    formula: 'HNO3',
    build: () => {
      const m = b()
      const n = m.add('N', [0, 0, 0], { charge: 1, geo: 'tri' })
      m.sub(n, 'O')
      m.sub(n, 'O', { order: 2 })
      m.sub(n, 'O', { charge: -1, len: 1.22 })
      return m.hs()
    },
  },
  H3PO4: { name: 'kyselina fosforečná', formula: 'H3PO4', build: () => oxo('P', [2, 1, 1, 1], [0, 0, 0, 0]).hs() },
  H2CO3: {
    name: 'kyselina uhličitá',
    formula: 'H2CO3',
    build: () => {
      const m = b()
      const c = m.add('C', [0, 0, 0], { geo: 'tri' })
      m.sub(c, 'O', { order: 2 })
      m.sub(c, 'O')
      m.sub(c, 'O')
      return m.hs()
    },
  },

  // hydrocarbons
  C2H6: { name: 'ethan', formula: 'C2H6', build: () => alkane(2) },
  C3H8: { name: 'propan', formula: 'C3H8', build: () => alkane(3) },
  butane: { name: 'butan', formula: 'C4H10', build: () => alkane(4) },
  isobutane: { name: 'isobutan (2-methylpropan)', formula: 'C4H10', build: () => tetra('C', ['C', 'C', 'C']).hs() },
  C2H4: { name: 'ethen (ethylen)', formula: 'C2H4', build: () => chainHs(['C', 'C'], [2], 120) },
  propene: { name: 'propen', formula: 'C3H6', build: () => chainHs(['C', 'C', 'C'], [2, 1], 124) },
  C2H2: { name: 'ethyn (acetylen)', formula: 'C2H2', build: () => chainHs(['C', 'C'], [3], 180) },
  'cis-but-2-ene': { name: 'cis-but-2-en', formula: 'C4H8', build: () => but2ene(true) },
  'trans-but-2-ene': { name: 'trans-but-2-en', formula: 'C4H8', build: () => but2ene(false) },
  cyclohexane: {
    name: 'cyklohexan',
    formula: 'C6H12',
    build: () => {
      const m = b()
      chair(m, ['C', 'C', 'C', 'C', 'C', 'C'])
      return m.hs()
    },
  },
  benzene: {
    name: 'benzen',
    formula: 'C6H6',
    build: () => {
      const m = b()
      benzene(m)
      return m.hs()
    },
  },
  toluene: {
    name: 'toluen',
    formula: 'C6H5CH3',
    build: () => {
      const m = b()
      const r = benzene(m)
      m.sub(r[0], 'C')
      return m.hs()
    },
  },
  naphthalene: {
    name: 'naftalen',
    formula: 'C10H8',
    build: () => {
      const m = b()
      const r = m.ring(['C', 'C', 'C', 'C', 'C', 'C'], { len: 1.4, orders: [1.5, 1.5, 1.5, 1.5, 1.5, 1], start: 0 })
      m.fuse(r[5], r[0], ['C', 'C', 'C', 'C'], m.centroid(r), [1.5, 1.5, 1.5, 1.5, 1.5])
      return m.hs()
    },
  },
  styrene: {
    name: 'styren',
    formula: 'C6H5CHCH2',
    build: () => {
      const m = b()
      const r = benzene(m)
      const c = m.sub(r[0], 'C', { geo: 'tri' })
      m.sub(c, 'C', { order: 2 })
      return m.hs()
    },
  },

  // derivatives
  CH3Cl: { name: 'chlormethan', formula: 'CH3Cl', build: () => tetra('C', ['Cl']).hs() },
  'vinyl-chloride': {
    name: 'vinylchlorid (chlorethen)',
    formula: 'CH2CHCl',
    build: () => {
      const m = b()
      const [, c2] = m.zig(['C', 'C'], { orders: [2] })
      m.sub(c2, 'Cl')
      return m.hs()
    },
  },
  methanol: { name: 'methanol', formula: 'CH3OH', build: () => chainHs(['C', 'O']) },
  ethanol: { name: 'ethanol', formula: 'C2H5OH', build: () => chainHs(['C', 'C', 'O']) },
  'propan-2-ol': {
    name: 'propan-2-ol',
    formula: 'CH3CH(OH)CH3',
    build: () => {
      const m = b()
      const [, c2] = m.zig(['C', 'C', 'C'])
      m.sub(c2, 'O', { pick: 'up' })
      return m.hs()
    },
  },
  'ethylene-glycol': { name: 'ethylenglykol (ethan-1,2-diol)', formula: 'C2H4(OH)2', build: () => chainHs(['O', 'C', 'C', 'O']) },
  glycerol: {
    name: 'glycerol',
    formula: 'C3H5(OH)3',
    build: () => {
      const m = b()
      const [c1, c2, c3] = m.zig(['C', 'C', 'C'])
      m.sub(c1, 'O')
      m.sub(c2, 'O', { pick: 'up' })
      m.sub(c3, 'O')
      return m.hs()
    },
  },
  phenol: {
    name: 'fenol',
    formula: 'C6H5OH',
    build: () => {
      const m = b()
      const r = benzene(m)
      m.sub(r[0], 'O')
      return m.hs()
    },
  },
  'diethyl-ether': { name: 'diethylether', formula: 'C2H5OC2H5', build: () => chainHs(['C', 'C', 'O', 'C', 'C'], [], 111) },
  formaldehyde: {
    name: 'formaldehyd (methanal)',
    formula: 'HCHO',
    build: () => {
      const m = b()
      const c = m.add('C', [0, 0, 0], { geo: 'tri' })
      m.sub(c, 'O', { order: 2 })
      return m.hs()
    },
  },
  acetaldehyde: {
    name: 'acetaldehyd (ethanal)',
    formula: 'CH3CHO',
    build: () => {
      const m = b()
      const [, c2] = m.zig(['C', 'C'])
      m.setGeo(c2, 'tri').sub(c2, 'O', { order: 2 })
      return m.hs()
    },
  },
  acetone: {
    name: 'aceton (propanon)',
    formula: 'CH3COCH3',
    build: () => {
      const m = b()
      const [, c2] = m.zig(['C', 'C', 'C'], { angle: 117 })
      m.setGeo(c2, 'tri').sub(c2, 'O', { order: 2 })
      return m.hs()
    },
  },
  'formic-acid': {
    name: 'kyselina mravenčí',
    formula: 'HCOOH',
    build: () => {
      const m = b()
      const c = m.add('C', [0, 0, 0], { geo: 'tri' })
      m.sub(c, 'H')
      m.sub(c, 'O', { order: 2 })
      m.sub(c, 'O')
      return m.hs()
    },
  },
  'acetic-acid': {
    name: 'kyselina octová',
    formula: 'CH3COOH',
    build: () => {
      const m = b()
      const [, c2] = m.zig(['C', 'C'])
      carboxyl(m, c2)
      return m.hs()
    },
  },
  'ethyl-acetate': {
    name: 'ethyl-acetát',
    formula: 'CH3COOC2H5',
    build: () => {
      const m = b()
      const [, c2] = m.zig(['C', 'C', 'O', 'C', 'C'], { angle: 114 })
      m.setGeo(c2, 'tri').sub(c2, 'O', { order: 2 })
      return m.hs()
    },
  },
  methylamine: { name: 'methylamin', formula: 'CH3NH2', build: () => chainHs(['C', 'N']) },
  urea: {
    name: 'močovina',
    formula: 'CO(NH2)2',
    build: () => {
      const m = b()
      const c = m.add('C', [0, 0, 0], { geo: 'tri' })
      m.sub(c, 'O', { order: 2 })
      m.sub(c, 'N', { geo: 'tri', len: 1.37 })
      m.sub(c, 'N', { geo: 'tri', len: 1.37 })
      return m.hs()
    },
  },
  nitrobenzene: {
    name: 'nitrobenzen',
    formula: 'C6H5NO2',
    build: () => {
      const m = b()
      const r = benzene(m)
      const n = m.sub(r[0], 'N', { charge: 1, geo: 'tri' })
      m.sub(n, 'O', { order: 2, len: 1.22 })
      m.sub(n, 'O', { charge: -1, len: 1.22 })
      return m.hs()
    },
  },

  // biomolecules
  glycine: {
    name: 'glycin',
    formula: 'NH2CH2COOH',
    build: () => {
      const m = b()
      const [, , c] = m.zig(['N', 'C', 'C'], { angle: 111 })
      carboxyl(m, c)
      return m.hs()
    },
  },
  alanine: {
    name: 'alanin',
    formula: 'CH3CH(NH2)COOH',
    build: () => {
      const m = b()
      const [, ca, c] = m.zig(['N', 'C', 'C'], { angle: 111 })
      carboxyl(m, c)
      m.sub(ca, 'C', { pick: 'up' })
      return m.hs()
    },
  },
  'lactic-acid': {
    name: 'kyselina mléčná',
    formula: 'CH3CH(OH)COOH',
    build: () => {
      const m = b()
      const [, c2, c3] = m.zig(['C', 'C', 'C'], { angle: 111 })
      carboxyl(m, c3)
      m.sub(c2, 'O', { pick: 'up' })
      return m.hs()
    },
  },
  glucose: { name: 'glukóza', formula: 'C6H12O6', build: () => pyranose('beta') },
  'alpha-glucose': { name: 'α-glukóza', formula: 'C6H12O6', build: () => pyranose('alpha') },
  fructose: {
    name: 'fruktóza',
    formula: 'C6H12O6',
    build: () => {
      const m = b()
      // β-D-fructofuranose: O5 C2 C3 C4 C5
      const [, c2, c3, c4, c5] = furanoseRing(m)
      m.sub(c2, 'O', { pick: 'up' })
      const c1 = m.sub(c2, 'C', { pick: 'down' })
      m.sub(c1, 'O')
      m.sub(c3, 'O', { pick: 'up' })
      m.sub(c4, 'O', { pick: 'down' })
      const c6 = m.sub(c5, 'C', { pick: 'up' })
      m.sub(c6, 'O')
      return m.hs()
    },
  },
  ribose: {
    name: 'ribóza',
    formula: 'C5H10O5',
    build: () => {
      const m = b()
      // β-D-ribofuranose: O4' C1' C2' C3' C4'
      const [, c1, c2, c3, c4] = furanoseRing(m)
      m.sub(c1, 'O', { pick: 'up' })
      m.sub(c2, 'O', { pick: 'down' })
      m.sub(c3, 'O', { pick: 'down' })
      const c5 = m.sub(c4, 'C', { pick: 'up' })
      m.sub(c5, 'O')
      return m.hs()
    },
  },
  aspirin: {
    name: 'aspirin (kyselina acetylsalicylová)',
    formula: 'C9H8O4',
    build: () => {
      const m = b()
      const r = benzene(m)
      const c7 = m.sub(r[0], 'C', { geo: 'tri' })
      m.sub(c7, 'O', { order: 2 })
      m.sub(c7, 'O')
      const o = m.sub(r[1], 'O')
      const c8 = m.sub(o, 'C', { geo: 'tri', len: 1.36, pick: 1 })
      m.sub(c8, 'C')
      m.sub(c8, 'O', { order: 2 })
      return m.hs()
    },
  },
  caffeine: {
    name: 'kofein',
    formula: 'C8H10N4O2',
    build: () => {
      const m = b()
      const p = purine(m, [1, 1, 1, 2, 1, 1], [1, 1, 2, 1])
      m.sub(p.c2, 'O', { order: 2, len: 1.23 })
      m.sub(p.c6, 'O', { order: 2, len: 1.23 })
      m.sub(p.n1, 'C')
      m.sub(p.n3, 'C')
      m.sub(p.n7, 'C')
      return m.hs()
    },
  },
  'palmitic-acid': {
    name: 'kyselina palmitová',
    formula: 'C15H31COOH',
    build: () => {
      const m = b()
      const cs = m.zig(Array(16).fill('C'))
      carboxyl(m, cs[15])
      return m.hs()
    },
  },
  'cholesterol-core': { name: 'cholesterol', formula: 'C27H46O', build: cholesterol },
  adenine: {
    name: 'adenin',
    formula: 'C5H5N5',
    build: () => {
      const m = b()
      const p = purine(m, [1, 2, 1, 2, 1, 2], [1, 2, 1, 1])
      m.sub(p.c6, 'N', { geo: 'tri', len: 1.35 })
      return m.hs()
    },
  },
  thymine: {
    name: 'thymin',
    formula: 'C5H6N2O2',
    build: () => {
      const m = b()
      const r = pyrimidine(m, [1, 1, 1, 1, 2, 1])
      m.sub(r.c2, 'O', { order: 2, len: 1.23 })
      m.sub(r.c4, 'O', { order: 2, len: 1.23 })
      m.sub(r.c5, 'C')
      return m.hs()
    },
  },
  guanine: {
    name: 'guanin',
    formula: 'C5H5N5O',
    build: () => {
      const m = b()
      const p = purine(m, [1, 2, 1, 2, 1, 1], [1, 2, 1, 1])
      m.sub(p.c6, 'O', { order: 2, len: 1.23 })
      m.sub(p.c2, 'N', { geo: 'tri', len: 1.35 })
      return m.hs()
    },
  },
  cytosine: {
    name: 'cytosin',
    formula: 'C4H5N3O',
    build: () => {
      const m = b()
      const r = pyrimidine(m, [1, 1, 2, 1, 2, 1])
      m.sub(r.c2, 'O', { order: 2, len: 1.23 })
      m.sub(r.c4, 'N', { geo: 'tri', len: 1.35 })
      return m.hs()
    },
  },
}

// ------------------------------------------------------------------ more helpers
function withAtom(el: string, charge = 0) {
  const m = b()
  m.add(el, [0, 0, 0], { charge })
  return m
}
function star(center: string, lig: string, dirs: Vec3[]) {
  const m = b()
  const c = m.add(center)
  for (const d of dirs) m.grow(c, lig, d)
  return m
}
/** Tetrahedral centre with the listed substituents (remaining positions free). */
function tetra(center: string, subs: string[]) {
  const m = b()
  const c = m.add(center, [0, 0, 0], { geo: 'tet' })
  for (const s of subs) m.sub(c, s)
  return m
}
/** Tetrahedral oxo-acid / oxo-anion centre. */
function oxo(center: string, orders: BondOrder[], charges: number[], len?: number) {
  const m = b()
  const c = m.add(center, [0, 0, 0], { geo: 'tet' })
  orders.forEach((o, k) => m.sub(c, 'O', { order: o, charge: charges[k], len }))
  return m
}
function chainHs(els: string[], orders: BondOrder[] = [], angle = 109.5) {
  const m = b()
  m.zig(els, { orders, angle })
  return m.hs()
}
function but2ene(cis: boolean) {
  const m = b()
  const c2 = m.add('C', [0, 0, 0], { geo: 'tri' })
  const c3 = m.grow(c2, 'C', [1, 0, 0], { order: 2 })
  m.grow(c2, 'C', polar(120))
  m.grow(c3, 'C', cis ? polar(60) : polar(-60))
  return m.hs()
}

// ------------------------------------------------------------------ public API
const cache = new Map<string, MoleculeData>()

/** Full 3D data for a catalog id (centred at the origin). */
export function getMolecule(id: MoleculeId): MoleculeData {
  let hit = cache.get(id)
  if (hit) return hit
  const def = DEFS[id]
  const built = def.build()
  hit = finish(id, def.name, def.formula, built)
  cache.set(id, hit)
  return hit
}

export function finish(id: string, name: string, formula: string, m: MolBuilder): MoleculeData {
  const n = m.atoms.length
  const c = vscale(
    m.atoms.reduce((s, a) => vadd(s, a.p), [0, 0, 0] as Vec3),
    1 / n,
  )
  const atoms = m.atoms.map((a) => ({ ...a, p: vsub(a.p, c) }))
  const charge = atoms.reduce((s, a) => s + (a.charge ?? 0), 0)
  return { id, name, formula, atoms, bonds: m.bonds.map((x) => ({ ...x })), charge }
}

export const MOLECULE_IDS: readonly MoleculeId[] = MOLECULES

// ---------------------------------------------------------- lookup by formula
/** Net charge written in a species ("SO4^2-", "H3O+", "Fe^{3+}"). */
export function chargeOf(species: string): number {
  const m = species.match(/\^\{?(\d*)([+\-−])\}?$/) ?? species.match(/[a-z0-9)\]]([+\-])$/i)
  if (!m) return 0
  const sign = m[m.length - 1] === '+' ? 1 : -1
  const num = m.length === 3 && m[1] ? Number(m[1]) : 1
  return sign * num
}

/** Formula without charge suffix (so parseFormula accepts "H3O+" too). */
export function stripCharge(species: string): string {
  return species.replace(/\^\{?\d*[+\-−]\}?$/, '').replace(/([A-Za-z0-9)\]])[+\-]$/, '$1')
}

/** Order-independent key: element counts + charge. */
export function signature(species: string): string | null {
  try {
    const counts = parseFormula(stripCharge(species))
    const keys = Object.keys(counts).sort()
    if (!keys.length) return null
    return keys.map((k) => k + counts[k]).join('') + '|' + chargeOf(species)
  } catch {
    return null
  }
}

let bySig: Map<string, MoleculeId> | null = null
let byFormula: Map<string, MoleculeId> | null = null

/** Find a library molecule by id, by its formula, or by element counts (first match). */
export function findMolecule(species: string): MoleculeData | undefined {
  const s = species.trim()
  if ((MOLECULES as readonly string[]).includes(s)) return getMolecule(s as MoleculeId)
  if (!bySig || !byFormula) {
    bySig = new Map()
    byFormula = new Map()
    for (const id of MOLECULES) {
      if (!byFormula.has(DEFS[id].formula)) byFormula.set(DEFS[id].formula, id)
      const sig = signature(DEFS[id].formula)
      if (sig && !bySig.has(sig)) bySig.set(sig, id)
    }
  }
  const f = byFormula.get(s)
  if (f) return getMolecule(f)
  const sig = signature(s)
  const id = sig ? bySig.get(sig) : undefined
  return id ? getMolecule(id) : undefined
}

